#!/usr/bin/env python3
"""
M088 — Figures 1, 3, 4.

Figure 2 is generated by m088_trends_joinpoint.py.

  Figure 1 — CONSORT cohort flow
  Figure 3 — Sankey: historical → 2022 WHO label
  Figure 4 — Forest plot of management-impact deltas (with bootstrap 95% CI)
"""

from __future__ import annotations
import csv
import math
from pathlib import Path

import numpy as np
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
from matplotlib.patches import FancyBboxPatch, Rectangle, FancyArrowPatch
from matplotlib.path import Path as MplPath
import matplotlib.patches as mpatches

ROOT    = Path(__file__).resolve().parent.parent
OUTPUT  = ROOT / "analysis" / "output"
TABLES  = ROOT / "tables"
FIGURES = ROOT / "figures"
FIGURES.mkdir(exist_ok=True)

# ---------------------------------------------------------------------------- #
# Figure 1 — CONSORT cohort flow

def figure_1():
    fig, ax = plt.subplots(figsize=(8, 10))
    ax.set_xlim(0, 10); ax.set_ylim(0, 12)
    ax.axis("off")

    boxes = [
        # (y, text)
        (11.0, "All patients in pub_canonical (2026-05-09 snapshot)\nn = 10,871"),
        (9.5,  "Filter to surgical resections, primary thyroid tissue\n1990-01-01 through 2025-12-31"),
        (8.0,  "Restrict to follicular-patterned diagnoses\n(FA, OA, FT-UMP, atypical FA, NIFTP, FTC, HCC,\n DHGTC, PDTC, hyalinizing trabecular tumor)\nn = 1,547 entity-level"),
        (6.0,  "Exclude metastatic-to-thyroid and recurrent disease\nDeduplicate to patient level\nn = 1,542 distinct patients"),
        (4.0,  "M088 analytic cohort\nn = 1,542 patients\n(1,537 with operative rollup; 5 missing surgery date)"),
    ]
    side_excl = [
        (10.25, "Excluded: non-surgical, non-primary,\nnon-follicular-patterned"),
        (8.75,  ""),
        (7.0,   "Excluded: 5 multiprimary patients\n(double-counted at entity level)"),
        (5.0,   "Excluded: 0 recurrent/metastatic\n(none flagged in pre-specified filter)"),
    ]
    for (y, txt), color in zip(boxes, ["#cfe2ff", "#cfe2ff", "#cfe2ff", "#cfe2ff", "#a8d5ff"]):
        ax.add_patch(FancyBboxPatch((1.5, y - 0.5), 5, 1.0,
                                    boxstyle="round,pad=0.04",
                                    fc=color, ec="black", lw=1.0))
        ax.text(4.0, y, txt, ha="center", va="center", fontsize=9)
    # Arrows between boxes
    for (y1, _), (y2, _) in zip(boxes[:-1], boxes[1:]):
        ax.annotate("", xy=(4.0, y2 + 0.5), xytext=(4.0, y1 - 0.5),
                    arrowprops=dict(arrowstyle="->", lw=1.2))
    # Side exclusions
    for (y, txt) in side_excl:
        if not txt:
            continue
        ax.add_patch(FancyBboxPatch((7.0, y - 0.4), 2.7, 0.8,
                                    boxstyle="round,pad=0.04",
                                    fc="#ffe5e5", ec="black", lw=0.8))
        ax.text(8.35, y, txt, ha="center", va="center", fontsize=7.5)
        ax.annotate("", xy=(7.0, y), xytext=(6.5, y),
                    arrowprops=dict(arrowstyle="->", lw=0.8, color="black"))
    ax.set_title("M088 Figure 1 — CONSORT cohort flow", fontsize=12, pad=4)
    fig.tight_layout()
    out = FIGURES / "figure_1_consort.png"
    fig.savefig(out, dpi=150, bbox_inches="tight")
    plt.close(fig)
    print(f"Wrote {out}")

# ---------------------------------------------------------------------------- #
# Figure 3 — Sankey-style historical → 2022 WHO

def figure_3():
    """
    A custom matplotlib Sankey-like figure.
    Left side: historical labels (pre-2022 WHO 4th).
    Right side: 2022 WHO labels (with oncocytic family separated).
    Flow widths proportional to n.
    """
    # Historical → 2022 WHO mapping with patient counts
    flows = [
        ("Follicular adenoma (n=707)",                 "Follicular adenoma",               705, "#1f77b4"),
        ("Follicular adenoma (n=707)",                 "FT-UMP (Tier A)",                  2,   "#1f77b4"),  # approx, strict bound
        ("Hurthle cell adenoma (n=143)",               "Oncocytic adenoma",                143, "#ff7f0e"),
        ("FT-UMP, historical (n=34)",                  "FT-UMP",                           34,  "#9467bd"),  # most stay
        ("Atypical FA (n=33)",                         "FT-UMP (from atypical FA)",        33,  "#bcbd22"),
        ("NIFTP (n=116)",                              "NIFTP",                            116, "#17becf"),
        ("FTC, NOS (n=106)",                           "FTC, NOS",                         106, "#2ca02c"),
        ("FTC, minimally invasive (n=169)",            "FTC, minimally invasive (Tier A strict)", 167, "#d62728"),
        ("FTC, minimally invasive (n=169)",            "FT-UMP (Tier A strict)",           2,   "#d62728"),
        ("FTC, oncocytic variant (n=209)",             "Oncocytic carcinoma",              209, "#9467bd"),
        ("FTC, widely invasive (n=12)",                "FTC, widely invasive",             12,  "#ff7f0e"),
        ("Hurthle cell carcinoma (n=2)",               "Oncocytic carcinoma",              2,   "#8c564b"),
        ("DHGTC (n=11)",                               "DHGTC",                            11,  "#e377c2"),
        ("PDTC (n=1)",                                 "PDTC",                             1,   "#7f7f7f"),
        ("Hyalinizing trabecular tumor (n=4)",         "Hyalinizing trabecular tumor",     4,   "#7f7f7f"),
    ]

    # Build node lists preserving order
    seen_l, seen_r = [], []
    for s, t, _, _ in flows:
        if s not in seen_l: seen_l.append(s)
        if t not in seen_r: seen_r.append(t)

    # Assign vertical positions proportional to n
    def y_positions(nodes, side):
        totals = {}
        for s, t, n, _ in flows:
            k = s if side == "left" else t
            totals[k] = totals.get(k, 0) + n
        ord_nodes = [n for n in nodes]
        pos = {}
        running = 0
        gap = 8
        max_total = sum(totals.values()) if side == "left" else sum(totals.values())
        # Sort by total descending for visual clarity
        ord_nodes.sort(key=lambda nm: -totals[nm])
        for nm in ord_nodes:
            h = totals[nm]
            pos[nm] = (running, running + h)
            running += h + gap
        return pos, running

    Lpos, Lspan = y_positions(seen_l, "left")
    Rpos, Rspan = y_positions(seen_r, "right")

    fig, ax = plt.subplots(figsize=(13, 11))
    ax.set_xlim(0, 100)
    ax.set_ylim(0, max(Lspan, Rspan) + 5)
    ax.invert_yaxis()
    ax.axis("off")

    # Draw nodes
    for nm, (lo, hi) in Lpos.items():
        ax.add_patch(Rectangle((5, lo), 2.5, hi - lo, fc="#444", ec="black", lw=0.5))
        ax.text(4.5, (lo + hi) / 2, nm, ha="right", va="center", fontsize=8.5)
    for nm, (lo, hi) in Rpos.items():
        ax.add_patch(Rectangle((92.5, lo), 2.5, hi - lo, fc="#444", ec="black", lw=0.5))
        ax.text(95.5, (lo + hi) / 2, nm, ha="left", va="center", fontsize=8.5)

    # Track running offsets within each node so flow ribbons don't overlap
    Loff = {nm: lo for nm, (lo, _) in Lpos.items()}
    Roff = {nm: lo for nm, (lo, _) in Rpos.items()}

    for s, t, n, color in flows:
        lo_l = Loff[s]; lo_r = Roff[t]
        hi_l = lo_l + n; hi_r = lo_r + n
        Loff[s] = hi_l; Roff[t] = hi_r
        # Bezier path
        x_l, x_r = 7.5, 92.5
        verts_top = [(x_l, lo_l), ((x_l + x_r) / 2, lo_l), ((x_l + x_r) / 2, lo_r), (x_r, lo_r)]
        verts_bot = [(x_r, hi_r), ((x_l + x_r) / 2, hi_r), ((x_l + x_r) / 2, hi_l), (x_l, hi_l)]
        codes_top = [MplPath.MOVETO, MplPath.CURVE4, MplPath.CURVE4, MplPath.CURVE4]
        codes_bot = [MplPath.LINETO, MplPath.CURVE4, MplPath.CURVE4, MplPath.CURVE4]
        verts = verts_top + verts_bot + [(x_l, lo_l)]
        codes = codes_top + codes_bot + [MplPath.CLOSEPOLY]
        path = MplPath(verts, codes)
        ax.add_patch(mpatches.PathPatch(path, fc=color, ec="none", alpha=0.55))

    ax.set_title("M088 Figure 3 — Sankey diagram: historical (pre-2022 WHO 4th) → 2022 WHO 5th label\nFlow width ∝ patient count. Tier A deterministic mapping.", fontsize=11)
    out = FIGURES / "figure_3_sankey.png"
    fig.savefig(out, dpi=150, bbox_inches="tight")
    plt.close(fig)
    print(f"Wrote {out}")

# ---------------------------------------------------------------------------- #
# Figure 4 — Forest plot of management-impact Δ (with bootstrap 95% CI)

def figure_4():
    rows = []
    with open(TABLES / "table_4_management_impact_bootstrap.csv") as f:
        rows = list(csv.DictReader(f))
    # Sort transitions by absolute Δ
    rows.sort(key=lambda r: abs(float(r["delta_pp"])), reverse=True)

    fig, ax = plt.subplots(figsize=(11, 6))
    labels = [r["transition"] for r in rows]
    deltas = [float(r["delta_pp"]) for r in rows]
    los    = [float(r["ci_lo_pp"]) for r in rows]
    his    = [float(r["ci_hi_pp"]) for r in rows]
    ys = list(range(len(labels)))[::-1]

    ax.axvline(0, color="gray", lw=0.8, ls="--")
    for y, d, lo, hi in zip(ys, deltas, los, his):
        color = "#d62728" if d < 0 else "#2ca02c"
        ax.errorbar(d, y, xerr=[[d - lo], [hi - d]], fmt="o",
                    color=color, capsize=4, lw=1.6, markersize=7)
    ax.set_yticks(ys)
    ax.set_yticklabels(labels, fontsize=9)
    ax.set_xlabel("Δ definitive total thyroidectomy at index (percentage points)\nNegative = reclassification de-escalates surgical management; positive = escalates")
    ax.set_title("M088 Figure 4 — Management impact of 2022 WHO reclassification\nForest plot of Δ definitive-total-thyroidectomy rate (target − historical), bootstrap 95% CI (1000 iter)")
    ax.grid(axis="x", lw=0.4, alpha=0.4)
    out = FIGURES / "figure_4_forest.png"
    fig.savefig(out, dpi=150, bbox_inches="tight")
    plt.close(fig)
    print(f"Wrote {out}")

# ---------------------------------------------------------------------------- #

if __name__ == "__main__":
    figure_1()
    figure_3()
    figure_4()
    print("All figures generated.")
