-- =============================================================================
-- Migration 180b — NLP UPSTREAM-MISSING family lineage investigation closure
-- =============================================================================
-- Date: 2026-04-29
-- Batch: mig_180b_nlp_upstream_missing_lineage_20260429
-- Target DB: thyroid_canonical_publication_v1_0
-- Data table touched: main.val_mig180b_nlp_upstream_lineage_v1
-- Registry touched: main.canonical_column_verification_registry_v1 notes only.
-- canonical_patient_master values touched: NONE.
-- =============================================================================

-- §0 pre-flight
SELECT COUNT(*) AS cpm_rows, COUNT(DISTINCT research_id) AS cpm_distinct_research_id FROM main.canonical_patient_master;

-- §A snapshot (script uses CREATE TABLE IF NOT EXISTS)
CREATE TABLE IF NOT EXISTS "Thyroid 2026 UPdated".archive_pub_v1_0.canonical_column_verification_registry_pre_mig180b_20260429 AS
SELECT *, CAST(CURRENT_TIMESTAMP AS TIMESTAMP) AS pre_mig180b_snapshot_ts
FROM thyroid_canonical_publication_v1_0.main.canonical_column_verification_registry_v1
WHERE schema_name='main' AND table_name='canonical_patient_master'
  AND column_name IN ('nlp_funcoutcome_has_data', 'nlp_funcoutcome_key_finding', 'nlp_funcoutcome_n_entities', 'nlp_funcoutcome_n_notes', 'nlp_imaging_has_data', 'nlp_imaging_key_finding', 'nlp_imaging_n_entities', 'nlp_imaging_n_notes', 'nlp_labs_has_data', 'nlp_labs_key_finding', 'nlp_labs_n_entities', 'nlp_labs_n_notes', 'nlp_ne_complications_has_data', 'nlp_ne_complications_n_rows', 'nlp_ne_genetics_has_data', 'nlp_ne_genetics_n_rows', 'nlp_ne_medications_has_data', 'nlp_ne_medications_n_rows', 'nlp_ne_problemlist_has_data', 'nlp_ne_problemlist_n_rows', 'nlp_ne_staging_has_data', 'nlp_ne_staging_n_rows', 'nlp_physexam_has_data', 'nlp_physexam_key_finding', 'nlp_physexam_n_entities', 'nlp_physexam_n_notes', 'nlp_ptdecision_has_data', 'nlp_ptdecision_key_finding', 'nlp_ptdecision_n_entities', 'nlp_ptdecision_n_notes', 'nlp_radtx_has_data', 'nlp_radtx_key_finding', 'nlp_radtx_n_entities', 'nlp_radtx_n_notes', 'nlp_usnodule_has_data', 'nlp_usnodule_key_finding', 'nlp_usnodule_n_entities', 'nlp_usnodule_n_notes');

-- §B validation table is materialized by qc_framework_v1/scripts/apply_mig180b_nlp_upstream_lineage.py
SELECT * FROM main.val_mig180b_nlp_upstream_lineage_v1 ORDER BY family;

-- §C idempotent closure-note updates
UPDATE main.canonical_column_verification_registry_v1
SET notes = CASE WHEN notes IS NULL OR TRIM(notes) = '' THEN 'mig_180b CLOSED upstream-missing lineage CF for nlp_funcoutcome; source=Thyroid 2026 UPdated.archive_pub_v1_0.note_entities_llm_functional_outcomes_pre251_20260417T012311Z; decision=closed_source_found_pm_strict_subset; exact_replay_pass=FALSE; mismatch_total=956; no canonical_patient_master data mutation' WHEN POSITION('mig_180b CLOSED upstream-missing lineage CF for nlp_funcoutcome; source=Thyroid 2026 UPdated.archive_pub_v1_0.note_entities_llm_functional_outcomes_pre251_20260417T012311Z; decision=closed_source_found_pm_strict_subset; exact_replay_pass=FALSE; mismatch_total=956; no canonical_patient_master data mutation' IN notes) > 0 THEN notes ELSE notes || '; ' || 'mig_180b CLOSED upstream-missing lineage CF for nlp_funcoutcome; source=Thyroid 2026 UPdated.archive_pub_v1_0.note_entities_llm_functional_outcomes_pre251_20260417T012311Z; decision=closed_source_found_pm_strict_subset; exact_replay_pass=FALSE; mismatch_total=956; no canonical_patient_master data mutation' END
WHERE schema_name='main' AND table_name='canonical_patient_master'
  AND column_name IN ('nlp_funcoutcome_has_data', 'nlp_funcoutcome_key_finding', 'nlp_funcoutcome_n_entities', 'nlp_funcoutcome_n_notes');

UPDATE main.canonical_column_verification_registry_v1
SET notes = CASE WHEN notes IS NULL OR TRIM(notes) = '' THEN 'mig_180b CLOSED upstream-missing lineage CF for nlp_imaging; source=Thyroid 2026 UPdated.archive_pub_v1_0.note_entities_llm_imaging_pre251_20260417T012311Z; decision=closed_source_found_pm_strict_subset; exact_replay_pass=FALSE; mismatch_total=390; no canonical_patient_master data mutation' WHEN POSITION('mig_180b CLOSED upstream-missing lineage CF for nlp_imaging; source=Thyroid 2026 UPdated.archive_pub_v1_0.note_entities_llm_imaging_pre251_20260417T012311Z; decision=closed_source_found_pm_strict_subset; exact_replay_pass=FALSE; mismatch_total=390; no canonical_patient_master data mutation' IN notes) > 0 THEN notes ELSE notes || '; ' || 'mig_180b CLOSED upstream-missing lineage CF for nlp_imaging; source=Thyroid 2026 UPdated.archive_pub_v1_0.note_entities_llm_imaging_pre251_20260417T012311Z; decision=closed_source_found_pm_strict_subset; exact_replay_pass=FALSE; mismatch_total=390; no canonical_patient_master data mutation' END
WHERE schema_name='main' AND table_name='canonical_patient_master'
  AND column_name IN ('nlp_imaging_has_data', 'nlp_imaging_key_finding', 'nlp_imaging_n_entities', 'nlp_imaging_n_notes');

UPDATE main.canonical_column_verification_registry_v1
SET notes = CASE WHEN notes IS NULL OR TRIM(notes) = '' THEN 'mig_180b CLOSED upstream-missing lineage CF for nlp_labs; source=Thyroid 2026 UPdated.archive_pub_v1_0.note_entities_llm_labs_pre251_20260417T012311Z; decision=closed_source_found_pm_strict_subset; exact_replay_pass=FALSE; mismatch_total=188; no canonical_patient_master data mutation' WHEN POSITION('mig_180b CLOSED upstream-missing lineage CF for nlp_labs; source=Thyroid 2026 UPdated.archive_pub_v1_0.note_entities_llm_labs_pre251_20260417T012311Z; decision=closed_source_found_pm_strict_subset; exact_replay_pass=FALSE; mismatch_total=188; no canonical_patient_master data mutation' IN notes) > 0 THEN notes ELSE notes || '; ' || 'mig_180b CLOSED upstream-missing lineage CF for nlp_labs; source=Thyroid 2026 UPdated.archive_pub_v1_0.note_entities_llm_labs_pre251_20260417T012311Z; decision=closed_source_found_pm_strict_subset; exact_replay_pass=FALSE; mismatch_total=188; no canonical_patient_master data mutation' END
WHERE schema_name='main' AND table_name='canonical_patient_master'
  AND column_name IN ('nlp_labs_has_data', 'nlp_labs_key_finding', 'nlp_labs_n_entities', 'nlp_labs_n_notes');

UPDATE main.canonical_column_verification_registry_v1
SET notes = CASE WHEN notes IS NULL OR TRIM(notes) = '' THEN 'mig_180b CLOSED upstream-missing lineage CF for nlp_ne_complications; source=Thyroid 2026 UPdated.archive_pub_v1_0.note_entities_complications_pre364_20260422_050902; decision=closed_exact_replay; exact_replay_pass=TRUE; mismatch_total=0; no canonical_patient_master data mutation' WHEN POSITION('mig_180b CLOSED upstream-missing lineage CF for nlp_ne_complications; source=Thyroid 2026 UPdated.archive_pub_v1_0.note_entities_complications_pre364_20260422_050902; decision=closed_exact_replay; exact_replay_pass=TRUE; mismatch_total=0; no canonical_patient_master data mutation' IN notes) > 0 THEN notes ELSE notes || '; ' || 'mig_180b CLOSED upstream-missing lineage CF for nlp_ne_complications; source=Thyroid 2026 UPdated.archive_pub_v1_0.note_entities_complications_pre364_20260422_050902; decision=closed_exact_replay; exact_replay_pass=TRUE; mismatch_total=0; no canonical_patient_master data mutation' END
WHERE schema_name='main' AND table_name='canonical_patient_master'
  AND column_name IN ('nlp_ne_complications_has_data', 'nlp_ne_complications_n_rows');

UPDATE main.canonical_column_verification_registry_v1
SET notes = CASE WHEN notes IS NULL OR TRIM(notes) = '' THEN 'mig_180b CLOSED upstream-missing lineage CF for nlp_ne_genetics; source=Thyroid 2026 UPdated.molecular_legacy_20260421.note_entities_genetics; decision=closed_exact_replay; exact_replay_pass=TRUE; mismatch_total=0; no canonical_patient_master data mutation' WHEN POSITION('mig_180b CLOSED upstream-missing lineage CF for nlp_ne_genetics; source=Thyroid 2026 UPdated.molecular_legacy_20260421.note_entities_genetics; decision=closed_exact_replay; exact_replay_pass=TRUE; mismatch_total=0; no canonical_patient_master data mutation' IN notes) > 0 THEN notes ELSE notes || '; ' || 'mig_180b CLOSED upstream-missing lineage CF for nlp_ne_genetics; source=Thyroid 2026 UPdated.molecular_legacy_20260421.note_entities_genetics; decision=closed_exact_replay; exact_replay_pass=TRUE; mismatch_total=0; no canonical_patient_master data mutation' END
WHERE schema_name='main' AND table_name='canonical_patient_master'
  AND column_name IN ('nlp_ne_genetics_has_data', 'nlp_ne_genetics_n_rows');

UPDATE main.canonical_column_verification_registry_v1
SET notes = CASE WHEN notes IS NULL OR TRIM(notes) = '' THEN 'mig_180b CLOSED upstream-missing lineage CF for nlp_ne_medications; source=Thyroid 2026 UPdated.archive_pub_v1_0.note_entities_medications_pre365b_20260422_122116; decision=closed_exact_replay; exact_replay_pass=TRUE; mismatch_total=0; no canonical_patient_master data mutation' WHEN POSITION('mig_180b CLOSED upstream-missing lineage CF for nlp_ne_medications; source=Thyroid 2026 UPdated.archive_pub_v1_0.note_entities_medications_pre365b_20260422_122116; decision=closed_exact_replay; exact_replay_pass=TRUE; mismatch_total=0; no canonical_patient_master data mutation' IN notes) > 0 THEN notes ELSE notes || '; ' || 'mig_180b CLOSED upstream-missing lineage CF for nlp_ne_medications; source=Thyroid 2026 UPdated.archive_pub_v1_0.note_entities_medications_pre365b_20260422_122116; decision=closed_exact_replay; exact_replay_pass=TRUE; mismatch_total=0; no canonical_patient_master data mutation' END
WHERE schema_name='main' AND table_name='canonical_patient_master'
  AND column_name IN ('nlp_ne_medications_has_data', 'nlp_ne_medications_n_rows');

UPDATE main.canonical_column_verification_registry_v1
SET notes = CASE WHEN notes IS NULL OR TRIM(notes) = '' THEN 'mig_180b CLOSED upstream-missing lineage CF for nlp_ne_problemlist; source=Thyroid 2026 UPdated.archive_pub_v1_0.note_entities_problem_list_pre365b_20260422_122116; decision=closed_exact_replay; exact_replay_pass=TRUE; mismatch_total=0; no canonical_patient_master data mutation' WHEN POSITION('mig_180b CLOSED upstream-missing lineage CF for nlp_ne_problemlist; source=Thyroid 2026 UPdated.archive_pub_v1_0.note_entities_problem_list_pre365b_20260422_122116; decision=closed_exact_replay; exact_replay_pass=TRUE; mismatch_total=0; no canonical_patient_master data mutation' IN notes) > 0 THEN notes ELSE notes || '; ' || 'mig_180b CLOSED upstream-missing lineage CF for nlp_ne_problemlist; source=Thyroid 2026 UPdated.archive_pub_v1_0.note_entities_problem_list_pre365b_20260422_122116; decision=closed_exact_replay; exact_replay_pass=TRUE; mismatch_total=0; no canonical_patient_master data mutation' END
WHERE schema_name='main' AND table_name='canonical_patient_master'
  AND column_name IN ('nlp_ne_problemlist_has_data', 'nlp_ne_problemlist_n_rows');

UPDATE main.canonical_column_verification_registry_v1
SET notes = CASE WHEN notes IS NULL OR TRIM(notes) = '' THEN 'mig_180b CLOSED upstream-missing lineage CF for nlp_ne_staging; source=Thyroid 2026 UPdated.main.note_entities_staging_archived_20260422; decision=closed_exact_replay; exact_replay_pass=TRUE; mismatch_total=0; no canonical_patient_master data mutation' WHEN POSITION('mig_180b CLOSED upstream-missing lineage CF for nlp_ne_staging; source=Thyroid 2026 UPdated.main.note_entities_staging_archived_20260422; decision=closed_exact_replay; exact_replay_pass=TRUE; mismatch_total=0; no canonical_patient_master data mutation' IN notes) > 0 THEN notes ELSE notes || '; ' || 'mig_180b CLOSED upstream-missing lineage CF for nlp_ne_staging; source=Thyroid 2026 UPdated.main.note_entities_staging_archived_20260422; decision=closed_exact_replay; exact_replay_pass=TRUE; mismatch_total=0; no canonical_patient_master data mutation' END
WHERE schema_name='main' AND table_name='canonical_patient_master'
  AND column_name IN ('nlp_ne_staging_has_data', 'nlp_ne_staging_n_rows');

UPDATE main.canonical_column_verification_registry_v1
SET notes = CASE WHEN notes IS NULL OR TRIM(notes) = '' THEN 'mig_180b CLOSED upstream-missing lineage CF for nlp_physexam; source=Thyroid 2026 UPdated.archive_pub_v1_0.note_entities_llm_physical_exam_pre251_20260417T012311Z; decision=closed_source_found_pm_strict_subset; exact_replay_pass=FALSE; mismatch_total=688; no canonical_patient_master data mutation' WHEN POSITION('mig_180b CLOSED upstream-missing lineage CF for nlp_physexam; source=Thyroid 2026 UPdated.archive_pub_v1_0.note_entities_llm_physical_exam_pre251_20260417T012311Z; decision=closed_source_found_pm_strict_subset; exact_replay_pass=FALSE; mismatch_total=688; no canonical_patient_master data mutation' IN notes) > 0 THEN notes ELSE notes || '; ' || 'mig_180b CLOSED upstream-missing lineage CF for nlp_physexam; source=Thyroid 2026 UPdated.archive_pub_v1_0.note_entities_llm_physical_exam_pre251_20260417T012311Z; decision=closed_source_found_pm_strict_subset; exact_replay_pass=FALSE; mismatch_total=688; no canonical_patient_master data mutation' END
WHERE schema_name='main' AND table_name='canonical_patient_master'
  AND column_name IN ('nlp_physexam_has_data', 'nlp_physexam_key_finding', 'nlp_physexam_n_entities', 'nlp_physexam_n_notes');

UPDATE main.canonical_column_verification_registry_v1
SET notes = CASE WHEN notes IS NULL OR TRIM(notes) = '' THEN 'mig_180b CLOSED upstream-missing lineage CF for nlp_ptdecision; source=Thyroid 2026 UPdated.archive_pub_v1_0.note_entities_llm_patient_decision_adherence_pre251_20260417T012311Z; decision=closed_source_found_pm_strict_subset; exact_replay_pass=FALSE; mismatch_total=117; no canonical_patient_master data mutation' WHEN POSITION('mig_180b CLOSED upstream-missing lineage CF for nlp_ptdecision; source=Thyroid 2026 UPdated.archive_pub_v1_0.note_entities_llm_patient_decision_adherence_pre251_20260417T012311Z; decision=closed_source_found_pm_strict_subset; exact_replay_pass=FALSE; mismatch_total=117; no canonical_patient_master data mutation' IN notes) > 0 THEN notes ELSE notes || '; ' || 'mig_180b CLOSED upstream-missing lineage CF for nlp_ptdecision; source=Thyroid 2026 UPdated.archive_pub_v1_0.note_entities_llm_patient_decision_adherence_pre251_20260417T012311Z; decision=closed_source_found_pm_strict_subset; exact_replay_pass=FALSE; mismatch_total=117; no canonical_patient_master data mutation' END
WHERE schema_name='main' AND table_name='canonical_patient_master'
  AND column_name IN ('nlp_ptdecision_has_data', 'nlp_ptdecision_key_finding', 'nlp_ptdecision_n_entities', 'nlp_ptdecision_n_notes');

UPDATE main.canonical_column_verification_registry_v1
SET notes = CASE WHEN notes IS NULL OR TRIM(notes) = '' THEN 'mig_180b CLOSED upstream-missing lineage CF for nlp_radtx; source=Thyroid 2026 UPdated.archive_pub_v1_0.note_entities_llm_rad_treatment_pre251_20260417T012311Z; decision=closed_source_found_pm_strict_subset; exact_replay_pass=FALSE; mismatch_total=17; no canonical_patient_master data mutation' WHEN POSITION('mig_180b CLOSED upstream-missing lineage CF for nlp_radtx; source=Thyroid 2026 UPdated.archive_pub_v1_0.note_entities_llm_rad_treatment_pre251_20260417T012311Z; decision=closed_source_found_pm_strict_subset; exact_replay_pass=FALSE; mismatch_total=17; no canonical_patient_master data mutation' IN notes) > 0 THEN notes ELSE notes || '; ' || 'mig_180b CLOSED upstream-missing lineage CF for nlp_radtx; source=Thyroid 2026 UPdated.archive_pub_v1_0.note_entities_llm_rad_treatment_pre251_20260417T012311Z; decision=closed_source_found_pm_strict_subset; exact_replay_pass=FALSE; mismatch_total=17; no canonical_patient_master data mutation' END
WHERE schema_name='main' AND table_name='canonical_patient_master'
  AND column_name IN ('nlp_radtx_has_data', 'nlp_radtx_key_finding', 'nlp_radtx_n_entities', 'nlp_radtx_n_notes');

UPDATE main.canonical_column_verification_registry_v1
SET notes = CASE WHEN notes IS NULL OR TRIM(notes) = '' THEN 'mig_180b CLOSED upstream-missing lineage CF for nlp_usnodule; source=Thyroid 2026 UPdated.archive_pub_v1_0.note_entities_llm_us_nodule_dynamics_pre251_20260417T012311Z; decision=closed_source_found_pm_strict_subset; exact_replay_pass=FALSE; mismatch_total=3; no canonical_patient_master data mutation' WHEN POSITION('mig_180b CLOSED upstream-missing lineage CF for nlp_usnodule; source=Thyroid 2026 UPdated.archive_pub_v1_0.note_entities_llm_us_nodule_dynamics_pre251_20260417T012311Z; decision=closed_source_found_pm_strict_subset; exact_replay_pass=FALSE; mismatch_total=3; no canonical_patient_master data mutation' IN notes) > 0 THEN notes ELSE notes || '; ' || 'mig_180b CLOSED upstream-missing lineage CF for nlp_usnodule; source=Thyroid 2026 UPdated.archive_pub_v1_0.note_entities_llm_us_nodule_dynamics_pre251_20260417T012311Z; decision=closed_source_found_pm_strict_subset; exact_replay_pass=FALSE; mismatch_total=3; no canonical_patient_master data mutation' END
WHERE schema_name='main' AND table_name='canonical_patient_master'
  AND column_name IN ('nlp_usnodule_has_data', 'nlp_usnodule_key_finding', 'nlp_usnodule_n_entities', 'nlp_usnodule_n_notes');

-- §D post-apply closure probe
SELECT COUNT(*) AS n_affected_cols,
       COUNT(*) FILTER (WHERE POSITION('mig_180b CLOSED upstream-missing lineage CF' IN notes) > 0) AS n_closed_cols
FROM main.canonical_column_verification_registry_v1
WHERE schema_name='main' AND table_name='canonical_patient_master'
  AND column_name IN ('nlp_funcoutcome_has_data', 'nlp_funcoutcome_key_finding', 'nlp_funcoutcome_n_entities', 'nlp_funcoutcome_n_notes', 'nlp_imaging_has_data', 'nlp_imaging_key_finding', 'nlp_imaging_n_entities', 'nlp_imaging_n_notes', 'nlp_labs_has_data', 'nlp_labs_key_finding', 'nlp_labs_n_entities', 'nlp_labs_n_notes', 'nlp_ne_complications_has_data', 'nlp_ne_complications_n_rows', 'nlp_ne_genetics_has_data', 'nlp_ne_genetics_n_rows', 'nlp_ne_medications_has_data', 'nlp_ne_medications_n_rows', 'nlp_ne_problemlist_has_data', 'nlp_ne_problemlist_n_rows', 'nlp_ne_staging_has_data', 'nlp_ne_staging_n_rows', 'nlp_physexam_has_data', 'nlp_physexam_key_finding', 'nlp_physexam_n_entities', 'nlp_physexam_n_notes', 'nlp_ptdecision_has_data', 'nlp_ptdecision_key_finding', 'nlp_ptdecision_n_entities', 'nlp_ptdecision_n_notes', 'nlp_radtx_has_data', 'nlp_radtx_key_finding', 'nlp_radtx_n_entities', 'nlp_radtx_n_notes', 'nlp_usnodule_has_data', 'nlp_usnodule_key_finding', 'nlp_usnodule_n_entities', 'nlp_usnodule_n_notes');
