-- mig_184 — R1 AJCC derivation skeleton (PLACEHOLDER; DO NOT EXECUTE)
-- Target DB: thyroid_canonical_publication_v1_0
-- Governance: LOGAN MUST RATIFY RULES BEFORE EXECUTION.
-- This file is intentionally non-runnable: <TBD_LOGAN_RATIFIED_RULE_*> placeholders remain.

-- §0 pre-flight (apply lane only)
SELECT COUNT(*) AS cpm_rows, COUNT(DISTINCT research_id) AS cpm_distinct_research_id
FROM main.canonical_patient_master;

-- §A pre-snapshot of future write targets
-- LOGAN MUST RATIFY RULES BEFORE EXECUTION.
-- CREATE TABLE "Thyroid 2026 UPdated".archive_pub_v1_0.canonical_patient_master_pre_mig184_<UTC> AS
-- SELECT research_id, ajcc7_t_stage, ajcc7_n_stage, ajcc7_m_stage, ajcc7_stage_group,
--        ajcc8_t_stage, ajcc8_n_stage, ajcc8_m_stage, ajcc8_stage_group
-- FROM main.canonical_patient_master;

-- §B add resolved columns (PLACEHOLDER)
-- LOGAN MUST RATIFY RULES BEFORE EXECUTION.
-- ALTER TABLE main.canonical_path_malignant_events_v1 ADD COLUMN IF NOT EXISTS t_stage_ajcc8_resolved VARCHAR;
-- ALTER TABLE main.canonical_path_malignant_events_v1 ADD COLUMN IF NOT EXISTS n_stage_ajcc8_resolved VARCHAR;
-- ALTER TABLE main.canonical_path_malignant_events_v1 ADD COLUMN IF NOT EXISTS m_stage_ajcc8_resolved VARCHAR;
-- ALTER TABLE main.canonical_path_malignant_events_v1 ADD COLUMN IF NOT EXISTS t_stage_ajcc7_resolved VARCHAR;
-- ALTER TABLE main.canonical_path_malignant_events_v1 ADD COLUMN IF NOT EXISTS n_stage_ajcc7_resolved VARCHAR;
-- ALTER TABLE main.canonical_path_malignant_events_v1 ADD COLUMN IF NOT EXISTS m_stage_ajcc7_resolved VARCHAR;
-- ALTER TABLE main.canonical_path_malignant_events_v1 ADD COLUMN IF NOT EXISTS ajcc_resolution_source VARCHAR;
-- ALTER TABLE main.canonical_path_malignant_events_v1 ADD COLUMN IF NOT EXISTS ajcc_resolution_confidence VARCHAR;
-- ALTER TABLE main.canonical_path_malignant_events_v1 ADD COLUMN IF NOT EXISTS ajcc_logan_adjudicated_flag BOOLEAN;
-- ALTER TABLE main.canonical_patient_master ADD COLUMN IF NOT EXISTS ajcc8_t_stage_resolved VARCHAR;
-- ALTER TABLE main.canonical_patient_master ADD COLUMN IF NOT EXISTS ajcc8_n_stage_resolved VARCHAR;
-- ALTER TABLE main.canonical_patient_master ADD COLUMN IF NOT EXISTS ajcc8_m_stage_resolved VARCHAR;
-- ALTER TABLE main.canonical_patient_master ADD COLUMN IF NOT EXISTS ajcc8_stage_group_resolved VARCHAR;
-- ALTER TABLE main.canonical_patient_master ADD COLUMN IF NOT EXISTS ajcc7_t_stage_resolved VARCHAR;
-- ALTER TABLE main.canonical_patient_master ADD COLUMN IF NOT EXISTS ajcc7_n_stage_resolved VARCHAR;
-- ALTER TABLE main.canonical_patient_master ADD COLUMN IF NOT EXISTS ajcc7_m_stage_resolved VARCHAR;
-- ALTER TABLE main.canonical_patient_master ADD COLUMN IF NOT EXISTS ajcc7_stage_group_resolved VARCHAR;
-- ALTER TABLE main.canonical_patient_master ADD COLUMN IF NOT EXISTS ajcc_resolution_source VARCHAR;
-- ALTER TABLE main.canonical_patient_master ADD COLUMN IF NOT EXISTS ajcc_resolution_confidence VARCHAR;
-- ALTER TABLE main.canonical_patient_master ADD COLUMN IF NOT EXISTS ajcc_logan_adjudicated_flag BOOLEAN;

-- §C update from ratified derivation rules (PLACEHOLDER)
-- LOGAN MUST RATIFY RULES BEFORE EXECUTION.
-- WITH event_derivation AS (
--   SELECT research_id, surgery_episode_id, tumor_ordinal,
--          CASE
--            WHEN <TBD_LOGAN_RATIFIED_RULE_T4B_ANATOMIC_INVASION> THEN 'T4b'
--            WHEN <TBD_LOGAN_RATIFIED_RULE_T4A_ANATOMIC_INVASION> THEN 'T4a'
--            WHEN <TBD_LOGAN_RATIFIED_RULE_GROSS_ETE_TO_T3B> THEN 'T3b'
--            WHEN size_greatest_dimension_cm <= 1 THEN 'T1a'
--            WHEN size_greatest_dimension_cm <= 2 THEN 'T1b'
--            WHEN size_greatest_dimension_cm <= 4 THEN 'T2'
--            WHEN size_greatest_dimension_cm > 4 THEN 'T3a'
--          END AS t_stage_ajcc8_resolved,
--          CASE
--            WHEN <TBD_LOGAN_RATIFIED_RULE_N1B_LOCATION> THEN 'N1b'
--            WHEN <TBD_LOGAN_RATIFIED_RULE_N1A_LOCATION> THEN 'N1a'
--            WHEN ln_involved > 0 THEN 'N1'
--            WHEN ln_examined > 0 AND COALESCE(ln_involved, 0) = 0 THEN 'N0'
--          END AS n_stage_ajcc8_resolved,
--          <TBD_LOGAN_RATIFIED_RULE_M_STAGE_SOURCE> AS m_stage_ajcc8_resolved
--   FROM main.canonical_path_malignant_events_v1
-- )
-- UPDATE main.canonical_path_malignant_events_v1 AS tgt
-- SET t_stage_ajcc8_resolved = src.t_stage_ajcc8_resolved,
--     n_stage_ajcc8_resolved = src.n_stage_ajcc8_resolved,
--     m_stage_ajcc8_resolved = src.m_stage_ajcc8_resolved,
--     ajcc_resolution_source = 'mig184_r1_ratified_findings_derivation',
--     ajcc_resolution_confidence = <TBD_LOGAN_RATIFIED_CONFIDENCE_RULE>,
--     ajcc_logan_adjudicated_flag = <TBD_LOGAN_RATIFIED_FLAG_RULE>
-- FROM event_derivation AS src
-- WHERE CAST(tgt.research_id AS VARCHAR) = CAST(src.research_id AS VARCHAR)
--   AND tgt.surgery_episode_id IS NOT DISTINCT FROM src.surgery_episode_id
--   AND tgt.tumor_ordinal IS NOT DISTINCT FROM src.tumor_ordinal;

-- §D registry note appendix closing CF-87-AJCC (PLACEHOLDER)
-- LOGAN MUST RATIFY RULES BEFORE EXECUTION.
-- UPDATE main.canonical_column_verification_registry_v1
-- SET notes = notes || ' | mig184: CF-87-AJCC closed by Logan-ratified R1 resolved AJCC derivation; legacy columns preserved.'
-- WHERE notes ILIKE '%CF-87-AJCC%' OR notes ILIKE '%CF-87%AJCC%';

-- §E provenance row insert (PLACEHOLDER)
-- LOGAN MUST RATIFY RULES BEFORE EXECUTION.
-- INSERT INTO manuscript_workspace.cpm_reconciliation_provenance_v1
--   (run_id, started_at, ended_at, phases_applied, critical_findings_cleared, high_findings_cleared, med_findings_cleared, held_for_adjudication)
-- VALUES
--   ('mig_184_r1_ajcc_apply_<DATE>', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'ajcc7_8_resolved_derivation', 'CF-87-AJCC', 'TBD', 'TBD', 'TBD');
