-- =============================================================================
-- mig_241: LN safe-view promotion to semantic_publication (3 views)
-- Generated: 2026-05-01 by Cline Sonnet 4.6 (mig_241 dispatch — v17 round)
-- Batch: mig_241_ln_safe_promotion
-- =============================================================================
-- Context: Lane LN (mig_224–229) shipped 3 LN-domain publication-safe views in
-- manuscript_workspace for prototyping speed.  They are now stable and used by
-- Lane M Methods.  This migration promotes them into semantic_publication (the
-- analyst SSOT) with release_id and research_id::VARCHAR.
--
-- Source views (manuscript_workspace — stay in place, do NOT drop):
--   vw_ln_patient_publication_safe_VIEW_v1       9 cols  4 008 rows
--   vw_ln_surgery_publication_safe_VIEW_v1      10 cols  4 008 rows
--   vw_ln_histology_attribution_VIEW_v1         74 cols  5 918 rows
--
-- Target views (semantic_publication — net-new):
--   vw_ln_patient_safe_VIEW_v1                  10 cols  (release_id + 9)
--   vw_ln_surgery_safe_VIEW_v1                  11 cols  (release_id + 10)
--   vw_ln_histology_attribution_safe_VIEW_v1    75 cols  (release_id + 74)
--
-- CROSS JOIN to semantic_publication.release_manifest_v1 (single row) adds release_id.
-- research_id CAST to VARCHAR per mig_239 convention.
-- =============================================================================

-- ─────────────────────────────────────────────────────────────────────────────
-- ── VIEW 1: vw_ln_patient_safe_VIEW_v1
-- ─────────────────────────────────────────────────────────────────────────────

CREATE OR REPLACE VIEW semantic_publication.vw_ln_patient_safe_VIEW_v1 AS
SELECT
    r.release_id,
    CAST(src.research_id AS VARCHAR)          AS research_id,
    src.ln_total_examined_safe,
    src.ln_total_positive_safe,
    src.n_impossible_surgery_ln_rows,
    src.ln_attribution_ambiguous_any,
    src.ln_denominator_source_conflict_any,
    src.cpm_ln_rollup_total_examined,
    src.cpm_ln_rollup_total_positive,
    src.ln_crossval_status
FROM manuscript_workspace.vw_ln_patient_publication_safe_VIEW_v1 src
CROSS JOIN semantic_publication.release_manifest_v1 r
;

-- ─────────────────────────────────────────────────────────────────────────────
-- ── VIEW 2: vw_ln_surgery_safe_VIEW_v1
-- ─────────────────────────────────────────────────────────────────────────────

CREATE OR REPLACE VIEW semantic_publication.vw_ln_surgery_safe_VIEW_v1 AS
SELECT
    r.release_id,
    CAST(src.research_id AS VARCHAR)          AS research_id,
    src.surgery_key,
    src.n_histologies_surgery,
    src.ln_examined_double,
    src.nodal_disease_total_count_int,
    src.ln_examined_safe,
    src.ln_positive_safe,
    src.ln_denominator_source_conflict_flag,
    src.ln_attribution_ambiguous_flag,
    src.ln_impossible_count_flag
FROM manuscript_workspace.vw_ln_surgery_publication_safe_VIEW_v1 src
CROSS JOIN semantic_publication.release_manifest_v1 r
;

-- ─────────────────────────────────────────────────────────────────────────────
-- ── VIEW 3: vw_ln_histology_attribution_safe_VIEW_v1
-- ─────────────────────────────────────────────────────────────────────────────

CREATE OR REPLACE VIEW semantic_publication.vw_ln_histology_attribution_safe_VIEW_v1 AS
SELECT
    r.release_id,
    CAST(src.research_id AS VARCHAR)          AS research_id,
    src.surgery_episode_id,
    src.tumor_ordinal,
    src.surgery_date,
    src.path_surgery_id,
    src.specimen_id,
    src.synoptic_row_ix,
    src.laterality,
    src.site,
    src.size_greatest_dimension_cm,
    src.tumor_size_cm_per_surgery,
    src.primary_histology,
    src.histology_variant,
    src.histology_source,
    src.extrathyroidal_extension,
    src.gross_ete,
    src.lymphatic_invasion,
    src.vascular_invasion,
    src.angioinvasion_quantify,
    src.perineural_invasion,
    src.capsular_invasion,
    src.margin_status,
    src.ln_examined,
    src.ln_involved,
    src.nodal_disease_positive_count,
    src.nodal_disease_total_count,
    src.extranodal_extension,
    src.number_of_tumors,
    src.multifocality_flag,
    src.source_tables,
    src.resolution_rule,
    src.data_completeness_pct,
    src.t_stage_ajcc7,
    src.n_stage_ajcc7,
    src.m_stage_ajcc7,
    src.overall_stage_ajcc7,
    src.stage_group_ajcc7,
    src.t_stage_ajcc8,
    src.n_stage_ajcc8,
    src.m_stage_ajcc8,
    src.overall_stage_ajcc8,
    src.stage_group_ajcc8,
    src.ajcc7_stage_calculable_flag,
    src.ajcc8_stage_calculable_flag,
    src.staging_source_note,
    src.stage_migration_7_to_8,
    src.discordance_histology_flag,
    src.discordance_t_stage_flag,
    src.discordance_laterality_flag,
    src.discordance_notes,
    src.specimen_focus_id,
    src.linkage_confidence_tier,
    src.linkage_score,
    src.build_script,
    src.build_ts,
    src.consolidation_source,
    src.t_stage_ajcc8_resolved,
    src.n_stage_ajcc8_resolved,
    src.m_stage_ajcc8_resolved,
    src.t_stage_ajcc7_resolved,
    src.n_stage_ajcc7_resolved,
    src.m_stage_ajcc7_resolved,
    src.ajcc_resolution_source,
    src.ajcc_resolution_confidence,
    src.is_source_distinct_duplicate_grain,
    src.is_borderline_or_benign_with_staging,
    src.surgery_key,
    src.surgery_n_histologies,
    src.surgery_ln_positive_safe,
    src.surgery_ln_examined_safe,
    src.surgery_distinct_ln_pos_patterns,
    src.ln_mets_tumor_types_array_any,
    src.ln_mets_histology_specific_evidence,
    src.ln_attribution_confidence
FROM manuscript_workspace.vw_ln_histology_attribution_VIEW_v1 src
CROSS JOIN semantic_publication.release_manifest_v1 r
;

-- =============================================================================
-- ── Register columns in canonical_column_verification_registry_v1 ────────────
-- =============================================================================

-- ── VIEW 1: vw_ln_patient_safe_VIEW_v1 (10 columns) ─────────────────────────

INSERT INTO main.canonical_column_verification_registry_v1
    (schema_name, table_name, column_name, data_type, ordinal_position,
     category, upstream_source, verification_status, verified_by, verified_ts,
     verification_method, batch_id, notes)
VALUES
    ('semantic_publication', 'vw_ln_patient_safe_VIEW_v1', 'release_id', 'VARCHAR', 1,
     'identifier',
     'semantic_publication.release_manifest_v1 (CROSS JOIN)',
     'verified', 'cline_sonnet_4_6_mig_241', CURRENT_TIMESTAMP,
     'view_create_safe_view_promotion',
     'mig_241_ln_safe_promotion',
     'mig_241 (2026-05-01): LN patient-level safe view promoted from manuscript_workspace to semantic_publication. release_id from CROSS JOIN to single-row release_manifest_v1.'),
    ('semantic_publication', 'vw_ln_patient_safe_VIEW_v1', 'research_id', 'VARCHAR', 2,
     'identifier',
     'manuscript_workspace.vw_ln_patient_publication_safe_VIEW_v1.research_id (CAST INTEGER→VARCHAR)',
     'verified', 'cline_sonnet_4_6_mig_241', CURRENT_TIMESTAMP,
     'view_create_safe_view_promotion',
     'mig_241_ln_safe_promotion',
     'mig_239 convention: research_id cast to VARCHAR for cross-domain join uniformity.'),
    ('semantic_publication', 'vw_ln_patient_safe_VIEW_v1', 'ln_total_examined_safe', 'DOUBLE', 3,
     'clinical_measure',
     'manuscript_workspace.vw_ln_patient_publication_safe_VIEW_v1.ln_total_examined_safe',
     'verified', 'cline_sonnet_4_6_mig_241', CURRENT_TIMESTAMP,
     'view_create_safe_view_promotion',
     'mig_241_ln_safe_promotion',
     'mig_241: patient-level total LN examined (quality-filtered, impossible rows excluded).'),
    ('semantic_publication', 'vw_ln_patient_safe_VIEW_v1', 'ln_total_positive_safe', 'HUGEINT', 4,
     'clinical_measure',
     'manuscript_workspace.vw_ln_patient_publication_safe_VIEW_v1.ln_total_positive_safe',
     'verified', 'cline_sonnet_4_6_mig_241', CURRENT_TIMESTAMP,
     'view_create_safe_view_promotion',
     'mig_241_ln_safe_promotion',
     'mig_241: patient-level total LN positive (quality-filtered, impossible rows excluded).'),
    ('semantic_publication', 'vw_ln_patient_safe_VIEW_v1', 'n_impossible_surgery_ln_rows', 'HUGEINT', 5,
     'data_quality',
     'manuscript_workspace.vw_ln_patient_publication_safe_VIEW_v1.n_impossible_surgery_ln_rows',
     'verified', 'cline_sonnet_4_6_mig_241', CURRENT_TIMESTAMP,
     'view_create_safe_view_promotion',
     'mig_241_ln_safe_promotion',
     'mig_241: count of surgery rows excluded for impossible LN counts (positive > examined).'),
    ('semantic_publication', 'vw_ln_patient_safe_VIEW_v1', 'ln_attribution_ambiguous_any', 'BOOLEAN', 6,
     'data_quality',
     'manuscript_workspace.vw_ln_patient_publication_safe_VIEW_v1.ln_attribution_ambiguous_any',
     'verified', 'cline_sonnet_4_6_mig_241', CURRENT_TIMESTAMP,
     'view_create_safe_view_promotion',
     'mig_241_ln_safe_promotion',
     'mig_241: TRUE if any surgery for this patient has ambiguous LN attribution across histologies.'),
    ('semantic_publication', 'vw_ln_patient_safe_VIEW_v1', 'ln_denominator_source_conflict_any', 'BOOLEAN', 7,
     'data_quality',
     'manuscript_workspace.vw_ln_patient_publication_safe_VIEW_v1.ln_denominator_source_conflict_any',
     'verified', 'cline_sonnet_4_6_mig_241', CURRENT_TIMESTAMP,
     'view_create_safe_view_promotion',
     'mig_241_ln_safe_promotion',
     'mig_241: TRUE if any surgery has conflicting LN denominator values across source tables.'),
    ('semantic_publication', 'vw_ln_patient_safe_VIEW_v1', 'cpm_ln_rollup_total_examined', 'BIGINT', 8,
     'clinical_measure',
     'manuscript_workspace.vw_ln_patient_publication_safe_VIEW_v1.cpm_ln_rollup_total_examined',
     'verified', 'cline_sonnet_4_6_mig_241', CURRENT_TIMESTAMP,
     'view_create_safe_view_promotion',
     'mig_241_ln_safe_promotion',
     'mig_241: total LN examined from CPM rollup (cross-validation reference).'),
    ('semantic_publication', 'vw_ln_patient_safe_VIEW_v1', 'cpm_ln_rollup_total_positive', 'BIGINT', 9,
     'clinical_measure',
     'manuscript_workspace.vw_ln_patient_publication_safe_VIEW_v1.cpm_ln_rollup_total_positive',
     'verified', 'cline_sonnet_4_6_mig_241', CURRENT_TIMESTAMP,
     'view_create_safe_view_promotion',
     'mig_241_ln_safe_promotion',
     'mig_241: total LN positive from CPM rollup (cross-validation reference).'),
    ('semantic_publication', 'vw_ln_patient_safe_VIEW_v1', 'ln_crossval_status', 'VARCHAR', 10,
     'data_quality',
     'manuscript_workspace.vw_ln_patient_publication_safe_VIEW_v1.ln_crossval_status',
     'verified', 'cline_sonnet_4_6_mig_241', CURRENT_TIMESTAMP,
     'view_create_safe_view_promotion',
     'mig_241_ln_safe_promotion',
     'mig_241: cross-validation status comparing LN counts from path events vs CPM rollup (e.g. match, mismatch, cpm_only).')
;

-- ── VIEW 2: vw_ln_surgery_safe_VIEW_v1 (11 columns) ─────────────────────────

INSERT INTO main.canonical_column_verification_registry_v1
    (schema_name, table_name, column_name, data_type, ordinal_position,
     category, upstream_source, verification_status, verified_by, verified_ts,
     verification_method, batch_id, notes)
VALUES
    ('semantic_publication', 'vw_ln_surgery_safe_VIEW_v1', 'release_id', 'VARCHAR', 1,
     'identifier',
     'semantic_publication.release_manifest_v1 (CROSS JOIN)',
     'verified', 'cline_sonnet_4_6_mig_241', CURRENT_TIMESTAMP,
     'view_create_safe_view_promotion',
     'mig_241_ln_safe_promotion',
     'mig_241 (2026-05-01): LN surgery-level safe view promoted from manuscript_workspace to semantic_publication. release_id from CROSS JOIN to single-row release_manifest_v1.'),
    ('semantic_publication', 'vw_ln_surgery_safe_VIEW_v1', 'research_id', 'VARCHAR', 2,
     'identifier',
     'manuscript_workspace.vw_ln_surgery_publication_safe_VIEW_v1.research_id (CAST INTEGER→VARCHAR)',
     'verified', 'cline_sonnet_4_6_mig_241', CURRENT_TIMESTAMP,
     'view_create_safe_view_promotion',
     'mig_241_ln_safe_promotion',
     'mig_239 convention: research_id cast to VARCHAR for cross-domain join uniformity.'),
    ('semantic_publication', 'vw_ln_surgery_safe_VIEW_v1', 'surgery_key', 'VARCHAR', 3,
     'identifier',
     'manuscript_workspace.vw_ln_surgery_publication_safe_VIEW_v1.surgery_key',
     'verified', 'cline_sonnet_4_6_mig_241', CURRENT_TIMESTAMP,
     'view_create_safe_view_promotion',
     'mig_241_ln_safe_promotion',
     'mig_241: surrogate key uniquely identifying the surgery episode (research_id + surgery sequence).'),
    ('semantic_publication', 'vw_ln_surgery_safe_VIEW_v1', 'n_histologies_surgery', 'BIGINT', 4,
     'clinical_measure',
     'manuscript_workspace.vw_ln_surgery_publication_safe_VIEW_v1.n_histologies_surgery',
     'verified', 'cline_sonnet_4_6_mig_241', CURRENT_TIMESTAMP,
     'view_create_safe_view_promotion',
     'mig_241_ln_safe_promotion',
     'mig_241: number of distinct histology records associated with this surgery.'),
    ('semantic_publication', 'vw_ln_surgery_safe_VIEW_v1', 'ln_examined_double', 'DOUBLE', 5,
     'clinical_measure',
     'manuscript_workspace.vw_ln_surgery_publication_safe_VIEW_v1.ln_examined_double',
     'verified', 'cline_sonnet_4_6_mig_241', CURRENT_TIMESTAMP,
     'view_create_safe_view_promotion',
     'mig_241_ln_safe_promotion',
     'mig_241: raw LN examined value as DOUBLE before quality filtering.'),
    ('semantic_publication', 'vw_ln_surgery_safe_VIEW_v1', 'nodal_disease_total_count_int', 'BIGINT', 6,
     'clinical_measure',
     'manuscript_workspace.vw_ln_surgery_publication_safe_VIEW_v1.nodal_disease_total_count_int',
     'verified', 'cline_sonnet_4_6_mig_241', CURRENT_TIMESTAMP,
     'view_create_safe_view_promotion',
     'mig_241_ln_safe_promotion',
     'mig_241: total nodal disease count (positive LN) as integer before quality filtering.'),
    ('semantic_publication', 'vw_ln_surgery_safe_VIEW_v1', 'ln_examined_safe', 'DOUBLE', 7,
     'clinical_measure',
     'manuscript_workspace.vw_ln_surgery_publication_safe_VIEW_v1.ln_examined_safe',
     'verified', 'cline_sonnet_4_6_mig_241', CURRENT_TIMESTAMP,
     'view_create_safe_view_promotion',
     'mig_241_ln_safe_promotion',
     'mig_241: LN examined after quality filtering (impossible rows nulled). Use this for analysis.'),
    ('semantic_publication', 'vw_ln_surgery_safe_VIEW_v1', 'ln_positive_safe', 'BIGINT', 8,
     'clinical_measure',
     'manuscript_workspace.vw_ln_surgery_publication_safe_VIEW_v1.ln_positive_safe',
     'verified', 'cline_sonnet_4_6_mig_241', CURRENT_TIMESTAMP,
     'view_create_safe_view_promotion',
     'mig_241_ln_safe_promotion',
     'mig_241: LN positive after quality filtering (impossible rows nulled). Use this for analysis.'),
    ('semantic_publication', 'vw_ln_surgery_safe_VIEW_v1', 'ln_denominator_source_conflict_flag', 'BOOLEAN', 9,
     'data_quality',
     'manuscript_workspace.vw_ln_surgery_publication_safe_VIEW_v1.ln_denominator_source_conflict_flag',
     'verified', 'cline_sonnet_4_6_mig_241', CURRENT_TIMESTAMP,
     'view_create_safe_view_promotion',
     'mig_241_ln_safe_promotion',
     'mig_241: TRUE if LN denominator values conflict across source tables for this surgery.'),
    ('semantic_publication', 'vw_ln_surgery_safe_VIEW_v1', 'ln_attribution_ambiguous_flag', 'BOOLEAN', 10,
     'data_quality',
     'manuscript_workspace.vw_ln_surgery_publication_safe_VIEW_v1.ln_attribution_ambiguous_flag',
     'verified', 'cline_sonnet_4_6_mig_241', CURRENT_TIMESTAMP,
     'view_create_safe_view_promotion',
     'mig_241_ln_safe_promotion',
     'mig_241: TRUE if LN attribution to histology type is ambiguous for this surgery.'),
    ('semantic_publication', 'vw_ln_surgery_safe_VIEW_v1', 'ln_impossible_count_flag', 'BOOLEAN', 11,
     'data_quality',
     'manuscript_workspace.vw_ln_surgery_publication_safe_VIEW_v1.ln_impossible_count_flag',
     'verified', 'cline_sonnet_4_6_mig_241', CURRENT_TIMESTAMP,
     'view_create_safe_view_promotion',
     'mig_241_ln_safe_promotion',
     'mig_241: TRUE if LN positive > LN examined for this surgery (data integrity flag).')
;

-- ── VIEW 3: vw_ln_histology_attribution_safe_VIEW_v1 (75 columns) ────────────

INSERT INTO main.canonical_column_verification_registry_v1
    (schema_name, table_name, column_name, data_type, ordinal_position,
     category, upstream_source, verification_status, verified_by, verified_ts,
     verification_method, batch_id, notes)
VALUES
    ('semantic_publication', 'vw_ln_histology_attribution_safe_VIEW_v1', 'release_id', 'VARCHAR', 1,
     'identifier', 'semantic_publication.release_manifest_v1 (CROSS JOIN)',
     'verified', 'cline_sonnet_4_6_mig_241', CURRENT_TIMESTAMP,
     'view_create_safe_view_promotion', 'mig_241_ln_safe_promotion',
     'mig_241 (2026-05-01): LN histology-attribution safe view promoted from manuscript_workspace. release_id from CROSS JOIN.'),
    ('semantic_publication', 'vw_ln_histology_attribution_safe_VIEW_v1', 'research_id', 'VARCHAR', 2,
     'identifier', 'manuscript_workspace.vw_ln_histology_attribution_VIEW_v1.research_id (CAST INTEGER→VARCHAR)',
     'verified', 'cline_sonnet_4_6_mig_241', CURRENT_TIMESTAMP,
     'view_create_safe_view_promotion', 'mig_241_ln_safe_promotion',
     'mig_239 convention: research_id cast to VARCHAR.'),
    ('semantic_publication', 'vw_ln_histology_attribution_safe_VIEW_v1', 'surgery_episode_id', 'BIGINT', 3,
     'identifier', 'manuscript_workspace.vw_ln_histology_attribution_VIEW_v1.surgery_episode_id',
     'verified', 'cline_sonnet_4_6_mig_241', CURRENT_TIMESTAMP,
     'view_create_safe_view_promotion', 'mig_241_ln_safe_promotion',
     'mig_241: surgery episode identifier within patient.'),
    ('semantic_publication', 'vw_ln_histology_attribution_safe_VIEW_v1', 'tumor_ordinal', 'BIGINT', 4,
     'identifier', 'manuscript_workspace.vw_ln_histology_attribution_VIEW_v1.tumor_ordinal',
     'verified', 'cline_sonnet_4_6_mig_241', CURRENT_TIMESTAMP,
     'view_create_safe_view_promotion', 'mig_241_ln_safe_promotion',
     'mig_241: ordinal position of this tumor within the surgery specimen.'),
    ('semantic_publication', 'vw_ln_histology_attribution_safe_VIEW_v1', 'surgery_date', 'DATE', 5,
     'date', 'manuscript_workspace.vw_ln_histology_attribution_VIEW_v1.surgery_date',
     'verified', 'cline_sonnet_4_6_mig_241', CURRENT_TIMESTAMP,
     'view_create_safe_view_promotion', 'mig_241_ln_safe_promotion',
     'mig_241: date of the surgery.'),
    ('semantic_publication', 'vw_ln_histology_attribution_safe_VIEW_v1', 'path_surgery_id', 'BIGINT', 6,
     'identifier', 'manuscript_workspace.vw_ln_histology_attribution_VIEW_v1.path_surgery_id',
     'verified', 'cline_sonnet_4_6_mig_241', CURRENT_TIMESTAMP,
     'view_create_safe_view_promotion', 'mig_241_ln_safe_promotion',
     'mig_241: pathology surgery surrogate key.'),
    ('semantic_publication', 'vw_ln_histology_attribution_safe_VIEW_v1', 'specimen_id', 'VARCHAR', 7,
     'identifier', 'manuscript_workspace.vw_ln_histology_attribution_VIEW_v1.specimen_id',
     'verified', 'cline_sonnet_4_6_mig_241', CURRENT_TIMESTAMP,
     'view_create_safe_view_promotion', 'mig_241_ln_safe_promotion',
     'mig_241: pathology specimen identifier.'),
    ('semantic_publication', 'vw_ln_histology_attribution_safe_VIEW_v1', 'synoptic_row_ix', 'BIGINT', 8,
     'metadata', 'manuscript_workspace.vw_ln_histology_attribution_VIEW_v1.synoptic_row_ix',
     'verified', 'cline_sonnet_4_6_mig_241', CURRENT_TIMESTAMP,
     'view_create_safe_view_promotion', 'mig_241_ln_safe_promotion',
     'mig_241: row index within path_synoptics source table.'),
    ('semantic_publication', 'vw_ln_histology_attribution_safe_VIEW_v1', 'laterality', 'VARCHAR', 9,
     'clinical_measure', 'manuscript_workspace.vw_ln_histology_attribution_VIEW_v1.laterality',
     'verified', 'cline_sonnet_4_6_mig_241', CURRENT_TIMESTAMP,
     'view_create_safe_view_promotion', 'mig_241_ln_safe_promotion',
     'mig_241: laterality of the tumor (left/right/isthmus/bilateral).'),
    ('semantic_publication', 'vw_ln_histology_attribution_safe_VIEW_v1', 'site', 'VARCHAR', 10,
     'clinical_measure', 'manuscript_workspace.vw_ln_histology_attribution_VIEW_v1.site',
     'verified', 'cline_sonnet_4_6_mig_241', CURRENT_TIMESTAMP,
     'view_create_safe_view_promotion', 'mig_241_ln_safe_promotion',
     'mig_241: anatomic site of the tumor within the thyroid.'),
    ('semantic_publication', 'vw_ln_histology_attribution_safe_VIEW_v1', 'size_greatest_dimension_cm', 'DOUBLE', 11,
     'clinical_measure', 'manuscript_workspace.vw_ln_histology_attribution_VIEW_v1.size_greatest_dimension_cm',
     'verified', 'cline_sonnet_4_6_mig_241', CURRENT_TIMESTAMP,
     'view_create_safe_view_promotion', 'mig_241_ln_safe_promotion',
     'mig_241: greatest dimension of the tumor in cm.'),
    ('semantic_publication', 'vw_ln_histology_attribution_safe_VIEW_v1', 'tumor_size_cm_per_surgery', 'DOUBLE', 12,
     'clinical_measure', 'manuscript_workspace.vw_ln_histology_attribution_VIEW_v1.tumor_size_cm_per_surgery',
     'verified', 'cline_sonnet_4_6_mig_241', CURRENT_TIMESTAMP,
     'view_create_safe_view_promotion', 'mig_241_ln_safe_promotion',
     'mig_241: tumor size (cm) resolved at surgery level.'),
    ('semantic_publication', 'vw_ln_histology_attribution_safe_VIEW_v1', 'primary_histology', 'VARCHAR', 13,
     'clinical_measure', 'manuscript_workspace.vw_ln_histology_attribution_VIEW_v1.primary_histology',
     'verified', 'cline_sonnet_4_6_mig_241', CURRENT_TIMESTAMP,
     'view_create_safe_view_promotion', 'mig_241_ln_safe_promotion',
     'mig_241: primary histologic diagnosis.'),
    ('semantic_publication', 'vw_ln_histology_attribution_safe_VIEW_v1', 'histology_variant', 'VARCHAR', 14,
     'clinical_measure', 'manuscript_workspace.vw_ln_histology_attribution_VIEW_v1.histology_variant',
     'verified', 'cline_sonnet_4_6_mig_241', CURRENT_TIMESTAMP,
     'view_create_safe_view_promotion', 'mig_241_ln_safe_promotion',
     'mig_241: histologic variant (e.g. follicular, tall cell).'),
    ('semantic_publication', 'vw_ln_histology_attribution_safe_VIEW_v1', 'histology_source', 'VARCHAR', 15,
     'metadata', 'manuscript_workspace.vw_ln_histology_attribution_VIEW_v1.histology_source',
     'verified', 'cline_sonnet_4_6_mig_241', CURRENT_TIMESTAMP,
     'view_create_safe_view_promotion', 'mig_241_ln_safe_promotion',
     'mig_241: provenance source for the histology value.'),
    ('semantic_publication', 'vw_ln_histology_attribution_safe_VIEW_v1', 'extrathyroidal_extension', 'VARCHAR', 16,
     'clinical_measure', 'manuscript_workspace.vw_ln_histology_attribution_VIEW_v1.extrathyroidal_extension',
     'verified', 'cline_sonnet_4_6_mig_241', CURRENT_TIMESTAMP,
     'view_create_safe_view_promotion', 'mig_241_ln_safe_promotion',
     'mig_241: ETE grade (none/microscopic/gross/present_ungraded).'),
    ('semantic_publication', 'vw_ln_histology_attribution_safe_VIEW_v1', 'gross_ete', 'BIGINT', 17,
     'clinical_flag', 'manuscript_workspace.vw_ln_histology_attribution_VIEW_v1.gross_ete',
     'verified', 'cline_sonnet_4_6_mig_241', CURRENT_TIMESTAMP,
     'view_create_safe_view_promotion', 'mig_241_ln_safe_promotion',
     'mig_241: 1 if gross ETE present, 0 otherwise.'),
    ('semantic_publication', 'vw_ln_histology_attribution_safe_VIEW_v1', 'lymphatic_invasion', 'VARCHAR', 18,
     'clinical_measure', 'manuscript_workspace.vw_ln_histology_attribution_VIEW_v1.lymphatic_invasion',
     'verified', 'cline_sonnet_4_6_mig_241', CURRENT_TIMESTAMP,
     'view_create_safe_view_promotion', 'mig_241_ln_safe_promotion',
     'mig_241: lymphatic (LVI) invasion status.'),
    ('semantic_publication', 'vw_ln_histology_attribution_safe_VIEW_v1', 'vascular_invasion', 'VARCHAR', 19,
     'clinical_measure', 'manuscript_workspace.vw_ln_histology_attribution_VIEW_v1.vascular_invasion',
     'verified', 'cline_sonnet_4_6_mig_241', CURRENT_TIMESTAMP,
     'view_create_safe_view_promotion', 'mig_241_ln_safe_promotion',
     'mig_241: vascular invasion status.'),
    ('semantic_publication', 'vw_ln_histology_attribution_safe_VIEW_v1', 'angioinvasion_quantify', 'DOUBLE', 20,
     'clinical_measure', 'manuscript_workspace.vw_ln_histology_attribution_VIEW_v1.angioinvasion_quantify',
     'verified', 'cline_sonnet_4_6_mig_241', CURRENT_TIMESTAMP,
     'view_create_safe_view_promotion', 'mig_241_ln_safe_promotion',
     'mig_241: number of angioinvasion foci (vessel count for WHO 2022 grading).'),
    ('semantic_publication', 'vw_ln_histology_attribution_safe_VIEW_v1', 'perineural_invasion', 'VARCHAR', 21,
     'clinical_measure', 'manuscript_workspace.vw_ln_histology_attribution_VIEW_v1.perineural_invasion',
     'verified', 'cline_sonnet_4_6_mig_241', CURRENT_TIMESTAMP,
     'view_create_safe_view_promotion', 'mig_241_ln_safe_promotion',
     'mig_241: perineural invasion status.'),
    ('semantic_publication', 'vw_ln_histology_attribution_safe_VIEW_v1', 'capsular_invasion', 'VARCHAR', 22,
     'clinical_measure', 'manuscript_workspace.vw_ln_histology_attribution_VIEW_v1.capsular_invasion',
     'verified', 'cline_sonnet_4_6_mig_241', CURRENT_TIMESTAMP,
     'view_create_safe_view_promotion', 'mig_241_ln_safe_promotion',
     'mig_241: capsular invasion status.'),
    ('semantic_publication', 'vw_ln_histology_attribution_safe_VIEW_v1', 'margin_status', 'VARCHAR', 23,
     'clinical_measure', 'manuscript_workspace.vw_ln_histology_attribution_VIEW_v1.margin_status',
     'verified', 'cline_sonnet_4_6_mig_241', CURRENT_TIMESTAMP,
     'view_create_safe_view_promotion', 'mig_241_ln_safe_promotion',
     'mig_241: surgical margin status (positive/negative/close).'),
    ('semantic_publication', 'vw_ln_histology_attribution_safe_VIEW_v1', 'ln_examined', 'DOUBLE', 24,
     'clinical_measure', 'manuscript_workspace.vw_ln_histology_attribution_VIEW_v1.ln_examined',
     'verified', 'cline_sonnet_4_6_mig_241', CURRENT_TIMESTAMP,
     'view_create_safe_view_promotion', 'mig_241_ln_safe_promotion',
     'mig_241: LN examined for this histology row.'),
    ('semantic_publication', 'vw_ln_histology_attribution_safe_VIEW_v1', 'ln_involved', 'DOUBLE', 25,
     'clinical_measure', 'manuscript_workspace.vw_ln_histology_attribution_VIEW_v1.ln_involved',
     'verified', 'cline_sonnet_4_6_mig_241', CURRENT_TIMESTAMP,
     'view_create_safe_view_promotion', 'mig_241_ln_safe_promotion',
     'mig_241: LN involved (positive) for this histology row.'),
    ('semantic_publication', 'vw_ln_histology_attribution_safe_VIEW_v1', 'nodal_disease_positive_count', 'INTEGER', 26,
     'clinical_measure', 'manuscript_workspace.vw_ln_histology_attribution_VIEW_v1.nodal_disease_positive_count',
     'verified', 'cline_sonnet_4_6_mig_241', CURRENT_TIMESTAMP,
     'view_create_safe_view_promotion', 'mig_241_ln_safe_promotion',
     'mig_241: nodal disease positive count.'),
    ('semantic_publication', 'vw_ln_histology_attribution_safe_VIEW_v1', 'nodal_disease_total_count', 'INTEGER', 27,
     'clinical_measure', 'manuscript_workspace.vw_ln_histology_attribution_VIEW_v1.nodal_disease_total_count',
     'verified', 'cline_sonnet_4_6_mig_241', CURRENT_TIMESTAMP,
     'view_create_safe_view_promotion', 'mig_241_ln_safe_promotion',
     'mig_241: nodal disease total count.'),
    ('semantic_publication', 'vw_ln_histology_attribution_safe_VIEW_v1', 'extranodal_extension', 'VARCHAR', 28,
     'clinical_measure', 'manuscript_workspace.vw_ln_histology_attribution_VIEW_v1.extranodal_extension',
     'verified', 'cline_sonnet_4_6_mig_241', CURRENT_TIMESTAMP,
     'view_create_safe_view_promotion', 'mig_241_ln_safe_promotion',
     'mig_241: extranodal extension status.'),
    ('semantic_publication', 'vw_ln_histology_attribution_safe_VIEW_v1', 'number_of_tumors', 'INTEGER', 29,
     'clinical_measure', 'manuscript_workspace.vw_ln_histology_attribution_VIEW_v1.number_of_tumors',
     'verified', 'cline_sonnet_4_6_mig_241', CURRENT_TIMESTAMP,
     'view_create_safe_view_promotion', 'mig_241_ln_safe_promotion',
     'mig_241: number of tumors in the specimen.'),
    ('semantic_publication', 'vw_ln_histology_attribution_safe_VIEW_v1', 'multifocality_flag', 'BOOLEAN', 30,
     'clinical_flag', 'manuscript_workspace.vw_ln_histology_attribution_VIEW_v1.multifocality_flag',
     'verified', 'cline_sonnet_4_6_mig_241', CURRENT_TIMESTAMP,
     'view_create_safe_view_promotion', 'mig_241_ln_safe_promotion',
     'mig_241: TRUE if multifocal disease present.'),
    ('semantic_publication', 'vw_ln_histology_attribution_safe_VIEW_v1', 'source_tables', 'VARCHAR', 31,
     'metadata', 'manuscript_workspace.vw_ln_histology_attribution_VIEW_v1.source_tables',
     'verified', 'cline_sonnet_4_6_mig_241', CURRENT_TIMESTAMP,
     'view_create_safe_view_promotion', 'mig_241_ln_safe_promotion',
     'mig_241: pipe-delimited list of source tables contributing to this row.'),
    ('semantic_publication', 'vw_ln_histology_attribution_safe_VIEW_v1', 'resolution_rule', 'VARCHAR', 32,
     'metadata', 'manuscript_workspace.vw_ln_histology_attribution_VIEW_v1.resolution_rule',
     'verified', 'cline_sonnet_4_6_mig_241', CURRENT_TIMESTAMP,
     'view_create_safe_view_promotion', 'mig_241_ln_safe_promotion',
     'mig_241: conflict resolution rule applied when merging sources.'),
    ('semantic_publication', 'vw_ln_histology_attribution_safe_VIEW_v1', 'data_completeness_pct', 'DOUBLE', 33,
     'data_quality', 'manuscript_workspace.vw_ln_histology_attribution_VIEW_v1.data_completeness_pct',
     'verified', 'cline_sonnet_4_6_mig_241', CURRENT_TIMESTAMP,
     'view_create_safe_view_promotion', 'mig_241_ln_safe_promotion',
     'mig_241: percentage of key fields populated for this row.'),
    ('semantic_publication', 'vw_ln_histology_attribution_safe_VIEW_v1', 't_stage_ajcc7', 'VARCHAR', 34,
     'clinical_measure', 'manuscript_workspace.vw_ln_histology_attribution_VIEW_v1.t_stage_ajcc7',
     'verified', 'cline_sonnet_4_6_mig_241', CURRENT_TIMESTAMP,
     'view_create_safe_view_promotion', 'mig_241_ln_safe_promotion',
     'mig_241: AJCC 7th edition T stage.'),
    ('semantic_publication', 'vw_ln_histology_attribution_safe_VIEW_v1', 'n_stage_ajcc7', 'VARCHAR', 35,
     'clinical_measure', 'manuscript_workspace.vw_ln_histology_attribution_VIEW_v1.n_stage_ajcc7',
     'verified', 'cline_sonnet_4_6_mig_241', CURRENT_TIMESTAMP,
     'view_create_safe_view_promotion', 'mig_241_ln_safe_promotion',
     'mig_241: AJCC 7th edition N stage.'),
    ('semantic_publication', 'vw_ln_histology_attribution_safe_VIEW_v1', 'm_stage_ajcc7', 'VARCHAR', 36,
     'clinical_measure', 'manuscript_workspace.vw_ln_histology_attribution_VIEW_v1.m_stage_ajcc7',
     'verified', 'cline_sonnet_4_6_mig_241', CURRENT_TIMESTAMP,
     'view_create_safe_view_promotion', 'mig_241_ln_safe_promotion',
     'mig_241: AJCC 7th edition M stage.'),
    ('semantic_publication', 'vw_ln_histology_attribution_safe_VIEW_v1', 'overall_stage_ajcc7', 'VARCHAR', 37,
     'clinical_measure', 'manuscript_workspace.vw_ln_histology_attribution_VIEW_v1.overall_stage_ajcc7',
     'verified', 'cline_sonnet_4_6_mig_241', CURRENT_TIMESTAMP,
     'view_create_safe_view_promotion', 'mig_241_ln_safe_promotion',
     'mig_241: AJCC 7th edition overall stage.'),
    ('semantic_publication', 'vw_ln_histology_attribution_safe_VIEW_v1', 'stage_group_ajcc7', 'VARCHAR', 38,
     'clinical_measure', 'manuscript_workspace.vw_ln_histology_attribution_VIEW_v1.stage_group_ajcc7',
     'verified', 'cline_sonnet_4_6_mig_241', CURRENT_TIMESTAMP,
     'view_create_safe_view_promotion', 'mig_241_ln_safe_promotion',
     'mig_241: AJCC 7th edition stage group.'),
    ('semantic_publication', 'vw_ln_histology_attribution_safe_VIEW_v1', 't_stage_ajcc8', 'VARCHAR', 39,
     'clinical_measure', 'manuscript_workspace.vw_ln_histology_attribution_VIEW_v1.t_stage_ajcc8',
     'verified', 'cline_sonnet_4_6_mig_241', CURRENT_TIMESTAMP,
     'view_create_safe_view_promotion', 'mig_241_ln_safe_promotion',
     'mig_241: AJCC 8th edition T stage.'),
    ('semantic_publication', 'vw_ln_histology_attribution_safe_VIEW_v1', 'n_stage_ajcc8', 'VARCHAR', 40,
     'clinical_measure', 'manuscript_workspace.vw_ln_histology_attribution_VIEW_v1.n_stage_ajcc8',
     'verified', 'cline_sonnet_4_6_mig_241', CURRENT_TIMESTAMP,
     'view_create_safe_view_promotion', 'mig_241_ln_safe_promotion',
     'mig_241: AJCC 8th edition N stage.'),
    ('semantic_publication', 'vw_ln_histology_attribution_safe_VIEW_v1', 'm_stage_ajcc8', 'VARCHAR', 41,
     'clinical_measure', 'manuscript_workspace.vw_ln_histology_attribution_VIEW_v1.m_stage_ajcc8',
     'verified', 'cline_sonnet_4_6_mig_241', CURRENT_TIMESTAMP,
     'view_create_safe_view_promotion', 'mig_241_ln_safe_promotion',
     'mig_241: AJCC 8th edition M stage.'),
    ('semantic_publication', 'vw_ln_histology_attribution_safe_VIEW_v1', 'overall_stage_ajcc8', 'VARCHAR', 42,
     'clinical_measure', 'manuscript_workspace.vw_ln_histology_attribution_VIEW_v1.overall_stage_ajcc8',
     'verified', 'cline_sonnet_4_6_mig_241', CURRENT_TIMESTAMP,
     'view_create_safe_view_promotion', 'mig_241_ln_safe_promotion',
     'mig_241: AJCC 8th edition overall stage.'),
    ('semantic_publication', 'vw_ln_histology_attribution_safe_VIEW_v1', 'stage_group_ajcc8', 'VARCHAR', 43,
     'clinical_measure', 'manuscript_workspace.vw_ln_histology_attribution_VIEW_v1.stage_group_ajcc8',
     'verified', 'cline_sonnet_4_6_mig_241', CURRENT_TIMESTAMP,
     'view_create_safe_view_promotion', 'mig_241_ln_safe_promotion',
     'mig_241: AJCC 8th edition stage group.'),
    ('semantic_publication', 'vw_ln_histology_attribution_safe_VIEW_v1', 'ajcc7_stage_calculable_flag', 'BOOLEAN', 44,
     'data_quality', 'manuscript_workspace.vw_ln_histology_attribution_VIEW_v1.ajcc7_stage_calculable_flag',
     'verified', 'cline_sonnet_4_6_mig_241', CURRENT_TIMESTAMP,
     'view_create_safe_view_promotion', 'mig_241_ln_safe_promotion',
     'mig_241: TRUE if required inputs for AJCC7 staging were available.'),
    ('semantic_publication', 'vw_ln_histology_attribution_safe_VIEW_v1', 'ajcc8_stage_calculable_flag', 'BOOLEAN', 45,
     'data_quality', 'manuscript_workspace.vw_ln_histology_attribution_VIEW_v1.ajcc8_stage_calculable_flag',
     'verified', 'cline_sonnet_4_6_mig_241', CURRENT_TIMESTAMP,
     'view_create_safe_view_promotion', 'mig_241_ln_safe_promotion',
     'mig_241: TRUE if required inputs for AJCC8 staging were available.'),
    ('semantic_publication', 'vw_ln_histology_attribution_safe_VIEW_v1', 'staging_source_note', 'VARCHAR', 46,
     'metadata', 'manuscript_workspace.vw_ln_histology_attribution_VIEW_v1.staging_source_note',
     'verified', 'cline_sonnet_4_6_mig_241', CURRENT_TIMESTAMP,
     'view_create_safe_view_promotion', 'mig_241_ln_safe_promotion',
     'mig_241: free-text note on the staging data source.'),
    ('semantic_publication', 'vw_ln_histology_attribution_safe_VIEW_v1', 'stage_migration_7_to_8', 'VARCHAR', 47,
     'clinical_measure', 'manuscript_workspace.vw_ln_histology_attribution_VIEW_v1.stage_migration_7_to_8',
     'verified', 'cline_sonnet_4_6_mig_241', CURRENT_TIMESTAMP,
     'view_create_safe_view_promotion', 'mig_241_ln_safe_promotion',
     'mig_241: stage migration direction from AJCC7 to AJCC8 (upstaged/downstaged/unchanged).'),
    ('semantic_publication', 'vw_ln_histology_attribution_safe_VIEW_v1', 'discordance_histology_flag', 'BOOLEAN', 48,
     'data_quality', 'manuscript_workspace.vw_ln_histology_attribution_VIEW_v1.discordance_histology_flag',
     'verified', 'cline_sonnet_4_6_mig_241', CURRENT_TIMESTAMP,
     'view_create_safe_view_promotion', 'mig_241_ln_safe_promotion',
     'mig_241: TRUE if histology type is discordant across source tables.'),
    ('semantic_publication', 'vw_ln_histology_attribution_safe_VIEW_v1', 'discordance_t_stage_flag', 'BOOLEAN', 49,
     'data_quality', 'manuscript_workspace.vw_ln_histology_attribution_VIEW_v1.discordance_t_stage_flag',
     'verified', 'cline_sonnet_4_6_mig_241', CURRENT_TIMESTAMP,
     'view_create_safe_view_promotion', 'mig_241_ln_safe_promotion',
     'mig_241: TRUE if T stage is discordant across source tables.'),
    ('semantic_publication', 'vw_ln_histology_attribution_safe_VIEW_v1', 'discordance_laterality_flag', 'BOOLEAN', 50,
     'data_quality', 'manuscript_workspace.vw_ln_histology_attribution_VIEW_v1.discordance_laterality_flag',
     'verified', 'cline_sonnet_4_6_mig_241', CURRENT_TIMESTAMP,
     'view_create_safe_view_promotion', 'mig_241_ln_safe_promotion',
     'mig_241: TRUE if laterality is discordant across source tables.'),
    ('semantic_publication', 'vw_ln_histology_attribution_safe_VIEW_v1', 'discordance_notes', 'VARCHAR', 51,
     'metadata', 'manuscript_workspace.vw_ln_histology_attribution_VIEW_v1.discordance_notes',
     'verified', 'cline_sonnet_4_6_mig_241', CURRENT_TIMESTAMP,
     'view_create_safe_view_promotion', 'mig_241_ln_safe_promotion',
     'mig_241: free-text notes on discordances found.'),
    ('semantic_publication', 'vw_ln_histology_attribution_safe_VIEW_v1', 'specimen_focus_id', 'VARCHAR', 52,
     'identifier', 'manuscript_workspace.vw_ln_histology_attribution_VIEW_v1.specimen_focus_id',
     'verified', 'cline_sonnet_4_6_mig_241', CURRENT_TIMESTAMP,
     'view_create_safe_view_promotion', 'mig_241_ln_safe_promotion',
     'mig_241: unique focus identifier within the specimen.'),
    ('semantic_publication', 'vw_ln_histology_attribution_safe_VIEW_v1', 'linkage_confidence_tier', 'VARCHAR', 53,
     'metadata', 'manuscript_workspace.vw_ln_histology_attribution_VIEW_v1.linkage_confidence_tier',
     'verified', 'cline_sonnet_4_6_mig_241', CURRENT_TIMESTAMP,
     'view_create_safe_view_promotion', 'mig_241_ln_safe_promotion',
     'mig_241: linkage confidence tier for pathology-surgery join.'),
    ('semantic_publication', 'vw_ln_histology_attribution_safe_VIEW_v1', 'linkage_score', 'DECIMAL(29,3)', 54,
     'metadata', 'manuscript_workspace.vw_ln_histology_attribution_VIEW_v1.linkage_score',
     'verified', 'cline_sonnet_4_6_mig_241', CURRENT_TIMESTAMP,
     'view_create_safe_view_promotion', 'mig_241_ln_safe_promotion',
     'mig_241: numeric linkage score (0–1) for pathology-surgery join.'),
    ('semantic_publication', 'vw_ln_histology_attribution_safe_VIEW_v1', 'build_script', 'VARCHAR', 55,
     'metadata', 'manuscript_workspace.vw_ln_histology_attribution_VIEW_v1.build_script',
     'verified', 'cline_sonnet_4_6_mig_241', CURRENT_TIMESTAMP,
     'view_create_safe_view_promotion', 'mig_241_ln_safe_promotion',
     'mig_241: script that built the upstream source view.'),
    ('semantic_publication', 'vw_ln_histology_attribution_safe_VIEW_v1', 'build_ts', 'TIMESTAMP', 56,
     'metadata', 'manuscript_workspace.vw_ln_histology_attribution_VIEW_v1.build_ts',
     'verified', 'cline_sonnet_4_6_mig_241', CURRENT_TIMESTAMP,
     'view_create_safe_view_promotion', 'mig_241_ln_safe_promotion',
     'mig_241: timestamp when the upstream source view was last built.'),
    ('semantic_publication', 'vw_ln_histology_attribution_safe_VIEW_v1', 'consolidation_source', 'VARCHAR', 57,
     'metadata', 'manuscript_workspace.vw_ln_histology_attribution_VIEW_v1.consolidation_source',
     'verified', 'cline_sonnet_4_6_mig_241', CURRENT_TIMESTAMP,
     'view_create_safe_view_promotion', 'mig_241_ln_safe_promotion',
     'mig_241: which consolidation pass produced this row.'),
    ('semantic_publication', 'vw_ln_histology_attribution_safe_VIEW_v1', 't_stage_ajcc8_resolved', 'VARCHAR', 58,
     'clinical_measure', 'manuscript_workspace.vw_ln_histology_attribution_VIEW_v1.t_stage_ajcc8_resolved',
     'verified', 'cline_sonnet_4_6_mig_241', CURRENT_TIMESTAMP,
     'view_create_safe_view_promotion', 'mig_241_ln_safe_promotion',
     'mig_241: AJCC8 T stage after multi-source resolution.'),
    ('semantic_publication', 'vw_ln_histology_attribution_safe_VIEW_v1', 'n_stage_ajcc8_resolved', 'VARCHAR', 59,
     'clinical_measure', 'manuscript_workspace.vw_ln_histology_attribution_VIEW_v1.n_stage_ajcc8_resolved',
     'verified', 'cline_sonnet_4_6_mig_241', CURRENT_TIMESTAMP,
     'view_create_safe_view_promotion', 'mig_241_ln_safe_promotion',
     'mig_241: AJCC8 N stage after multi-source resolution.'),
    ('semantic_publication', 'vw_ln_histology_attribution_safe_VIEW_v1', 'm_stage_ajcc8_resolved', 'VARCHAR', 60,
     'clinical_measure', 'manuscript_workspace.vw_ln_histology_attribution_VIEW_v1.m_stage_ajcc8_resolved',
     'verified', 'cline_sonnet_4_6_mig_241', CURRENT_TIMESTAMP,
     'view_create_safe_view_promotion', 'mig_241_ln_safe_promotion',
     'mig_241: AJCC8 M stage after multi-source resolution.'),
    ('semantic_publication', 'vw_ln_histology_attribution_safe_VIEW_v1', 't_stage_ajcc7_resolved', 'VARCHAR', 61,
     'clinical_measure', 'manuscript_workspace.vw_ln_histology_attribution_VIEW_v1.t_stage_ajcc7_resolved',
     'verified', 'cline_sonnet_4_6_mig_241', CURRENT_TIMESTAMP,
     'view_create_safe_view_promotion', 'mig_241_ln_safe_promotion',
     'mig_241: AJCC7 T stage after multi-source resolution.'),
    ('semantic_publication', 'vw_ln_histology_attribution_safe_VIEW_v1', 'n_stage_ajcc7_resolved', 'VARCHAR', 62,
     'clinical_measure', 'manuscript_workspace.vw_ln_histology_attribution_VIEW_v1.n_stage_ajcc7_resolved',
     'verified', 'cline_sonnet_4_6_mig_241', CURRENT_TIMESTAMP,
     'view_create_safe_view_promotion', 'mig_241_ln_safe_promotion',
     'mig_241: AJCC7 N stage after multi-source resolution.'),
    ('semantic_publication', 'vw_ln_histology_attribution_safe_VIEW_v1', 'm_stage_ajcc7_resolved', 'VARCHAR', 63,
     'clinical_measure', 'manuscript_workspace.vw_ln_histology_attribution_VIEW_v1.m_stage_ajcc7_resolved',
     'verified', 'cline_sonnet_4_6_mig_241', CURRENT_TIMESTAMP,
     'view_create_safe_view_promotion', 'mig_241_ln_safe_promotion',
     'mig_241: AJCC7 M stage after multi-source resolution.'),
    ('semantic_publication', 'vw_ln_histology_attribution_safe_VIEW_v1', 'ajcc_resolution_source', 'VARCHAR', 64,
     'metadata', 'manuscript_workspace.vw_ln_histology_attribution_VIEW_v1.ajcc_resolution_source',
     'verified', 'cline_sonnet_4_6_mig_241', CURRENT_TIMESTAMP,
     'view_create_safe_view_promotion', 'mig_241_ln_safe_promotion',
     'mig_241: source table used for AJCC stage resolution.'),
    ('semantic_publication', 'vw_ln_histology_attribution_safe_VIEW_v1', 'ajcc_resolution_confidence', 'VARCHAR', 65,
     'metadata', 'manuscript_workspace.vw_ln_histology_attribution_VIEW_v1.ajcc_resolution_confidence',
     'verified', 'cline_sonnet_4_6_mig_241', CURRENT_TIMESTAMP,
     'view_create_safe_view_promotion', 'mig_241_ln_safe_promotion',
     'mig_241: confidence tier for the AJCC stage resolution.'),
    ('semantic_publication', 'vw_ln_histology_attribution_safe_VIEW_v1', 'is_source_distinct_duplicate_grain', 'BOOLEAN', 66,
     'data_quality', 'manuscript_workspace.vw_ln_histology_attribution_VIEW_v1.is_source_distinct_duplicate_grain',
     'verified', 'cline_sonnet_4_6_mig_241', CURRENT_TIMESTAMP,
     'view_create_safe_view_promotion', 'mig_241_ln_safe_promotion',
     'mig_241: TRUE if this row represents a duplicate grain from distinct source tables.'),
    ('semantic_publication', 'vw_ln_histology_attribution_safe_VIEW_v1', 'is_borderline_or_benign_with_staging', 'BOOLEAN', 67,
     'data_quality', 'manuscript_workspace.vw_ln_histology_attribution_VIEW_v1.is_borderline_or_benign_with_staging',
     'verified', 'cline_sonnet_4_6_mig_241', CURRENT_TIMESTAMP,
     'view_create_safe_view_promotion', 'mig_241_ln_safe_promotion',
     'mig_241: TRUE if this row has borderline/benign histology but was assigned staging (quarantine flag).'),
    ('semantic_publication', 'vw_ln_histology_attribution_safe_VIEW_v1', 'surgery_key', 'VARCHAR', 68,
     'identifier', 'manuscript_workspace.vw_ln_histology_attribution_VIEW_v1.surgery_key',
     'verified', 'cline_sonnet_4_6_mig_241', CURRENT_TIMESTAMP,
     'view_create_safe_view_promotion', 'mig_241_ln_safe_promotion',
     'mig_241: surrogate surgery key (matches vw_ln_surgery_safe_VIEW_v1.surgery_key for join).'),
    ('semantic_publication', 'vw_ln_histology_attribution_safe_VIEW_v1', 'surgery_n_histologies', 'BIGINT', 69,
     'clinical_measure', 'manuscript_workspace.vw_ln_histology_attribution_VIEW_v1.surgery_n_histologies',
     'verified', 'cline_sonnet_4_6_mig_241', CURRENT_TIMESTAMP,
     'view_create_safe_view_promotion', 'mig_241_ln_safe_promotion',
     'mig_241: number of histologies for the surgery (denormalized from surgery grain).'),
    ('semantic_publication', 'vw_ln_histology_attribution_safe_VIEW_v1', 'surgery_ln_positive_safe', 'BIGINT', 70,
     'clinical_measure', 'manuscript_workspace.vw_ln_histology_attribution_VIEW_v1.surgery_ln_positive_safe',
     'verified', 'cline_sonnet_4_6_mig_241', CURRENT_TIMESTAMP,
     'view_create_safe_view_promotion', 'mig_241_ln_safe_promotion',
     'mig_241: surgery-level quality-filtered LN positive count (denormalized).'),
    ('semantic_publication', 'vw_ln_histology_attribution_safe_VIEW_v1', 'surgery_ln_examined_safe', 'DOUBLE', 71,
     'clinical_measure', 'manuscript_workspace.vw_ln_histology_attribution_VIEW_v1.surgery_ln_examined_safe',
     'verified', 'cline_sonnet_4_6_mig_241', CURRENT_TIMESTAMP,
     'view_create_safe_view_promotion', 'mig_241_ln_safe_promotion',
     'mig_241: surgery-level quality-filtered LN examined count (denormalized).'),
    ('semantic_publication', 'vw_ln_histology_attribution_safe_VIEW_v1', 'surgery_distinct_ln_pos_patterns', 'BIGINT', 72,
     'data_quality', 'manuscript_workspace.vw_ln_histology_attribution_VIEW_v1.surgery_distinct_ln_pos_patterns',
     'verified', 'cline_sonnet_4_6_mig_241', CURRENT_TIMESTAMP,
     'view_create_safe_view_promotion', 'mig_241_ln_safe_promotion',
     'mig_241: number of distinct LN positive count patterns seen across histologies for this surgery.'),
    ('semantic_publication', 'vw_ln_histology_attribution_safe_VIEW_v1', 'ln_mets_tumor_types_array_any', 'VARCHAR', 73,
     'clinical_measure', 'manuscript_workspace.vw_ln_histology_attribution_VIEW_v1.ln_mets_tumor_types_array_any',
     'verified', 'cline_sonnet_4_6_mig_241', CURRENT_TIMESTAMP,
     'view_create_safe_view_promotion', 'mig_241_ln_safe_promotion',
     'mig_241: array (as string) of histology types with LN metastases present.'),
    ('semantic_publication', 'vw_ln_histology_attribution_safe_VIEW_v1', 'ln_mets_histology_specific_evidence', 'BOOLEAN', 74,
     'clinical_flag', 'manuscript_workspace.vw_ln_histology_attribution_VIEW_v1.ln_mets_histology_specific_evidence',
     'verified', 'cline_sonnet_4_6_mig_241', CURRENT_TIMESTAMP,
     'view_create_safe_view_promotion', 'mig_241_ln_safe_promotion',
     'mig_241: TRUE if histology-specific evidence for LN metastases is present.'),
    ('semantic_publication', 'vw_ln_histology_attribution_safe_VIEW_v1', 'ln_attribution_confidence', 'VARCHAR', 75,
     'metadata', 'manuscript_workspace.vw_ln_histology_attribution_VIEW_v1.ln_attribution_confidence',
     'verified', 'cline_sonnet_4_6_mig_241', CURRENT_TIMESTAMP,
     'view_create_safe_view_promotion', 'mig_241_ln_safe_promotion',
     'mig_241: confidence level for LN attribution to specific histology type (high/medium/low/ambiguous).')
;

-- =============================================================================
-- ── Register views in canonical_table_signoff_registry_v1 ────────────────────
-- =============================================================================

INSERT INTO main.canonical_table_signoff_registry_v1
    (schema_name, table_name, n_columns_total, n_verified, n_not_started, n_failed, n_na,
     table_status, signed_off_ts, signoff_migration, priority_tier, notes)
VALUES
    ('semantic_publication', 'vw_ln_patient_safe_VIEW_v1',
     10, 10, 0, 0, 0,
     'verified',
     CURRENT_TIMESTAMP,
     'qc_framework_v1/migrations/241_ln_safe_view_promotion_to_semantic_publication_20260501.sql',
     'tier2_canonical_view',
     'mig_241 (2026-05-01): patient-level LN safe view promoted from manuscript_workspace.vw_ln_patient_publication_safe_VIEW_v1. 10 cols (release_id + research_id::VARCHAR + 8 LN measures). 4008 rows. Source manuscript_workspace view stays in place. batch_id=mig_241_ln_safe_promotion.'),
    ('semantic_publication', 'vw_ln_surgery_safe_VIEW_v1',
     11, 11, 0, 0, 0,
     'verified',
     CURRENT_TIMESTAMP,
     'qc_framework_v1/migrations/241_ln_safe_view_promotion_to_semantic_publication_20260501.sql',
     'tier2_canonical_view',
     'mig_241 (2026-05-01): surgery-level LN safe view promoted from manuscript_workspace.vw_ln_surgery_publication_safe_VIEW_v1. 11 cols (release_id + research_id::VARCHAR + 9 LN measures). 4008 rows. Source manuscript_workspace view stays in place. batch_id=mig_241_ln_safe_promotion.'),
    ('semantic_publication', 'vw_ln_histology_attribution_safe_VIEW_v1',
     75, 75, 0, 0, 0,
     'verified',
     CURRENT_TIMESTAMP,
     'qc_framework_v1/migrations/241_ln_safe_view_promotion_to_semantic_publication_20260501.sql',
     'tier2_canonical_view',
     'mig_241 (2026-05-01): histology-attribution LN safe view promoted from manuscript_workspace.vw_ln_histology_attribution_VIEW_v1. 75 cols (release_id + research_id::VARCHAR + 73 cols). 5918 rows. Source manuscript_workspace view stays in place. batch_id=mig_241_ln_safe_promotion.')
;

-- =============================================================================
-- ── Path-C verification queries (run after apply) ────────────────────────────
-- =============================================================================
-- SELECT COUNT(*) FROM semantic_publication.vw_ln_patient_safe_VIEW_v1;
--   expected: 4008
-- SELECT COUNT(*) FROM semantic_publication.vw_ln_surgery_safe_VIEW_v1;
--   expected: 4008
-- SELECT COUNT(*) FROM semantic_publication.vw_ln_histology_attribution_safe_VIEW_v1;
--   expected: 5918
-- SELECT * FROM semantic_publication.vw_publication_qc_status_VIEW_v1;
--   expected: gate1 = 217 (214 + 3), gates 2-5 = 0, cohort_parity_ok = TRUE
