-- =============================================================================
-- mig_249 — manuscript_workspace.manuscript_feasibility_v1 re-refresh
-- Date:    2026-05-01
-- DB:      thyroid_canonical_publication_v1_0
--
-- Post-mig_248: resolves key_variables via cohort_descriptive_full_cohort_v1
-- aliases (tumor_size_cm, tirads_*_v12, syn_*_legacy_raw, rai_received_flag).
-- Generated by scripts/_mig249_build_feasibility_re_refresh.py
-- =============================================================================

USE "thyroid_canonical_publication_v1_0";
USE main;

-- M001 Patient characteristics and outcomes for patients with cytologically i
UPDATE manuscript_workspace.manuscript_feasibility_v1 SET candidate_n = 1266, variable_coverage_pct = [46.23, 8.92, 8.92, 38.06, 80.33]::DOUBLE[], feasibility_color = 'RED', gating_issues = 'Molecular coverage 40% in Beth III/IV post-v17 feasibility YELLOW→RED (coverage/cohort reassessed).', recommended_next_step = 'Analyze tested vs untested subgroups', canonical_version_at_scoring = 'v1_0_post_mig_248', scored_at = CAST(CURRENT_TIMESTAMP AS TIMESTAMP WITH TIME ZONE) WHERE manuscript_id = 1;

-- M002 Patient characteristics and outcomes for Lobectomy vs. total thyroidec
UPDATE manuscript_workspace.manuscript_feasibility_v1 SET candidate_n = 539, variable_coverage_pct = [80.33, 8.92, 38.06, 23.61, 100.0]::DOUBLE[], feasibility_color = 'RED', gating_issues = 'TSH/Tg coverage low in tested cohort', recommended_next_step = 'Focus on surgical outcomes; labs secondary', canonical_version_at_scoring = 'v1_0_post_mig_248', scored_at = CAST(CURRENT_TIMESTAMP AS TIMESTAMP WITH TIME ZONE) WHERE manuscript_id = 2;

-- M003 genetic analysis, mutational changes correlations with lab values.
UPDATE manuscript_workspace.manuscript_feasibility_v1 SET candidate_n = 969, variable_coverage_pct = [2.91, 6.47, 100.0, 38.06]::DOUBLE[], feasibility_color = 'RED', gating_issues = 'TSH lab coverage less than 10pct in molecular cohort', recommended_next_step = 'Wait for v1_1 lab pull; analyze mutations standalone', canonical_version_at_scoring = 'v1_0_post_mig_248', scored_at = CAST(CURRENT_TIMESTAMP AS TIMESTAMP WITH TIME ZONE) WHERE manuscript_id = 3;

-- M004 Graves versus hashimotos with thyroid cancer
UPDATE manuscript_workspace.manuscript_feasibility_v1 SET candidate_n = 1761, variable_coverage_pct = [5.28, 2.28, 100.0, 37.99, 37.35, 38.06]::DOUBLE[], feasibility_color = 'RED', gating_issues = 'N=822 Graves+Hashimoto+thyroiditis', recommended_next_step = 'Focus on malignancy rates; path detail for malig subset only', canonical_version_at_scoring = 'v1_0_post_mig_248', scored_at = CAST(CURRENT_TIMESTAMP AS TIMESTAMP WITH TIME ZONE) WHERE manuscript_id = 4;

-- M005 Medications: immunologic medications - pembro, ipilimumab, methimazole
UPDATE manuscript_workspace.manuscript_feasibility_v1 SET candidate_n = 0, variable_coverage_pct = [18.53, 2.67]::DOUBLE[], feasibility_color = 'RED', gating_issues = 'Medication data too sparse. immunotherapy not tracked', recommended_next_step = 'Requires dedicated chart review for medication exposure', canonical_version_at_scoring = 'v1_0_post_mig_248', scored_at = CAST(CURRENT_TIMESTAMP AS TIMESTAMP WITH TIME ZONE) WHERE manuscript_id = 5;

-- M006 Did preop molecular profile change the decision for total versus hemit
UPDATE manuscript_workspace.manuscript_feasibility_v1 SET candidate_n = 1286, variable_coverage_pct = [11.83, 2.91, 80.33, 46.23, 38.06]::DOUBLE[], feasibility_color = 'RED', gating_issues = 'Bethesda coverage 54pct in molecular cohort post-v17 feasibility YELLOW→RED (coverage/cohort reassessed).', recommended_next_step = 'Build cohort view; analyze surgical concordance with mol results', canonical_version_at_scoring = 'v1_0_post_mig_248', scored_at = CAST(CURRENT_TIMESTAMP AS TIMESTAMP WITH TIME ZONE) WHERE manuscript_id = 6;

-- M007 2025 RSS versus 2015 RSS - will reclassification change outcomes?
UPDATE manuscript_workspace.manuscript_feasibility_v1 SET candidate_n = 3144, variable_coverage_pct = [28.92, 100.0, 100.0, 38.06]::DOUBLE[], feasibility_color = 'RED', gating_issues = 'post-v17 feasibility GREEN→RED (coverage/cohort reassessed).', recommended_next_step = 'Implement 2025 RSS algorithm; compare reclassification', canonical_version_at_scoring = 'v1_0_post_mig_248', scored_at = CAST(CURRENT_TIMESTAMP AS TIMESTAMP WITH TIME ZONE) WHERE manuscript_id = 7;

-- M008 Post-op thyroglobulin levels, genetic testing, and recurrence risk in 
UPDATE manuscript_workspace.manuscript_feasibility_v1 SET candidate_n = 2063, variable_coverage_pct = [23.61, 25.03, 80.33, 100.0, 8.92]::DOUBLE[], feasibility_color = 'RED', gating_issues = 'Tg data available but molecular overlap limited', recommended_next_step = 'Analyze Tg cutoffs by surgery type; molecular subgroup secondary', canonical_version_at_scoring = 'v1_0_post_mig_248', scored_at = CAST(CURRENT_TIMESTAMP AS TIMESTAMP WITH TIME ZONE) WHERE manuscript_id = 8;

-- M009 Parathyroid Tissue on final path. Evaluation
UPDATE manuscript_workspace.manuscript_feasibility_v1 SET candidate_n = 1409, variable_coverage_pct = [13.72, 33.67, 17.96, 80.33]::DOUBLE[], feasibility_color = 'RED', gating_issues = 'post-v17 feasibility GREEN→RED (coverage/cohort reassessed).', recommended_next_step = 'Build cohort view of incidental parathyroid findings', canonical_version_at_scoring = 'v1_0_post_mig_248', scored_at = CAST(CURRENT_TIMESTAMP AS TIMESTAMP WITH TIME ZONE) WHERE manuscript_id = 9;

-- M010 Zip codes of N. Ga Thyroid cancers and aggressive pathology
UPDATE manuscript_workspace.manuscript_feasibility_v1 SET candidate_n = 0, variable_coverage_pct = [NULL::DOUBLE]::DOUBLE[], feasibility_color = 'RED', gating_issues = 'Zip code data not in publication DB. requires IRB-approved geocoding post-v17 schema: zip_code MISSING from canonical_patient_master. Schema/coverage gaps: zip_code MISSING from canonical_patient_master and cohort_descriptive_full_cohort_v1', recommended_next_step = 'Request geocoded data from research coordinator', canonical_version_at_scoring = 'v1_0_post_mig_248', scored_at = CAST(CURRENT_TIMESTAMP AS TIMESTAMP WITH TIME ZONE) WHERE manuscript_id = 10;

-- M011 Predictive modeling for thyroid cancer using TIRADs, FNA, and genetic 
UPDATE manuscript_workspace.manuscript_feasibility_v1 SET candidate_n = 3282, variable_coverage_pct = [30.19, 46.23, 8.92, 100.0, 38.06]::DOUBLE[], feasibility_color = 'RED', gating_issues = 'NLP rollup: nlp_tirads_max_category. cohort views alias cupm.max_tirads_category_ever) post-v17 feasibility GREEN→RED (coverage/cohort reassessed).', recommended_next_step = 'Build multivariate prediction model', canonical_version_at_scoring = 'v1_0_post_mig_248', scored_at = CAST(CURRENT_TIMESTAMP AS TIMESTAMP WITH TIME ZONE) WHERE manuscript_id = 11;

-- M012 Multiple TIRADs scored nodules scoring system
UPDATE manuscript_workspace.manuscript_feasibility_v1 SET candidate_n = 3474, variable_coverage_pct = [NULL::DOUBLE, 30.19, 31.24, 46.23, 38.06]::DOUBLE[], feasibility_color = 'RED', gating_issues = 'Histology coverage low in full TIRADS cohort post-v17 schema: tirads_nodules_scored_combined MISSING (rename hint: no direct CPM column. use canonical_us / imaging rollup). NLP rollup: nlp_tirads_max_category. cohort views alias cupm.max_tirads_category_ever). Schema/coverage gaps: tirads_nodules_scored_combined MISSING (rename hint: no direct CPM column; use canonical_us / imaging rollup)', recommended_next_step = 'Focus on nodules with FNA; analyze multi-nodule patterns', canonical_version_at_scoring = 'v1_0_post_mig_248', scored_at = CAST(CURRENT_TIMESTAMP AS TIMESTAMP WITH TIME ZONE) WHERE manuscript_id = 12;

-- M013 Characteristics and outcomes of Re-operative thyroid surgery
UPDATE manuscript_workspace.manuscript_feasibility_v1 SET candidate_n = 46, variable_coverage_pct = [0.42, 80.33, 100.0, 100.0]::DOUBLE[], feasibility_color = 'RED', gating_issues = 'N=46 below 50 threshold. may need expanded reop definition', recommended_next_step = 'Check completion thyroidectomy + second_surgery tables', canonical_version_at_scoring = 'v1_0_post_mig_248', scored_at = CAST(CURRENT_TIMESTAMP AS TIMESTAMP WITH TIME ZONE) WHERE manuscript_id = 13;

-- M014 Post surgery Lymph node management ultrasound monitoring
UPDATE manuscript_workspace.manuscript_feasibility_v1 SET candidate_n = 2751, variable_coverage_pct = [37.35, 0.56, 0.56, 30.19, 100.0]::DOUBLE[], feasibility_color = 'RED', gating_issues = 'NLP rollup: nlp_tirads_max_category. cohort views alias cupm.max_tirads_category_ever)', recommended_next_step = 'Quantify LN US follow-up rates; assess surveillance patterns', canonical_version_at_scoring = 'v1_0_post_mig_248', scored_at = CAST(CURRENT_TIMESTAMP AS TIMESTAMP WITH TIME ZONE) WHERE manuscript_id = 14;

-- M015 Quality of life outcomes in survivorship clinics
UPDATE manuscript_workspace.manuscript_feasibility_v1 SET candidate_n = 0, variable_coverage_pct = [NULL::DOUBLE]::DOUBLE[], feasibility_color = 'RED', gating_issues = 'QoL data not collected. requires prospective PRO instrument post-v17 schema: quality_of_life MISSING from canonical_patient_master. Schema/coverage gaps: quality_of_life MISSING from canonical_patient_master and cohort_descriptive_full_cohort_v1', recommended_next_step = 'Design prospective QoL study', canonical_version_at_scoring = 'v1_0_post_mig_248', scored_at = CAST(CURRENT_TIMESTAMP AS TIMESTAMP WITH TIME ZONE) WHERE manuscript_id = 15;

-- M016 Carcinoma in Graves disease - survival, pathology, recurrence
UPDATE manuscript_workspace.manuscript_feasibility_v1 SET candidate_n = 574, variable_coverage_pct = [5.28, 100.0, 38.06, 37.99, 37.35, 100.0, 23.61]::DOUBLE[], feasibility_color = 'RED', gating_issues = '', recommended_next_step = 'Build cohort; descriptive analysis first', canonical_version_at_scoring = 'v1_0_post_mig_248', scored_at = CAST(CURRENT_TIMESTAMP AS TIMESTAMP WITH TIME ZONE) WHERE manuscript_id = 16;

-- M017 Eucalcemic hypoparathyroidism surgical management outcomes
UPDATE manuscript_workspace.manuscript_feasibility_v1 SET candidate_n = 66, variable_coverage_pct = [100.0, 100.0, 100.0]::DOUBLE[], feasibility_color = 'YELLOW', gating_issues = 'Only 66 TT patients with PTH labs. requires expanded lab pull', recommended_next_step = 'Wait for v1_1 lab pull', canonical_version_at_scoring = 'v1_0_post_mig_248', scored_at = CAST(CURRENT_TIMESTAMP AS TIMESTAMP WITH TIME ZONE) WHERE manuscript_id = 17;

-- M018 Value of molecular testing for Beth 5/6 nodules
UPDATE manuscript_workspace.manuscript_feasibility_v1 SET candidate_n = 1494, variable_coverage_pct = [46.23, 8.92, 8.92, 38.06, 80.33]::DOUBLE[], feasibility_color = 'RED', gating_issues = 'Molecular coverage 48pct in Beth V/VI post-v17 feasibility YELLOW→RED (coverage/cohort reassessed).', recommended_next_step = 'Analyze molecular vs no-molecular outcomes', canonical_version_at_scoring = 'v1_0_post_mig_248', scored_at = CAST(CURRENT_TIMESTAMP AS TIMESTAMP WITH TIME ZONE) WHERE manuscript_id = 18;

-- M019 RAI outcomes: recurrence, mutations, treatment response
UPDATE manuscript_workspace.manuscript_feasibility_v1 SET candidate_n = 862, variable_coverage_pct = [100.0, 100.0, 2.91, 28.92, 3.12]::DOUBLE[], feasibility_color = 'RED', gating_issues = 'ATA risk only 54pct in RAI cohort post-v17 feasibility YELLOW→RED (coverage/cohort reassessed).', recommended_next_step = 'Focus on RAI outcomes by ATA risk', canonical_version_at_scoring = 'v1_0_post_mig_248', scored_at = CAST(CURRENT_TIMESTAMP AS TIMESTAMP WITH TIME ZONE) WHERE manuscript_id = 19;

-- M020 Parathyroid tumors on final thyroid path
UPDATE manuscript_workspace.manuscript_feasibility_v1 SET candidate_n = 1353, variable_coverage_pct = [13.72, 17.96, 33.67, 38.06]::DOUBLE[], feasibility_color = 'RED', gating_issues = 'Histology coverage low for benign thyroidectomies', recommended_next_step = 'Use benign_diagnosis table for non-malignant histology', canonical_version_at_scoring = 'v1_0_post_mig_248', scored_at = CAST(CURRENT_TIMESTAMP AS TIMESTAMP WITH TIME ZONE) WHERE manuscript_id = 20;

-- M021 Parathyroid tumors: commonalities and thyroid pathology correlations
UPDATE manuscript_workspace.manuscript_feasibility_v1 SET candidate_n = 0, variable_coverage_pct = []::DOUBLE[], feasibility_color = 'RED', gating_issues = 'Extremely rare. not identifiable from current schema', recommended_next_step = 'Manual chart review needed', canonical_version_at_scoring = 'v1_0_post_mig_248', scored_at = CAST(CURRENT_TIMESTAMP AS TIMESTAMP WITH TIME ZONE) WHERE manuscript_id = 21;

-- M022 Metastatic pancreatic endocrine tumor and struma ovarii
UPDATE manuscript_workspace.manuscript_feasibility_v1 SET candidate_n = 0, variable_coverage_pct = []::DOUBLE[], feasibility_color = 'RED', gating_issues = 'Extremely rare case types', recommended_next_step = 'Manual chart review needed', canonical_version_at_scoring = 'v1_0_post_mig_248', scored_at = CAST(CURRENT_TIMESTAMP AS TIMESTAMP WITH TIME ZONE) WHERE manuscript_id = 22;

-- M023 Thyroidectomy patients with preoperative genetics testing outcomes
UPDATE manuscript_workspace.manuscript_feasibility_v1 SET candidate_n = 1286, variable_coverage_pct = [80.33, 8.92, 38.06]::DOUBLE[], feasibility_color = 'RED', gating_issues = 'Tg/TSH coverage will improve at v1_1 post-v17 feasibility YELLOW→RED (coverage/cohort reassessed).', recommended_next_step = 'Merge with M002 analysis', canonical_version_at_scoring = 'v1_0_post_mig_248', scored_at = CAST(CURRENT_TIMESTAMP AS TIMESTAMP WITH TIME ZONE) WHERE manuscript_id = 23;

-- M024 Recurrence-free survival with molecular testing: ThyroSeq risk groups 
UPDATE manuscript_workspace.manuscript_feasibility_v1 SET candidate_n = 969, variable_coverage_pct = [11.83, 100.0, 100.0, 28.92]::DOUBLE[], feasibility_color = 'RED', gating_issues = 'ATA risk coverage limited in molecular-tested cohort', recommended_next_step = 'Build RFS survival models', canonical_version_at_scoring = 'v1_0_post_mig_248', scored_at = CAST(CURRENT_TIMESTAMP AS TIMESTAMP WITH TIME ZONE) WHERE manuscript_id = 24;

-- M025 ACR TI-RADS Performance Study - All Patients
UPDATE manuscript_workspace.manuscript_feasibility_v1 SET candidate_n = 3375, variable_coverage_pct = [30.19, 46.23, 38.06, 100.0, 37.99]::DOUBLE[], feasibility_color = 'YELLOW', gating_issues = 'Primary outcome (malignancy detection) is 100pct. NLP rollup: nlp_tirads_max_category. cohort views alias cupm.max_tirads_category_ever). Feasibility RED→YELLOW post-mig_248 rescoring.', recommended_next_step = 'Finalize analysis - ready to submit', canonical_version_at_scoring = 'v1_0_post_mig_248', scored_at = CAST(CURRENT_TIMESTAMP AS TIMESTAMP WITH TIME ZONE) WHERE manuscript_id = 25;

-- M026 Heavy Metals and Thyroid Cancer Association
UPDATE manuscript_workspace.manuscript_feasibility_v1 SET candidate_n = 0, variable_coverage_pct = [NULL::DOUBLE]::DOUBLE[], feasibility_color = 'RED', gating_issues = 'Heavy metal data not in publication DB. requires external environmental data linkage post-v17 schema: heavy_metal_exposure MISSING from canonical_patient_master. Schema/coverage gaps: heavy_metal_exposure MISSING from canonical_patient_master and cohort_descriptive_full_cohort_v1', recommended_next_step = 'Requires IRB-approved geocoding + environmental databases', canonical_version_at_scoring = 'v1_0_post_mig_248', scored_at = CAST(CURRENT_TIMESTAMP AS TIMESTAMP WITH TIME ZONE) WHERE manuscript_id = 26;

-- M027 Metabolomics Profiling in Thyroid Carcinoma
UPDATE manuscript_workspace.manuscript_feasibility_v1 SET candidate_n = 0, variable_coverage_pct = [NULL::DOUBLE]::DOUBLE[], feasibility_color = 'RED', gating_issues = 'Metabolomics data not in publication DB. requires prospective biospecimen collection post-v17 schema: metabolomics_panel MISSING from canonical_patient_master. Schema/coverage gaps: metabolomics_panel MISSING from canonical_patient_master and cohort_descriptive_full_cohort_v1', recommended_next_step = 'Design prospective metabolomics study', canonical_version_at_scoring = 'v1_0_post_mig_248', scored_at = CAST(CURRENT_TIMESTAMP AS TIMESTAMP WITH TIME ZONE) WHERE manuscript_id = 27;

-- M028 Bethesda III and IV Nodules - Comprehensive Analysis
UPDATE manuscript_workspace.manuscript_feasibility_v1 SET candidate_n = 1266, variable_coverage_pct = [46.23, 38.06, 80.33, 8.92, 100.0, 37.99]::DOUBLE[], feasibility_color = 'RED', gating_issues = '', recommended_next_step = 'Build cohort view; analyze ROM in tested vs untested', canonical_version_at_scoring = 'v1_0_post_mig_248', scored_at = CAST(CURRENT_TIMESTAMP AS TIMESTAMP WITH TIME ZONE) WHERE manuscript_id = 28;

-- M029 FNA Cytology vs Final Pathology Concordance
UPDATE manuscript_workspace.manuscript_feasibility_v1 SET candidate_n = 2401, variable_coverage_pct = [46.23, 38.06, 100.0, 37.99]::DOUBLE[], feasibility_color = 'YELLOW', gating_issues = 'Feasibility RED→YELLOW post-mig_248 rescoring.', recommended_next_step = 'Build concordance matrix; analyze discordant cases', canonical_version_at_scoring = 'v1_0_post_mig_248', scored_at = CAST(CURRENT_TIMESTAMP AS TIMESTAMP WITH TIME ZONE) WHERE manuscript_id = 29;

-- M030 Predictive Modeling with Genetic Testing for Thyroid Cancer
UPDATE manuscript_workspace.manuscript_feasibility_v1 SET candidate_n = 1286, variable_coverage_pct = [30.19, 46.23, 8.92, 8.92, 100.0, 38.06]::DOUBLE[], feasibility_color = 'RED', gating_issues = 'NLP rollup: nlp_tirads_max_category. cohort views alias cupm.max_tirads_category_ever) post-v17 feasibility GREEN→RED (coverage/cohort reassessed).', recommended_next_step = 'Build multivariate model; assess incremental value of each modality', canonical_version_at_scoring = 'v1_0_post_mig_248', scored_at = CAST(CURRENT_TIMESTAMP AS TIMESTAMP WITH TIME ZONE) WHERE manuscript_id = 30;

-- M031 Nuclear Medicine Thyroid Scans 1999-2025 Analysis
UPDATE manuscript_workspace.manuscript_feasibility_v1 SET candidate_n = 1148, variable_coverage_pct = [10.56, 10.3, 2.65, 100.0, 2.54]::DOUBLE[], feasibility_color = 'RED', gating_issues = 'Histology 69pct in nucmed cohort (many benign scans) post-v17 feasibility GREEN→RED (coverage/cohort reassessed).', recommended_next_step = 'Build temporal analysis of nuclear med utilization', canonical_version_at_scoring = 'v1_0_post_mig_248', scored_at = CAST(CURRENT_TIMESTAMP AS TIMESTAMP WITH TIME ZONE) WHERE manuscript_id = 31;

-- M032 25-Year Descriptive Analysis of Thyroid Surgery
UPDATE manuscript_workspace.manuscript_feasibility_v1 SET candidate_n = 10871, variable_coverage_pct = [100.0, 100.0, 99.92, 80.33, 100.0, 80.31]::DOUBLE[], feasibility_color = 'GREEN', gating_issues = 'Refreshed post-mig_248.', recommended_next_step = 'Build 25-year temporal trends; demographic breakdowns; refreshed post-mig_248', canonical_version_at_scoring = 'v1_0_post_mig_248', scored_at = CAST(CURRENT_TIMESTAMP AS TIMESTAMP WITH TIME ZONE) WHERE manuscript_id = 32;

-- M033 Afirma and ThyroSeq Molecular Testing Outcomes
UPDATE manuscript_workspace.manuscript_feasibility_v1 SET candidate_n = 969, variable_coverage_pct = [8.92, 8.92, 11.83, 38.06, 80.33, 46.23]::DOUBLE[], feasibility_color = 'RED', gating_issues = 'Surgery type 68pct in mol+histol overlap post-v17 feasibility GREEN→RED (coverage/cohort reassessed).', recommended_next_step = 'Build Afirma vs ThyroSeq comparative analysis', canonical_version_at_scoring = 'v1_0_post_mig_248', scored_at = CAST(CURRENT_TIMESTAMP AS TIMESTAMP WITH TIME ZONE) WHERE manuscript_id = 33;

-- M034 Literature Review: Trends in Thyroid Surgery
UPDATE manuscript_workspace.manuscript_feasibility_v1 SET candidate_n = 0, variable_coverage_pct = []::DOUBLE[], feasibility_color = 'RED', gating_issues = 'Literature review - no database analysis needed', recommended_next_step = 'Systematic search and review', canonical_version_at_scoring = 'v1_0_post_mig_248', scored_at = CAST(CURRENT_TIMESTAMP AS TIMESTAMP WITH TIME ZONE) WHERE manuscript_id = 34;

-- M035 Bethesda V (Suspicious for Malignancy) Analysis
UPDATE manuscript_workspace.manuscript_feasibility_v1 SET candidate_n = 273, variable_coverage_pct = [46.23, 38.06, 100.0, 80.33, 8.92]::DOUBLE[], feasibility_color = 'RED', gating_issues = 'Molecular testing 27pct in Beth V cohort - secondary analysis only post-v17 feasibility GREEN→RED (coverage/cohort reassessed).', recommended_next_step = 'Build Beth V cohort; analyze ROM and management patterns', canonical_version_at_scoring = 'v1_0_post_mig_248', scored_at = CAST(CURRENT_TIMESTAMP AS TIMESTAMP WITH TIME ZONE) WHERE manuscript_id = 35;

-- M036 2015 vs 2025 ATA Risk Stratification Comparison
UPDATE manuscript_workspace.manuscript_feasibility_v1 SET candidate_n = 4137, variable_coverage_pct = [28.92, 100.0, 100.0, 38.06, 37.89]::DOUBLE[], feasibility_color = 'RED', gating_issues = 'post-v17 feasibility GREEN→RED (coverage/cohort reassessed).', recommended_next_step = 'Implement 2025 RSS algorithm; compare reclassification and outcomes', canonical_version_at_scoring = 'v1_0_post_mig_248', scored_at = CAST(CURRENT_TIMESTAMP AS TIMESTAMP WITH TIME ZONE) WHERE manuscript_id = 36;

-- M037 Lymph Node Metastasis Patterns in Thyroid Carcinoma
UPDATE manuscript_workspace.manuscript_feasibility_v1 SET candidate_n = 2271, variable_coverage_pct = [37.35, 50.5, 38.06, 37.99, 37.89]::DOUBLE[], feasibility_color = 'YELLOW', gating_issues = 'Feasibility RED→YELLOW post-mig_248 rescoring.', recommended_next_step = 'Build LN metastasis pattern analysis; multivariate predictors', canonical_version_at_scoring = 'v1_0_post_mig_248', scored_at = CAST(CURRENT_TIMESTAMP AS TIMESTAMP WITH TIME ZONE) WHERE manuscript_id = 37;

-- M038 ECMO Support for Massive Goiter Surgery
UPDATE manuscript_workspace.manuscript_feasibility_v1 SET candidate_n = 10871, variable_coverage_pct = [100.0, 80.33, 100.0]::DOUBLE[], feasibility_color = 'GREEN', gating_issues = 'Need specific study definition. Refreshed post-mig_248.', recommended_next_step = 'Define research question; refreshed post-mig_248', canonical_version_at_scoring = 'v1_0_post_mig_248', scored_at = CAST(CURRENT_TIMESTAMP AS TIMESTAMP WITH TIME ZONE) WHERE manuscript_id = 38;

-- M039 PTH and Calcium Protocol Post-Thyroidectomy
UPDATE manuscript_workspace.manuscript_feasibility_v1 SET candidate_n = 4561, variable_coverage_pct = [100.0, 100.0, 100.0, 80.33]::DOUBLE[], feasibility_color = 'GREEN', gating_issues = 'Only 87 TT patients with calcium labs. PTH 76pct of those post-v17 feasibility YELLOW→GREEN (coverage/cohort reassessed). post-v17: NEW feasibility GREEN — prior gate cleared on coverage/cohort sizing.. Refreshed post-mig_248.', recommended_next_step = 'Reassess after v17 schema improvements; refreshed post-mig_248', canonical_version_at_scoring = 'v1_0_post_mig_248', scored_at = CAST(CURRENT_TIMESTAMP AS TIMESTAMP WITH TIME ZONE) WHERE manuscript_id = 39;

-- M040 Reoperative Thyroid Surgery: Single Institution Experience
UPDATE manuscript_workspace.manuscript_feasibility_v1 SET candidate_n = 1470, variable_coverage_pct = [0.42, 6.3, 80.33, 100.0, 100.0]::DOUBLE[], feasibility_color = 'RED', gating_issues = 'Strict reop N=46. expanded with completion thyroidectomy N=731 post-v17 feasibility YELLOW→RED (coverage/cohort reassessed).', recommended_next_step = 'Define reop cohort including completion; analyze complications', canonical_version_at_scoring = 'v1_0_post_mig_248', scored_at = CAST(CURRENT_TIMESTAMP AS TIMESTAMP WITH TIME ZONE) WHERE manuscript_id = 40;

-- M041 Thyroglossal Duct Cyst Analysis
UPDATE manuscript_workspace.manuscript_feasibility_v1 SET candidate_n = 0, variable_coverage_pct = []::DOUBLE[], feasibility_color = 'RED', gating_issues = 'Not identifiable from current schema', recommended_next_step = 'N/A', canonical_version_at_scoring = 'v1_0_post_mig_248', scored_at = CAST(CURRENT_TIMESTAMP AS TIMESTAMP WITH TIME ZONE) WHERE manuscript_id = 41;

-- M042 Incidental Parathyroid Tissue in Thyroid Pathology
UPDATE manuscript_workspace.manuscript_feasibility_v1 SET candidate_n = 4798, variable_coverage_pct = [13.72, 33.67, 17.96, 33.67, 80.33, 100.0]::DOUBLE[], feasibility_color = 'RED', gating_issues = 'post-v17 feasibility GREEN→RED (coverage/cohort reassessed).', recommended_next_step = 'Build cohort view; analyze incidental findings and hypocalcemia risk', canonical_version_at_scoring = 'v1_0_post_mig_248', scored_at = CAST(CURRENT_TIMESTAMP AS TIMESTAMP WITH TIME ZONE) WHERE manuscript_id = 42;

-- M043 Anatomic Lymph Node Metastases Predictors in Malignant Thyroid Cohort
UPDATE manuscript_workspace.manuscript_feasibility_v1 SET candidate_n = 4137, variable_coverage_pct = [12.38, 37.35, 50.5, 38.06, 37.99, 37.89]::DOUBLE[], feasibility_color = 'RED', gating_issues = '', recommended_next_step = 'Build predictive model for LN involvement', canonical_version_at_scoring = 'v1_0_post_mig_248', scored_at = CAST(CURRENT_TIMESTAMP AS TIMESTAMP WITH TIME ZONE) WHERE manuscript_id = 43;

-- M044 AJCC 8th Edition Staging: Impact of Microscopic vs Gross ETE
UPDATE manuscript_workspace.manuscript_feasibility_v1 SET candidate_n = 4128, variable_coverage_pct = [38.0, 38.4, 37.89, 32.73, 100.0, 100.0]::DOUBLE[], feasibility_color = 'YELLOW', gating_issues = 'post-v17 feasibility GREEN→YELLOW (coverage/cohort reassessed).', recommended_next_step = 'Build survival analysis: micro vs gross ETE impact on staging', canonical_version_at_scoring = 'v1_0_post_mig_248', scored_at = CAST(CURRENT_TIMESTAMP AS TIMESTAMP WITH TIME ZONE) WHERE manuscript_id = 44;

-- M045 Multimodal Risk Stratification: TI-RADS + Bethesda + Final Pathology
UPDATE manuscript_workspace.manuscript_feasibility_v1 SET candidate_n = 1165, variable_coverage_pct = [30.19, 46.23, 38.06, 100.0, 37.99]::DOUBLE[], feasibility_color = 'YELLOW', gating_issues = 'NLP rollup: nlp_tirads_max_category. cohort views alias cupm.max_tirads_category_ever). Feasibility RED→YELLOW post-mig_248 rescoring.', recommended_next_step = 'Build integrated risk model combining all 3 modalities', canonical_version_at_scoring = 'v1_0_post_mig_248', scored_at = CAST(CURRENT_TIMESTAMP AS TIMESTAMP WITH TIME ZONE) WHERE manuscript_id = 45;

-- M046 Bethesda Risk of Malignancy with NIFTP-Era Stratification (pre/post 20
UPDATE manuscript_workspace.manuscript_feasibility_v1 SET candidate_n = 5026, variable_coverage_pct = [46.23, 80.31, 38.06, 100.0]::DOUBLE[], feasibility_color = 'YELLOW', gating_issues = 'post-v17 feasibility GREEN→YELLOW (coverage/cohort reassessed).', recommended_next_step = 'Build pre/post 2017 comparison of ROM by Bethesda category', canonical_version_at_scoring = 'v1_0_post_mig_248', scored_at = CAST(CURRENT_TIMESTAMP AS TIMESTAMP WITH TIME ZONE) WHERE manuscript_id = 46;

-- M047 Frozen Section Diagnostic Concordance and Clinical Utility
UPDATE manuscript_workspace.manuscript_feasibility_v1 SET candidate_n = 10871, variable_coverage_pct = [100.0, 100.0, 38.06, 100.0]::DOUBLE[], feasibility_color = 'YELLOW', gating_issues = 'Use syn_carcinoma_on_frozen for concordance post-v17 feasibility GREEN→YELLOW (coverage/cohort reassessed).', recommended_next_step = 'Build frozen vs final path concordance analysis', canonical_version_at_scoring = 'v1_0_post_mig_248', scored_at = CAST(CURRENT_TIMESTAMP AS TIMESTAMP WITH TIME ZONE) WHERE manuscript_id = 47;

-- M048 TNM staging in multifocal thyroid carcinoma
UPDATE manuscript_workspace.manuscript_feasibility_v1 SET candidate_n = 10871, variable_coverage_pct = [100.0, 80.33, 100.0]::DOUBLE[], feasibility_color = 'GREEN', gating_issues = 'candidate_n=8733 from CPM intersect of non-null resolvable keys (mig_248 repair).. Refreshed post-mig_248.', recommended_next_step = 'Refine research question; refreshed post-mig_248', canonical_version_at_scoring = 'v1_0_post_mig_248', scored_at = CAST(CURRENT_TIMESTAMP AS TIMESTAMP WITH TIME ZONE) WHERE manuscript_id = 48;

-- M049 Malignancy and pyramidal lobe presence
UPDATE manuscript_workspace.manuscript_feasibility_v1 SET candidate_n = 10871, variable_coverage_pct = [100.0, 80.33, 100.0]::DOUBLE[], feasibility_color = 'GREEN', gating_issues = 'candidate_n=8733 from CPM intersect of non-null resolvable keys (mig_248 repair).. Refreshed post-mig_248.', recommended_next_step = 'Refine research question; refreshed post-mig_248', canonical_version_at_scoring = 'v1_0_post_mig_248', scored_at = CAST(CURRENT_TIMESTAMP AS TIMESTAMP WITH TIME ZONE) WHERE manuscript_id = 49;

-- M050 Tumor size: max dimension vs volume and outcomes
UPDATE manuscript_workspace.manuscript_feasibility_v1 SET candidate_n = 10871, variable_coverage_pct = [100.0, 80.33, 100.0]::DOUBLE[], feasibility_color = 'GREEN', gating_issues = 'candidate_n=8733 from CPM intersect of non-null resolvable keys (mig_248 repair).. Refreshed post-mig_248.', recommended_next_step = 'Refine research question; refreshed post-mig_248', canonical_version_at_scoring = 'v1_0_post_mig_248', scored_at = CAST(CURRENT_TIMESTAMP AS TIMESTAMP WITH TIME ZONE) WHERE manuscript_id = 50;

-- M051 ETE and lymph node involvement significance
UPDATE manuscript_workspace.manuscript_feasibility_v1 SET candidate_n = 10871, variable_coverage_pct = [100.0, 80.33, 100.0]::DOUBLE[], feasibility_color = 'GREEN', gating_issues = 'candidate_n=8733 from CPM intersect of non-null resolvable keys (mig_248 repair).. Refreshed post-mig_248.', recommended_next_step = 'Refine research question; refreshed post-mig_248', canonical_version_at_scoring = 'v1_0_post_mig_248', scored_at = CAST(CURRENT_TIMESTAMP AS TIMESTAMP WITH TIME ZONE) WHERE manuscript_id = 51;

-- M052 LN resection count in MRLND and recurrence
UPDATE manuscript_workspace.manuscript_feasibility_v1 SET candidate_n = 10871, variable_coverage_pct = [100.0, 80.33, 100.0]::DOUBLE[], feasibility_color = 'GREEN', gating_issues = 'candidate_n=8733 from CPM intersect of non-null resolvable keys (mig_248 repair).. Refreshed post-mig_248.', recommended_next_step = 'Refine research question; refreshed post-mig_248', canonical_version_at_scoring = 'v1_0_post_mig_248', scored_at = CAST(CURRENT_TIMESTAMP AS TIMESTAMP WITH TIME ZONE) WHERE manuscript_id = 52;

-- M053 Non-diagnostic FNA specimens and thyroidectomy outcomes
UPDATE manuscript_workspace.manuscript_feasibility_v1 SET candidate_n = 10871, variable_coverage_pct = [100.0, 80.33, 100.0]::DOUBLE[], feasibility_color = 'GREEN', gating_issues = 'candidate_n=8733 from CPM intersect of non-null resolvable keys (mig_248 repair).. Refreshed post-mig_248.', recommended_next_step = 'Refine research question; refreshed post-mig_248', canonical_version_at_scoring = 'v1_0_post_mig_248', scored_at = CAST(CURRENT_TIMESTAMP AS TIMESTAMP WITH TIME ZONE) WHERE manuscript_id = 53;

-- M054 PTC follicular variant reclassification as NIFTP
UPDATE manuscript_workspace.manuscript_feasibility_v1 SET candidate_n = 10871, variable_coverage_pct = [100.0, 80.33, 100.0]::DOUBLE[], feasibility_color = 'GREEN', gating_issues = 'candidate_n=8733 from CPM intersect of non-null resolvable keys (mig_248 repair).. Refreshed post-mig_248.', recommended_next_step = 'Refine research question; refreshed post-mig_248', canonical_version_at_scoring = 'v1_0_post_mig_248', scored_at = CAST(CURRENT_TIMESTAMP AS TIMESTAMP WITH TIME ZONE) WHERE manuscript_id = 54;

-- M055 Recurrence rates and RAI treatment analysis
UPDATE manuscript_workspace.manuscript_feasibility_v1 SET candidate_n = 10871, variable_coverage_pct = [100.0, 80.33, 100.0]::DOUBLE[], feasibility_color = 'GREEN', gating_issues = 'candidate_n=8733 from CPM intersect of non-null resolvable keys (mig_248 repair).. Refreshed post-mig_248.', recommended_next_step = 'Refine research question; refreshed post-mig_248', canonical_version_at_scoring = 'v1_0_post_mig_248', scored_at = CAST(CURRENT_TIMESTAMP AS TIMESTAMP WITH TIME ZONE) WHERE manuscript_id = 55;

-- M056 Age at cancer diagnosis - epidemiological analysis
UPDATE manuscript_workspace.manuscript_feasibility_v1 SET candidate_n = 10871, variable_coverage_pct = [100.0, 80.33, 100.0]::DOUBLE[], feasibility_color = 'GREEN', gating_issues = 'candidate_n=8733 from CPM intersect of non-null resolvable keys (mig_248 repair).. Refreshed post-mig_248.', recommended_next_step = 'Refine research question; refreshed post-mig_248', canonical_version_at_scoring = 'v1_0_post_mig_248', scored_at = CAST(CURRENT_TIMESTAMP AS TIMESTAMP WITH TIME ZONE) WHERE manuscript_id = 56;

-- M057 Risk stratification for recurrent disease
UPDATE manuscript_workspace.manuscript_feasibility_v1 SET candidate_n = 10871, variable_coverage_pct = [100.0, 80.33, 100.0]::DOUBLE[], feasibility_color = 'GREEN', gating_issues = 'candidate_n=8733 from CPM intersect of non-null resolvable keys (mig_248 repair).. Refreshed post-mig_248.', recommended_next_step = 'Refine research question; refreshed post-mig_248', canonical_version_at_scoring = 'v1_0_post_mig_248', scored_at = CAST(CURRENT_TIMESTAMP AS TIMESTAMP WITH TIME ZONE) WHERE manuscript_id = 57;

-- M058 Thyroid size/weight and malignancy risk
UPDATE manuscript_workspace.manuscript_feasibility_v1 SET candidate_n = 10871, variable_coverage_pct = [100.0, 80.33, 100.0]::DOUBLE[], feasibility_color = 'GREEN', gating_issues = 'candidate_n=8733 from CPM intersect of non-null resolvable keys (mig_248 repair).. Refreshed post-mig_248.', recommended_next_step = 'Refine research question; refreshed post-mig_248', canonical_version_at_scoring = 'v1_0_post_mig_248', scored_at = CAST(CURRENT_TIMESTAMP AS TIMESTAMP WITH TIME ZONE) WHERE manuscript_id = 58;

-- M059 Prognostic scoring vs staging systems
UPDATE manuscript_workspace.manuscript_feasibility_v1 SET candidate_n = 10871, variable_coverage_pct = [100.0, 80.33, 100.0]::DOUBLE[], feasibility_color = 'GREEN', gating_issues = 'candidate_n=8733 from CPM intersect of non-null resolvable keys (mig_248 repair).. Refreshed post-mig_248.', recommended_next_step = 'Refine research question; refreshed post-mig_248', canonical_version_at_scoring = 'v1_0_post_mig_248', scored_at = CAST(CURRENT_TIMESTAMP AS TIMESTAMP WITH TIME ZONE) WHERE manuscript_id = 59;

-- M060 Follicular adenomas, Hurthle cell adenomas, FTUMPs trends
UPDATE manuscript_workspace.manuscript_feasibility_v1 SET candidate_n = 10871, variable_coverage_pct = [100.0, 80.33, 100.0]::DOUBLE[], feasibility_color = 'GREEN', gating_issues = 'candidate_n=8733 from CPM intersect of non-null resolvable keys (mig_248 repair).. Refreshed post-mig_248.', recommended_next_step = 'Refine research question; refreshed post-mig_248', canonical_version_at_scoring = 'v1_0_post_mig_248', scored_at = CAST(CURRENT_TIMESTAMP AS TIMESTAMP WITH TIME ZONE) WHERE manuscript_id = 60;

-- M061 Thyroiditis and thyroid cancer outcomes
UPDATE manuscript_workspace.manuscript_feasibility_v1 SET candidate_n = 10871, variable_coverage_pct = [100.0, 80.33, 100.0]::DOUBLE[], feasibility_color = 'GREEN', gating_issues = 'candidate_n=8733 from CPM intersect of non-null resolvable keys (mig_248 repair).. Refreshed post-mig_248.', recommended_next_step = 'Refine research question; refreshed post-mig_248', canonical_version_at_scoring = 'v1_0_post_mig_248', scored_at = CAST(CURRENT_TIMESTAMP AS TIMESTAMP WITH TIME ZONE) WHERE manuscript_id = 61;

-- M062 Incidental cancer on frozen section analysis
UPDATE manuscript_workspace.manuscript_feasibility_v1 SET candidate_n = 10871, variable_coverage_pct = [100.0, 80.33, 100.0]::DOUBLE[], feasibility_color = 'GREEN', gating_issues = 'candidate_n=8733 from CPM intersect of non-null resolvable keys (mig_248 repair).. Refreshed post-mig_248.', recommended_next_step = 'Refine research question; refreshed post-mig_248', canonical_version_at_scoring = 'v1_0_post_mig_248', scored_at = CAST(CURRENT_TIMESTAMP AS TIMESTAMP WITH TIME ZONE) WHERE manuscript_id = 62;

-- M063 Frozen section false negatives analysis
UPDATE manuscript_workspace.manuscript_feasibility_v1 SET candidate_n = 10871, variable_coverage_pct = [100.0, 80.33, 100.0]::DOUBLE[], feasibility_color = 'GREEN', gating_issues = 'candidate_n=8733 from CPM intersect of non-null resolvable keys (mig_248 repair).. Refreshed post-mig_248.', recommended_next_step = 'Refine research question; refreshed post-mig_248', canonical_version_at_scoring = 'v1_0_post_mig_248', scored_at = CAST(CURRENT_TIMESTAMP AS TIMESTAMP WITH TIME ZONE) WHERE manuscript_id = 63;

-- M064 Decision algorithm for intraoperative frozen section
UPDATE manuscript_workspace.manuscript_feasibility_v1 SET candidate_n = 10871, variable_coverage_pct = [100.0, 80.33, 100.0]::DOUBLE[], feasibility_color = 'GREEN', gating_issues = 'candidate_n=8733 from CPM intersect of non-null resolvable keys (mig_248 repair).. Refreshed post-mig_248.', recommended_next_step = 'Refine research question; refreshed post-mig_248', canonical_version_at_scoring = 'v1_0_post_mig_248', scored_at = CAST(CURRENT_TIMESTAMP AS TIMESTAMP WITH TIME ZONE) WHERE manuscript_id = 64;

-- M065 Frozen section utility: TT vs lobectomy outcomes
UPDATE manuscript_workspace.manuscript_feasibility_v1 SET candidate_n = 10871, variable_coverage_pct = [100.0, 80.33, 100.0]::DOUBLE[], feasibility_color = 'GREEN', gating_issues = 'candidate_n=8733 from CPM intersect of non-null resolvable keys (mig_248 repair).. Refreshed post-mig_248.', recommended_next_step = 'Refine research question; refreshed post-mig_248', canonical_version_at_scoring = 'v1_0_post_mig_248', scored_at = CAST(CURRENT_TIMESTAMP AS TIMESTAMP WITH TIME ZONE) WHERE manuscript_id = 65;

-- M066 Parathyroid gland identification vs resection specimen
UPDATE manuscript_workspace.manuscript_feasibility_v1 SET candidate_n = 10871, variable_coverage_pct = [100.0, 80.33, 100.0]::DOUBLE[], feasibility_color = 'GREEN', gating_issues = 'candidate_n=8733 from CPM intersect of non-null resolvable keys (mig_248 repair).. Refreshed post-mig_248.', recommended_next_step = 'Refine research question; refreshed post-mig_248', canonical_version_at_scoring = 'v1_0_post_mig_248', scored_at = CAST(CURRENT_TIMESTAMP AS TIMESTAMP WITH TIME ZONE) WHERE manuscript_id = 66;

-- M067 TSH/Thyroglobulin as tumorigenesis driver
UPDATE manuscript_workspace.manuscript_feasibility_v1 SET candidate_n = 2567, variable_coverage_pct = [23.61, 25.03, 80.33]::DOUBLE[], feasibility_color = 'RED', gating_issues = 'Idea stage post-v17 feasibility GREEN→RED (coverage/cohort reassessed).', recommended_next_step = 'Refine question', canonical_version_at_scoring = 'v1_0_post_mig_248', scored_at = CAST(CURRENT_TIMESTAMP AS TIMESTAMP WITH TIME ZONE) WHERE manuscript_id = 67;

-- M068 Mutational changes and lab value correlations
UPDATE manuscript_workspace.manuscript_feasibility_v1 SET candidate_n = 10871, variable_coverage_pct = [100.0, 80.33, 100.0]::DOUBLE[], feasibility_color = 'GREEN', gating_issues = 'candidate_n=8733 from CPM intersect of non-null resolvable keys (mig_248 repair).. Refreshed post-mig_248.', recommended_next_step = 'Refine research question; refreshed post-mig_248', canonical_version_at_scoring = 'v1_0_post_mig_248', scored_at = CAST(CURRENT_TIMESTAMP AS TIMESTAMP WITH TIME ZONE) WHERE manuscript_id = 68;

-- M069 Graves vs Hashimoto thyroid cancer comparison
UPDATE manuscript_workspace.manuscript_feasibility_v1 SET candidate_n = 10871, variable_coverage_pct = [100.0, 80.33, 100.0]::DOUBLE[], feasibility_color = 'GREEN', gating_issues = 'candidate_n=8733 from CPM intersect of non-null resolvable keys (mig_248 repair).. Refreshed post-mig_248.', recommended_next_step = 'Refine research question; refreshed post-mig_248', canonical_version_at_scoring = 'v1_0_post_mig_248', scored_at = CAST(CURRENT_TIMESTAMP AS TIMESTAMP WITH TIME ZONE) WHERE manuscript_id = 69;

-- M070 Hereditary conditions and thyroid cancer
UPDATE manuscript_workspace.manuscript_feasibility_v1 SET candidate_n = 10871, variable_coverage_pct = [100.0, 80.33, 100.0]::DOUBLE[], feasibility_color = 'GREEN', gating_issues = 'candidate_n=8733 from CPM intersect of non-null resolvable keys (mig_248 repair).. Refreshed post-mig_248.', recommended_next_step = 'Refine research question; refreshed post-mig_248', canonical_version_at_scoring = 'v1_0_post_mig_248', scored_at = CAST(CURRENT_TIMESTAMP AS TIMESTAMP WITH TIME ZONE) WHERE manuscript_id = 70;

-- M071 Immunologic medications and thyroid cancer
UPDATE manuscript_workspace.manuscript_feasibility_v1 SET candidate_n = 10871, variable_coverage_pct = [100.0, 80.33, 100.0]::DOUBLE[], feasibility_color = 'GREEN', gating_issues = 'candidate_n=8733 from CPM intersect of non-null resolvable keys (mig_248 repair).. Refreshed post-mig_248.', recommended_next_step = 'Refine research question; refreshed post-mig_248', canonical_version_at_scoring = 'v1_0_post_mig_248', scored_at = CAST(CURRENT_TIMESTAMP AS TIMESTAMP WITH TIME ZONE) WHERE manuscript_id = 71;

-- M072 Preop molecular profile impact on surgical decision-making
UPDATE manuscript_workspace.manuscript_feasibility_v1 SET candidate_n = 1286, variable_coverage_pct = [11.83, 2.91, 38.06]::DOUBLE[], feasibility_color = 'RED', gating_issues = 'Histology 64pct in molecular cohort post-v17 feasibility YELLOW→RED (coverage/cohort reassessed).', recommended_next_step = 'Refine question', canonical_version_at_scoring = 'v1_0_post_mig_248', scored_at = CAST(CURRENT_TIMESTAMP AS TIMESTAMP WITH TIME ZONE) WHERE manuscript_id = 72;

-- M073 Post-op Tg levels and recurrence: lobectomy vs total thyroidectomy
UPDATE manuscript_workspace.manuscript_feasibility_v1 SET candidate_n = 2567, variable_coverage_pct = [23.61, 25.03, 80.33]::DOUBLE[], feasibility_color = 'RED', gating_issues = 'Idea stage post-v17 feasibility GREEN→RED (coverage/cohort reassessed).', recommended_next_step = 'Refine question', canonical_version_at_scoring = 'v1_0_post_mig_248', scored_at = CAST(CURRENT_TIMESTAMP AS TIMESTAMP WITH TIME ZONE) WHERE manuscript_id = 73;

-- M074 Geographic analysis: zip codes and thyroid cancer patterns
UPDATE manuscript_workspace.manuscript_feasibility_v1 SET candidate_n = 0, variable_coverage_pct = [NULL::DOUBLE]::DOUBLE[], feasibility_color = 'RED', gating_issues = 'Zip code data not available post-v17 schema: zip_code MISSING from canonical_patient_master. Schema/coverage gaps: zip_code MISSING from canonical_patient_master and cohort_descriptive_full_cohort_v1', recommended_next_step = 'Requires geocoded data', canonical_version_at_scoring = 'v1_0_post_mig_248', scored_at = CAST(CURRENT_TIMESTAMP AS TIMESTAMP WITH TIME ZONE) WHERE manuscript_id = 74;

-- M075 Multiple TI-RADS scored nodules: FNA selection
UPDATE manuscript_workspace.manuscript_feasibility_v1 SET candidate_n = 3282, variable_coverage_pct = [30.19, 46.23, 38.06]::DOUBLE[], feasibility_color = 'YELLOW', gating_issues = 'NLP rollup: nlp_tirads_max_category. cohort views alias cupm.max_tirads_category_ever) post-v17 feasibility YELLOW→RED (coverage/cohort reassessed).. Feasibility RED→YELLOW post-mig_248 rescoring.', recommended_next_step = 'Refine question; focus on FNA-biopsied subset', canonical_version_at_scoring = 'v1_0_post_mig_248', scored_at = CAST(CURRENT_TIMESTAMP AS TIMESTAMP WITH TIME ZONE) WHERE manuscript_id = 75;

-- M076 Post-surgery LN surveillance: US with/without FNA
UPDATE manuscript_workspace.manuscript_feasibility_v1 SET candidate_n = 10871, variable_coverage_pct = [100.0, 80.33, 100.0]::DOUBLE[], feasibility_color = 'GREEN', gating_issues = 'candidate_n=8733 from CPM intersect of non-null resolvable keys (mig_248 repair).. Refreshed post-mig_248.', recommended_next_step = 'Refine research question; refreshed post-mig_248', canonical_version_at_scoring = 'v1_0_post_mig_248', scored_at = CAST(CURRENT_TIMESTAMP AS TIMESTAMP WITH TIME ZONE) WHERE manuscript_id = 76;

-- M077 Quality of life: hemi vs total +/- RAI
UPDATE manuscript_workspace.manuscript_feasibility_v1 SET candidate_n = 0, variable_coverage_pct = [NULL::DOUBLE]::DOUBLE[], feasibility_color = 'RED', gating_issues = 'QoL data not collected post-v17 schema: quality_of_life MISSING from canonical_patient_master. Schema/coverage gaps: quality_of_life MISSING from canonical_patient_master and cohort_descriptive_full_cohort_v1', recommended_next_step = 'Requires prospective study', canonical_version_at_scoring = 'v1_0_post_mig_248', scored_at = CAST(CURRENT_TIMESTAMP AS TIMESTAMP WITH TIME ZONE) WHERE manuscript_id = 77;

-- M078 Carcinoma in Graves: survival and recurrence
UPDATE manuscript_workspace.manuscript_feasibility_v1 SET candidate_n = 1530, variable_coverage_pct = [5.28, 100.0, 38.06]::DOUBLE[], feasibility_color = 'RED', gating_issues = 'Histology 50pct in Graves cohort post-v17 feasibility YELLOW→RED (coverage/cohort reassessed).', recommended_next_step = 'Build cohort; focus on malignant subset', canonical_version_at_scoring = 'v1_0_post_mig_248', scored_at = CAST(CURRENT_TIMESTAMP AS TIMESTAMP WITH TIME ZONE) WHERE manuscript_id = 78;

-- M079 Eucalcemic hypoparathyroidism outcomes
UPDATE manuscript_workspace.manuscript_feasibility_v1 SET candidate_n = 66, variable_coverage_pct = [100.0, 100.0]::DOUBLE[], feasibility_color = 'YELLOW', gating_issues = 'N=66 limited by lab coverage', recommended_next_step = 'Wait for v1_1 lab pull', canonical_version_at_scoring = 'v1_0_post_mig_248', scored_at = CAST(CURRENT_TIMESTAMP AS TIMESTAMP WITH TIME ZONE) WHERE manuscript_id = 79;

-- M080 Value of molecular testing for Bethesda V/VI nodules
UPDATE manuscript_workspace.manuscript_feasibility_v1 SET candidate_n = 306, variable_coverage_pct = [11.83, 2.91, 38.06]::DOUBLE[], feasibility_color = 'RED', gating_issues = 'Histology 64pct in molecular cohort post-v17 feasibility YELLOW→RED (coverage/cohort reassessed).', recommended_next_step = 'Refine question', canonical_version_at_scoring = 'v1_0_post_mig_248', scored_at = CAST(CURRENT_TIMESTAMP AS TIMESTAMP WITH TIME ZONE) WHERE manuscript_id = 80;

-- M081 RAI-resistant tumors: detection and recurrence patterns
UPDATE manuscript_workspace.manuscript_feasibility_v1 SET candidate_n = 862, variable_coverage_pct = [100.0, 100.0, 28.92]::DOUBLE[], feasibility_color = 'RED', gating_issues = 'ATA risk 54pct in RAI cohort post-v17 feasibility YELLOW→RED (coverage/cohort reassessed).', recommended_next_step = 'Focus on RAI outcomes stratified by ATA risk', canonical_version_at_scoring = 'v1_0_post_mig_248', scored_at = CAST(CURRENT_TIMESTAMP AS TIMESTAMP WITH TIME ZONE) WHERE manuscript_id = 81;

-- M082 Parathyroid tumors in thyroid pathology
UPDATE manuscript_workspace.manuscript_feasibility_v1 SET candidate_n = 1399, variable_coverage_pct = [13.72, 17.96]::DOUBLE[], feasibility_color = 'RED', gating_issues = 'Idea stage post-v17 feasibility GREEN→RED (coverage/cohort reassessed).', recommended_next_step = 'Refine question', canonical_version_at_scoring = 'v1_0_post_mig_248', scored_at = CAST(CURRENT_TIMESTAMP AS TIMESTAMP WITH TIME ZONE) WHERE manuscript_id = 82;

-- M083 Metastatic pancreatic endocrine tumor and struma ovarii
UPDATE manuscript_workspace.manuscript_feasibility_v1 SET candidate_n = 0, variable_coverage_pct = []::DOUBLE[], feasibility_color = 'RED', gating_issues = 'Extremely rare case types', recommended_next_step = 'Manual chart review needed', canonical_version_at_scoring = 'v1_0_post_mig_248', scored_at = CAST(CURRENT_TIMESTAMP AS TIMESTAMP WITH TIME ZONE) WHERE manuscript_id = 83;

-- =============================================================================
-- Post-apply verification (see CURSOR_PROMPT_MIG_249 §4)
-- =============================================================================
