-- mig_100 — DEPRECATED (2026-05-14)
--
-- This parquet → staging → MERGE path loaded recurrence_histology /
-- recurrence_evidence_source from MotherDuck mig_332 / pre_mig284 archive.
-- That lineage is retired in favor of BigQuery-native reconstruction from
-- operative spine + path_synoptics + FNA + Tg + LLM + recurrence_event_clean_v1.
--
-- Use instead:
--   bq query < bq_migrations/mig_101_canonical_recurrence_v1_bq_native_histology_evidence_20260514.sql
--
-- Historical MERGE (DO NOT RUN — kept only as audit reference):
-- -----------------------------------------------------------------------------
-- MERGE `thyroid-canonical-pub-2026.pub_canonical.canonical_recurrence_v1` AS T
-- USING `thyroid-canonical-pub-2026.pub_workspace.stg_canonical_recurrence_v1_mig332` AS S
-- ON CAST(T.research_id AS STRING) = CAST(S.research_id AS STRING)
-- WHEN MATCHED THEN UPDATE SET
--   T.recurrence_histology = S.recurrence_histology,
--   T.recurrence_evidence_source = S.recurrence_evidence_source;
-- -----------------------------------------------------------------------------

SELECT 'mig_100 deprecated — run mig_101 BQ-native recurrence column rebuild instead' AS notice;
