-- Date Association Enrichment Views
-- Generated by 15_date_association_audit.py
-- Deploy to thyroid_research_2026 via: USE thyroid_research_2026;
--
-- NOTE: After script 27 adds provenance columns (inferred_event_date,
-- date_source, date_granularity, date_confidence) to the base tables,
-- these views must use EXCLUDE to avoid duplicate column names from e.*.

-- === enriched_note_entities_genetics ===
CREATE OR REPLACE VIEW enriched_note_entities_genetics AS
WITH ps_primary AS (
    SELECT
        research_id,
        TRY_CAST(surg_date AS DATE) AS surg_date_parsed,
        surg_date AS surg_date_raw,
        ROW_NUMBER() OVER (
            PARTITION BY research_id
            ORDER BY TRY_CAST(surg_date AS DATE) ASC NULLS LAST
        ) AS op_seq
    FROM path_synoptics
    WHERE surg_date IS NOT NULL AND surg_date != ''
),
fna_primary AS (
    SELECT
        research_id,
        fna_date_parsed,
        TRY_CAST(fna_date_parsed AS DATE) AS fna_date,
        fna_index,
        ROW_NUMBER() OVER (
            PARTITION BY research_id
            ORDER BY TRY_CAST(fna_date_parsed AS DATE) DESC NULLS LAST,
                     fna_index DESC
        ) AS fna_seq
    FROM fna_history
    WHERE fna_date_parsed IS NOT NULL AND fna_date_parsed != ''
),
mt_valid AS (
    SELECT
        research_id,
        CASE
            WHEN TRY_CAST("date" AS DATE) IS NOT NULL
                THEN TRY_CAST("date" AS DATE)
            WHEN regexp_matches(CAST("date" AS VARCHAR), '^\d{4}$')
                THEN TRY_CAST(CAST("date" AS VARCHAR) || '-01-01' AS DATE)
            ELSE NULL
        END AS mt_date_parsed,
        CASE
            WHEN regexp_matches(CAST("date" AS VARCHAR), '^\d{4}$')
                THEN 'year'
            ELSE 'day'
        END AS mt_date_granularity,
        "date" AS mt_date_raw,
        test_index,
        ROW_NUMBER() OVER (
            PARTITION BY research_id
            ORDER BY
                CASE WHEN TRY_CAST("date" AS DATE) IS NOT NULL THEN 0 ELSE 1 END,
                TRY_CAST("date" AS DATE) DESC NULLS LAST,
                test_index DESC
        ) AS mt_seq
    FROM molecular_testing
    WHERE "date" IS NOT NULL
      AND CAST("date" AS VARCHAR) NOT IN ('x', 'X', '', 'None', 'maybe?')
)
SELECT
    e.* EXCLUDE (inferred_event_date, date_source, date_granularity, date_confidence),
    COALESCE(
            TRY_CAST(e.entity_date AS DATE),
            TRY_CAST(e.note_date AS DATE),
            ps.surg_date_parsed,
            mt.mt_date_parsed,
            fna.fna_date
    ) AS inferred_event_date,
    CASE
            WHEN e.entity_date IS NOT NULL AND TRY_CAST(e.entity_date AS DATE) IS NOT NULL
            THEN 'entity_date'
            WHEN e.note_date IS NOT NULL AND TRY_CAST(e.note_date AS DATE) IS NOT NULL
            THEN 'note_date'
            WHEN ps.surg_date_parsed IS NOT NULL THEN 'surg_date'
            WHEN mt.mt_date_parsed IS NOT NULL THEN 'molecular_testing_date'
            WHEN fna.fna_date IS NOT NULL THEN 'fna_date_parsed'
            ELSE 'unrecoverable'
    END AS date_source,
    CASE
            WHEN e.entity_date IS NOT NULL AND TRY_CAST(e.entity_date AS DATE) IS NOT NULL
            THEN 'day'
            WHEN e.note_date IS NOT NULL AND TRY_CAST(e.note_date AS DATE) IS NOT NULL
            THEN 'day'
            WHEN ps.surg_date_parsed IS NOT NULL THEN 'day'
            WHEN mt.mt_date_parsed IS NOT NULL THEN mt.mt_date_granularity
            WHEN fna.fna_date IS NOT NULL THEN 'day'
            ELSE NULL
    END AS date_granularity,
    CASE
            WHEN e.entity_date IS NOT NULL AND TRY_CAST(e.entity_date AS DATE) IS NOT NULL
            THEN 100
            WHEN e.note_date IS NOT NULL AND TRY_CAST(e.note_date AS DATE) IS NOT NULL
            THEN 70
            WHEN ps.surg_date_parsed IS NOT NULL THEN 60
            WHEN mt.mt_date_parsed IS NOT NULL
            THEN CASE WHEN mt.mt_date_granularity = 'year' THEN 50 ELSE 60 END
            WHEN fna.fna_date IS NOT NULL THEN 55
            ELSE 0
    END AS date_confidence,
    CASE
            WHEN e.entity_date IS NOT NULL AND TRY_CAST(e.entity_date AS DATE) IS NOT NULL
            THEN 'extracted'
            WHEN e.note_date IS NOT NULL AND TRY_CAST(e.note_date AS DATE) IS NOT NULL
            THEN 'encounter'
            WHEN ps.surg_date_parsed IS NOT NULL THEN 'surgical'
            WHEN mt.mt_date_parsed IS NOT NULL THEN 'molecular'
            WHEN fna.fna_date IS NOT NULL THEN 'cytology'
            ELSE 'none'
    END AS date_anchor_type,
    CASE
            WHEN e.entity_date IS NOT NULL AND TRY_CAST(e.entity_date AS DATE) IS NOT NULL
            THEN 'note_entities_genetics'
            WHEN e.note_date IS NOT NULL AND TRY_CAST(e.note_date AS DATE) IS NOT NULL
            THEN 'clinical_notes_long'
            WHEN ps.surg_date_parsed IS NOT NULL THEN 'path_synoptics'
            WHEN mt.mt_date_parsed IS NOT NULL THEN 'molecular_testing'
            WHEN fna.fna_date IS NOT NULL THEN 'fna_history'
            ELSE 'none'
    END AS date_anchor_table
FROM note_entities_genetics e
LEFT JOIN ps_primary ps
    ON CAST(e.research_id AS BIGINT) = ps.research_id AND ps.op_seq = 1
LEFT JOIN mt_valid mt
    ON CAST(e.research_id AS BIGINT) = mt.research_id AND mt.mt_seq = 1
LEFT JOIN fna_primary fna
    ON CAST(e.research_id AS BIGINT) = fna.research_id AND fna.fna_seq = 1;

-- === enriched_note_entities_staging ===
CREATE OR REPLACE VIEW enriched_note_entities_staging AS
WITH ps_primary AS (
    SELECT
        research_id,
        TRY_CAST(surg_date AS DATE) AS surg_date_parsed,
        surg_date AS surg_date_raw,
        ROW_NUMBER() OVER (
            PARTITION BY research_id
            ORDER BY TRY_CAST(surg_date AS DATE) ASC NULLS LAST
        ) AS op_seq
    FROM path_synoptics
    WHERE surg_date IS NOT NULL AND surg_date != ''
)
SELECT
    e.* EXCLUDE (inferred_event_date, date_source, date_granularity, date_confidence),
    COALESCE(
            TRY_CAST(e.entity_date AS DATE),
            TRY_CAST(e.note_date AS DATE),
            ps.surg_date_parsed
    ) AS inferred_event_date,
    CASE
            WHEN e.entity_date IS NOT NULL AND TRY_CAST(e.entity_date AS DATE) IS NOT NULL
            THEN 'entity_date'
            WHEN e.note_date IS NOT NULL AND TRY_CAST(e.note_date AS DATE) IS NOT NULL
            THEN 'note_date'
            WHEN ps.surg_date_parsed IS NOT NULL THEN 'surg_date'
            ELSE 'unrecoverable'
    END AS date_source,
    CASE
            WHEN e.entity_date IS NOT NULL AND TRY_CAST(e.entity_date AS DATE) IS NOT NULL
            THEN 'day'
            WHEN e.note_date IS NOT NULL AND TRY_CAST(e.note_date AS DATE) IS NOT NULL
            THEN 'day'
            WHEN ps.surg_date_parsed IS NOT NULL THEN 'day'
            ELSE NULL
    END AS date_granularity,
    CASE
            WHEN e.entity_date IS NOT NULL AND TRY_CAST(e.entity_date AS DATE) IS NOT NULL
            THEN 100
            WHEN e.note_date IS NOT NULL AND TRY_CAST(e.note_date AS DATE) IS NOT NULL
            THEN 70
            WHEN ps.surg_date_parsed IS NOT NULL THEN 60
            ELSE 0
    END AS date_confidence,
    CASE
            WHEN e.entity_date IS NOT NULL AND TRY_CAST(e.entity_date AS DATE) IS NOT NULL
            THEN 'extracted'
            WHEN e.note_date IS NOT NULL AND TRY_CAST(e.note_date AS DATE) IS NOT NULL
            THEN 'encounter'
            WHEN ps.surg_date_parsed IS NOT NULL THEN 'surgical'
            ELSE 'none'
    END AS date_anchor_type,
    CASE
            WHEN e.entity_date IS NOT NULL AND TRY_CAST(e.entity_date AS DATE) IS NOT NULL
            THEN 'note_entities_staging'
            WHEN e.note_date IS NOT NULL AND TRY_CAST(e.note_date AS DATE) IS NOT NULL
            THEN 'clinical_notes_long'
            WHEN ps.surg_date_parsed IS NOT NULL THEN 'path_synoptics'
            ELSE 'none'
    END AS date_anchor_table
FROM note_entities_staging e
LEFT JOIN ps_primary ps
    ON CAST(e.research_id AS BIGINT) = ps.research_id AND ps.op_seq = 1;

-- === enriched_note_entities_procedures ===
CREATE OR REPLACE VIEW enriched_note_entities_procedures AS
WITH ps_primary AS (
    SELECT
        research_id,
        TRY_CAST(surg_date AS DATE) AS surg_date_parsed,
        surg_date AS surg_date_raw,
        ROW_NUMBER() OVER (
            PARTITION BY research_id
            ORDER BY TRY_CAST(surg_date AS DATE) ASC NULLS LAST
        ) AS op_seq
    FROM path_synoptics
    WHERE surg_date IS NOT NULL AND surg_date != ''
)
SELECT
    e.* EXCLUDE (inferred_event_date, date_source, date_granularity, date_confidence),
    COALESCE(
            TRY_CAST(e.entity_date AS DATE),
            TRY_CAST(e.note_date AS DATE),
            ps.surg_date_parsed
    ) AS inferred_event_date,
    CASE
            WHEN e.entity_date IS NOT NULL AND TRY_CAST(e.entity_date AS DATE) IS NOT NULL
            THEN 'entity_date'
            WHEN e.note_date IS NOT NULL AND TRY_CAST(e.note_date AS DATE) IS NOT NULL
            THEN 'note_date'
            WHEN ps.surg_date_parsed IS NOT NULL THEN 'surg_date'
            ELSE 'unrecoverable'
    END AS date_source,
    CASE
            WHEN e.entity_date IS NOT NULL AND TRY_CAST(e.entity_date AS DATE) IS NOT NULL
            THEN 'day'
            WHEN e.note_date IS NOT NULL AND TRY_CAST(e.note_date AS DATE) IS NOT NULL
            THEN 'day'
            WHEN ps.surg_date_parsed IS NOT NULL THEN 'day'
            ELSE NULL
    END AS date_granularity,
    CASE
            WHEN e.entity_date IS NOT NULL AND TRY_CAST(e.entity_date AS DATE) IS NOT NULL
            THEN 100
            WHEN e.note_date IS NOT NULL AND TRY_CAST(e.note_date AS DATE) IS NOT NULL
            THEN 70
            WHEN ps.surg_date_parsed IS NOT NULL THEN 60
            ELSE 0
    END AS date_confidence,
    CASE
            WHEN e.entity_date IS NOT NULL AND TRY_CAST(e.entity_date AS DATE) IS NOT NULL
            THEN 'extracted'
            WHEN e.note_date IS NOT NULL AND TRY_CAST(e.note_date AS DATE) IS NOT NULL
            THEN 'encounter'
            WHEN ps.surg_date_parsed IS NOT NULL THEN 'surgical'
            ELSE 'none'
    END AS date_anchor_type,
    CASE
            WHEN e.entity_date IS NOT NULL AND TRY_CAST(e.entity_date AS DATE) IS NOT NULL
            THEN 'note_entities_procedures'
            WHEN e.note_date IS NOT NULL AND TRY_CAST(e.note_date AS DATE) IS NOT NULL
            THEN 'clinical_notes_long'
            WHEN ps.surg_date_parsed IS NOT NULL THEN 'path_synoptics'
            ELSE 'none'
    END AS date_anchor_table
FROM note_entities_procedures e
LEFT JOIN ps_primary ps
    ON CAST(e.research_id AS BIGINT) = ps.research_id AND ps.op_seq = 1;

-- === enriched_note_entities_complications ===
CREATE OR REPLACE VIEW enriched_note_entities_complications AS
WITH ps_primary AS (
    SELECT
        research_id,
        TRY_CAST(surg_date AS DATE) AS surg_date_parsed,
        surg_date AS surg_date_raw,
        ROW_NUMBER() OVER (
            PARTITION BY research_id
            ORDER BY TRY_CAST(surg_date AS DATE) ASC NULLS LAST
        ) AS op_seq
    FROM path_synoptics
    WHERE surg_date IS NOT NULL AND surg_date != ''
)
SELECT
    e.* EXCLUDE (inferred_event_date, date_source, date_granularity, date_confidence),
    COALESCE(
            TRY_CAST(e.entity_date AS DATE),
            TRY_CAST(e.note_date AS DATE),
            ps.surg_date_parsed
    ) AS inferred_event_date,
    CASE
            WHEN e.entity_date IS NOT NULL AND TRY_CAST(e.entity_date AS DATE) IS NOT NULL
            THEN 'entity_date'
            WHEN e.note_date IS NOT NULL AND TRY_CAST(e.note_date AS DATE) IS NOT NULL
            THEN 'note_date'
            WHEN ps.surg_date_parsed IS NOT NULL THEN 'surg_date'
            ELSE 'unrecoverable'
    END AS date_source,
    CASE
            WHEN e.entity_date IS NOT NULL AND TRY_CAST(e.entity_date AS DATE) IS NOT NULL
            THEN 'day'
            WHEN e.note_date IS NOT NULL AND TRY_CAST(e.note_date AS DATE) IS NOT NULL
            THEN 'day'
            WHEN ps.surg_date_parsed IS NOT NULL THEN 'day'
            ELSE NULL
    END AS date_granularity,
    CASE
            WHEN e.entity_date IS NOT NULL AND TRY_CAST(e.entity_date AS DATE) IS NOT NULL
            THEN 100
            WHEN e.note_date IS NOT NULL AND TRY_CAST(e.note_date AS DATE) IS NOT NULL
            THEN 70
            WHEN ps.surg_date_parsed IS NOT NULL THEN 60
            ELSE 0
    END AS date_confidence,
    CASE
            WHEN e.entity_date IS NOT NULL AND TRY_CAST(e.entity_date AS DATE) IS NOT NULL
            THEN 'extracted'
            WHEN e.note_date IS NOT NULL AND TRY_CAST(e.note_date AS DATE) IS NOT NULL
            THEN 'encounter'
            WHEN ps.surg_date_parsed IS NOT NULL THEN 'surgical'
            ELSE 'none'
    END AS date_anchor_type,
    CASE
            WHEN e.entity_date IS NOT NULL AND TRY_CAST(e.entity_date AS DATE) IS NOT NULL
            THEN 'note_entities_complications'
            WHEN e.note_date IS NOT NULL AND TRY_CAST(e.note_date AS DATE) IS NOT NULL
            THEN 'clinical_notes_long'
            WHEN ps.surg_date_parsed IS NOT NULL THEN 'path_synoptics'
            ELSE 'none'
    END AS date_anchor_table
FROM note_entities_complications e
LEFT JOIN ps_primary ps
    ON CAST(e.research_id AS BIGINT) = ps.research_id AND ps.op_seq = 1;

-- === enriched_note_entities_medications ===
CREATE OR REPLACE VIEW enriched_note_entities_medications AS

SELECT
    e.* EXCLUDE (inferred_event_date, date_source, date_granularity, date_confidence),
    COALESCE(
            TRY_CAST(e.entity_date AS DATE),
            TRY_CAST(e.note_date AS DATE)
    ) AS inferred_event_date,
    CASE
            WHEN e.entity_date IS NOT NULL AND TRY_CAST(e.entity_date AS DATE) IS NOT NULL
            THEN 'entity_date'
            WHEN e.note_date IS NOT NULL AND TRY_CAST(e.note_date AS DATE) IS NOT NULL
            THEN 'note_date'
            ELSE 'unrecoverable'
    END AS date_source,
    CASE
            WHEN e.entity_date IS NOT NULL AND TRY_CAST(e.entity_date AS DATE) IS NOT NULL
            THEN 'day'
            WHEN e.note_date IS NOT NULL AND TRY_CAST(e.note_date AS DATE) IS NOT NULL
            THEN 'day'
            ELSE NULL
    END AS date_granularity,
    CASE
            WHEN e.entity_date IS NOT NULL AND TRY_CAST(e.entity_date AS DATE) IS NOT NULL
            THEN 100
            WHEN e.note_date IS NOT NULL AND TRY_CAST(e.note_date AS DATE) IS NOT NULL
            THEN 70
            ELSE 0
    END AS date_confidence,
    CASE
            WHEN e.entity_date IS NOT NULL AND TRY_CAST(e.entity_date AS DATE) IS NOT NULL
            THEN 'extracted'
            WHEN e.note_date IS NOT NULL AND TRY_CAST(e.note_date AS DATE) IS NOT NULL
            THEN 'encounter'
            ELSE 'none'
    END AS date_anchor_type,
    CASE
            WHEN e.entity_date IS NOT NULL AND TRY_CAST(e.entity_date AS DATE) IS NOT NULL
            THEN 'note_entities_medications'
            WHEN e.note_date IS NOT NULL AND TRY_CAST(e.note_date AS DATE) IS NOT NULL
            THEN 'clinical_notes_long'
            ELSE 'none'
    END AS date_anchor_table
FROM note_entities_medications e;

-- === enriched_note_entities_problem_list ===
CREATE OR REPLACE VIEW enriched_note_entities_problem_list AS

SELECT
    e.* EXCLUDE (inferred_event_date, date_source, date_granularity, date_confidence),
    COALESCE(
            TRY_CAST(e.entity_date AS DATE),
            TRY_CAST(e.note_date AS DATE)
    ) AS inferred_event_date,
    CASE
            WHEN e.entity_date IS NOT NULL AND TRY_CAST(e.entity_date AS DATE) IS NOT NULL
            THEN 'entity_date'
            WHEN e.note_date IS NOT NULL AND TRY_CAST(e.note_date AS DATE) IS NOT NULL
            THEN 'note_date'
            ELSE 'unrecoverable'
    END AS date_source,
    CASE
            WHEN e.entity_date IS NOT NULL AND TRY_CAST(e.entity_date AS DATE) IS NOT NULL
            THEN 'day'
            WHEN e.note_date IS NOT NULL AND TRY_CAST(e.note_date AS DATE) IS NOT NULL
            THEN 'day'
            ELSE NULL
    END AS date_granularity,
    CASE
            WHEN e.entity_date IS NOT NULL AND TRY_CAST(e.entity_date AS DATE) IS NOT NULL
            THEN 100
            WHEN e.note_date IS NOT NULL AND TRY_CAST(e.note_date AS DATE) IS NOT NULL
            THEN 70
            ELSE 0
    END AS date_confidence,
    CASE
            WHEN e.entity_date IS NOT NULL AND TRY_CAST(e.entity_date AS DATE) IS NOT NULL
            THEN 'extracted'
            WHEN e.note_date IS NOT NULL AND TRY_CAST(e.note_date AS DATE) IS NOT NULL
            THEN 'encounter'
            ELSE 'none'
    END AS date_anchor_type,
    CASE
            WHEN e.entity_date IS NOT NULL AND TRY_CAST(e.entity_date AS DATE) IS NOT NULL
            THEN 'note_entities_problem_list'
            WHEN e.note_date IS NOT NULL AND TRY_CAST(e.note_date AS DATE) IS NOT NULL
            THEN 'clinical_notes_long'
            ELSE 'none'
    END AS date_anchor_table
FROM note_entities_problem_list e;

-- === missing_date_associations_audit ===
CREATE OR REPLACE VIEW missing_date_associations_audit AS
SELECT 'genetics' AS entity_table, research_id, entity_date, note_date,
       inferred_event_date, date_source, date_granularity, date_confidence,
       date_anchor_type, date_anchor_table
FROM enriched_note_entities_genetics
UNION ALL
SELECT 'staging', research_id, entity_date, note_date,
       inferred_event_date, date_source, date_granularity, date_confidence,
       date_anchor_type, date_anchor_table
FROM enriched_note_entities_staging
UNION ALL
SELECT 'procedures', research_id, entity_date, note_date,
       inferred_event_date, date_source, date_granularity, date_confidence,
       date_anchor_type, date_anchor_table
FROM enriched_note_entities_procedures
UNION ALL
SELECT 'complications', research_id, entity_date, note_date,
       inferred_event_date, date_source, date_granularity, date_confidence,
       date_anchor_type, date_anchor_table
FROM enriched_note_entities_complications
UNION ALL
SELECT 'medications', research_id, entity_date, note_date,
       inferred_event_date, date_source, date_granularity, date_confidence,
       date_anchor_type, date_anchor_table
FROM enriched_note_entities_medications
UNION ALL
SELECT 'problem_list', research_id, entity_date, note_date,
       inferred_event_date, date_source, date_granularity, date_confidence,
       date_anchor_type, date_anchor_table
FROM enriched_note_entities_problem_list;

-- === date_recovery_summary ===
CREATE OR REPLACE VIEW date_recovery_summary AS
SELECT
    entity_table,
    date_source,
    date_anchor_type,
    COUNT(*) AS rows_affected,
    COUNT(DISTINCT research_id) AS unique_patients,
    ROUND(100.0 * COUNT(*) / SUM(COUNT(*)) OVER (PARTITION BY entity_table), 2)
        AS pct_of_table,
    ROUND(AVG(date_confidence), 1) AS avg_confidence
FROM missing_date_associations_audit
GROUP BY 1, 2, 3
ORDER BY entity_table, rows_affected DESC;

-- === histology_reconciliation_mv ===
CREATE OR REPLACE VIEW histology_reconciliation_mv AS
WITH ps_tumors AS (
    SELECT
        ps.research_id,
        TRY_CAST(ps.surg_date AS DATE) AS surg_date,
        ps.tumor_1_histologic_type,
        ps.tumor_1_variant,
        ps.tumor_1_extrathyroidal_extension,
        ps.tumor_1_margin_status,
        ps.tumor_1_pt,
        ps.tumor_1_pn,
        ps.tumor_1_pm,
        ps.tumor_1_size_greatest_dimension_cm,
        ps.tumor_1_ln_involved,
        ps.tumor_1_ln_examined,
        ps.tumor_1_angioinvasion,
        ps.tumor_1_lymphatic_invasion,
        ps.tumor_1_perineural_invasion,
        ps.tumor_1_capsular_invasion,
        ps.reop,
        ROW_NUMBER() OVER (
            PARTITION BY ps.research_id
            ORDER BY TRY_CAST(ps.surg_date AS DATE) ASC NULLS LAST
        ) AS op_seq
    FROM path_synoptics ps
    WHERE ps.surg_date IS NOT NULL AND ps.surg_date != ''
),
staging_entities AS (
    SELECT
        e.research_id,
        e.entity_type,
        e.entity_value_norm,
        e.present_or_negated,
        e.confidence,
        TRY_CAST(COALESCE(e.entity_date, e.note_date) AS DATE) AS entity_resolved_date
    FROM note_entities_staging e
    WHERE e.present_or_negated = 'present'
)
SELECT
    ps.research_id,
    ps.surg_date,
    ps.op_seq,
    ps.tumor_1_histologic_type,
    ps.tumor_1_variant,
    ps.tumor_1_extrathyroidal_extension,
    ps.tumor_1_margin_status,
    ps.tumor_1_pt,
    ps.tumor_1_pn,
    ps.tumor_1_pm,
    ps.tumor_1_size_greatest_dimension_cm,
    ps.tumor_1_ln_involved,
    ps.tumor_1_ln_examined,
    ps.tumor_1_angioinvasion,
    ps.tumor_1_lymphatic_invasion,
    ps.tumor_1_perineural_invasion,
    ps.tumor_1_capsular_invasion,
    ps.reop,
    se_t.entity_value_norm AS note_t_stage,
    se_n.entity_value_norm AS note_n_stage,
    se_m.entity_value_norm AS note_m_stage,
    se_ov.entity_value_norm AS note_overall_stage,
    CASE
        WHEN ps.tumor_1_pt IS NOT NULL AND se_t.entity_value_norm IS NOT NULL
             AND LOWER(REPLACE(ps.tumor_1_pt, ' ', '')) != LOWER(REPLACE(se_t.entity_value_norm, ' ', ''))
            THEN TRUE ELSE FALSE
    END AS t_stage_discordant,
    CASE
        WHEN ps.tumor_1_pn IS NOT NULL AND se_n.entity_value_norm IS NOT NULL
             AND LOWER(REPLACE(ps.tumor_1_pn, ' ', '')) != LOWER(REPLACE(se_n.entity_value_norm, ' ', ''))
            THEN TRUE ELSE FALSE
    END AS n_stage_discordant,
    CASE
        WHEN ps.tumor_1_pt IS NULL AND ps.tumor_1_pn IS NULL THEN 'path_missing'
        WHEN se_t.entity_value_norm IS NULL AND se_n.entity_value_norm IS NULL THEN 'notes_missing'
        ELSE 'both_present'
    END AS reconciliation_status
FROM ps_tumors ps
LEFT JOIN staging_entities se_t
    ON CAST(ps.research_id AS BIGINT) = CAST(se_t.research_id AS BIGINT)
    AND se_t.entity_type = 'T_stage'
LEFT JOIN staging_entities se_n
    ON CAST(ps.research_id AS BIGINT) = CAST(se_n.research_id AS BIGINT)
    AND se_n.entity_type = 'N_stage'
LEFT JOIN staging_entities se_m
    ON CAST(ps.research_id AS BIGINT) = CAST(se_m.research_id AS BIGINT)
    AND se_m.entity_type = 'M_stage'
LEFT JOIN staging_entities se_ov
    ON CAST(ps.research_id AS BIGINT) = CAST(se_ov.research_id AS BIGINT)
    AND se_ov.entity_type = 'overall_stage'
WHERE ps.op_seq = 1;

-- === molecular_episode_mv ===
CREATE OR REPLACE VIEW molecular_episode_mv AS
WITH fna_dedup AS (
    SELECT
        research_id,
        TRY_CAST(fna_date_parsed AS DATE) AS fna_date,
        bethesda,
        fna_index,
        ROW_NUMBER() OVER (
            PARTITION BY research_id, fna_index
            ORDER BY TRY_CAST(fna_date_parsed AS DATE) DESC NULLS LAST
        ) AS rn
    FROM fna_history
    WHERE fna_date_parsed IS NOT NULL AND fna_date_parsed != ''
),
genetics_notes AS (
    SELECT
        research_id,
        entity_value_norm AS gene,
        present_or_negated,
        confidence,
        entity_date,
        note_date,
        TRY_CAST(COALESCE(entity_date, note_date) AS DATE) AS resolved_date,
        evidence_span
    FROM note_entities_genetics
    WHERE present_or_negated = 'present'
),
mt_base AS (
    SELECT
        mt.research_id,
        mt.thyroseq_afirma,
        mt.genetic_test_performed,
        mt.genetic_test,
        mt.result,
        mt.mutation,
        mt.detailed_findings,
        mt.nodule_info,
        mt.fna_bethesda,
        mt.test_index,
        CASE
            WHEN TRY_CAST(mt."date" AS DATE) IS NOT NULL
                THEN TRY_CAST(mt."date" AS DATE)
            WHEN regexp_matches(CAST(mt."date" AS VARCHAR), '^\d{4}$')
                THEN TRY_CAST(CAST(mt."date" AS VARCHAR) || '-01-01' AS DATE)
            ELSE NULL
        END AS mt_date,
        CASE
            WHEN regexp_matches(CAST(mt."date" AS VARCHAR), '^\d{4}$')
                THEN 'year'
            WHEN TRY_CAST(mt."date" AS DATE) IS NOT NULL THEN 'day'
            ELSE 'none'
        END AS mt_date_granularity
    FROM molecular_testing mt
)
SELECT
    COALESCE(mt.research_id, gn.research_id) AS research_id,
    mt.thyroseq_afirma,
    mt.genetic_test_performed,
    mt.genetic_test,
    mt.result AS mt_result,
    mt.mutation AS mt_mutation,
    mt.detailed_findings,
    mt.nodule_info,
    mt.fna_bethesda AS mt_fna_bethesda,
    mt.test_index,
    mt.mt_date,
    mt.mt_date_granularity,
    gn.gene AS note_gene,
    gn.confidence AS note_gene_confidence,
    gn.resolved_date AS note_gene_date,
    fd.fna_date AS closest_fna_date,
    fd.bethesda AS fna_bethesda,
    fd.fna_index,
    COALESCE(mt.mt_date, gn.resolved_date, fd.fna_date) AS best_episode_date,
    CASE
        WHEN mt.mt_date IS NOT NULL THEN 'molecular_testing'
        WHEN gn.resolved_date IS NOT NULL THEN 'note_entities_genetics'
        WHEN fd.fna_date IS NOT NULL THEN 'fna_history'
        ELSE 'unresolved'
    END AS episode_date_source
FROM mt_base mt
FULL OUTER JOIN genetics_notes gn
    ON CAST(mt.research_id AS BIGINT) = CAST(gn.research_id AS BIGINT)
LEFT JOIN fna_dedup fd
    ON COALESCE(CAST(mt.research_id AS BIGINT), CAST(gn.research_id AS BIGINT)) = fd.research_id
    AND fd.rn = 1;

-- === rai_episode_mv ===
CREATE OR REPLACE VIEW rai_episode_mv AS
WITH rai_meds AS (
    SELECT
        e.research_id,
        e.entity_value_norm,
        e.entity_value_raw,
        e.present_or_negated,
        e.confidence,
        e.entity_date,
        e.note_date,
        TRY_CAST(COALESCE(e.entity_date, e.note_date) AS DATE) AS resolved_date,
        e.evidence_span
    FROM note_entities_medications e
    WHERE e.present_or_negated = 'present'
      AND (
          LOWER(e.entity_value_norm) LIKE '%rai%'
          OR LOWER(e.entity_value_norm) LIKE '%radioactive%'
          OR LOWER(e.entity_value_norm) LIKE '%i-131%'
          OR LOWER(e.entity_value_norm) LIKE '%i131%'
          OR LOWER(e.entity_value_norm) LIKE '%iodine%'
          OR LOWER(e.entity_value_norm) LIKE '%thyrogen%'
      )
),
rai_procedures AS (
    SELECT
        e.research_id,
        e.entity_value_norm,
        e.entity_value_raw,
        e.present_or_negated,
        e.confidence,
        e.entity_date,
        e.note_date,
        TRY_CAST(COALESCE(e.entity_date, e.note_date) AS DATE) AS resolved_date,
        e.evidence_span
    FROM note_entities_procedures e
    WHERE e.present_or_negated = 'present'
      AND (
          LOWER(e.entity_value_norm) LIKE '%ablation%'
          OR LOWER(e.entity_value_raw) LIKE '%rai%'
          OR LOWER(e.entity_value_raw) LIKE '%radioactive%'
          OR LOWER(e.entity_value_raw) LIKE '%i-131%'
      )
),
rai_combined AS (
    SELECT research_id, entity_value_norm, entity_value_raw, present_or_negated,
           confidence, entity_date, note_date, resolved_date, evidence_span,
           'medications' AS source_domain
    FROM rai_meds
    UNION ALL
    SELECT research_id, entity_value_norm, entity_value_raw, present_or_negated,
           confidence, entity_date, note_date, resolved_date, evidence_span,
           'procedures' AS source_domain
    FROM rai_procedures
),
ps_primary AS (
    SELECT
        research_id,
        TRY_CAST(surg_date AS DATE) AS surg_date,
        ROW_NUMBER() OVER (
            PARTITION BY research_id
            ORDER BY TRY_CAST(surg_date AS DATE) ASC NULLS LAST
        ) AS op_seq
    FROM path_synoptics
    WHERE surg_date IS NOT NULL AND surg_date != ''
)
SELECT
    r.research_id,
    r.entity_value_norm AS rai_mention,
    r.entity_value_raw,
    r.source_domain,
    r.confidence,
    r.entity_date,
    r.note_date,
    r.resolved_date AS rai_resolved_date,
    ps.surg_date AS primary_surg_date,
    CASE
        WHEN r.resolved_date IS NOT NULL AND ps.surg_date IS NOT NULL
            THEN DATE_DIFF('day', ps.surg_date, r.resolved_date)
        ELSE NULL
    END AS days_surgery_to_rai,
    CASE
        WHEN r.resolved_date IS NULL THEN 'date_missing'
        WHEN ps.surg_date IS NULL THEN 'surgery_date_missing'
        WHEN DATE_DIFF('day', ps.surg_date, r.resolved_date) < 0 THEN 'pre_surgical'
        WHEN DATE_DIFF('day', ps.surg_date, r.resolved_date) <= 180 THEN 'within_6mo'
        WHEN DATE_DIFF('day', ps.surg_date, r.resolved_date) <= 365 THEN 'within_1yr'
        ELSE 'after_1yr'
    END AS rai_timing_category,
    r.evidence_span
FROM rai_combined r
LEFT JOIN ps_primary ps
    ON CAST(r.research_id AS BIGINT) = ps.research_id
    AND ps.op_seq = 1;

-- === validation_failures_mv ===
CREATE OR REPLACE VIEW validation_failures_mv AS
WITH all_enriched AS (
    SELECT 'genetics' AS domain, research_id, entity_date, note_date,
           inferred_event_date, date_source, date_confidence, date_anchor_type
    FROM enriched_note_entities_genetics
    UNION ALL
    SELECT 'staging', research_id, entity_date, note_date,
           inferred_event_date, date_source, date_confidence, date_anchor_type
    FROM enriched_note_entities_staging
    UNION ALL
    SELECT 'procedures', research_id, entity_date, note_date,
           inferred_event_date, date_source, date_confidence, date_anchor_type
    FROM enriched_note_entities_procedures
    UNION ALL
    SELECT 'complications', research_id, entity_date, note_date,
           inferred_event_date, date_source, date_confidence, date_anchor_type
    FROM enriched_note_entities_complications
    UNION ALL
    SELECT 'medications', research_id, entity_date, note_date,
           inferred_event_date, date_source, date_confidence, date_anchor_type
    FROM enriched_note_entities_medications
    UNION ALL
    SELECT 'problem_list', research_id, entity_date, note_date,
           inferred_event_date, date_source, date_confidence, date_anchor_type
    FROM enriched_note_entities_problem_list
)
SELECT
    domain,
    CASE
        WHEN inferred_event_date IS NULL THEN 'no_date_recoverable'
        WHEN inferred_event_date > CURRENT_DATE THEN 'future_date'
        WHEN inferred_event_date < DATE '1990-01-01' THEN 'implausible_past'
        WHEN entity_date IS NOT NULL AND note_date IS NOT NULL
             AND ABS(DATE_DIFF('day',
                     TRY_CAST(entity_date AS DATE),
                     TRY_CAST(note_date AS DATE))) > 365
            THEN 'entity_note_date_mismatch_gt_1yr'
        WHEN date_confidence < 50 THEN 'low_confidence'
        ELSE NULL
    END AS failure_type,
    research_id,
    entity_date,
    note_date,
    inferred_event_date,
    date_source,
    date_confidence,
    date_anchor_type
FROM all_enriched
WHERE
    inferred_event_date IS NULL
    OR inferred_event_date > CURRENT_DATE
    OR inferred_event_date < DATE '1990-01-01'
    OR (entity_date IS NOT NULL AND note_date IS NOT NULL
        AND ABS(DATE_DIFF('day',
                TRY_CAST(entity_date AS DATE),
                TRY_CAST(note_date AS DATE))) > 365)
    OR date_confidence < 50;

