-- Semantic Cleanup V3 Views
-- Generated by 17_semantic_cleanup_v3.py
-- Fixes the timeline/validation contradiction from reconciliation_v2.
--
-- Date status taxonomy applied to all enriched views:
--   exact_source_date       entity_date parsed (confidence 100)
--   inferred_day_level_date  note_date used (confidence 70)
--   coarse_anchor_date       surgery/FNA/molecular anchor (confidence 35-60)
--   unresolved_date          no date from any source (confidence 0)
--
-- Replaces: enriched_note_entities_* (all 6), timeline_rescue_mv,
--           validation_failures_v2
-- Adds: validation_failures_v3, timeline_rescue_v2_mv,
--        timeline_unresolved_summary_v2_mv, patient_validation_rollup_v2_mv
--
-- Depends on: base tables (note_entities_*, path_synoptics, fna_history,
--              molecular_testing), reconciliation_v2 views

-- === enriched_note_entities_genetics ===
CREATE OR REPLACE VIEW enriched_note_entities_genetics AS
WITH 
ps_primary AS (
    SELECT
        research_id,
        TRY_CAST(surg_date AS DATE) AS surg_date_parsed,
        surg_date AS surg_date_raw,
        ROW_NUMBER() OVER (
            PARTITION BY research_id
            ORDER BY TRY_CAST(surg_date AS DATE) ASC NULLS LAST
        ) AS op_seq
    FROM path_synoptics
    WHERE surg_date IS NOT NULL AND surg_date != ''
),

fna_primary AS (
    SELECT
        research_id,
        fna_date_parsed,
        TRY_CAST(fna_date_parsed AS DATE) AS fna_date,
        fna_index,
        ROW_NUMBER() OVER (
            PARTITION BY research_id
            ORDER BY TRY_CAST(fna_date_parsed AS DATE) DESC NULLS LAST,
                     fna_index DESC
        ) AS fna_seq
    FROM fna_history
    WHERE fna_date_parsed IS NOT NULL AND fna_date_parsed != ''
),

mt_valid AS (
    SELECT
        research_id,
        CASE
            WHEN TRY_CAST("date" AS DATE) IS NOT NULL
                THEN TRY_CAST("date" AS DATE)
            WHEN regexp_matches(CAST("date" AS VARCHAR), '^\d{4}$')
                THEN TRY_CAST(CAST("date" AS VARCHAR) || '-01-01' AS DATE)
            ELSE NULL
        END AS mt_date_parsed,
        CASE
            WHEN regexp_matches(CAST("date" AS VARCHAR), '^\d{4}$')
                THEN 'year'
            ELSE 'day'
        END AS mt_date_granularity,
        "date" AS mt_date_raw,
        test_index,
        ROW_NUMBER() OVER (
            PARTITION BY research_id
            ORDER BY
                CASE WHEN TRY_CAST("date" AS DATE) IS NOT NULL THEN 0 ELSE 1 END,
                TRY_CAST("date" AS DATE) DESC NULLS LAST,
                test_index DESC
        ) AS mt_seq
    FROM molecular_testing
    WHERE "date" IS NOT NULL
      AND CAST("date" AS VARCHAR) NOT IN ('x', 'X', '', 'None', 'maybe?')
)
SELECT
    e.*,
    COALESCE(
            TRY_CAST(e.entity_date AS DATE),
            TRY_CAST(e.note_date AS DATE),
            ps.surg_date_parsed,
            mt.mt_date_parsed,
            fna.fna_date
    ) AS inferred_event_date,
    CASE
            WHEN e.entity_date IS NOT NULL AND TRY_CAST(e.entity_date AS DATE) IS NOT NULL
            THEN 'entity_date'
            WHEN e.note_date IS NOT NULL AND TRY_CAST(e.note_date AS DATE) IS NOT NULL
            THEN 'note_date'
            WHEN ps.surg_date_parsed IS NOT NULL THEN 'surg_date'
            WHEN mt.mt_date_parsed IS NOT NULL THEN 'molecular_testing_date'
            WHEN fna.fna_date IS NOT NULL THEN 'fna_date_parsed'
            ELSE 'unrecoverable'
    END AS date_source,
    CASE
            WHEN e.entity_date IS NOT NULL AND TRY_CAST(e.entity_date AS DATE) IS NOT NULL
            THEN 'day'
            WHEN e.note_date IS NOT NULL AND TRY_CAST(e.note_date AS DATE) IS NOT NULL
            THEN 'day'
            WHEN ps.surg_date_parsed IS NOT NULL THEN 'day'
            WHEN mt.mt_date_parsed IS NOT NULL THEN mt.mt_date_granularity
            WHEN fna.fna_date IS NOT NULL THEN 'day'
            ELSE NULL
    END AS date_granularity,
    CASE
            WHEN e.entity_date IS NOT NULL AND TRY_CAST(e.entity_date AS DATE) IS NOT NULL
            THEN 100
            WHEN e.note_date IS NOT NULL AND TRY_CAST(e.note_date AS DATE) IS NOT NULL
            THEN 70
            WHEN ps.surg_date_parsed IS NOT NULL THEN 60
            WHEN mt.mt_date_parsed IS NOT NULL
            THEN CASE WHEN mt.mt_date_granularity = 'year' THEN 50 ELSE 60 END
            WHEN fna.fna_date IS NOT NULL THEN 55
            ELSE 0
    END AS date_confidence,
    CASE
            WHEN e.entity_date IS NOT NULL AND TRY_CAST(e.entity_date AS DATE) IS NOT NULL
            THEN 'extracted'
            WHEN e.note_date IS NOT NULL AND TRY_CAST(e.note_date AS DATE) IS NOT NULL
            THEN 'encounter'
            WHEN ps.surg_date_parsed IS NOT NULL THEN 'surgical'
            WHEN mt.mt_date_parsed IS NOT NULL THEN 'molecular'
            WHEN fna.fna_date IS NOT NULL THEN 'cytology'
            ELSE 'none'
    END AS date_anchor_type,
    CASE
            WHEN e.entity_date IS NOT NULL AND TRY_CAST(e.entity_date AS DATE) IS NOT NULL
            THEN 'note_entities_genetics'
            WHEN e.note_date IS NOT NULL AND TRY_CAST(e.note_date AS DATE) IS NOT NULL
            THEN 'clinical_notes_long'
            WHEN ps.surg_date_parsed IS NOT NULL THEN 'path_synoptics'
            WHEN mt.mt_date_parsed IS NOT NULL THEN 'molecular_testing'
            WHEN fna.fna_date IS NOT NULL THEN 'fna_history'
            ELSE 'none'
    END AS date_anchor_table,
    -- v3: date_status taxonomy
    CASE
        WHEN e.entity_date IS NOT NULL AND TRY_CAST(e.entity_date AS DATE) IS NOT NULL
            THEN 'exact_source_date'
        WHEN e.note_date IS NOT NULL AND TRY_CAST(e.note_date AS DATE) IS NOT NULL
            THEN 'inferred_day_level_date'
        WHEN ps.surg_date_parsed IS NOT NULL OR mt.mt_date_parsed IS NOT NULL
             OR fna.fna_date IS NOT NULL
            THEN 'coarse_anchor_date'
        ELSE 'unresolved_date'
    END AS date_status,
    CASE WHEN e.entity_date IS NOT NULL AND TRY_CAST(e.entity_date AS DATE) IS NOT NULL
        THEN TRUE ELSE FALSE END AS date_is_source_native_flag,
    CASE WHEN (e.entity_date IS NULL OR TRY_CAST(e.entity_date AS DATE) IS NULL)
              AND COALESCE(TRY_CAST(e.note_date AS DATE), ps.surg_date_parsed,
                           mt.mt_date_parsed, fna.fna_date) IS NOT NULL
        THEN TRUE ELSE FALSE END AS date_is_inferred_flag,
    CASE
        WHEN e.entity_date IS NULL AND e.note_date IS NULL
             AND ps.surg_date_parsed IS NULL AND mt.mt_date_parsed IS NULL
             AND fna.fna_date IS NULL THEN TRUE
        WHEN ps.surg_date_parsed IS NOT NULL
             AND e.entity_date IS NULL AND TRY_CAST(e.note_date AS DATE) IS NULL
            THEN TRUE
        WHEN fna.fna_date IS NOT NULL
             AND e.entity_date IS NULL AND TRY_CAST(e.note_date AS DATE) IS NULL
             AND ps.surg_date_parsed IS NULL
            THEN TRUE
        ELSE FALSE
    END AS date_requires_manual_review_flag
FROM note_entities_genetics e
LEFT JOIN ps_primary ps
    ON CAST(e.research_id AS BIGINT) = ps.research_id AND ps.op_seq = 1
LEFT JOIN mt_valid mt
    ON CAST(e.research_id AS BIGINT) = mt.research_id AND mt.mt_seq = 1
LEFT JOIN fna_primary fna
    ON CAST(e.research_id AS BIGINT) = fna.research_id AND fna.fna_seq = 1;

-- === enriched_note_entities_staging ===
CREATE OR REPLACE VIEW enriched_note_entities_staging AS
WITH 
ps_primary AS (
    SELECT
        research_id,
        TRY_CAST(surg_date AS DATE) AS surg_date_parsed,
        surg_date AS surg_date_raw,
        ROW_NUMBER() OVER (
            PARTITION BY research_id
            ORDER BY TRY_CAST(surg_date AS DATE) ASC NULLS LAST
        ) AS op_seq
    FROM path_synoptics
    WHERE surg_date IS NOT NULL AND surg_date != ''
)
SELECT
    e.*,
    COALESCE(
            TRY_CAST(e.entity_date AS DATE),
            TRY_CAST(e.note_date AS DATE),
            ps.surg_date_parsed
    ) AS inferred_event_date,
    CASE
            WHEN e.entity_date IS NOT NULL AND TRY_CAST(e.entity_date AS DATE) IS NOT NULL
            THEN 'entity_date'
            WHEN e.note_date IS NOT NULL AND TRY_CAST(e.note_date AS DATE) IS NOT NULL
            THEN 'note_date'
            WHEN ps.surg_date_parsed IS NOT NULL THEN 'surg_date'
            ELSE 'unrecoverable'
    END AS date_source,
    CASE
            WHEN e.entity_date IS NOT NULL AND TRY_CAST(e.entity_date AS DATE) IS NOT NULL
            THEN 'day'
            WHEN e.note_date IS NOT NULL AND TRY_CAST(e.note_date AS DATE) IS NOT NULL
            THEN 'day'
            WHEN ps.surg_date_parsed IS NOT NULL THEN 'day'
            ELSE NULL
    END AS date_granularity,
    CASE
            WHEN e.entity_date IS NOT NULL AND TRY_CAST(e.entity_date AS DATE) IS NOT NULL
            THEN 100
            WHEN e.note_date IS NOT NULL AND TRY_CAST(e.note_date AS DATE) IS NOT NULL
            THEN 70
            WHEN ps.surg_date_parsed IS NOT NULL THEN 60
            ELSE 0
    END AS date_confidence,
    CASE
            WHEN e.entity_date IS NOT NULL AND TRY_CAST(e.entity_date AS DATE) IS NOT NULL
            THEN 'extracted'
            WHEN e.note_date IS NOT NULL AND TRY_CAST(e.note_date AS DATE) IS NOT NULL
            THEN 'encounter'
            WHEN ps.surg_date_parsed IS NOT NULL THEN 'surgical'
            ELSE 'none'
    END AS date_anchor_type,
    CASE
            WHEN e.entity_date IS NOT NULL AND TRY_CAST(e.entity_date AS DATE) IS NOT NULL
            THEN 'note_entities_staging'
            WHEN e.note_date IS NOT NULL AND TRY_CAST(e.note_date AS DATE) IS NOT NULL
            THEN 'clinical_notes_long'
            WHEN ps.surg_date_parsed IS NOT NULL THEN 'path_synoptics'
            ELSE 'none'
    END AS date_anchor_table,
    -- v3: date_status taxonomy
    CASE
        WHEN e.entity_date IS NOT NULL AND TRY_CAST(e.entity_date AS DATE) IS NOT NULL
            THEN 'exact_source_date'
        WHEN e.note_date IS NOT NULL AND TRY_CAST(e.note_date AS DATE) IS NOT NULL
            THEN 'inferred_day_level_date'
        WHEN ps.surg_date_parsed IS NOT NULL THEN 'coarse_anchor_date'
        ELSE 'unresolved_date'
    END AS date_status,
    CASE WHEN e.entity_date IS NOT NULL AND TRY_CAST(e.entity_date AS DATE) IS NOT NULL
        THEN TRUE ELSE FALSE END AS date_is_source_native_flag,
    CASE WHEN (e.entity_date IS NULL OR TRY_CAST(e.entity_date AS DATE) IS NULL)
              AND COALESCE(TRY_CAST(e.note_date AS DATE), ps.surg_date_parsed) IS NOT NULL
        THEN TRUE ELSE FALSE END AS date_is_inferred_flag,
    CASE
        WHEN e.entity_date IS NULL AND e.note_date IS NULL
             AND ps.surg_date_parsed IS NULL THEN TRUE
        WHEN ps.surg_date_parsed IS NOT NULL
             AND e.entity_date IS NULL AND TRY_CAST(e.note_date AS DATE) IS NULL
            THEN TRUE
        ELSE FALSE
    END AS date_requires_manual_review_flag
FROM note_entities_staging e
LEFT JOIN ps_primary ps
    ON CAST(e.research_id AS BIGINT) = ps.research_id AND ps.op_seq = 1;

-- === enriched_note_entities_procedures ===
CREATE OR REPLACE VIEW enriched_note_entities_procedures AS
WITH 
ps_primary AS (
    SELECT
        research_id,
        TRY_CAST(surg_date AS DATE) AS surg_date_parsed,
        surg_date AS surg_date_raw,
        ROW_NUMBER() OVER (
            PARTITION BY research_id
            ORDER BY TRY_CAST(surg_date AS DATE) ASC NULLS LAST
        ) AS op_seq
    FROM path_synoptics
    WHERE surg_date IS NOT NULL AND surg_date != ''
)
SELECT
    e.*,
    COALESCE(
            TRY_CAST(e.entity_date AS DATE),
            TRY_CAST(e.note_date AS DATE),
            ps.surg_date_parsed
    ) AS inferred_event_date,
    CASE
            WHEN e.entity_date IS NOT NULL AND TRY_CAST(e.entity_date AS DATE) IS NOT NULL
            THEN 'entity_date'
            WHEN e.note_date IS NOT NULL AND TRY_CAST(e.note_date AS DATE) IS NOT NULL
            THEN 'note_date'
            WHEN ps.surg_date_parsed IS NOT NULL THEN 'surg_date'
            ELSE 'unrecoverable'
    END AS date_source,
    CASE
            WHEN e.entity_date IS NOT NULL AND TRY_CAST(e.entity_date AS DATE) IS NOT NULL
            THEN 'day'
            WHEN e.note_date IS NOT NULL AND TRY_CAST(e.note_date AS DATE) IS NOT NULL
            THEN 'day'
            WHEN ps.surg_date_parsed IS NOT NULL THEN 'day'
            ELSE NULL
    END AS date_granularity,
    CASE
            WHEN e.entity_date IS NOT NULL AND TRY_CAST(e.entity_date AS DATE) IS NOT NULL
            THEN 100
            WHEN e.note_date IS NOT NULL AND TRY_CAST(e.note_date AS DATE) IS NOT NULL
            THEN 70
            WHEN ps.surg_date_parsed IS NOT NULL THEN 60
            ELSE 0
    END AS date_confidence,
    CASE
            WHEN e.entity_date IS NOT NULL AND TRY_CAST(e.entity_date AS DATE) IS NOT NULL
            THEN 'extracted'
            WHEN e.note_date IS NOT NULL AND TRY_CAST(e.note_date AS DATE) IS NOT NULL
            THEN 'encounter'
            WHEN ps.surg_date_parsed IS NOT NULL THEN 'surgical'
            ELSE 'none'
    END AS date_anchor_type,
    CASE
            WHEN e.entity_date IS NOT NULL AND TRY_CAST(e.entity_date AS DATE) IS NOT NULL
            THEN 'note_entities_procedures'
            WHEN e.note_date IS NOT NULL AND TRY_CAST(e.note_date AS DATE) IS NOT NULL
            THEN 'clinical_notes_long'
            WHEN ps.surg_date_parsed IS NOT NULL THEN 'path_synoptics'
            ELSE 'none'
    END AS date_anchor_table,
    -- v3: date_status taxonomy
    CASE
        WHEN e.entity_date IS NOT NULL AND TRY_CAST(e.entity_date AS DATE) IS NOT NULL
            THEN 'exact_source_date'
        WHEN e.note_date IS NOT NULL AND TRY_CAST(e.note_date AS DATE) IS NOT NULL
            THEN 'inferred_day_level_date'
        WHEN ps.surg_date_parsed IS NOT NULL THEN 'coarse_anchor_date'
        ELSE 'unresolved_date'
    END AS date_status,
    CASE WHEN e.entity_date IS NOT NULL AND TRY_CAST(e.entity_date AS DATE) IS NOT NULL
        THEN TRUE ELSE FALSE END AS date_is_source_native_flag,
    CASE WHEN (e.entity_date IS NULL OR TRY_CAST(e.entity_date AS DATE) IS NULL)
              AND COALESCE(TRY_CAST(e.note_date AS DATE), ps.surg_date_parsed) IS NOT NULL
        THEN TRUE ELSE FALSE END AS date_is_inferred_flag,
    CASE
        WHEN e.entity_date IS NULL AND e.note_date IS NULL
             AND ps.surg_date_parsed IS NULL THEN TRUE
        WHEN ps.surg_date_parsed IS NOT NULL
             AND e.entity_date IS NULL AND TRY_CAST(e.note_date AS DATE) IS NULL
            THEN TRUE
        ELSE FALSE
    END AS date_requires_manual_review_flag
FROM note_entities_procedures e
LEFT JOIN ps_primary ps
    ON CAST(e.research_id AS BIGINT) = ps.research_id AND ps.op_seq = 1;

-- === enriched_note_entities_complications ===
CREATE OR REPLACE VIEW enriched_note_entities_complications AS
WITH 
ps_primary AS (
    SELECT
        research_id,
        TRY_CAST(surg_date AS DATE) AS surg_date_parsed,
        surg_date AS surg_date_raw,
        ROW_NUMBER() OVER (
            PARTITION BY research_id
            ORDER BY TRY_CAST(surg_date AS DATE) ASC NULLS LAST
        ) AS op_seq
    FROM path_synoptics
    WHERE surg_date IS NOT NULL AND surg_date != ''
)
SELECT
    e.*,
    COALESCE(
            TRY_CAST(e.entity_date AS DATE),
            TRY_CAST(e.note_date AS DATE),
            ps.surg_date_parsed
    ) AS inferred_event_date,
    CASE
            WHEN e.entity_date IS NOT NULL AND TRY_CAST(e.entity_date AS DATE) IS NOT NULL
            THEN 'entity_date'
            WHEN e.note_date IS NOT NULL AND TRY_CAST(e.note_date AS DATE) IS NOT NULL
            THEN 'note_date'
            WHEN ps.surg_date_parsed IS NOT NULL THEN 'surg_date'
            ELSE 'unrecoverable'
    END AS date_source,
    CASE
            WHEN e.entity_date IS NOT NULL AND TRY_CAST(e.entity_date AS DATE) IS NOT NULL
            THEN 'day'
            WHEN e.note_date IS NOT NULL AND TRY_CAST(e.note_date AS DATE) IS NOT NULL
            THEN 'day'
            WHEN ps.surg_date_parsed IS NOT NULL THEN 'day'
            ELSE NULL
    END AS date_granularity,
    CASE
            WHEN e.entity_date IS NOT NULL AND TRY_CAST(e.entity_date AS DATE) IS NOT NULL
            THEN 100
            WHEN e.note_date IS NOT NULL AND TRY_CAST(e.note_date AS DATE) IS NOT NULL
            THEN 70
            WHEN ps.surg_date_parsed IS NOT NULL THEN 60
            ELSE 0
    END AS date_confidence,
    CASE
            WHEN e.entity_date IS NOT NULL AND TRY_CAST(e.entity_date AS DATE) IS NOT NULL
            THEN 'extracted'
            WHEN e.note_date IS NOT NULL AND TRY_CAST(e.note_date AS DATE) IS NOT NULL
            THEN 'encounter'
            WHEN ps.surg_date_parsed IS NOT NULL THEN 'surgical'
            ELSE 'none'
    END AS date_anchor_type,
    CASE
            WHEN e.entity_date IS NOT NULL AND TRY_CAST(e.entity_date AS DATE) IS NOT NULL
            THEN 'note_entities_complications'
            WHEN e.note_date IS NOT NULL AND TRY_CAST(e.note_date AS DATE) IS NOT NULL
            THEN 'clinical_notes_long'
            WHEN ps.surg_date_parsed IS NOT NULL THEN 'path_synoptics'
            ELSE 'none'
    END AS date_anchor_table,
    -- v3: date_status taxonomy
    CASE
        WHEN e.entity_date IS NOT NULL AND TRY_CAST(e.entity_date AS DATE) IS NOT NULL
            THEN 'exact_source_date'
        WHEN e.note_date IS NOT NULL AND TRY_CAST(e.note_date AS DATE) IS NOT NULL
            THEN 'inferred_day_level_date'
        WHEN ps.surg_date_parsed IS NOT NULL THEN 'coarse_anchor_date'
        ELSE 'unresolved_date'
    END AS date_status,
    CASE WHEN e.entity_date IS NOT NULL AND TRY_CAST(e.entity_date AS DATE) IS NOT NULL
        THEN TRUE ELSE FALSE END AS date_is_source_native_flag,
    CASE WHEN (e.entity_date IS NULL OR TRY_CAST(e.entity_date AS DATE) IS NULL)
              AND COALESCE(TRY_CAST(e.note_date AS DATE), ps.surg_date_parsed) IS NOT NULL
        THEN TRUE ELSE FALSE END AS date_is_inferred_flag,
    CASE
        WHEN e.entity_date IS NULL AND e.note_date IS NULL
             AND ps.surg_date_parsed IS NULL THEN TRUE
        WHEN ps.surg_date_parsed IS NOT NULL
             AND e.entity_date IS NULL AND TRY_CAST(e.note_date AS DATE) IS NULL
            THEN TRUE
        ELSE FALSE
    END AS date_requires_manual_review_flag
FROM note_entities_complications e
LEFT JOIN ps_primary ps
    ON CAST(e.research_id AS BIGINT) = ps.research_id AND ps.op_seq = 1;

-- === enriched_note_entities_medications ===
CREATE OR REPLACE VIEW enriched_note_entities_medications AS
WITH 
ps_primary AS (
    SELECT
        research_id,
        TRY_CAST(surg_date AS DATE) AS surg_date_parsed,
        surg_date AS surg_date_raw,
        ROW_NUMBER() OVER (
            PARTITION BY research_id
            ORDER BY TRY_CAST(surg_date AS DATE) ASC NULLS LAST
        ) AS op_seq
    FROM path_synoptics
    WHERE surg_date IS NOT NULL AND surg_date != ''
),

fna_primary AS (
    SELECT
        research_id,
        fna_date_parsed,
        TRY_CAST(fna_date_parsed AS DATE) AS fna_date,
        fna_index,
        ROW_NUMBER() OVER (
            PARTITION BY research_id
            ORDER BY TRY_CAST(fna_date_parsed AS DATE) DESC NULLS LAST,
                     fna_index DESC
        ) AS fna_seq
    FROM fna_history
    WHERE fna_date_parsed IS NOT NULL AND fna_date_parsed != ''
)
SELECT
    e.*,
    COALESCE(
            TRY_CAST(e.entity_date AS DATE),
            TRY_CAST(e.note_date AS DATE),
            ps.surg_date_parsed,
            fna.fna_date
    ) AS inferred_event_date,
    CASE
            WHEN e.entity_date IS NOT NULL AND TRY_CAST(e.entity_date AS DATE) IS NOT NULL
            THEN 'entity_date'
            WHEN e.note_date IS NOT NULL AND TRY_CAST(e.note_date AS DATE) IS NOT NULL
            THEN 'note_date'
            WHEN ps.surg_date_parsed IS NOT NULL THEN 'surg_date'
            WHEN fna.fna_date IS NOT NULL THEN 'fna_date_parsed'
            ELSE 'unrecoverable'
    END AS date_source,
    CASE
            WHEN e.entity_date IS NOT NULL AND TRY_CAST(e.entity_date AS DATE) IS NOT NULL
            THEN 'day'
            WHEN e.note_date IS NOT NULL AND TRY_CAST(e.note_date AS DATE) IS NOT NULL
            THEN 'day'
            WHEN ps.surg_date_parsed IS NOT NULL THEN 'day'
            WHEN fna.fna_date IS NOT NULL THEN 'day'
            ELSE NULL
    END AS date_granularity,
    CASE
            WHEN e.entity_date IS NOT NULL AND TRY_CAST(e.entity_date AS DATE) IS NOT NULL
            THEN 100
            WHEN e.note_date IS NOT NULL AND TRY_CAST(e.note_date AS DATE) IS NOT NULL
            THEN 70
            WHEN ps.surg_date_parsed IS NOT NULL THEN 40
            WHEN fna.fna_date IS NOT NULL THEN 35
            ELSE 0
    END AS date_confidence,
    CASE
            WHEN e.entity_date IS NOT NULL AND TRY_CAST(e.entity_date AS DATE) IS NOT NULL
            THEN 'extracted'
            WHEN e.note_date IS NOT NULL AND TRY_CAST(e.note_date AS DATE) IS NOT NULL
            THEN 'encounter'
            WHEN ps.surg_date_parsed IS NOT NULL THEN 'surgical'
            WHEN fna.fna_date IS NOT NULL THEN 'cytology'
            ELSE 'none'
    END AS date_anchor_type,
    CASE
            WHEN e.entity_date IS NOT NULL AND TRY_CAST(e.entity_date AS DATE) IS NOT NULL
            THEN 'note_entities_medications'
            WHEN e.note_date IS NOT NULL AND TRY_CAST(e.note_date AS DATE) IS NOT NULL
            THEN 'clinical_notes_long'
            WHEN ps.surg_date_parsed IS NOT NULL THEN 'path_synoptics'
            WHEN fna.fna_date IS NOT NULL THEN 'fna_history'
            ELSE 'none'
    END AS date_anchor_table,
    -- v3: date_status taxonomy
    CASE
        WHEN e.entity_date IS NOT NULL AND TRY_CAST(e.entity_date AS DATE) IS NOT NULL
            THEN 'exact_source_date'
        WHEN e.note_date IS NOT NULL AND TRY_CAST(e.note_date AS DATE) IS NOT NULL
            THEN 'inferred_day_level_date'
        WHEN ps.surg_date_parsed IS NOT NULL OR fna.fna_date IS NOT NULL
            THEN 'coarse_anchor_date'
        ELSE 'unresolved_date'
    END AS date_status,
    CASE WHEN e.entity_date IS NOT NULL AND TRY_CAST(e.entity_date AS DATE) IS NOT NULL
        THEN TRUE ELSE FALSE END AS date_is_source_native_flag,
    CASE WHEN (e.entity_date IS NULL OR TRY_CAST(e.entity_date AS DATE) IS NULL)
              AND COALESCE(TRY_CAST(e.note_date AS DATE), ps.surg_date_parsed,
                           fna.fna_date) IS NOT NULL
        THEN TRUE ELSE FALSE END AS date_is_inferred_flag,
    CASE
        WHEN e.entity_date IS NULL AND e.note_date IS NULL
             AND ps.surg_date_parsed IS NULL AND fna.fna_date IS NULL THEN TRUE
        WHEN ps.surg_date_parsed IS NOT NULL
             AND e.entity_date IS NULL AND TRY_CAST(e.note_date AS DATE) IS NULL
            THEN TRUE
        WHEN fna.fna_date IS NOT NULL
             AND e.entity_date IS NULL AND TRY_CAST(e.note_date AS DATE) IS NULL
             AND ps.surg_date_parsed IS NULL
            THEN TRUE
        ELSE FALSE
    END AS date_requires_manual_review_flag
FROM note_entities_medications e
LEFT JOIN ps_primary ps
    ON CAST(e.research_id AS BIGINT) = ps.research_id AND ps.op_seq = 1
LEFT JOIN fna_primary fna
    ON CAST(e.research_id AS BIGINT) = fna.research_id AND fna.fna_seq = 1;

-- === enriched_note_entities_problem_list ===
CREATE OR REPLACE VIEW enriched_note_entities_problem_list AS
WITH 
ps_primary AS (
    SELECT
        research_id,
        TRY_CAST(surg_date AS DATE) AS surg_date_parsed,
        surg_date AS surg_date_raw,
        ROW_NUMBER() OVER (
            PARTITION BY research_id
            ORDER BY TRY_CAST(surg_date AS DATE) ASC NULLS LAST
        ) AS op_seq
    FROM path_synoptics
    WHERE surg_date IS NOT NULL AND surg_date != ''
),

fna_primary AS (
    SELECT
        research_id,
        fna_date_parsed,
        TRY_CAST(fna_date_parsed AS DATE) AS fna_date,
        fna_index,
        ROW_NUMBER() OVER (
            PARTITION BY research_id
            ORDER BY TRY_CAST(fna_date_parsed AS DATE) DESC NULLS LAST,
                     fna_index DESC
        ) AS fna_seq
    FROM fna_history
    WHERE fna_date_parsed IS NOT NULL AND fna_date_parsed != ''
)
SELECT
    e.*,
    COALESCE(
            TRY_CAST(e.entity_date AS DATE),
            TRY_CAST(e.note_date AS DATE),
            ps.surg_date_parsed,
            fna.fna_date
    ) AS inferred_event_date,
    CASE
            WHEN e.entity_date IS NOT NULL AND TRY_CAST(e.entity_date AS DATE) IS NOT NULL
            THEN 'entity_date'
            WHEN e.note_date IS NOT NULL AND TRY_CAST(e.note_date AS DATE) IS NOT NULL
            THEN 'note_date'
            WHEN ps.surg_date_parsed IS NOT NULL THEN 'surg_date'
            WHEN fna.fna_date IS NOT NULL THEN 'fna_date_parsed'
            ELSE 'unrecoverable'
    END AS date_source,
    CASE
            WHEN e.entity_date IS NOT NULL AND TRY_CAST(e.entity_date AS DATE) IS NOT NULL
            THEN 'day'
            WHEN e.note_date IS NOT NULL AND TRY_CAST(e.note_date AS DATE) IS NOT NULL
            THEN 'day'
            WHEN ps.surg_date_parsed IS NOT NULL THEN 'day'
            WHEN fna.fna_date IS NOT NULL THEN 'day'
            ELSE NULL
    END AS date_granularity,
    CASE
            WHEN e.entity_date IS NOT NULL AND TRY_CAST(e.entity_date AS DATE) IS NOT NULL
            THEN 100
            WHEN e.note_date IS NOT NULL AND TRY_CAST(e.note_date AS DATE) IS NOT NULL
            THEN 70
            WHEN ps.surg_date_parsed IS NOT NULL THEN 40
            WHEN fna.fna_date IS NOT NULL THEN 35
            ELSE 0
    END AS date_confidence,
    CASE
            WHEN e.entity_date IS NOT NULL AND TRY_CAST(e.entity_date AS DATE) IS NOT NULL
            THEN 'extracted'
            WHEN e.note_date IS NOT NULL AND TRY_CAST(e.note_date AS DATE) IS NOT NULL
            THEN 'encounter'
            WHEN ps.surg_date_parsed IS NOT NULL THEN 'surgical'
            WHEN fna.fna_date IS NOT NULL THEN 'cytology'
            ELSE 'none'
    END AS date_anchor_type,
    CASE
            WHEN e.entity_date IS NOT NULL AND TRY_CAST(e.entity_date AS DATE) IS NOT NULL
            THEN 'note_entities_problem_list'
            WHEN e.note_date IS NOT NULL AND TRY_CAST(e.note_date AS DATE) IS NOT NULL
            THEN 'clinical_notes_long'
            WHEN ps.surg_date_parsed IS NOT NULL THEN 'path_synoptics'
            WHEN fna.fna_date IS NOT NULL THEN 'fna_history'
            ELSE 'none'
    END AS date_anchor_table,
    -- v3: date_status taxonomy
    CASE
        WHEN e.entity_date IS NOT NULL AND TRY_CAST(e.entity_date AS DATE) IS NOT NULL
            THEN 'exact_source_date'
        WHEN e.note_date IS NOT NULL AND TRY_CAST(e.note_date AS DATE) IS NOT NULL
            THEN 'inferred_day_level_date'
        WHEN ps.surg_date_parsed IS NOT NULL OR fna.fna_date IS NOT NULL
            THEN 'coarse_anchor_date'
        ELSE 'unresolved_date'
    END AS date_status,
    CASE WHEN e.entity_date IS NOT NULL AND TRY_CAST(e.entity_date AS DATE) IS NOT NULL
        THEN TRUE ELSE FALSE END AS date_is_source_native_flag,
    CASE WHEN (e.entity_date IS NULL OR TRY_CAST(e.entity_date AS DATE) IS NULL)
              AND COALESCE(TRY_CAST(e.note_date AS DATE), ps.surg_date_parsed,
                           fna.fna_date) IS NOT NULL
        THEN TRUE ELSE FALSE END AS date_is_inferred_flag,
    CASE
        WHEN e.entity_date IS NULL AND e.note_date IS NULL
             AND ps.surg_date_parsed IS NULL AND fna.fna_date IS NULL THEN TRUE
        WHEN ps.surg_date_parsed IS NOT NULL
             AND e.entity_date IS NULL AND TRY_CAST(e.note_date AS DATE) IS NULL
            THEN TRUE
        WHEN fna.fna_date IS NOT NULL
             AND e.entity_date IS NULL AND TRY_CAST(e.note_date AS DATE) IS NULL
             AND ps.surg_date_parsed IS NULL
            THEN TRUE
        ELSE FALSE
    END AS date_requires_manual_review_flag
FROM note_entities_problem_list e
LEFT JOIN ps_primary ps
    ON CAST(e.research_id AS BIGINT) = ps.research_id AND ps.op_seq = 1
LEFT JOIN fna_primary fna
    ON CAST(e.research_id AS BIGINT) = fna.research_id AND fna.fna_seq = 1;

-- === timeline_rescue_v2_mv ===
CREATE OR REPLACE VIEW timeline_rescue_v2_mv AS
SELECT
    CASE
        WHEN e.research_id IS NOT NULL THEN 'medications'
        ELSE NULL
    END AS source_table,
    e.research_id,
    e.entity_value_norm,
    e.entity_value_raw,
    e.entity_date AS original_entity_date,
    e.note_date AS original_note_date,
    e.inferred_event_date,
    e.date_source,
    e.date_granularity AS date_resolution_level,
    e.date_confidence,
    e.date_status,
    e.date_is_inferred_flag,
    e.date_requires_manual_review_flag,
    CASE
        WHEN e.date_status = 'unresolved_date' AND NOT EXISTS (
            SELECT 1 FROM path_synoptics p2
            WHERE p2.research_id = CAST(e.research_id AS BIGINT)
        ) THEN 'patient_missing_anchor_tables'
        WHEN e.date_status = 'unresolved_date' AND e.entity_date IS NOT NULL
             AND TRY_CAST(e.entity_date AS DATE) IS NULL
            THEN 'parse_failure'
        WHEN e.date_status = 'unresolved_date'
            THEN 'no_source_date'
        WHEN e.date_status = 'coarse_anchor_date'
            THEN 'rescued_coarse_anchor'
        WHEN e.date_status IN ('exact_source_date', 'inferred_day_level_date')
            THEN 'has_direct_date'
        ELSE 'unknown'
    END AS rescue_status
FROM enriched_note_entities_medications e
WHERE e.date_status IN ('unresolved_date', 'coarse_anchor_date')

UNION ALL

SELECT
    'problem_list' AS source_table,
    e.research_id,
    e.entity_value_norm,
    e.entity_value_raw,
    e.entity_date AS original_entity_date,
    e.note_date AS original_note_date,
    e.inferred_event_date,
    e.date_source,
    e.date_granularity AS date_resolution_level,
    e.date_confidence,
    e.date_status,
    e.date_is_inferred_flag,
    e.date_requires_manual_review_flag,
    CASE
        WHEN e.date_status = 'unresolved_date' AND NOT EXISTS (
            SELECT 1 FROM path_synoptics p2
            WHERE p2.research_id = CAST(e.research_id AS BIGINT)
        ) THEN 'patient_missing_anchor_tables'
        WHEN e.date_status = 'unresolved_date' AND e.entity_date IS NOT NULL
             AND TRY_CAST(e.entity_date AS DATE) IS NULL
            THEN 'parse_failure'
        WHEN e.date_status = 'unresolved_date'
            THEN 'no_source_date'
        WHEN e.date_status = 'coarse_anchor_date'
            THEN 'rescued_coarse_anchor'
        WHEN e.date_status IN ('exact_source_date', 'inferred_day_level_date')
            THEN 'has_direct_date'
        ELSE 'unknown'
    END AS rescue_status
FROM enriched_note_entities_problem_list e
WHERE e.date_status IN ('unresolved_date', 'coarse_anchor_date');

-- === timeline_unresolved_summary_v2_mv ===
CREATE OR REPLACE VIEW timeline_unresolved_summary_v2_mv AS
SELECT
    source_table,
    rescue_status,
    date_status,
    COUNT(*) AS row_count,
    COUNT(DISTINCT research_id) AS patient_count,
    ROUND(100.0 * COUNT(*) /
        SUM(COUNT(*)) OVER (PARTITION BY source_table), 2) AS pct_of_table,
    ROUND(AVG(date_confidence), 1) AS avg_confidence
FROM timeline_rescue_v2_mv
GROUP BY 1, 2, 3
ORDER BY source_table, row_count DESC;

-- === validation_failures_v3 ===
CREATE OR REPLACE VIEW validation_failures_v3 AS

WITH date_issues AS (
    SELECT
        domain,
        research_id,
        'date_validation' AS validation_domain,
        CASE
            WHEN date_status = 'unresolved_date' THEN 'no_date_recoverable'
            WHEN inferred_event_date > CURRENT_DATE THEN 'future_date'
            WHEN inferred_event_date < DATE '1990-01-01' THEN 'implausible_historical_date'
            WHEN entity_date IS NOT NULL AND note_date IS NOT NULL
                 AND ABS(DATE_DIFF('day',
                         TRY_CAST(entity_date AS DATE),
                         TRY_CAST(note_date AS DATE))) > 365
                THEN 'entity_vs_note_date_gap'
            WHEN date_status = 'coarse_anchor_date' THEN 'coarse_anchor_only'
            WHEN date_confidence < 50 AND date_status != 'coarse_anchor_date'
                THEN 'low_confidence'
        END AS issue_code,
        CASE
            WHEN date_status = 'unresolved_date' THEN 'error'
            WHEN inferred_event_date > CURRENT_DATE THEN 'error'
            WHEN inferred_event_date < DATE '1990-01-01' THEN 'error'
            WHEN entity_date IS NOT NULL AND note_date IS NOT NULL
                 AND ABS(DATE_DIFF('day',
                         TRY_CAST(entity_date AS DATE),
                         TRY_CAST(note_date AS DATE))) > 365
                THEN 'warning'
            WHEN date_status = 'coarse_anchor_date' THEN 'info'
            WHEN date_confidence < 50 AND date_status != 'coarse_anchor_date'
                THEN 'info'
            ELSE NULL
        END AS severity,
        CAST(inferred_event_date AS VARCHAR) AS detected_value,
        domain AS source_objects,
        date_status,
        date_confidence
    FROM (
        SELECT 'genetics' AS domain, research_id, entity_date, note_date,
               inferred_event_date, date_source, date_confidence, date_status
        FROM enriched_note_entities_genetics
        UNION ALL
        SELECT 'staging', research_id, entity_date, note_date,
               inferred_event_date, date_source, date_confidence, date_status
        FROM enriched_note_entities_staging
        UNION ALL
        SELECT 'procedures', research_id, entity_date, note_date,
               inferred_event_date, date_source, date_confidence, date_status
        FROM enriched_note_entities_procedures
        UNION ALL
        SELECT 'complications', research_id, entity_date, note_date,
               inferred_event_date, date_source, date_confidence, date_status
        FROM enriched_note_entities_complications
        UNION ALL
        SELECT 'medications', research_id, entity_date, note_date,
               inferred_event_date, date_source, date_confidence, date_status
        FROM enriched_note_entities_medications
        UNION ALL
        SELECT 'problem_list', research_id, entity_date, note_date,
               inferred_event_date, date_source, date_confidence, date_status
        FROM enriched_note_entities_problem_list
    ) all_enriched
    WHERE date_status = 'unresolved_date'
       OR inferred_event_date > CURRENT_DATE
       OR inferred_event_date < DATE '1990-01-01'
       OR (entity_date IS NOT NULL AND note_date IS NOT NULL
           AND ABS(DATE_DIFF('day',
                   TRY_CAST(entity_date AS DATE),
                   TRY_CAST(note_date AS DATE))) > 365)
       OR date_status = 'coarse_anchor_date'
       OR (date_confidence < 50 AND date_status != 'coarse_anchor_date')
),

molecular_issues AS (
    SELECT
        'molecular' AS domain,
        CAST(research_id AS VARCHAR) AS research_id,
        'molecular_linkage' AS validation_domain,
        'molecular_without_anchor' AS issue_code,
        'warning' AS severity,
        CAST(molecular_date AS VARCHAR) AS detected_value,
        'molecular_episode_v2' AS source_objects,
        NULL AS date_status,
        NULL::INTEGER AS date_confidence
    FROM molecular_episode_v2
    WHERE unresolved_flag = TRUE
),

rai_issues AS (
    SELECT
        'rai' AS domain,
        CAST(research_id AS VARCHAR) AS research_id,
        'rai_linkage' AS validation_domain,
        CASE
            WHEN rai_date IS NULL THEN 'rai_without_date'
            WHEN linked_surgery_date IS NULL THEN 'rai_without_surgery_anchor'
            WHEN days_surgery_to_rai < -30 THEN 'invalid_interval_surgery_to_rai'
            WHEN days_surgery_to_rai > 730 THEN 'invalid_interval_surgery_to_rai'
        END AS issue_code,
        CASE
            WHEN rai_date IS NULL THEN 'error'
            WHEN linked_surgery_date IS NULL THEN 'warning'
            ELSE 'warning'
        END AS severity,
        CAST(days_surgery_to_rai AS VARCHAR) AS detected_value,
        'rai_episode_v2' AS source_objects,
        NULL AS date_status,
        NULL::INTEGER AS date_confidence
    FROM rai_episode_v2
    WHERE unresolved_flag = TRUE
),

histology_issues AS (
    SELECT
        'histology' AS domain,
        CAST(research_id AS VARCHAR) AS research_id,
        'histology_reconciliation' AS validation_domain,
        'histology_conflict' AS issue_code,
        'warning' AS severity,
        source_histology_raw_ps || ' vs ' ||
            COALESCE(source_histology_raw_tp, 'NULL') AS detected_value,
        'histology_reconciliation_v2' AS source_objects,
        NULL AS date_status,
        NULL::INTEGER AS date_confidence
    FROM histology_reconciliation_v2
    WHERE histology_discordance_flag = TRUE
),

stage_issues AS (
    SELECT
        'staging' AS domain,
        CAST(research_id AS VARCHAR) AS research_id,
        'stage_reconciliation' AS validation_domain,
        'stage_conflict' AS issue_code,
        'warning' AS severity,
        COALESCE(t_stage_source_path, 'NULL') || ' vs ' ||
            COALESCE(t_stage_source_note, 'NULL') AS detected_value,
        'histology_reconciliation_v2' AS source_objects,
        NULL AS date_status,
        NULL::INTEGER AS date_confidence
    FROM histology_reconciliation_v2
    WHERE stage_discordance_flag = TRUE
),

n_stage_issues AS (
    SELECT
        'staging' AS domain,
        CAST(research_id AS VARCHAR) AS research_id,
        'stage_reconciliation' AS validation_domain,
        'n_stage_conflict' AS issue_code,
        'info' AS severity,
        COALESCE(n_stage_source_path, 'NULL') || ' vs ' ||
            COALESCE(n_stage_source_note, 'NULL') AS detected_value,
        'histology_reconciliation_v2' AS source_objects,
        NULL AS date_status,
        NULL::INTEGER AS date_confidence
    FROM histology_reconciliation_v2
    WHERE n_stage_discordance_flag = TRUE
)

SELECT
    ROW_NUMBER() OVER (ORDER BY severity DESC, domain, research_id) AS validation_id,
    CAST(research_id AS VARCHAR) AS research_id,
    domain,
    validation_domain,
    severity,
    issue_code,
    CASE
        WHEN issue_code = 'no_date_recoverable'
            THEN 'Entity has no recoverable date from any source (including cross-table fallback)'
        WHEN issue_code = 'future_date'
            THEN 'Inferred date is in the future'
        WHEN issue_code = 'implausible_historical_date'
            THEN 'Inferred date before 1990'
        WHEN issue_code = 'entity_vs_note_date_gap'
            THEN 'Entity date and note date differ by >1 year'
        WHEN issue_code = 'coarse_anchor_only'
            THEN 'Date assigned from cross-table anchor (surgery/FNA), not from entity source'
        WHEN issue_code = 'low_confidence'
            THEN 'Date confidence score below 50'
        WHEN issue_code = 'molecular_without_anchor'
            THEN 'Molecular test has no date or episode linkage'
        WHEN issue_code = 'rai_without_date'
            THEN 'RAI mention has no resolved date'
        WHEN issue_code = 'rai_without_surgery_anchor'
            THEN 'RAI mention has no linked surgery'
        WHEN issue_code = 'invalid_interval_surgery_to_rai'
            THEN 'Surgery-to-RAI interval implausible (<-30d or >730d)'
        WHEN issue_code = 'histology_conflict'
            THEN 'Histology type differs between path_synoptics and tumor_pathology'
        WHEN issue_code = 'stage_conflict'
            THEN 'T-stage differs between pathology report and clinical notes'
        WHEN issue_code = 'n_stage_conflict'
            THEN 'N-stage differs between pathology report and clinical notes'
        ELSE issue_code
    END AS issue_description,
    source_objects,
    NULL AS related_episode_ids,
    detected_value,
    date_status AS date_status_context,
    CASE
        WHEN issue_code IN ('future_date','implausible_historical_date')
            THEN 'date must be between 1990-01-01 and today'
        WHEN issue_code = 'entity_vs_note_date_gap'
            THEN 'entity_date and note_date should be within 365 days'
        WHEN issue_code = 'invalid_interval_surgery_to_rai'
            THEN 'surgery_to_rai interval should be -30..730 days'
        WHEN issue_code = 'coarse_anchor_only'
            THEN 'date is usable but low precision; consider for timeline display, not clinical analysis'
        ELSE NULL
    END AS expected_rule,
    CASE
        WHEN severity = 'error' THEN 'manual_review_required'
        WHEN severity = 'warning' THEN 'verify_and_resolve'
        WHEN severity = 'info' THEN 'monitor'
        ELSE NULL
    END AS recommended_action
FROM (
    SELECT domain, research_id, validation_domain, issue_code,
           severity, detected_value, source_objects, date_status, date_confidence
    FROM date_issues WHERE issue_code IS NOT NULL
    UNION ALL
    SELECT domain, research_id, validation_domain, issue_code,
           severity, detected_value, source_objects, date_status, date_confidence
    FROM molecular_issues
    UNION ALL
    SELECT domain, research_id, validation_domain, issue_code,
           severity, detected_value, source_objects, date_status, date_confidence
    FROM rai_issues WHERE issue_code IS NOT NULL
    UNION ALL
    SELECT domain, research_id, validation_domain, issue_code,
           severity, detected_value, source_objects, date_status, date_confidence
    FROM histology_issues
    UNION ALL
    SELECT domain, research_id, validation_domain, issue_code,
           severity, detected_value, source_objects, date_status, date_confidence
    FROM stage_issues
    UNION ALL
    SELECT domain, research_id, validation_domain, issue_code,
           severity, detected_value, source_objects, date_status, date_confidence
    FROM n_stage_issues
) combined;

-- === patient_validation_rollup_v2_mv ===
CREATE OR REPLACE VIEW patient_validation_rollup_v2_mv AS
SELECT
    research_id,
    COUNT(*) AS total_issues,
    SUM(CASE WHEN severity = 'error' THEN 1 ELSE 0 END) AS error_count,
    SUM(CASE WHEN severity = 'warning' THEN 1 ELSE 0 END) AS warning_count,
    SUM(CASE WHEN severity = 'info' THEN 1 ELSE 0 END) AS info_count,
    CASE
        WHEN SUM(CASE WHEN severity = 'error' THEN 1 ELSE 0 END) > 0
            THEN 'error'
        WHEN SUM(CASE WHEN severity = 'warning' THEN 1 ELSE 0 END) > 0
            THEN 'warning'
        ELSE 'info'
    END AS highest_severity,
    STRING_AGG(DISTINCT domain, ', ' ORDER BY domain) AS affected_domains,
    STRING_AGG(DISTINCT issue_code, ', ' ORDER BY issue_code) AS issue_codes
FROM validation_failures_v3
GROUP BY research_id;

