-- Adjudication Framework Views (Phases B-G)
-- Generated by 18_adjudication_framework.py
-- Depends on: scripts 15, 16, 17
--
-- Phase B: Manual review queues (histology, molecular, RAI, timeline)
-- Phase C: molecular_episode_v3, molecular_analysis_cohort_v
-- Phase D: rai_episode_v3, rai_analysis_cohort_v
-- Phase E: histology_analysis_cohort_v, histology_discordance_summary_v
-- Phase F: patient_reconciliation_summary_v (fixed)
-- Phase G: streamlit_* views

-- === molecular_analysis_cohort_v ===
CREATE OR REPLACE VIEW molecular_analysis_cohort_v AS
SELECT *
FROM molecular_episode_v3
WHERE molecular_analysis_eligible_flag = TRUE;

-- === histology_analysis_cohort_v ===
CREATE OR REPLACE VIEW histology_analysis_cohort_v AS
SELECT
    h.research_id,
    h.op_seq,
    h.pathology_date,

    -- Final analysis values with explicit source priority
    COALESCE(h.histology_normalized, 'unclassified') AS final_histology_for_analysis,
    h.variant_normalized AS final_variant_for_analysis,
    COALESCE(h.t_stage_reconciled, h.t_stage_source_note) AS final_t_stage_for_analysis,
    COALESCE(h.n_stage_reconciled, h.n_stage_source_note) AS final_n_stage_for_analysis,
    COALESCE(h.laterality_reconciled, 'unknown') AS final_laterality_for_analysis,
    h.tumor_behavior_category,

    -- Raw values preserved
    h.source_histology_raw_ps,
    h.source_histology_raw_tp,
    h.source_histology_raw,
    h.t_stage_source_path,
    h.t_stage_tp,
    h.t_stage_source_note,
    h.n_stage_source_path,
    h.n_stage_tp,
    h.n_stage_source_note,
    h.overall_stage_tp,
    h.laterality_path,
    h.multifocality_path,
    h.largest_focus_cm,
    h.tumor_1_extrathyroidal_extension,
    h.source_priority_used,

    -- Discordance typing (expanded)
    CASE
        WHEN h.histology_discordance_flag THEN 'histology_type_conflict'
        WHEN h.stage_discordance_flag AND h.n_stage_discordance_flag
            THEN 't_stage_conflict,n_stage_conflict'
        WHEN h.stage_discordance_flag THEN 't_stage_conflict'
        WHEN h.n_stage_discordance_flag THEN 'n_stage_conflict'
        WHEN h.laterality_reconciled IS NULL AND h.pathology_date IS NOT NULL
            THEN 'laterality_conflict'
        WHEN h.histology_normalized IS NULL AND h.source_histology_raw IS NOT NULL
            THEN 'note_only_histology'
        WHEN h.t_stage_reconciled IS NULL AND h.t_stage_source_note IS NOT NULL
            THEN 'missing_path_primary'
        ELSE NULL
    END AS discordance_type,

    -- Adjudication flags
    CASE
        WHEN h.histology_discordance_flag OR h.stage_discordance_flag
            THEN TRUE
        ELSE FALSE
    END AS adjudication_needed_flag,

    CASE
        WHEN h.unresolved_flag THEN FALSE
        WHEN h.histology_normalized IS NULL THEN FALSE
        WHEN h.histology_discordance_flag THEN FALSE
        ELSE TRUE
    END AS analysis_eligible_flag,

    h.histology_discordance_flag,
    h.stage_discordance_flag,
    h.n_stage_discordance_flag,
    h.unresolved_flag,
    h.reconciliation_status

FROM histology_reconciliation_v2 h;

-- === histology_discordance_summary_v ===
CREATE OR REPLACE VIEW histology_discordance_summary_v AS
SELECT
    discordance_type,
    analysis_eligible_flag,
    adjudication_needed_flag,
    COUNT(*) AS row_count,
    COUNT(DISTINCT research_id) AS patient_count
FROM histology_analysis_cohort_v
WHERE discordance_type IS NOT NULL
GROUP BY 1, 2, 3
ORDER BY row_count DESC;

-- === histology_manual_review_queue_v ===
CREATE OR REPLACE VIEW histology_manual_review_queue_v AS
SELECT
    ROW_NUMBER() OVER (ORDER BY
        CASE WHEN h.histology_discordance_flag THEN 0 ELSE 1 END,
        CASE WHEN h.stage_discordance_flag THEN 0 ELSE 1 END,
        h.research_id
    ) AS queue_row_id,
    CAST(h.research_id AS BIGINT) AS research_id,
    CASE
        WHEN h.histology_discordance_flag AND h.stage_discordance_flag THEN 100
        WHEN h.histology_discordance_flag THEN 90
        WHEN h.stage_discordance_flag THEN 80
        WHEN h.n_stage_discordance_flag THEN 50
        WHEN h.unresolved_flag THEN 40
        ELSE 10
    END AS priority_score,
    'histology' AS review_domain,
    h.discordance_type AS unresolved_reason,
    CASE
        WHEN h.histology_discordance_flag
            THEN 'PS=' || COALESCE(h.source_histology_raw_ps, 'NULL')
                 || ' vs TP=' || COALESCE(h.source_histology_raw_tp, 'NULL')
        WHEN h.stage_discordance_flag
            THEN 'Path T=' || COALESCE(h.t_stage_source_path, 'NULL')
                 || ' vs Note T=' || COALESCE(h.t_stage_source_note, 'NULL')
        ELSE 'staging incomplete'
    END AS conflict_summary,
    h.source_histology_raw_ps,
    h.source_histology_raw_tp,
    h.t_stage_source_path,
    h.t_stage_source_note,
    h.final_histology_for_analysis,
    h.final_t_stage_for_analysis,
    CASE
        WHEN h.histology_discordance_flag
            THEN 'Review pathology reports; determine correct histology type'
        WHEN h.stage_discordance_flag
            THEN 'Compare synoptic vs note staging; confirm AJCC8 stage'
        WHEN h.unresolved_flag
            THEN 'Obtain missing staging data from chart review'
        ELSE 'Verify reconciled values'
    END AS recommended_reviewer_action,
    'path_synoptics, tumor_pathology, note_entities_staging' AS supporting_source_objects,
    h.op_seq AS linked_episode_id
FROM histology_analysis_cohort_v h
WHERE h.adjudication_needed_flag = TRUE OR h.unresolved_flag = TRUE;

-- === streamlit_patient_timeline_v ===
CREATE OR REPLACE VIEW streamlit_patient_timeline_v AS
SELECT
    CAST(research_id AS BIGINT) AS research_id,
    episode_seq,
    event_date,
    event_type,
    event_detail,
    stage_info,
    status AS resolution_status,
    CASE
        WHEN event_type = 'surgery' THEN '#2196F3'
        WHEN event_type = 'molecular_test' THEN '#FF9800'
        WHEN event_type = 'rai_treatment' THEN '#F44336'
        ELSE '#9E9E9E'
    END AS display_color,
    CASE
        WHEN status = 'unresolved' THEN 'dashed'
        ELSE 'solid'
    END AS display_line_style
FROM patient_master_timeline_v2
ORDER BY research_id, event_date NULLS LAST;

