-- Reviewer Persistence & Post-Review Views
-- Generated by 19_reviewer_persistence.py
-- Depends on: scripts 15, 16, 17, 18
--
-- Tables: adjudication_decisions, adjudication_decision_history
-- Views: reviewer summaries, post-review overlays, batch tools

-- === adjudication_decisions ===
CREATE SEQUENCE IF NOT EXISTS adj_seq START 1;

CREATE TABLE IF NOT EXISTS adjudication_decisions (
    decision_id              INTEGER DEFAULT(nextval('adj_seq')),
    research_id              BIGINT NOT NULL,
    review_domain            VARCHAR NOT NULL,
    linked_episode_id        VARCHAR,
    conflict_type            VARCHAR,
    unresolved_reason        VARCHAR,
    reviewer_action          VARCHAR NOT NULL,
    reviewer_resolution_status VARCHAR NOT NULL DEFAULT 'resolved',
    final_value_selected     VARCHAR,
    final_value_notes        VARCHAR,
    reviewer_name            VARCHAR NOT NULL,
    reviewed_at              TIMESTAMP DEFAULT current_timestamp,
    source_view              VARCHAR,
    active_flag              BOOLEAN DEFAULT TRUE
);

-- === adjudication_decision_history ===
CREATE TABLE IF NOT EXISTS adjudication_decision_history (
    history_id               INTEGER DEFAULT(nextval('adj_hist_seq')),
    decision_id              INTEGER NOT NULL,
    research_id              BIGINT NOT NULL,
    review_domain            VARCHAR NOT NULL,
    linked_episode_id        VARCHAR,
    conflict_type            VARCHAR,
    unresolved_reason        VARCHAR,
    reviewer_action          VARCHAR NOT NULL,
    reviewer_resolution_status VARCHAR NOT NULL,
    final_value_selected     VARCHAR,
    final_value_notes        VARCHAR,
    reviewer_name            VARCHAR NOT NULL,
    reviewed_at              TIMESTAMP,
    source_view              VARCHAR,
    active_flag              BOOLEAN,
    history_recorded_at      TIMESTAMP DEFAULT current_timestamp
);

-- === reviewer_resolved_patient_summary_v ===
CREATE OR REPLACE VIEW reviewer_resolved_patient_summary_v AS
SELECT
    d.research_id,
    COUNT(*) FILTER (WHERE d.active_flag = TRUE) AS active_decisions,
    COUNT(*) FILTER (WHERE d.active_flag = TRUE AND d.review_domain = 'histology') AS histology_resolved,
    COUNT(*) FILTER (WHERE d.active_flag = TRUE AND d.review_domain = 'molecular') AS molecular_resolved,
    COUNT(*) FILTER (WHERE d.active_flag = TRUE AND d.review_domain = 'rai') AS rai_resolved,
    COUNT(*) FILTER (WHERE d.active_flag = TRUE AND d.review_domain = 'timeline') AS timeline_resolved,
    MAX(d.reviewed_at) FILTER (WHERE d.active_flag = TRUE) AS last_reviewed_at,
    MAX(d.reviewer_name) FILTER (WHERE d.active_flag = TRUE) AS last_reviewer
FROM adjudication_decisions d
GROUP BY d.research_id;

-- === histology_post_review_v ===
CREATE OR REPLACE VIEW histology_post_review_v AS
SELECT
    h.research_id,
    h.op_seq,
    h.pathology_date,

    -- Algorithmic values
    h.final_histology_for_analysis AS algorithmic_histology,
    h.final_t_stage_for_analysis AS algorithmic_t_stage,
    h.final_n_stage_for_analysis AS algorithmic_n_stage,
    h.final_variant_for_analysis AS algorithmic_variant,

    -- Reviewer-final values (from active decisions)
    d.final_value_selected AS reviewer_histology,
    d.reviewer_action,
    d.reviewer_resolution_status,
    d.reviewer_name,
    d.reviewed_at,
    d.final_value_notes AS reviewer_notes,

    -- Effective values: prefer reviewer when available
    COALESCE(d.final_value_selected, h.final_histology_for_analysis) AS effective_histology,
    h.final_t_stage_for_analysis AS effective_t_stage,
    h.final_n_stage_for_analysis AS effective_n_stage,

    -- Provenance
    CASE WHEN d.decision_id IS NOT NULL THEN TRUE ELSE FALSE END AS adjudication_applied_flag,
    CASE WHEN d.decision_id IS NOT NULL THEN 'reviewer' ELSE 'algorithmic' END AS value_source,

    -- Original flags
    h.discordance_type,
    h.adjudication_needed_flag,
    h.analysis_eligible_flag AS algorithmic_eligible,
    CASE
        WHEN d.reviewer_resolution_status = 'resolved' THEN TRUE
        WHEN h.analysis_eligible_flag = TRUE THEN TRUE
        ELSE FALSE
    END AS effective_eligible,

    -- Raw sources for audit
    h.source_histology_raw_ps,
    h.source_histology_raw_tp,
    h.source_histology_raw,
    h.t_stage_source_path,
    h.t_stage_source_note,
    h.reconciliation_status

FROM histology_analysis_cohort_v h
LEFT JOIN adjudication_decisions d
    ON CAST(h.research_id AS BIGINT) = d.research_id
    AND d.review_domain = 'histology'
    AND d.linked_episode_id = CAST(h.op_seq AS VARCHAR)
    AND d.active_flag = TRUE;

