-- Manuscript Export Views
-- Generated by 20_manuscript_exports.py
-- Depends on: scripts 15-19

-- === manuscript_histology_cohort_v ===
CREATE OR REPLACE VIEW manuscript_histology_cohort_v AS
SELECT
    research_id,
    op_seq,
    pathology_date,
    effective_histology AS histology_for_analysis,
    effective_t_stage AS t_stage_for_analysis,
    effective_n_stage AS n_stage_for_analysis,
    algorithmic_variant AS variant_for_analysis,
    effective_eligible AS analysis_inclusion_flag,
    CASE
        WHEN NOT effective_eligible THEN discordance_type
        ELSE NULL
    END AS exclusion_reason,
    value_source AS algorithmic_vs_reviewer_source,
    adjudication_applied_flag,
    CURRENT_DATE AS analysis_ready_date,
    -- Raw provenance
    source_histology_raw_ps,
    source_histology_raw_tp,
    t_stage_source_path,
    t_stage_source_note,
    reconciliation_status
FROM histology_post_review_v
WHERE effective_eligible = TRUE;

-- === manuscript_molecular_cohort_v ===
CREATE OR REPLACE VIEW manuscript_molecular_cohort_v AS
SELECT
    CAST(research_id AS BIGINT) AS research_id,
    molecular_episode_id,
    specimen_date_raw,
    platform_normalized,
    test_name_raw,
    result_category_normalized,
    result_summary_raw,
    temporal_linkage_confidence,
    platform_confidence,
    pathology_concordance_confidence,
    overall_linkage_confidence,
    effective_eligible AS analysis_inclusion_flag,
    CASE
        WHEN NOT effective_eligible THEN 'ineligible_after_review'
        ELSE NULL
    END AS exclusion_reason,
    value_source AS algorithmic_vs_reviewer_source,
    adjudication_applied_flag,
    CURRENT_DATE AS analysis_ready_date,
    molecular_date_raw_class,
    linkage_method,
    high_risk_molecular_flag
FROM molecular_post_review_v
WHERE effective_eligible = TRUE;

-- === manuscript_rai_cohort_v ===
CREATE OR REPLACE VIEW manuscript_rai_cohort_v AS
SELECT
    CAST(research_id AS BIGINT) AS research_id,
    rai_episode_id,
    rai_date,
    dose_mci,
    rai_term_normalized,
    rai_assertion_status,
    rai_treatment_certainty,
    rai_interval_class,
    effective_eligible AS analysis_inclusion_flag,
    CASE
        WHEN NOT effective_eligible THEN 'ineligible_after_review'
        ELSE NULL
    END AS exclusion_reason,
    value_source AS algorithmic_vs_reviewer_source,
    adjudication_applied_flag,
    CURRENT_DATE AS analysis_ready_date,
    linked_surgery_date,
    days_surgery_to_rai,
    post_thyroidectomy_flag
FROM rai_post_review_v
WHERE effective_eligible = TRUE;

-- === manuscript_patient_summary_v ===
CREATE OR REPLACE VIEW manuscript_patient_summary_v AS
WITH hist AS (
    SELECT research_id,
           COUNT(*) AS histology_records,
           MAX(adjudication_applied_flag::INT) > 0 AS histology_adjudicated
    FROM manuscript_histology_cohort_v
    GROUP BY research_id
),
mol AS (
    SELECT research_id,
           COUNT(*) AS molecular_records,
           MAX(adjudication_applied_flag::INT) > 0 AS molecular_adjudicated
    FROM manuscript_molecular_cohort_v
    GROUP BY research_id
),
rai AS (
    SELECT research_id,
           COUNT(*) AS rai_records,
           MAX(adjudication_applied_flag::INT) > 0 AS rai_adjudicated
    FROM manuscript_rai_cohort_v
    GROUP BY research_id
),
all_ids AS (
    SELECT research_id FROM hist
    UNION SELECT research_id FROM mol
    UNION SELECT research_id FROM rai
)
SELECT
    a.research_id,
    COALESCE(h.histology_records, 0) AS histology_records,
    COALESCE(m.molecular_records, 0) AS molecular_records,
    COALESCE(r.rai_records, 0) AS rai_records,
    COALESCE(h.histology_adjudicated, FALSE) AS histology_adjudicated,
    COALESCE(m.molecular_adjudicated, FALSE) AS molecular_adjudicated,
    COALESCE(r.rai_adjudicated, FALSE) AS rai_adjudicated,
    (COALESCE(h.histology_records, 0) > 0)::INT
      + (COALESCE(m.molecular_records, 0) > 0)::INT
      + (COALESCE(r.rai_records, 0) > 0)::INT AS domains_with_data,
    CURRENT_DATE AS analysis_ready_date
FROM all_ids a
LEFT JOIN hist h ON a.research_id = h.research_id
LEFT JOIN mol m ON a.research_id = m.research_id
LEFT JOIN rai r ON a.research_id = r.research_id;

