#!/usr/bin/env python3
"""
Script 266b — Per-tumor AJCC7 + AJCC8 buildout + CPM dominant-tumor surface
==========================================================================

DRAFT — generated by Cursor agent 2026-04-17. Reviewed by user before run.
Sequencing requirement (HARD): MUST run AFTER the PART2/PROMPT_18 big cleanup
(specifically Phase 4.6 which renames ajcc8_t_stage_corrected -> ajcc8_t_stage)
and AFTER Script 266a (data_dictionary_v266a, registry feeder updates,
cpm_unmapped_triage_v266a). Phase 0 hard-gates on both preconditions.

Scope (P0 of the original 266 prompt):
  - Phase 0 : connect + preflight; assert big-cleanup post-state and 266a state.
  - Phase 1 : snapshot canonical_tumor_characteristics_v1 (CTC) + CPM to
              "Thyroid 2026 UPdated".archive_pub_v1_0.<orig>_pre266b_<UTC>.
  - Phase 2 : ALTER TABLE ADD COLUMN on CTC for 14 new per-tumor staging
              columns (10 stage values + 2 calculable flags + 2 notes).
  - Phase 3 : build per-tumor AJCC7/AJCC8 in pandas using the canonical
              helpers (compute_t_stage etc. from 51b; compute_ajcc7_t_stage
              etc. from 224); UPDATE CTC from a temp staging table.
              ETE input: pulled DIRECTLY from synoptic_tumor_long_v1 per
              tumor (joined via synoptic_row_ix); fall back to
              ete_adjudication_v1.adjudicated_grade per-PATIENT only when
              STL is NULL (~45 adjudicated patients). NEVER reads
              CPM.gross_ete_flag or CTC.gross_ete (both broadcast).
              Tumor size: STL size_greatest_dimension_cm only, NO fallback
              to CTC.tumor_size_cm_per_surgery (TEM per-surgery broadcast).
              Tumors with NULL STL size are flagged uncalculable, not
              filled from a broadcast value.
  - Phase 4 : CREATE TABLE tumor_stage_heterogeneity_v1 (patient grain;
              dominant tumor + heterogeneity flags rolled up from CTC).
  - Phase 5 : ALTER TABLE ADD COLUMN on CPM for dominant_tumor_* +
              heterogeneity flags + n_tumors_ajcc{7,8}_staged; UPDATE CPM
              from tumor_stage_heterogeneity_v1.
  - Phase 6 : validation suite (CTC.dominant vs tumor_pathology.histology_1
              concordance ≥ 95%, calculable counts vs malignant cohort, etc).
  - Phase 7 : acceptance gates + view smoke check (65 ws views) + summary.
              Concordance gate is 3-tier:
                pct >= 95 → pass
                90 <= pct < 95 → soft-pass: write HOLD table
                  manuscript_workspace.cpm_ajcc_dominant_discordance_266b
                  for review-in-daylight; do NOT block apply.
                pct < 90 → hard fail.

Flags:
  --apply       Execute writes.
  --dry-run     Default. Logs every planned DDL but executes none.
  --phase N     Run a single phase (0..7). Phase 0 always runs first.

Outputs (scripts/output/):
  266b_run_log.md
  266b_decision_log.json
  266b_final_confirmation.json
  266b_view_smoke_check.csv
  266b_dominant_vs_histology1_discordance.csv
  266b_ete_classification_audit.csv
  266b_summary.md

==============================================================================
ALL 16 __conventions LIVE-VERIFIED 2026-04-17 (preflight). Each rule below
applies to every statement in this script. (Source: live SELECT against
manuscript_workspace.__conventions; not the stale 6-item prompt list.)
==============================================================================

1.  as_aliasing — column_naming
    Every CTE-to-target mapping in derivation SQL uses explicit AS, even when
    source and target names match. Source-name leakage breaks the canonical
    contract. Applies to every SELECT … FROM … in this script.

2.  assembly_bookkeeping_build_pipeline — registry_mapping
    CPM columns recording how the row was assembled (provenance_*,
    source_script, *_assembled_at, *_confidence_meta) resolve to feeder =
    build_pipeline. The new CPM dominant_tumor_* and heterogeneity flag
    columns ARE clinical facts, not bookkeeping — they resolve to feeder =
    tumor_stage_heterogeneity_v1, NOT build_pipeline.

3.  audit_status_taxonomy — audit_discipline
    v1_1_finalization_audit_v1 status semantics:
      OK = check passed; DOCUMENTED_NOOP = nothing to do, evaluated;
      DOCUMENTED_GAP = open work accepted for this release;
      OK_DEFERRED_HUMAN = routed to human review; FAIL = halt.
    266b emits: OK on each populated stage column; DOCUMENTED_GAP for any
    tumor row whose ajcc8_stage_calculable_flag=FALSE due to missing inputs.

4.  bethesda_semantics — semantics
    OUT OF SCOPE for 266b. Do not modify any bethesda_* derivation.

5.  catalog_vs_queryable_drift — cleanup_safety
    No DROP TABLE in 266b (additive only). Not in scope.

6.  cohort_scoping — table_design
    CTC is NOT cohort-shape-aligned with CPM (8,422 tumor-bearing pts vs
    10,871 CPM pts). The 2,449 benign tumor-free patients are intentionally
    absent. 266b's per-tumor outputs cover only those 8,422; CPM dominant
    columns are NULL for the 2,449. Phase 6 distribution checks normalize
    against the malignant tumor cohort, not full CPM.

7.  derived_column_build_pipeline — registry_mapping
    Compute-from-2+-feeder columns resolve to feeder = build_pipeline.
    266b's new CTC.t_stage_ajcc8 IS computed from 3 inputs (size, gross_ete,
    extrathyroidal_extension), so under strict reading it would be
    build_pipeline. BUT — single-table aggregation (single_source_rollup)
    over CTC's own columns means the feeder for CTC.t_stage_ajcc8 is CTC
    itself (self-reference is implicit since the new col lives in CTC).
    Decision: 266b registers CTC.{t_stage_ajcc8, n_stage_ajcc8, ...} as
    intra-table derivation; the CPM dominant_tumor_* columns register
    against tumor_stage_heterogeneity_v1.

8.  feeder_eligibility_patterns — registry_mapping
    Per Phase 5: the new tumor_stage_heterogeneity_v1 must NOT be excluded
    by EXCLUDE_PATTERNS. Verify name does not match any excluded regex
    (^analysis_.*_subset_v\\d+$, ^manuscript_cohort_v\\d+$, ^__readme$,
    ^data_dictionary_v\\d+$, .*_review_v\\d+$). 'tumor_stage_heterogeneity_v1'
    matches none — safe.

9.  identity_column_self_reference — registry_mapping
    research_id resolves to feeder = canonical_patient_master (self-ref).
    No change in 266b.

10. main_schema_keep_list — archival_discipline
    266b creates one new main-schema table: tumor_stage_heterogeneity_v1.
    This IS a production feeder (feeds CPM dominant + heterogeneity cols),
    NOT a review/staged artifact, so it does NOT need keep-list registration.

11. pre_flight_decision_log — audit_trail
    266b emits scripts/output/266b_decision_log.json with one entry per
    pre-flight discovery that diverges from this draft's assertions.
    Mandatory.

12. restore_test_prefers_widest_schema — archival_discipline
    Phase 1 snapshot of CPM is by definition the widest schema (1,499 cols
    + new ones we're about to add). Snapshot taken BEFORE ALTER TABLE so
    restore baseline = 1,499 cols. Snapshot of CTC similarly captured pre-ALTER.

13. rid_type_consistency — join_safety
    canonical_patient_master.research_id = VARCHAR.
    canonical_tumor_characteristics_v1.research_id = INTEGER (per script 245
    line 209: CAST(s.research_id AS INTEGER) AS research_id).
    tumor_pathology.research_id = BIGINT.
    ln_master_rollup_v1.research_id = BIGINT.
    EVERY join in 266b uses CAST(<src>.research_id AS VARCHAR) = cpm.research_id
    or, when joining among the BIGINT tables, CAST consistently. NEVER
    Python set intersection on raw RID columns.

14. single_source_rollup_inherits_feeder — registry_mapping
    See #7. CPM.dominant_tumor_ajcc8_t_stage is MAX/FIRST_VALUE over a
    single-source rollup (tumor_stage_heterogeneity_v1) — feeder is that
    table, not build_pipeline.

15. tech_debt_aggregation — tech_debt_discipline
    If 266b discovers any homogeneous backlog (e.g., N tumors with NULL
    primary_histology blocking AJCC), register ONE tech_debt entry, not N.

16. v1_1_tech_debt_register — convention_drift
    Any naming/structural debt out of scope for 266b (e.g., legacy
    overall_stage column still un-renamed) → register in
    manuscript_workspace.v1_1_tech_debt_v1, not in code comments.

==============================================================================
Canonical staging helpers reused VERBATIM (per "don't invent staging" rule):
==============================================================================
  - scripts/51b_thyroid_scoring_python.py
      compute_t_stage(row)          — AJCC8 T (path_t_stage_raw authoritative,
                                       else size + ETE rules; T1a ≤1cm, T1b ≤2cm,
                                       T2 ≤4cm, T3a >4cm, T3b gross ETE)
      compute_n_stage(row)          — AJCC8 N (path_n_stage_raw authoritative,
                                       else LN counts + laterality)
      compute_m_stage(row)          — AJCC8 M (path_m_stage_raw + pet_distant_mets_ever)
      compute_stage_group(row)      — AJCC8 stage group (age 55 cutoff for DTC)
  - scripts/224_canonical_etl_fixes.py
      compute_ajcc7_t_stage(t8, ete) — AJCC7 T = AJCC8 T except T3b -> T3, T3a -> T3
      compute_ajcc7_stage_group(row) — AJCC7 stage group (age 45 cutoff for DTC,
                                        IVA/IVB/IVC tier system)
      AJCC7 N = AJCC8 N (N-staging unchanged between 7 and 8)
      AJCC7 M = AJCC8 M

==============================================================================
PER-TUMOR ADAPTATIONS (deviating from patient-level helpers — explicit):
==============================================================================
The 51b helpers operate on patient-level rows from CPM (path_t_stage_raw is a
patient-level field). For per-tumor staging we MUST NOT use patient-level
raw_t/raw_n as authoritative because one patient may have multiple tumors of
different sizes. Per-tumor T-stage uses size + ETE only (skips raw_t shortcut).
Per-tumor N-stage and M-stage are surgery-level / patient-level and are
broadcast (with staging_source_note recording the broadcast source).

Adaptation functions (defined inline below):
  compute_t_stage_per_tumor(row)   — same as compute_t_stage but skips the
                                      path_t_stage_raw shortcut at the top.
  _classify_ete(row)               — per-tumor ETE classifier. Reads ONLY
                                      synoptic_tumor_long_v1.extrathyroidal_extension
                                      (joined per-tumor via synoptic_row_ix);
                                      falls back to ete_adjudication_v1.
                                      adjudicated_grade per-PATIENT only when
                                      STL is NULL. NEVER reads CPM.gross_ete_flag
                                      or CTC.gross_ete (both are TEM-broadcast
                                      / patient-level → would inflate
                                      multifocal-patient secondary tumors).
                                      Returns (ete_grade_text, gross_ete_flag,
                                      ete_source_label).
  broadcast_n_stage(row)           — uses ln_master_rollup_v1.histology_1_n_stage_ajcc8
                                      for the patient (joined via VARCHAR cast).
                                      Sets staging_source_note accordingly.
  broadcast_m_stage(row)           — uses CPM.ajcc8_m_stage (post-cleanup
                                      anchor). Sets staging_source_note.

Tumor size per-tumor:
  Phase 3 reads ONLY canonical_tumor_characteristics_v1.size_greatest_dimension_cm
  (the STL per-tumor value). Does NOT fall back to tumor_size_cm_per_surgery
  (TEM per-surgery broadcast). When STL size is NULL, t_stage_ajcc8 = NULL,
  ajcc8_stage_calculable_flag = FALSE, staging_source_note records
  'stl_size_unavailable'. Inflated-from-broadcast is a manuscript-defensibility
  problem; uncalculable-and-honest is acceptable.
"""
from __future__ import annotations

import argparse
import csv
import json
import sys
import time
import traceback
from datetime import datetime, timezone
from pathlib import Path

import pandas as pd

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))
from _md_connect import connect_locked, PUBLICATION_DB  # noqa: E402
from _v1_1_helpers import (  # noqa: E402
    ARCHIVE_QUALIFIED,
    ensure_archive_schema, ensure_audit_table,
    make_logger, record_audit, snapshot_table, utc_ts, write_decision_log,
)

# Import canonical staging helpers VERBATIM (no copy-paste, no re-implementation).
# Path massage so we can `import 51b_thyroid_scoring_python` despite the leading digit.
import importlib.util as _ilu  # noqa: E402

def _load(module_path: Path, mod_name: str):
    spec = _ilu.spec_from_file_location(mod_name, module_path)
    mod = _ilu.module_from_spec(spec)
    spec.loader.exec_module(mod)  # type: ignore[union-attr]
    return mod

_M51B = _load(HERE / "51b_thyroid_scoring_python.py", "thyroid_scoring_51b")
_M224 = _load(HERE / "224_canonical_etl_fixes.py", "canonical_etl_fixes_224")

compute_t_stage           = _M51B.compute_t_stage
compute_n_stage           = _M51B.compute_n_stage
compute_m_stage           = _M51B.compute_m_stage
compute_stage_group       = _M51B.compute_stage_group
compute_ajcc7_t_stage     = _M224.compute_ajcc7_t_stage
compute_ajcc7_stage_group = _M224.compute_ajcc7_stage_group


# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------
REPO = HERE.parent
OUT_DIR = REPO / "scripts" / "output"
OUT_DIR.mkdir(parents=True, exist_ok=True)
RUN_LOG               = OUT_DIR / "266b_run_log.md"
DECISION_LOG          = OUT_DIR / "266b_decision_log.json"
FINAL_JSON            = OUT_DIR / "266b_final_confirmation.json"
VIEW_SMOKE_CSV        = OUT_DIR / "266b_view_smoke_check.csv"
DISCORDANCE_CSV       = OUT_DIR / "266b_dominant_vs_histology1_discordance.csv"
SUMMARY_MD            = OUT_DIR / "266b_summary.md"

SCRIPT_TAG = "Script 266b"
SCRIPT_NUM = "266b"
RUN_DATE   = "2026-04-17"

CPM   = f"{PUBLICATION_DB}.main.canonical_patient_master"
CTC   = f"{PUBLICATION_DB}.main.canonical_tumor_characteristics_v1"
TPATH = f"{PUBLICATION_DB}.main.tumor_pathology"
LNROL = f"{PUBLICATION_DB}.main.ln_master_rollup_v1"
HET   = f"{PUBLICATION_DB}.main.tumor_stage_heterogeneity_v1"
HOLD_DISCORDANCE = (
    f"{PUBLICATION_DB}.manuscript_workspace.cpm_ajcc_dominant_discordance_266b"
)

# 3-tier concordance gate (per user direction):
#   pct >= CONCORDANCE_PASS  → pass
#   CONCORDANCE_SOFT <= pct < CONCORDANCE_PASS → soft pass: write HOLD table, proceed
#   pct < CONCORDANCE_SOFT   → hard fail
CONCORDANCE_PASS = 95.0
CONCORDANCE_SOFT = 90.0

# 14 new CTC columns (per prompt STEP 1)
CTC_NEW_COLUMNS: list[tuple[str, str]] = [
    ("t_stage_ajcc7",                 "VARCHAR"),
    ("n_stage_ajcc7",                 "VARCHAR"),
    ("m_stage_ajcc7",                 "VARCHAR"),
    ("overall_stage_ajcc7",           "VARCHAR"),
    ("stage_group_ajcc7",             "VARCHAR"),
    ("t_stage_ajcc8",                 "VARCHAR"),
    ("n_stage_ajcc8",                 "VARCHAR"),
    ("m_stage_ajcc8",                 "VARCHAR"),
    ("overall_stage_ajcc8",           "VARCHAR"),
    ("stage_group_ajcc8",             "VARCHAR"),
    ("ajcc7_stage_calculable_flag",   "BOOLEAN"),
    ("ajcc8_stage_calculable_flag",   "BOOLEAN"),
    ("staging_source_note",           "VARCHAR"),
    ("stage_migration_7_to_8",        "VARCHAR"),
]

# 12 new CPM columns (per prompt STEP 4)
CPM_NEW_COLUMNS: list[tuple[str, str]] = [
    ("dominant_tumor_ajcc7_t_stage",                 "VARCHAR"),
    ("dominant_tumor_ajcc7_n_stage",                 "VARCHAR"),
    ("dominant_tumor_ajcc7_m_stage",                 "VARCHAR"),
    ("dominant_tumor_ajcc7_stage_group",             "VARCHAR"),
    ("dominant_tumor_ajcc8_t_stage",                 "VARCHAR"),
    ("dominant_tumor_ajcc8_n_stage",                 "VARCHAR"),
    ("dominant_tumor_ajcc8_m_stage",                 "VARCHAR"),
    ("dominant_tumor_ajcc8_stage_group",             "VARCHAR"),
    ("tumor_stage_heterogeneous_t_ajcc8_flag",       "BOOLEAN"),
    ("tumor_stage_heterogeneous_overall_ajcc8_flag", "BOOLEAN"),
    ("n_tumors_ajcc7_staged",                        "INTEGER"),
    ("n_tumors_ajcc8_staged",                        "INTEGER"),
]

# Per-tumor adaptation: skip the path_t_stage_raw shortcut so multifocal
# patients don't all collapse to the same T-stage. Identical to
# compute_t_stage from 51b otherwise.
def compute_t_stage_per_tumor(row) -> str | None:
    size = row.get("tumor_size_cm")
    ete = str(row.get("ete_grade", "") or "").lower()
    gross_ete = row.get("gross_ete_flag") is True

    # Fix C (2026-04-17): substrate-aware T-stage assignment.
    # Substrate determines T3b vs T4a vs T4b for gross ETE per AJCC 8.
    # Sources, in priority order:
    #   1. STL extrathyroidal_extension text keywords
    #   2. OED structure-specific flags (strap_muscle/tracheal/esophageal)
    # OED currently carries no RLN/prevertebral/carotid flags -> those
    # substrates only appear if STL text mentions them.
    is_t4a = False
    is_t4b = False
    if any(k in ete for k in ("trachea", "tracheal", "cricoid",
                               "esophag",
                               "recurrent laryngeal", "rln",
                               "invading trachea", "invading esophagus",
                               "recurrent laryngeal nerve invasion")):
        is_t4a = True
    if any(k in ete for k in ("prevertebral", "carotid",
                               "mediastinal vessels", "unresectable")):
        is_t4b = True
    if row.get("oed_trachea_flag") is True or row.get("oed_esophag_flag") is True:
        is_t4a = True
    # Note: OED.strap_muscle_involvement_flag does NOT escalate beyond T3b
    # (strap-only invasion = T3b in AJCC 8). It just confirms gross.

    if pd.isna(size) or size is None:
        if is_t4b:
            return "T4b"
        if is_t4a:
            return "T4a"
        if gross_ete or "gross" in ete:
            return "T3b"
        return None
    size = float(size)
    if is_t4b:
        return "T4b"
    if is_t4a:
        return "T4a"
    if gross_ete or "gross" in ete:
        return "T3b"
    if size <= 1.0:
        return "T1a"
    elif size <= 2.0:
        return "T1b"
    elif size <= 4.0:
        return "T2"
    elif size > 4.0:
        return "T3a"
    return None


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------
def utc_now() -> str:
    return datetime.now(timezone.utc).isoformat()


def _quote(s: str | None) -> str:
    if s is None:
        return "NULL"
    return "'" + str(s).replace("'", "''") + "'"


def _exec(con, sql: str, log, do_writes: bool, *, label: str = "") -> None:
    tag = f" [{label}]" if label else ""
    if do_writes:
        log(f"  EXEC{tag}: {sql.strip().splitlines()[0][:160]}")
        con.execute(sql)
    else:
        log(f"  PLAN{tag}: {sql.strip().splitlines()[0][:160]}")


# ---------------------------------------------------------------------------
# Phase 0 — connect + sequencing preconditions
# ---------------------------------------------------------------------------
def phase_0(con, log, do_writes: bool) -> dict:
    log("\n## Phase 0 — preflight + sequencing gates")
    info = con.execute(
        f"SELECT current_database(), "
        f"(SELECT COUNT(*) FROM {CPM}), "
        f"(SELECT COUNT(*) FROM {CTC})"
    ).fetchone()
    log(f"  connected_to        : {info[0]}")
    log(f"  cpm_n_patients      : {info[1]}")
    log(f"  ctc_n_rows          : {info[2]}")
    if info[1] != 10871:
        raise SystemExit(f"CPM patient count mismatch: {info[1]} != 10871")
    if info[2] < 11000:
        raise SystemExit(f"CTC row count {info[2]} unexpectedly low")

    # Gate A — Script 266a applied (data_dictionary_v266a present)
    n_v266a = con.execute(f"""
        SELECT COUNT(*) FROM information_schema.tables
         WHERE table_catalog='{PUBLICATION_DB}' AND table_schema='main'
           AND table_name='data_dictionary_v266a'
    """).fetchone()[0]
    log(f"  GATE 266a applied   : data_dictionary_v266a exists = {bool(n_v266a)}")
    if not n_v266a:
        raise SystemExit(
            "266b precondition: data_dictionary_v266a not found. "
            "Run scripts/266a_dictionary_and_feeder_registration.py --apply first."
        )

    # Gate B — big-cleanup Phase 4.6 applied. Original Gate B also required
    # `ajcc8_t_stage_v2` absent, but the cleanup prompt scoped Phase 4.6 ONLY
    # to renaming `ajcc8_t_stage_corrected -> ajcc8_t_stage`. `_v2` is an
    # unrelated historical intermediate column from an earlier staging
    # refinement; 266b does not consume it. Relaxed 2026-04-17 (Logan
    # direction) to remove the `_v2` check while preserving the
    # semantic-correctness checks: `_corrected` must be absent (proves the
    # rename happened) and `ajcc8_t_stage` must be present (proves the
    # canonical column now points to the corrected values).
    cpm_ajcc_cols = [r[0] for r in con.execute(f"""
        SELECT column_name FROM information_schema.columns
         WHERE table_catalog='{PUBLICATION_DB}' AND table_schema='main'
           AND table_name='canonical_patient_master'
           AND column_name ILIKE 'ajcc8_%'
         ORDER BY column_name
    """).fetchall()]
    has_clean = "ajcc8_t_stage" in cpm_ajcc_cols
    has_corrected = "ajcc8_t_stage_corrected" in cpm_ajcc_cols
    has_v2 = "ajcc8_t_stage_v2" in cpm_ajcc_cols  # informational only
    has_deprecated = (
        "ajcc8_t_stage_with_microete_t3b_DEPRECATED" in cpm_ajcc_cols
    )
    log(f"  GATE big-cleanup    : ajcc8_t_stage={has_clean} "
        f"corrected={has_corrected} v2={has_v2} "
        f"DEPRECATED__present={has_deprecated}")
    if has_corrected:
        raise SystemExit(
            "266b precondition: PART2/PROMPT_18 big cleanup Phase 4.6 "
            "rename not applied. `ajcc8_t_stage_corrected` is still present "
            "on CPM. Per user direction, 266b derivation must anchor to the "
            "renamed canonical `ajcc8_t_stage` column. Run the big cleanup "
            "Phases 1-7 first (or 274b rename), merge, then re-run 266b."
        )
    if not has_clean:
        raise SystemExit(
            "266b precondition: ajcc8_t_stage is missing from CPM. "
            "Cannot anchor per-tumor derivation."
        )

    # Gate C — CTC-side un-versioned t_stage/n_stage/m_stage/overall_stage
    # present (we will leave them in place; 266c will rename them).
    ctc_cols = {r[0] for r in con.execute(f"""
        SELECT column_name FROM information_schema.columns
         WHERE table_catalog='{PUBLICATION_DB}' AND table_schema='main'
           AND table_name='canonical_tumor_characteristics_v1'
    """).fetchall()}
    log(f"  CTC has un-versioned t_stage : {'t_stage' in ctc_cols}")
    log(f"  CTC has un-versioned n_stage : {'n_stage' in ctc_cols}")
    log(f"  CTC has un-versioned m_stage : {'m_stage' in ctc_cols}")
    log(f"  CTC has un-versioned overall_stage : {'overall_stage' in ctc_cols}")

    # Gate D — required inputs present in CTC
    required = ["research_id", "surgery_episode_id", "tumor_ordinal",
                "size_greatest_dimension_cm", "tumor_size_cm_per_surgery",
                "primary_histology", "extrathyroidal_extension", "gross_ete"]
    missing = [c for c in required if c not in ctc_cols]
    log(f"  CTC required inputs missing : {missing or 'none'}")
    if missing:
        raise SystemExit(f"CTC missing required input columns: {missing}")

    return {
        "cpm_n_patients": info[1], "ctc_n_rows": info[2],
        "v266a_applied": bool(n_v266a),
        "ajcc8_t_stage_clean": has_clean,
        "ajcc8_t_stage_corrected_residual": has_corrected,
        "ajcc8_t_stage_v2_present_informational": has_v2,
        "ajcc8_t_stage_DEPRECATED_present": has_deprecated,
        "gate_b_relaxation_note": (
            "Gate B relaxed 2026-04-17: removed check for "
            "ajcc8_t_stage_v2 absence. Big cleanup Phase 4.6 was scoped "
            "only to the ajcc8_t_stage_corrected -> ajcc8_t_stage rename; "
            "_v2 is an unrelated historical intermediate column that 266b "
            "does not consume. Retaining the check for _corrected absence "
            "(semantic-correctness gate) and ajcc8_t_stage presence "
            "(rename-completed gate)."
        ),
        "cpm_ajcc8_columns": cpm_ajcc_cols,
    }


# ---------------------------------------------------------------------------
# Phase 1 — snapshot CTC + CPM to archive
# ---------------------------------------------------------------------------
def phase_1(con, log, do_writes: bool) -> dict:
    log("\n## Phase 1 — snapshot CTC + CPM to archive_pub_v1_0")
    ts = utc_ts()
    snaps: dict[str, str | None] = {}
    for src, label in [(CTC, f"canonical_tumor_characteristics_v1_pre266b_{ts}"),
                       (CPM, f"canonical_patient_master_pre266b_{ts}")]:
        if do_writes:
            ensure_archive_schema(con)
            dest = snapshot_table(
                con, src, label, SCRIPT_TAG,
                f"Pre-266b snapshot of {src} before per-tumor AJCC build "
                f"and CPM dominant-tumor surface ADD COLUMN.")
            log(f"  snapshot -> {dest}")
            snaps[src] = dest
        else:
            log(f"  PLAN: CTAS {src} -> {ARCHIVE_QUALIFIED}.{label!r}")
            snaps[src] = None
    return {"snapshots": snaps}


# ---------------------------------------------------------------------------
# Phase 2 — ALTER TABLE ADD COLUMN on CTC
# ---------------------------------------------------------------------------
def phase_2(con, log, do_writes: bool) -> dict:
    log("\n## Phase 2 — ALTER TABLE ADD COLUMN on CTC (14 columns)")
    existing = {r[0] for r in con.execute(f"""
        SELECT column_name FROM information_schema.columns
         WHERE table_catalog='{PUBLICATION_DB}' AND table_schema='main'
           AND table_name='canonical_tumor_characteristics_v1'
    """).fetchall()}
    added = []
    for col, typ in CTC_NEW_COLUMNS:
        if col in existing:
            log(f"  SKIP (already present): {col}")
            continue
        sql = f"ALTER TABLE {CTC} ADD COLUMN {col} {typ}"
        _exec(con, sql, log, do_writes, label=f"add:{col}")
        added.append(col)
    return {"added_columns": added, "skipped_present": [
        c for c, _ in CTC_NEW_COLUMNS if c in existing
    ]}


# ---------------------------------------------------------------------------
# Phase 3 — derive per-tumor AJCC7/AJCC8 in pandas; UPDATE CTC
# ---------------------------------------------------------------------------
def phase_3(con, log, do_writes: bool) -> dict:
    log("\n## Phase 3 — derive per-tumor AJCC7/AJCC8 (pandas + UPDATE CTC)")

    # Pull CTC + per-patient broadcast inputs.
    # rid_type_consistency: CTC.research_id is INTEGER; CPM is VARCHAR.
    # Cast all sources to VARCHAR for consistent joining downstream.
    log("  pulling per-tumor frame ...")
    # Per-tumor inputs: STL is the AUTHORITATIVE per-tumor source.
    # CTC.extrathyroidal_extension is COALESCE(STL, TEM) and CTC.gross_ete is
    # TEM-only (per-surgery, broadcast across all tumors of the surgery).
    # Both have the multifocal-broadcast bug — using them would inflate
    # secondary tumors of multifocal patients to the dominant ETE level
    # → wrongly upstage them to T3b/T4a.
    # 266b therefore (a) joins synoptic_tumor_long_v1 directly via
    # synoptic_row_ix to recover the true per-tumor STL value, and
    # (b) falls back to ete_adjudication_v1.adjudicated_grade per-PATIENT
    # only when STL is NULL (~45 adjudicated patients).
    # tumor_size_cm: same principle — STL per-tumor only, NO fallback to
    # CTC.tumor_size_cm_per_surgery (which is TEM per-surgery broadcast).
    df = con.execute(f"""
        WITH stl_real AS (
          -- Fix A (2026-04-17): filter STL placeholder rows.
          -- 45.13% of STL rows have NULL size; audit confirmed these are
          -- workbook design (slot rows for benign/metastatic-only patients
          -- with no primary thyroid tumor), not extraction failure. Treating
          -- them as "no STL row" is semantically correct.
          SELECT *
          FROM {PUBLICATION_DB}.main.synoptic_tumor_long_v1
          WHERE size_greatest_dimension_cm IS NOT NULL
             OR histologic_type IS NOT NULL
             OR extrathyroidal_extension IS NOT NULL
             OR margin_status IS NOT NULL
        ),
        per_tumor AS (
          SELECT
            CAST(ctc.research_id AS VARCHAR)               AS research_id,
            ctc.surgery_episode_id                          AS surgery_episode_id,
            ctc.tumor_ordinal                               AS tumor_ordinal,
            ctc.synoptic_row_ix                             AS synoptic_row_ix,
            ctc.size_greatest_dimension_cm                  AS tumor_size_cm,
            ctc.primary_histology                           AS primary_histology,
            stl.extrathyroidal_extension                    AS stl_ete_text,
            eaj.adjudicated_grade                           AS adjudicated_ete_grade,
            ctc.ln_examined                                 AS ln_examined,
            ctc.ln_involved                                 AS ln_involved,
            ctc.nodal_disease_positive_count                AS nodal_disease_positive_count,
            ctc.extranodal_extension                        AS extranodal_extension,
            -- Fix C (2026-04-17): OED substrate flags for T4a/T4b. Per-surgery
            -- via surgery_episode_id. Only OED currently carries these signals;
            -- STL extrathyroidal_extension text has 0 mentions of strap/trachea/
            -- esophag/RLN.
            oed.strap_muscle_involvement_flag               AS oed_strap_flag,
            oed.tracheal_involvement_flag                   AS oed_trachea_flag,
            oed.esophageal_involvement_flag                 AS oed_esophag_flag
          FROM {CTC} AS ctc
          LEFT JOIN stl_real AS stl
            ON CAST(ctc.research_id AS VARCHAR) = CAST(stl.research_id AS VARCHAR)
           AND ctc.synoptic_row_ix = stl.synoptic_row_ix
          LEFT JOIN {PUBLICATION_DB}.main.ete_adjudication_v1 AS eaj
            ON CAST(ctc.research_id AS VARCHAR) = CAST(eaj.research_id AS VARCHAR)
          LEFT JOIN {PUBLICATION_DB}.main.operative_episode_detail_v2 AS oed
            ON CAST(ctc.research_id AS VARCHAR) = CAST(oed.research_id AS VARCHAR)
           AND ctc.surgery_episode_id = oed.surgery_episode_id
        ),
        cpm_anchor AS (
          SELECT
            cpm.research_id                                 AS research_id,
            cpm.is_malignant                                AS is_malignant,
            cpm.age_at_surgery                              AS age_at_surgery,
            cpm.histology_final                             AS histology_final,
            cpm.ajcc8_n_stage                               AS cpm_ajcc8_n_stage,
            cpm.ajcc8_m_stage                               AS cpm_ajcc8_m_stage,
            cpm.ajcc8_t_stage                               AS cpm_ajcc8_t_stage,
            cpm.path_t_stage_raw                            AS path_t_stage_raw,
            cpm.path_n_stage_raw                            AS path_n_stage_raw,
            cpm.path_m_stage_raw                            AS path_m_stage_raw,
            cpm.pet_distant_mets_ever                       AS pet_distant_mets_ever,
            cpm.ete_grade_final_v2                          AS cpm_ete_grade_final_v2
          FROM {CPM} AS cpm
        ),
        ln_anchor AS (
          -- Bug 5 fix (2026-04-17): pre-aggregate to ONE row per research_id
          -- with severity priority N1b > N1a > N1 > NX > N0 > NULL.
          --
          -- ln_master_rollup_v1 is per-(research_id, histology), so a
          -- patient with multi-histology cancer can have multiple rollup
          -- rows with different n_stage_ajcc8 values (179 rids in current
          -- cohort have >=2 distinct n_stage values across histologies).
          -- Without aggregation, the per_tumor join fans out and the
          -- post-Bug-4 dedup picks DIFFERENT rollup branches for different
          -- tumors of the same surgery -- violating the n_stage broadcast
          -- convention (n_stage should be uniform across all tumors of one
          -- surgery). Detected by Phase 4 Gate 4 verification (2 violator
          -- surgeries: rid 1732 surg 3, rid 2505 surg 1).
          --
          -- Severity-priority pick keeps the worst N-stage across the
          -- patient's histologies, preserving clinical conservatism.
          SELECT
            CAST(research_id AS VARCHAR) AS research_id,
            CASE MAX(CASE histology_1_n_stage_ajcc8
                       WHEN 'N1b' THEN 5
                       WHEN 'N1a' THEN 4
                       WHEN 'N1'  THEN 3
                       WHEN 'NX'  THEN 2
                       WHEN 'N0'  THEN 1
                       ELSE 0
                     END)
              WHEN 5 THEN 'N1b'
              WHEN 4 THEN 'N1a'
              WHEN 3 THEN 'N1'
              WHEN 2 THEN 'NX'
              WHEN 1 THEN 'N0'
              ELSE NULL
            END AS ln_histology_1_n_stage_ajcc8
          FROM {LNROL}
          WHERE research_id IS NOT NULL
          GROUP BY CAST(research_id AS VARCHAR)
        )
        SELECT
          pt.*,
          ca.is_malignant                                   AS is_malignant,
          ca.age_at_surgery                                 AS age_at_surgery,
          ca.histology_final                                AS histology_final,
          ca.cpm_ajcc8_n_stage                              AS cpm_ajcc8_n_stage,
          ca.cpm_ajcc8_m_stage                              AS cpm_ajcc8_m_stage,
          ca.cpm_ajcc8_t_stage                              AS cpm_ajcc8_t_stage,
          ca.path_t_stage_raw                               AS path_t_stage_raw,
          ca.path_n_stage_raw                               AS path_n_stage_raw,
          ca.path_m_stage_raw                               AS path_m_stage_raw,
          ca.pet_distant_mets_ever                          AS pet_distant_mets_ever,
          ca.cpm_ete_grade_final_v2                         AS cpm_ete_grade_final_v2,
          la.ln_histology_1_n_stage_ajcc8                   AS ln_histology_1_n_stage_ajcc8
        FROM per_tumor AS pt
        LEFT JOIN cpm_anchor AS ca
          ON ca.research_id = pt.research_id
        LEFT JOIN ln_anchor AS la
          ON la.research_id = pt.research_id
    """).fetchdf()
    log(f"  rows: {len(df)}  patients: {df['research_id'].nunique()}")

    # ---- Per-tumor ETE classification (STL primary, adjudication fallback) ----
    # Returns (ete_grade_text_canonical, gross_ete_flag, ete_source_label).
    # NEVER reads CPM.gross_ete_flag — that's patient-level and would
    # broadcast a tumor-1-only gross finding across all tumors of a
    # multifocal patient. ete_adjudication_v1 IS per-patient but the
    # adjudicator presumably reviewed every tumor when assigning the grade.
    GROSS_KEYWORDS = (
        "gross", "strap muscle", "sternothyroid", "sternohyoid", "omohyoid",
        "macroscopic extension", "visible gross", "invading trachea",
        "invading esophagus", "recurrent laryngeal nerve invasion",
    )
    # 2026-04-17 vocabulary additions per Logan: minimal/focal -> MICRO;
    # microscopiic typo -> MICRO. (extensive/extesive intentionally stay
    # unclassified -- ambiguous without substrate.)
    MICRO_KEYWORDS = (
        "microscopic", "microscopiic",
        "minimal extension", "minimal",
        "focally extending", "focal perithyroidal", "focal",
        "perithyroidal soft tissue",
        "perithyroidal fibroadipose", "perithyroidal fat",
    )
    ABSENT_KEYWORDS = ("absent", "none", "no extension", "negative", "not present")

    # CPM overlay tier 4 mapping: clinical grades from CPM ete_grade_final_v2
    # that we are willing to broadcast to the dominant tumor when the STL
    # classifier returns unclassified_present. Limited to the unambiguous
    # clinical grades; 'present_ungraded', 'true', 'false' deliberately
    # excluded (would not improve the classification or risks overriding
    # STL-positive signal).
    CPM_OVERLAY_GRADES = {"gross": True, "microscopic": False, "absent": False}

    def _classify_ete(row) -> tuple[str | None, bool | None, str]:
        stl_raw = row.get("stl_ete_text")
        if pd.notna(stl_raw) and stl_raw is not None and str(stl_raw).strip():
            text = str(stl_raw).strip().lower()
            if any(k in text for k in GROSS_KEYWORDS):
                return text, True, "stl_per_tumor:gross"
            if any(k in text for k in MICRO_KEYWORDS):
                return text, False, "stl_per_tumor:microscopic"
            if any(k in text for k in ABSENT_KEYWORDS):
                return text, False, "stl_per_tumor:absent"
            # Tier 4 — CPM overlay (added 2026-04-17). When the per-tumor
            # STL text is positive but the keyword vocabulary cannot grade
            # it, defer to the CPM patient-level clinical grade ONLY for
            # the dominant tumor. Multifocal patients' secondary tumors
            # remain unclassified to avoid the broadcast bug.
            cpm_g = row.get("cpm_ete_grade_final_v2")
            is_dom = bool(row.get("is_dominant_tumor", False))
            if (is_dom and pd.notna(cpm_g) and cpm_g is not None
                    and str(cpm_g).strip().lower() in CPM_OVERLAY_GRADES):
                cg = str(cpm_g).strip().lower()
                gross_flag = CPM_OVERLAY_GRADES[cg]
                return cg, gross_flag, f"cpm_patient_level:broadcast_to_dominant:{cg}"
            # Otherwise keep as unclassified_present (no override).
            return text, False, "stl_per_tumor:unclassified_present"

        adj = row.get("adjudicated_ete_grade")
        if pd.notna(adj) and adj is not None and str(adj).strip():
            a = str(adj).strip().lower()
            if a == "gross":
                return a, True, "ete_adjudication_v1:gross"
            if a == "microscopic":
                return a, False, "ete_adjudication_v1:microscopic"
            if a == "absent":
                return a, False, "ete_adjudication_v1:absent"
            return a, None, "ete_adjudication_v1:unable_to_determine"

        return None, None, "uncalculable:no_stl_no_adjudication"

    # Tag dominant tumor per patient (largest size_greatest_dimension_cm,
    # tumor_ordinal as tiebreaker -- mirrors Phase 4's ROW_NUMBER OVER
    # PARTITION BY research_id ORDER BY tumor_size_cm DESC NULLS LAST,
    # tumor_ordinal ASC). Used by Tier 4 CPM overlay above.
    _sorted = df.sort_values(
        ["research_id", "tumor_size_cm", "tumor_ordinal"],
        ascending=[True, False, True],
        na_position="last",
        kind="mergesort",
    )
    _dominant_indices = _sorted.groupby("research_id", sort=False).head(1).index
    df["is_dominant_tumor"] = df.index.isin(_dominant_indices)

    ete_triples = df.apply(_classify_ete, axis=1)
    df["ete_grade"] = [t[0] for t in ete_triples]
    df["gross_ete_flag"] = [t[1] for t in ete_triples]
    df["ete_source"] = [t[2] for t in ete_triples]

    # Audit CSV — distinct STL ETE values + their classification (for review).
    audit_path = OUT_DIR / "266b_ete_classification_audit.csv"
    audit = (
        df.groupby(["stl_ete_text", "ete_source"], dropna=False)
        .size()
        .reset_index(name="n_tumors")
        .sort_values("n_tumors", ascending=False)
    )
    audit.to_csv(audit_path, index=False)
    log(f"  ete classification audit -> {audit_path.name} "
        f"({len(audit)} unique (stl_text, source) pairs)")
    log(f"  ete source counts: {df['ete_source'].value_counts().to_dict()}")

    # ---- Per-tumor T (AJCC8) — uses STL-derived ete_grade + gross_ete_flag ----
    df["t_stage_ajcc8"] = df.apply(compute_t_stage_per_tumor, axis=1)

    # ---- Per-tumor T (AJCC7) ----
    df["t_stage_ajcc7"] = df["t_stage_ajcc8"].apply(
        lambda t: compute_ajcc7_t_stage(t) if pd.notna(t) and t is not None else None
    )

    # ---- N-stage broadcast ----
    # Prefer ln_master_rollup_v1 per-patient AJCC8 N. Fallback: CPM.ajcc8_n_stage.
    def _n_broadcast(row):
        ln = row.get("ln_histology_1_n_stage_ajcc8")
        if pd.notna(ln) and ln is not None:
            return ln, "n_stage broadcast from ln_master_rollup_v1.histology_1_n_stage_ajcc8"
        ncpm = row.get("cpm_ajcc8_n_stage")
        if pd.notna(ncpm) and ncpm is not None:
            return ncpm, "n_stage broadcast from CPM ajcc8_n_stage (LN rollup absent)"
        return None, "n_stage unresolved (no LN rollup, no CPM N)"

    n_pairs = df.apply(_n_broadcast, axis=1)
    df["n_stage_ajcc8"] = [p[0] for p in n_pairs]
    df["n_note"]        = [p[1] for p in n_pairs]
    df["n_stage_ajcc7"] = df["n_stage_ajcc8"]  # AJCC7 N == AJCC8 N

    # ---- M-stage broadcast (patient-level) ----
    def _m_broadcast(row):
        m = row.get("cpm_ajcc8_m_stage") or "M0"
        return m, ("m_stage broadcast from patient-level CPM ajcc8_m_stage "
                   "(default M0 unless distant-mets flag set)")

    m_pairs = df.apply(_m_broadcast, axis=1)
    df["m_stage_ajcc8"] = [p[0] for p in m_pairs]
    df["m_note"]        = [p[1] for p in m_pairs]
    df["m_stage_ajcc7"] = df["m_stage_ajcc8"]  # AJCC7 M == AJCC8 M

    # ---- AJCC8 stage group (per-tumor) ----
    # Helper expects ajcc8_t_stage / ajcc8_n_stage / ajcc8_m_stage on the row.
    df["ajcc8_t_stage"] = df["t_stage_ajcc8"]
    df["ajcc8_n_stage"] = df["n_stage_ajcc8"]
    df["ajcc8_m_stage"] = df["m_stage_ajcc8"]
    df["stage_group_ajcc8"] = df.apply(compute_stage_group, axis=1)

    # ---- AJCC7 stage group (per-tumor) ----
    # Helper reads ajcc7_t_stage and ajcc7_n_stage (= ajcc8_n_stage).
    df["ajcc7_t_stage"] = df["t_stage_ajcc7"]
    df["ajcc7_n_stage"] = df["n_stage_ajcc7"]
    df["ajcc7_m_stage"] = df["m_stage_ajcc7"]
    df["histology"] = df["histology_final"].fillna(df["primary_histology"])
    df["stage_group_ajcc7"] = df.apply(compute_ajcc7_stage_group, axis=1)

    # ---- Calculable flags ----
    df["ajcc8_stage_calculable_flag"] = df["stage_group_ajcc8"].notna()
    df["ajcc7_stage_calculable_flag"] = df["stage_group_ajcc7"].notna()

    # ---- staging_source_note (concatenate per-component notes) ----
    def _stage_note(row) -> str:
        notes = []
        size = row.get("tumor_size_cm")
        size_null = pd.isna(size) or size is None
        ete_src = row.get("ete_source", "")
        if pd.isna(row["t_stage_ajcc8"]) or row["t_stage_ajcc8"] is None:
            if size_null and ete_src.startswith("uncalculable"):
                notes.append("t_stage uncalculable: stl_size_unavailable + no_ete")
            elif size_null:
                notes.append(
                    "t_stage uncalculable: stl_size_unavailable "
                    f"(ete_source={ete_src})"
                )
            else:
                notes.append(f"t_stage uncalculable (ete_source={ete_src})")
        else:
            notes.append(
                f"t_stage from per-tumor size (stl) + ete_source={ete_src}"
            )
        notes.append(row.get("n_note", ""))
        notes.append(row.get("m_note", ""))
        return " | ".join(n for n in notes if n)
    df["staging_source_note"] = df.apply(_stage_note, axis=1)

    # ---- stage_migration_7_to_8 (per-tumor analog of CPM column) ----
    def _migration(row):
        s7 = row.get("stage_group_ajcc7")
        s8 = row.get("stage_group_ajcc8")
        if s7 is None or s8 is None or pd.isna(s7) or pd.isna(s8):
            return None
        if s7 == s8:
            return f"unchanged ({s7})"
        return f"{s7} -> {s8}"
    df["stage_migration_7_to_8"] = df.apply(_migration, axis=1)

    # ---- overall_stage_ajcc7 / overall_stage_ajcc8 ----
    # Convention: overall_stage = stage_group (DTC-style). Carry-through.
    df["overall_stage_ajcc7"] = df["stage_group_ajcc7"]
    df["overall_stage_ajcc8"] = df["stage_group_ajcc8"]

    # ---- Bug 4 fix (2026-04-17): dedup staging frame before UPDATE FROM. ----
    # ln_master_rollup_v1 fans out CTC rows in the per_tumor join (some keys
    # have 2-4 staging rows). Pandas marks is_dominant_tumor=TRUE on exactly
    # one row per CTC key; the CPM-overlay broadcast only fires on that row.
    # DuckDB's UPDATE FROM picks ONE staging row per CTC key non-
    # deterministically -- if a non-dominant twin wins, the broadcast is lost
    # and the t_stage silently downstages. Dedup deterministically here
    # (priority: dominant > classified > calculable > stable index) so the
    # write is reproducible.
    df["_is_uncalculable"] = df["ete_source"].str.startswith("uncalculable", na=False)
    df["_is_unclassified"] = df["ete_source"].eq("stl_per_tumor:unclassified_present")
    df["_orig_idx"] = df.index  # stable monotonic tiebreaker
    df_sorted = df.sort_values(
        by=["research_id", "surgery_episode_id", "tumor_ordinal",
            "is_dominant_tumor",            # True first
            "_is_uncalculable",             # False first (classified beats uncalculable)
            "_is_unclassified",             # False first (classified beats unclassified_present)
            "ajcc8_stage_calculable_flag",  # True first
            "_orig_idx"],                   # ascending tiebreaker
        ascending=[True, True, True, False, True, True, False, True],
        kind="mergesort",
    )
    df_dedup = df_sorted.drop_duplicates(
        subset=["research_id", "surgery_episode_id", "tumor_ordinal"],
        keep="first",
    )
    n_distinct_ctc_keys = (
        df.drop_duplicates(subset=["research_id", "surgery_episode_id", "tumor_ordinal"])
        .shape[0]
    )
    if len(df_dedup) != n_distinct_ctc_keys:
        raise SystemExit(
            f"[Bug 4 dedup] post-dedup rowcount {len(df_dedup)} != "
            f"distinct-CTC-key count {n_distinct_ctc_keys}; dedup invariant broken"
        )

    keep = ["research_id", "surgery_episode_id", "tumor_ordinal",
            "t_stage_ajcc7", "n_stage_ajcc7", "m_stage_ajcc7",
            "overall_stage_ajcc7", "stage_group_ajcc7",
            "t_stage_ajcc8", "n_stage_ajcc8", "m_stage_ajcc8",
            "overall_stage_ajcc8", "stage_group_ajcc8",
            "ajcc7_stage_calculable_flag", "ajcc8_stage_calculable_flag",
            "staging_source_note", "stage_migration_7_to_8"]
    stg = df_dedup[keep].copy()
    log(f"  post-dedup staging frame: {len(stg)} rows "
        f"(must equal distinct-CTC-key count {n_distinct_ctc_keys})")
    log("  distribution snapshot (AJCC8 T per-tumor, post-dedup -- this IS what UPDATE writes):")
    log("    " + str(stg["t_stage_ajcc8"].value_counts(dropna=False).to_dict()))

    log(f"  staging frame ready: {len(stg)} rows")
    # Per-grain reporting (added 2026-04-17 per Logan): report at three grains
    # so apply-vs-dry-run comparisons are unambiguous. The staging frame
    # cardinality differs from CTC's (ln_master_rollup_v1 fan-out) so the
    # raw value_counts() doesn't predict what gets written.
    log("  distribution snapshot (AJCC8 T per-tumor, staging-frame grain):")
    log("    " + str(stg["t_stage_ajcc8"].value_counts(dropna=False).to_dict()))
    _stg_distinct = stg.drop_duplicates(
        subset=["research_id", "surgery_episode_id", "tumor_ordinal"]
    )
    log("  distribution snapshot (AJCC8 T per-tumor, distinct-CTC-key grain "
        f"-- {len(_stg_distinct)} keys; this matches what UPDATE writes):")
    log("    " + str(_stg_distinct["t_stage_ajcc8"].value_counts(dropna=False).to_dict()))
    # Patient-dominant grain preview (Phase 4 result): use Phase 3's
    # is_dominant_tumor flag which is now unified with Phase 4's rank.
    if "is_dominant_tumor" in df.columns:
        _dom = df[df["is_dominant_tumor"]].drop_duplicates(subset=["research_id"])
        log("  distribution snapshot (AJCC8 T per-PATIENT dominant tumor "
            f"-- {len(_dom)} patients; Phase 4 will surface this on CPM):")
        log("    " + str(_dom["t_stage_ajcc8"].value_counts(dropna=False).to_dict()))
    log("  distribution snapshot (AJCC7 T per-tumor):")
    log("    " + str(stg["t_stage_ajcc7"].value_counts(dropna=False).to_dict()))
    log("  calculable flags:")
    log(f"    ajcc8_stage_calculable_flag=TRUE : {int(stg['ajcc8_stage_calculable_flag'].sum())}")
    log(f"    ajcc7_stage_calculable_flag=TRUE : {int(stg['ajcc7_stage_calculable_flag'].sum())}")

    if not do_writes:
        log("  PLAN: would register stg as DuckDB temp view + 14-column UPDATE.")
        return {"rows_staged": int(len(stg)),
                "ajcc8_calculable": int(stg["ajcc8_stage_calculable_flag"].sum()),
                "ajcc7_calculable": int(stg["ajcc7_stage_calculable_flag"].sum())}

    con.register("ctc_stage_v266b", stg)
    set_clauses = ", ".join(
        f"{c} = s.{c}" for c, _ in CTC_NEW_COLUMNS
    )
    sql = f"""
        UPDATE {CTC} AS t
           SET {set_clauses}
          FROM ctc_stage_v266b AS s
         WHERE CAST(t.research_id AS VARCHAR) = s.research_id
           AND COALESCE(t.surgery_episode_id, -1) = COALESCE(s.surgery_episode_id, -1)
           AND COALESCE(t.tumor_ordinal, -1)     = COALESCE(s.tumor_ordinal, -1)
    """
    _exec(con, sql, log, do_writes, label="update_ctc")

    # COMMENT ON COLUMN for each new col
    for col, _typ in CTC_NEW_COLUMNS:
        msg = ("Per-tumor AJCC staging populated by Script 266b "
               "(2026-04-17). Derived via canonical helpers from 51b/224 "
               "with per-tumor T (no patient-level raw shortcut), N broadcast "
               "from ln_master_rollup_v1, M broadcast from CPM patient level.")
        sql_c = f"COMMENT ON COLUMN {CTC}.{col} IS {_quote(msg)}"
        _exec(con, sql_c, log, do_writes, label=f"comment:{col}")

    return {"rows_staged": int(len(stg)),
            "ajcc8_calculable": int(stg["ajcc8_stage_calculable_flag"].sum()),
            "ajcc7_calculable": int(stg["ajcc7_stage_calculable_flag"].sum())}


# ---------------------------------------------------------------------------
# Phase 4 — CREATE TABLE tumor_stage_heterogeneity_v1
# ---------------------------------------------------------------------------
def phase_4(con, log, do_writes: bool) -> dict:
    log("\n## Phase 4 — CREATE TABLE tumor_stage_heterogeneity_v1")

    # T-stage rank (for max - min spread)
    T_RANK_CASE = """
      CASE t_stage_ajcc8
        WHEN 'T1a' THEN 1 WHEN 'T1b' THEN 2 WHEN 'T2' THEN 3
        WHEN 'T3a' THEN 4 WHEN 'T3b' THEN 5
        WHEN 'T4a' THEN 6 WHEN 'T4b' THEN 7 ELSE NULL
      END
    """
    STAGE_RANK_CASE = """
      CASE stage_group_ajcc8
        WHEN 'I' THEN 1 WHEN 'II' THEN 2 WHEN 'III' THEN 3
        WHEN 'IVA' THEN 4 WHEN 'IVB' THEN 5 WHEN 'IVC' THEN 6 ELSE NULL
      END
    """

    sql = f"""
        CREATE OR REPLACE TABLE {HET} AS
        WITH per_tumor AS (
          SELECT
            CAST(research_id AS VARCHAR)        AS research_id,
            tumor_ordinal                        AS tumor_ordinal,
            -- Fix B (2026-04-17): unified dominant definition with Phase 3.
            -- Phase 3 ranks by size_greatest_dimension_cm only (in pandas).
            -- Removing COALESCE here so the SAME tumor is dominant in both
            -- phases. Tumors with NULL size_greatest_dimension_cm are not
            -- dominant-eligible (rank NULLS LAST -> they sort to the bottom).
            size_greatest_dimension_cm           AS tumor_size_cm,
            t_stage_ajcc7                        AS t_stage_ajcc7,
            stage_group_ajcc7                    AS stage_group_ajcc7,
            t_stage_ajcc8                        AS t_stage_ajcc8,
            stage_group_ajcc8                    AS stage_group_ajcc8,
            n_stage_ajcc7                        AS n_stage_ajcc7,
            n_stage_ajcc8                        AS n_stage_ajcc8,
            m_stage_ajcc7                        AS m_stage_ajcc7,
            m_stage_ajcc8                        AS m_stage_ajcc8,
            ajcc7_stage_calculable_flag          AS ajcc7_stage_calculable_flag,
            ajcc8_stage_calculable_flag          AS ajcc8_stage_calculable_flag,
            {T_RANK_CASE}                        AS t_rank_ajcc8,
            {STAGE_RANK_CASE}                    AS stage_rank_ajcc8
          FROM {CTC}
        ),
        ranked AS (
          SELECT *,
                 ROW_NUMBER() OVER (
                   PARTITION BY research_id
                   ORDER BY tumor_size_cm DESC NULLS LAST, tumor_ordinal ASC
                 ) AS dom_rank
          FROM per_tumor
        ),
        dominant AS (
          SELECT
            research_id                          AS research_id,
            tumor_ordinal                        AS dominant_tumor_ordinal,
            t_stage_ajcc7                        AS dominant_tumor_ajcc7_t_stage,
            n_stage_ajcc7                        AS dominant_tumor_ajcc7_n_stage,
            m_stage_ajcc7                        AS dominant_tumor_ajcc7_m_stage,
            stage_group_ajcc7                    AS dominant_tumor_ajcc7_stage_group,
            t_stage_ajcc8                        AS dominant_tumor_ajcc8_t_stage,
            n_stage_ajcc8                        AS dominant_tumor_ajcc8_n_stage,
            m_stage_ajcc8                        AS dominant_tumor_ajcc8_m_stage,
            stage_group_ajcc8                    AS dominant_tumor_ajcc8_stage_group
          FROM ranked WHERE dom_rank = 1
        ),
        agg AS (
          SELECT
            research_id                                                        AS research_id,
            COUNT(*) FILTER (WHERE ajcc7_stage_calculable_flag)                 AS n_tumors_staged_ajcc7,
            COUNT(*) FILTER (WHERE ajcc8_stage_calculable_flag)                 AS n_tumors_staged_ajcc8,
            COALESCE(MAX(t_rank_ajcc8) - MIN(t_rank_ajcc8), 0)                 AS max_t_minus_min_t_ajcc8,
            COALESCE(MAX(stage_rank_ajcc8) - MIN(stage_rank_ajcc8), 0)         AS max_stage_minus_min_stage_ajcc8,
            (COUNT(*) FILTER (WHERE ajcc8_stage_calculable_flag) > 1
             AND COUNT(DISTINCT t_stage_ajcc8) FILTER (WHERE ajcc8_stage_calculable_flag) > 1)
                                                                                AS heterogeneous_t_ajcc8_flag,
            (COUNT(*) FILTER (WHERE ajcc8_stage_calculable_flag) > 1
             AND COUNT(DISTINCT stage_group_ajcc8) FILTER (WHERE ajcc8_stage_calculable_flag) > 1)
                                                                                AS heterogeneous_stage_ajcc8_flag
          FROM per_tumor
          GROUP BY research_id
        )
        SELECT
          a.research_id                                              AS research_id,
          a.n_tumors_staged_ajcc7                                    AS n_tumors_staged_ajcc7,
          a.n_tumors_staged_ajcc8                                    AS n_tumors_staged_ajcc8,
          a.max_t_minus_min_t_ajcc8                                  AS max_t_minus_min_t_ajcc8,
          a.max_stage_minus_min_stage_ajcc8                          AS max_stage_minus_min_stage_ajcc8,
          a.heterogeneous_t_ajcc8_flag                               AS heterogeneous_t_ajcc8_flag,
          a.heterogeneous_stage_ajcc8_flag                           AS heterogeneous_stage_ajcc8_flag,
          d.dominant_tumor_ordinal                                   AS dominant_tumor_ordinal,
          d.dominant_tumor_ajcc7_t_stage                             AS dominant_tumor_ajcc7_t_stage,
          d.dominant_tumor_ajcc7_n_stage                             AS dominant_tumor_ajcc7_n_stage,
          d.dominant_tumor_ajcc7_m_stage                             AS dominant_tumor_ajcc7_m_stage,
          d.dominant_tumor_ajcc7_stage_group                         AS dominant_tumor_ajcc7_stage_group,
          d.dominant_tumor_ajcc8_t_stage                             AS dominant_tumor_ajcc8_t_stage,
          d.dominant_tumor_ajcc8_n_stage                             AS dominant_tumor_ajcc8_n_stage,
          d.dominant_tumor_ajcc8_m_stage                             AS dominant_tumor_ajcc8_m_stage,
          d.dominant_tumor_ajcc8_stage_group                         AS dominant_tumor_ajcc8_stage_group,
          'Built by Script 266b 2026-04-17 from canonical_tumor_characteristics_v1; '
          || 'dominance rule = max tumor_size_cm, ties broken by min tumor_ordinal.' AS notes
        FROM agg a
        LEFT JOIN dominant d ON d.research_id = a.research_id
    """
    _exec(con, sql, log, do_writes, label="ctas_heterogeneity")

    comment = (
        "Script 266b (2026-04-17). Patient-grain rollup of per-tumor "
        "AJCC stages from canonical_tumor_characteristics_v1. Feeds CPM "
        "dominant_tumor_* columns and heterogeneity flags. Cohort-scoped "
        "to the 8,422 tumor-bearing patients per cohort_scoping convention; "
        "the 2,449 benign tumor-free CPM patients are intentionally absent."
    ).replace("'", "''")
    _exec(con, f"COMMENT ON TABLE {HET} IS '{comment}'", log, do_writes,
          label="comment_het")

    if do_writes:
        n = int(con.execute(f"SELECT COUNT(*) FROM {HET}").fetchone()[0])
        log(f"  tumor_stage_heterogeneity_v1 rows: {n}")
        return {"het_rows": n}
    return {"het_rows": None}


# ---------------------------------------------------------------------------
# Phase 5 — ALTER CPM ADD COLUMN + UPDATE from heterogeneity table
# ---------------------------------------------------------------------------
def phase_5(con, log, do_writes: bool) -> dict:
    log("\n## Phase 5 — ALTER CPM ADD COLUMN + UPDATE from heterogeneity")

    existing = {r[0] for r in con.execute(f"""
        SELECT column_name FROM information_schema.columns
         WHERE table_catalog='{PUBLICATION_DB}' AND table_schema='main'
           AND table_name='canonical_patient_master'
    """).fetchall()}
    added = []
    for col, typ in CPM_NEW_COLUMNS:
        if col in existing:
            log(f"  SKIP (already present): {col}")
            continue
        sql = f"ALTER TABLE {CPM} ADD COLUMN {col} {typ}"
        _exec(con, sql, log, do_writes, label=f"add:{col}")
        added.append(col)

    set_clauses = ", ".join([
        "dominant_tumor_ajcc7_t_stage = h.dominant_tumor_ajcc7_t_stage",
        "dominant_tumor_ajcc7_n_stage = h.dominant_tumor_ajcc7_n_stage",
        "dominant_tumor_ajcc7_m_stage = h.dominant_tumor_ajcc7_m_stage",
        "dominant_tumor_ajcc7_stage_group = h.dominant_tumor_ajcc7_stage_group",
        "dominant_tumor_ajcc8_t_stage = h.dominant_tumor_ajcc8_t_stage",
        "dominant_tumor_ajcc8_n_stage = h.dominant_tumor_ajcc8_n_stage",
        "dominant_tumor_ajcc8_m_stage = h.dominant_tumor_ajcc8_m_stage",
        "dominant_tumor_ajcc8_stage_group = h.dominant_tumor_ajcc8_stage_group",
        "tumor_stage_heterogeneous_t_ajcc8_flag = h.heterogeneous_t_ajcc8_flag",
        "tumor_stage_heterogeneous_overall_ajcc8_flag = h.heterogeneous_stage_ajcc8_flag",
        "n_tumors_ajcc7_staged = h.n_tumors_staged_ajcc7",
        "n_tumors_ajcc8_staged = h.n_tumors_staged_ajcc8",
    ])
    sql = f"""
        UPDATE {CPM} AS cpm
           SET {set_clauses}
          FROM {HET} AS h
         WHERE h.research_id = cpm.research_id
    """
    _exec(con, sql, log, do_writes, label="update_cpm_dominant")

    # COMMENT ON COLUMN for each
    for col, _typ in CPM_NEW_COLUMNS:
        msg = ("Script 266b (2026-04-17). Sourced from "
               "main.tumor_stage_heterogeneity_v1 (single-source rollup; "
               "feeder convention: single_source_rollup_inherits_feeder).")
        sql_c = f"COMMENT ON COLUMN {CPM}.{col} IS {_quote(msg)}"
        _exec(con, sql_c, log, do_writes, label=f"comment:{col}")

    return {"added_columns": added}


# ---------------------------------------------------------------------------
# Phase 6 — validation suite
# ---------------------------------------------------------------------------
def phase_6(con, log, do_writes: bool) -> dict:
    log("\n## Phase 6 — validation suite")
    if not do_writes:
        log("  PLAN: would run validations against post-apply state.")
        return {"skipped_dryrun": True}

    out: dict = {}

    # --- V1: dominant vs tumor_pathology.histology_1 concordance ---
    # Cohort: malignant patients with both dominant_tumor_ajcc8_t_stage and
    # tumor_pathology.histology_1_t_stage_ajcc8 populated.
    rows = con.execute(f"""
        WITH joined AS (
          SELECT
            cpm.research_id                                 AS research_id,
            cpm.dominant_tumor_ajcc8_t_stage                AS dom_t,
            tp.histology_1_t_stage_ajcc8                    AS hist1_t
          FROM {CPM} AS cpm
          INNER JOIN {TPATH} AS tp
            ON CAST(tp.research_id AS VARCHAR) = cpm.research_id
          WHERE cpm.dominant_tumor_ajcc8_t_stage IS NOT NULL
            AND tp.histology_1_t_stage_ajcc8 IS NOT NULL
        )
        SELECT
          COUNT(*)                                          AS n_pairs,
          COUNT(*) FILTER (WHERE dom_t = hist1_t)           AS n_concordant
        FROM joined
    """).fetchone()
    n_pairs, n_concordant = int(rows[0]), int(rows[1])
    pct = 100.0 * n_concordant / n_pairs if n_pairs else 0.0
    log(f"  V1 dominant_t8 vs histology_1_t8: {n_concordant}/{n_pairs} = {pct:.2f}%")
    out["dominant_vs_histology1_n_pairs"] = n_pairs
    out["dominant_vs_histology1_n_concordant"] = n_concordant
    out["dominant_vs_histology1_pct"] = round(pct, 2)

    # Discordance dump
    disc = con.execute(f"""
        SELECT
          cpm.research_id                                   AS research_id,
          cpm.dominant_tumor_ajcc8_t_stage                  AS dominant_tumor_ajcc8_t_stage,
          tp.histology_1_t_stage_ajcc8                      AS histology_1_t_stage_ajcc8,
          cpm.tumor_stage_heterogeneous_t_ajcc8_flag        AS heterogeneous_t_flag,
          cpm.n_tumors_ajcc8_staged                         AS n_tumors_ajcc8_staged
        FROM {CPM} AS cpm
        INNER JOIN {TPATH} AS tp
          ON CAST(tp.research_id AS VARCHAR) = cpm.research_id
        WHERE cpm.dominant_tumor_ajcc8_t_stage IS NOT NULL
          AND tp.histology_1_t_stage_ajcc8 IS NOT NULL
          AND cpm.dominant_tumor_ajcc8_t_stage <> tp.histology_1_t_stage_ajcc8
        ORDER BY research_id
    """).fetchall()
    with DISCORDANCE_CSV.open("w", newline="") as f:
        w = csv.writer(f)
        w.writerow(["research_id", "dominant_tumor_ajcc8_t_stage",
                    "histology_1_t_stage_ajcc8", "heterogeneous_t_flag",
                    "n_tumors_ajcc8_staged"])
        w.writerows(disc)
    log(f"  V1 discordance rows -> {DISCORDANCE_CSV.name}: {len(disc)}")

    # --- V2: per-tumor calculable count ---
    n_pt_calc = int(con.execute(f"""
        SELECT COUNT(*) FROM {CTC} WHERE ajcc8_stage_calculable_flag
    """).fetchone()[0])
    n_pat_calc = int(con.execute(f"""
        SELECT COUNT(DISTINCT research_id) FROM {CTC}
         WHERE ajcc8_stage_calculable_flag
    """).fetchone()[0])
    log(f"  V2 per-tumor ajcc8 calculable: tumors={n_pt_calc} patients={n_pat_calc}")
    out["per_tumor_ajcc8_calculable_tumors"] = n_pt_calc
    out["per_tumor_ajcc8_calculable_patients"] = n_pat_calc

    # --- V3: AJCC7 / AJCC8 t-stage distributions ---
    out["ajcc8_t_distribution"] = {
        r[0]: int(r[1]) for r in con.execute(f"""
            SELECT t_stage_ajcc8, COUNT(*) FROM {CTC}
             GROUP BY 1 ORDER BY 1 NULLS LAST
        """).fetchall()
    }
    out["ajcc7_t_distribution"] = {
        r[0]: int(r[1]) for r in con.execute(f"""
            SELECT t_stage_ajcc7, COUNT(*) FROM {CTC}
             GROUP BY 1 ORDER BY 1 NULLS LAST
        """).fetchall()
    }
    log(f"  V3 ajcc8_t distribution: {out['ajcc8_t_distribution']}")
    log(f"  V3 ajcc7_t distribution: {out['ajcc7_t_distribution']}")

    # --- V4: heterogeneity counts ---
    out["n_pts_t_heterogeneous"] = int(con.execute(f"""
        SELECT COUNT(*) FROM {CPM}
         WHERE tumor_stage_heterogeneous_t_ajcc8_flag
    """).fetchone()[0])
    out["n_pts_overall_heterogeneous"] = int(con.execute(f"""
        SELECT COUNT(*) FROM {CPM}
         WHERE tumor_stage_heterogeneous_overall_ajcc8_flag
    """).fetchone()[0])
    log(f"  V4 heterogeneous t_ajcc8 patients: {out['n_pts_t_heterogeneous']}")
    log(f"  V4 heterogeneous overall_ajcc8 patients: {out['n_pts_overall_heterogeneous']}")

    return out


# ---------------------------------------------------------------------------
# Phase 7 — acceptance gates + view smoke check
# ---------------------------------------------------------------------------
def phase_7(con, log, do_writes: bool, prior: dict) -> dict:
    log("\n## Phase 7 — acceptance gates + view smoke check")
    if not do_writes:
        log("  PLAN: skip in dry-run.")
        return {"skipped_dryrun": True}

    # Gate A: CTC has all 14 new cols
    ctc_cols = {r[0] for r in con.execute(f"""
        SELECT column_name FROM information_schema.columns
         WHERE table_catalog='{PUBLICATION_DB}' AND table_schema='main'
           AND table_name='canonical_tumor_characteristics_v1'
    """).fetchall()}
    ctc_missing = [c for c, _ in CTC_NEW_COLUMNS if c not in ctc_cols]
    log(f"  GATE CTC new cols missing: {ctc_missing or 'none'}")
    if ctc_missing:
        raise SystemExit(f"CTC missing {ctc_missing}")

    # Gate B: CPM has all 12 new cols
    cpm_cols = {r[0] for r in con.execute(f"""
        SELECT column_name FROM information_schema.columns
         WHERE table_catalog='{PUBLICATION_DB}' AND table_schema='main'
           AND table_name='canonical_patient_master'
    """).fetchall()}
    cpm_missing = [c for c, _ in CPM_NEW_COLUMNS if c not in cpm_cols]
    log(f"  GATE CPM new cols missing: {cpm_missing or 'none'}")
    if cpm_missing:
        raise SystemExit(f"CPM missing {cpm_missing}")

    # Gate C: tumor_stage_heterogeneity_v1 exists with rows
    n_het = int(con.execute(f"SELECT COUNT(*) FROM {HET}").fetchone()[0])
    log(f"  GATE heterogeneity rows: {n_het}")
    if n_het < 5000:
        raise SystemExit(f"Heterogeneity table too small: {n_het} (expected >= 5000)")

    # Gate D: per-tumor AJCC8 calculable patients ≥ 3,900
    n_pat = prior.get("phase_6", {}).get(
        "per_tumor_ajcc8_calculable_patients", 0
    )
    log(f"  GATE per-tumor ajcc8 calculable patients: {n_pat} (required >= 3900)")
    if n_pat < 3900:
        raise SystemExit(f"Per-tumor AJCC8 calculable patients {n_pat} < 3,900")

    # Gate E: dominant vs histology_1 concordance — 3-tier gate.
    pct = prior.get("phase_6", {}).get("dominant_vs_histology1_pct", 0.0)
    log(f"  GATE dominant_t8 vs histology_1_t8 concordance: {pct:.2f}% "
        f"(pass>={CONCORDANCE_PASS} | soft>={CONCORDANCE_SOFT} | "
        f"hard_fail<{CONCORDANCE_SOFT})")
    concordance_status = "pass"
    if pct < CONCORDANCE_SOFT:
        raise SystemExit(
            f"Concordance {pct:.2f}% < {CONCORDANCE_SOFT}% — hard fail. "
            f"Per-tumor derivation is materially out of agreement with "
            f"tumor_pathology.histology_1_t_stage_ajcc8. Review "
            f"scripts/output/266b_dominant_vs_histology1_discordance.csv."
        )
    if pct < CONCORDANCE_PASS:
        concordance_status = "soft_pass"
        log(f"  SOFT-PASS at {pct:.2f}% — building HOLD table {HOLD_DISCORDANCE} "
            f"for review-in-daylight; proceeding with merge plan.")
        sql_hold = f"""
            CREATE OR REPLACE TABLE {HOLD_DISCORDANCE} AS
            SELECT
              cpm.research_id                                     AS research_id,
              cpm.dominant_tumor_ajcc8_t_stage                    AS dominant_tumor_ajcc8_t_stage,
              tp.histology_1_t_stage_ajcc8                        AS histology_1_t_stage_ajcc8,
              cpm.tumor_stage_heterogeneous_t_ajcc8_flag          AS heterogeneous_t_flag,
              cpm.n_tumors_ajcc8_staged                           AS n_tumors_ajcc8_staged,
              {pct:.4f}                                           AS overall_concordance_pct,
              CURRENT_TIMESTAMP                                   AS captured_at,
              '266b'                                              AS source_script,
              'soft_pass'                                         AS gate_status
            FROM {CPM} AS cpm
            INNER JOIN {TPATH} AS tp
              ON CAST(tp.research_id AS VARCHAR) = cpm.research_id
            WHERE cpm.dominant_tumor_ajcc8_t_stage IS NOT NULL
              AND tp.histology_1_t_stage_ajcc8 IS NOT NULL
              AND cpm.dominant_tumor_ajcc8_t_stage <> tp.histology_1_t_stage_ajcc8
        """
        con.execute(sql_hold)
        comment_hold = (
            f"Script 266b (2026-04-17). HOLD table for soft-pass concordance "
            f"({pct:.2f}% < {CONCORDANCE_PASS}% but >= {CONCORDANCE_SOFT}%). "
            f"Each row is a patient where dominant_tumor_ajcc8_t_stage "
            f"(266b derivation) disagrees with tumor_pathology."
            f"histology_1_t_stage_ajcc8 (existing patient-level value). "
            f"For human review; does NOT block 266b apply."
        ).replace("'", "''")
        con.execute(f"COMMENT ON TABLE {HOLD_DISCORDANCE} IS '{comment_hold}'")
        n_hold = int(con.execute(f"SELECT COUNT(*) FROM {HOLD_DISCORDANCE}").fetchone()[0])
        log(f"  HOLD table written with {n_hold} discordance rows.")

    # Gate F: 65 ws views still queryable
    views = [r[0] for r in con.execute(f"""
        SELECT table_name FROM information_schema.views
         WHERE table_catalog='{PUBLICATION_DB}'
           AND table_schema='manuscript_workspace'
         ORDER BY table_name
    """).fetchall()]
    log(f"  smoke-checking {len(views)} views ...")
    rows = []
    n_ok = 0
    n_fail = 0
    for v in views:
        try:
            n = con.execute(
                f"SELECT COUNT(*) FROM {PUBLICATION_DB}.manuscript_workspace.\"{v}\""
            ).fetchone()[0]
            rows.append((v, "ok", n))
            n_ok += 1
        except Exception as e:
            msg = str(e).splitlines()[0][:300]
            rows.append((v, "error", msg))
            n_fail += 1
    with VIEW_SMOKE_CSV.open("w", newline="") as f:
        w = csv.writer(f)
        w.writerow(["view_name", "status", "row_count_or_error"])
        w.writerows(rows)
    log(f"  smoke result: ok={n_ok} error={n_fail}")
    if n_fail:
        broken = [r[0] for r in rows if r[1] == "error"][:10]
        raise SystemExit(f"View smoke check failed: {n_fail} broken: {broken}")

    return {
        "ctc_new_cols": len(CTC_NEW_COLUMNS),
        "cpm_new_cols": len(CPM_NEW_COLUMNS),
        "het_rows": n_het,
        "per_tumor_ajcc8_calculable_patients": n_pat,
        "dominant_vs_histology1_pct": pct,
        "concordance_status": concordance_status,
        "views_total": len(views), "views_ok": n_ok, "views_error": n_fail,
    }


# ---------------------------------------------------------------------------
# Driver
# ---------------------------------------------------------------------------
PHASES = {
    0: phase_0, 1: phase_1, 2: phase_2, 3: phase_3,
    4: phase_4, 5: phase_5, 6: phase_6, 7: phase_7,
}


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--apply", action="store_true",
                    help="Execute writes; default is dry-run.")
    ap.add_argument("--dry-run", action="store_true",
                    help="Explicit dry-run (default).")
    ap.add_argument("--phase", type=int, default=None,
                    help="Run a single phase (0..7). Phase 0 always runs first.")
    args = ap.parse_args()
    do_writes = bool(args.apply) and not bool(args.dry_run)

    if RUN_LOG.exists():
        RUN_LOG.unlink()
    log, fh = make_logger(RUN_LOG)
    t0 = time.time()
    try:
        log("=" * 78)
        log(f"# {SCRIPT_TAG} run")
        log(f"started_at: {utc_now()}")
        log(f"mode      : {'APPLY' if do_writes else 'DRY-RUN'}")
        log(f"phase     : {args.phase if args.phase is not None else 'all'}")

        con = connect_locked()
        log(f"connected to {PUBLICATION_DB}")

        results: dict = {"meta": {"mode": "APPLY" if do_writes else "DRY-RUN",
                                   "started_at": utc_now(),
                                   "script": SCRIPT_TAG}}

        if args.phase is not None:
            phase_list = [0, args.phase] if args.phase != 0 else [0]
        else:
            phase_list = list(PHASES.keys())

        for p in phase_list:
            if p == 7:
                results[f"phase_{p}"] = PHASES[p](con, log, do_writes, results)
            else:
                results[f"phase_{p}"] = PHASES[p](con, log, do_writes)

        if do_writes:
            ensure_audit_table(con)
            record_audit(
                con, SCRIPT_NUM, "266b_per_tumor_ajcc",
                "per_tumor_ajcc8_calculable_patients",
                count_before=0,
                count_after=int(results.get("phase_6", {}).get(
                    "per_tumor_ajcc8_calculable_patients", 0)),
                target_after=3900, status="OK",
                notes=("Per-tumor AJCC7+AJCC8 + CPM dominant + heterogeneity surface."))

        write_decision_log(DECISION_LOG, {
            "script": SCRIPT_TAG, "run_date": RUN_DATE,
            "mode": "APPLY" if do_writes else "DRY-RUN",
            "preflight_divergences": [],
            "results": results,
            "elapsed_seconds": round(time.time() - t0, 1),
        })

        if do_writes and 7 in phase_list:
            FINAL_JSON.write_text(
                json.dumps(results.get("phase_7", {}), indent=2, default=str)
            )
            p6 = results.get("phase_6", {})
            p7 = results.get("phase_7", {})
            summary = f"""# Script 266b — summary

- **Mode:** APPLY
- **CTC new columns:** {p7.get('ctc_new_cols')}
- **CPM new columns:** {p7.get('cpm_new_cols')}
- **tumor_stage_heterogeneity_v1 rows:** {p7.get('het_rows')}
- **Per-tumor AJCC8 calculable:** {p6.get('per_tumor_ajcc8_calculable_tumors')} tumors / {p6.get('per_tumor_ajcc8_calculable_patients')} patients
- **Per-tumor AJCC7 calculable:** {results.get('phase_3', {}).get('ajcc7_calculable')} tumors
- **Dominant vs histology_1 concordance:** {p6.get('dominant_vs_histology1_pct')}% ({p6.get('dominant_vs_histology1_n_concordant')}/{p6.get('dominant_vs_histology1_n_pairs')})
- **Heterogeneous T (AJCC8) patients:** {p6.get('n_pts_t_heterogeneous')}
- **Heterogeneous overall (AJCC8) patients:** {p6.get('n_pts_overall_heterogeneous')}
- **Concordance gate status:** {p7.get('concordance_status')}
- **Views smoke-checked:** {p7.get('views_ok')} / {p7.get('views_total')} OK
- **Run log:** scripts/output/266b_run_log.md
- **Decision log:** scripts/output/266b_decision_log.json
- **Final confirmation:** scripts/output/266b_final_confirmation.json
- **Discordance CSV:** scripts/output/266b_dominant_vs_histology1_discordance.csv
- **View smoke CSV:** scripts/output/266b_view_smoke_check.csv
"""
            SUMMARY_MD.write_text(summary)

        log(f"\nelapsed: {time.time() - t0:.1f}s")
        log("DONE")
        return 0
    except Exception as e:
        log(f"FATAL: {e!r}")
        log(traceback.format_exc())
        return 1
    finally:
        fh.close()


if __name__ == "__main__":
    sys.exit(main())
