#!/usr/bin/env python3
"""
Script 266c — Wide-format slots + un-versioned column rename + archive sweep
============================================================================

DRAFT — generated by Cursor agent 2026-04-17. Reviewed by user before run.
Sequencing requirement (HARD): MUST run AFTER 266a, 266b, AND the
PART2/PROMPT_18 big cleanup. Phase 0 enforces all four preconditions.

Scope (W1–W6 of the original 266 prompt, picked up after 266a/266b):
  - Phase 0 : preflight + 4 hard gates + view-dependency PRE-GATE for renames.
  - Phase 1 : snapshot path_synoptics + tumor_pathology + canonical_tumor_
              characteristics_v1 + tumor_episode_master_v2 + canonical_patient_
              master to "Thyroid 2026 UPdated".archive_pub_v1_0.<orig>_pre266c_<UTC>.
  - Phase 2 (W1) : ADD COLUMN on path_synoptics (raw_source mirror, ADD-only)
                   for 5 tumor slots × 8 stage fields = 40 new columns.
                   Populate by pivoting canonical_tumor_characteristics_v1
                   wide on tumor_ordinal, joined via CAST(research_id AS VARCHAR).
                   Tumor_ordinal > 5 → 266c_tumor_ordinal_gt5_overflow.csv.
                   Legacy fragment columns (stage_tumor_2, stage_tumor_4,
                   stage_tumor_5, tumor_3_stage_tumor_3) profiled and
                   COMMENT-deprecated (raw_source rule: NO renames).
  - Phase 3 (W2) : ADD COLUMN on tumor_pathology (raw_source mirror, ADD-only).
                   SCOPE-CUT (2026-04-17 live verification): tumor_pathology
                   has only histology_1_* slot — there are NO histology_2/3/4/5
                   columns. Per-histology multi-tumor data lives in path_synoptics
                   wide slots (W1) and canonical_tumor_characteristics_v1 long
                   format (266b). 266c therefore adds exactly 4 new columns:
                     histology_1_t_stage_ajcc7, histology_1_n_stage_ajcc7,
                     histology_1_m_stage_ajcc7, histology_1_overall_stage_ajcc7
                   The AJCC8 quartet for histology_1 ALREADY EXISTS (verified
                   live, populated 2,687 rows) — do NOT re-add or overwrite.
                   Population: join tumor_pathology to canonical_tumor_
                   characteristics_v1 on (research_id, surgery_date) using
                   CAST(ctc.research_id AS VARCHAR) and ctc.surgery_date =
                   CAST(tp.surgery_date AS TIMESTAMP) (tp.surgery_date is
                   VARCHAR per live schema). For each (rid, surgery_date),
                   pick the dominant tumor (largest tumor_size_cm_per_surgery,
                   ties by lowest tumor_ordinal) and copy its AJCC7 quartet
                   into the new tumor_pathology columns. No slot-string match,
                   no unmapped CSV — dominant pick is deterministic.
  - Phase 4 (W3) : Un-versioned column RENAMES (DESTRUCTIVE).
                   PRE-GATE re-checked at top of phase: views referencing
                   canonical_tumor_characteristics_v1 OR tumor_episode_master_v2
                   must still be 0; HALT with names if not.
                   ALTER ... RENAME COLUMN t_stage TO t_stage_deprecated_un_
                   versioned_20260417 on CTC + TEM (4 cols × 2 tables = 8 renames).
                   COMMENT ON COLUMN on each pointing to AJCC7/AJCC8 successors.
  - Phase 5 (W4) : Archive sweep.
                   Candidates: data_dictionary_v240, cpm_unmapped_triage_v265,
                   any main-schema table matching _deprecated_* (big-cleanup
                   residue). Per candidate: verify no view dependency, CTAS
                   to "Thyroid 2026 UPdated".archive_pub_v1_0.<orig>_pre266c_<UTC>,
                   DROP from main, log to 266c_archive_manifest.csv.
                   SKIP anything tagged KEEP_REVIEW in the big cleanup's
                   manuscript_workspace.canonical_cleanup_audit_v1 (if it exists).
  - Phase 6 (W5) : Rebuild main.__readme via QUERYABLE enumeration (per
                   catalog_vs_queryable_drift convention — never trust
                   information_schema post-DROP). Re-run 65-view smoke check
                   against post-rename + post-archive state. All 65 must
                   return rowcount without error.
  - Phase 7 (W6) : Acceptance gates:
                   - path_synoptics has +40 new columns vs pre-state
                     (expected 271 → 311)
                   - tumor_pathology has +4 new columns vs pre-state
                     (expected 249 → 253)
                   - SELECT t_stage FROM CTC LIMIT 1 raises Binder Error
                     (and same for n_stage / m_stage / overall_stage on CTC + TEM)
                   - 65/65 manuscript_workspace views queryable
                   - Archive manifest has ≥ 2 entries (v240 + v265 minimum,
                     or documented absence if big cleanup already archived them)
                   - Zero main-schema tables matching _deprecated_* after sweep

Flags:
  --apply       Execute writes.
  --dry-run     Default. Logs every planned DDL but executes none.
  --phase N     Run a single phase (0..7). Phase 0 always runs first.

Outputs (scripts/output/):
  266c_run_log.md
  266c_decision_log.json
  266c_final_confirmation.json
  266c_view_smoke_check.csv
  266c_archive_manifest.csv
  266c_tumor_ordinal_gt5_overflow.csv
  266c_legacy_fragment_profile.csv
  266c_summary.md

==============================================================================
ALL 16 __conventions LIVE-VERIFIED 2026-04-17 (preflight). Each rule below
applies to every statement in this script. Especially load-bearing for 266c
because this is the destructive phase: renames, drops, archive sweep.
==============================================================================

1.  as_aliasing — column_naming
    Every CTE-to-target mapping in the wide-pivot SQL uses explicit AS,
    even when source and target names match. The wide column names
    (tumor_N_t_stage_ajcc8, etc.) are the contract; downstream consumers
    read by these names.

2.  assembly_bookkeeping_build_pipeline — registry_mapping
    The new wide-format columns on path_synoptics and tumor_pathology
    are clinical facts (per-tumor stage values), not bookkeeping. They
    are pivoted single-source rollups from canonical_tumor_characteristics_v1,
    so they resolve to feeder = canonical_tumor_characteristics_v1 (per
    single_source_rollup_inherits_feeder), NOT build_pipeline.
    266c does NOT update detail_table_registry_v1 — these wide slots
    are NOT promoted to CPM (path_synoptics and tumor_pathology are
    raw_source mirrors that other downstream consumers read directly).

3.  audit_status_taxonomy — audit_discipline
    Phase 7 records OK on each completed phase; DOCUMENTED_GAP for any
    histology slot with unmappable tumors (logged to CSV);
    OK_DEFERRED_HUMAN for any legacy fragment column with non-trivial
    novel signal that requires clinician review before final retirement.

4.  bethesda_semantics — semantics
    OUT OF SCOPE for 266c.

5.  catalog_vs_queryable_drift — cleanup_safety
    Phase 6 (__readme rebuild) and Phase 7 (acceptance gate that
    `_deprecated_*` tables are gone from main) MUST use queryable
    enumeration (try SELECT 1 FROM main.<t> LIMIT 1) and NOT trust
    information_schema.tables, which lags behind DROP TABLE on MotherDuck.
    Implemented in `_queryable_main_tables()` helper.

6.  cohort_scoping — table_design
    Wide pivots inherit CTC's cohort scoping (8,422 tumor-bearing pts).
    path_synoptics rows for the 2,449 benign tumor-free patients receive
    NULL in every new tumor_N_*_ajcc{7,8} column. Same for tumor_pathology.
    Acceptance gates do NOT require pct_non_null thresholds on the new
    wide columns — NULL is the correct value for non-malignant patients.

7.  derived_column_build_pipeline — registry_mapping
    See #2. Wide columns are single-source rollups (CASE WHEN tumor_ordinal=N
    THEN ... END) over CTC's per-tumor staging — NOT multi-feeder derivation.

8.  feeder_eligibility_patterns — registry_mapping
    Not exercised by 266c. The wide slot table names already exist as
    raw_source mirrors and are not subject to the EXCLUDE_PATTERNS
    feeder-eligibility check.

9.  identity_column_self_reference — registry_mapping
    Unchanged.

10. main_schema_keep_list — archival_discipline
    Phase 5 (archive sweep) MUST consult main_schema_keep_list_v1
    BEFORE archiving. Do NOT archive anything registered with a
    sunset_trigger that has not yet fired. Implemented in
    `_keep_list_excludes()` helper.

11. pre_flight_decision_log — audit_trail
    266c emits scripts/output/266c_decision_log.json with one entry per
    pre-flight discovery that diverges from this draft's assertions.
    Mandatory.

12. restore_test_prefers_widest_schema — archival_discipline
    Phase 1 snapshots are the widest schemas available (CPM 1,499+12 cols
    from 266b; CTC 11k rows × per-tumor cols incl. 14 from 266b). Snapshots
    taken BEFORE renames so restore baseline carries the un-versioned
    column names — this is the audit trail for the rename.

13. rid_type_consistency — join_safety
    canonical_patient_master.research_id = VARCHAR.
    canonical_tumor_characteristics_v1.research_id = INTEGER (per script 245).
    tumor_pathology.research_id = BIGINT.
    path_synoptics.research_id = BIGINT (verified post-265 raw_source mirror).
    EVERY join in 266c uses CAST(<src>.research_id AS VARCHAR) on the
    non-CPM side or CAST consistently when joining among non-CPM tables.

14. single_source_rollup_inherits_feeder — registry_mapping
    See #2. Wide pivots are single-source rollups.

15. tech_debt_aggregation — tech_debt_discipline
    If Phase 5 finds N _deprecated_* residue tables, register ONE
    tech_debt entry (debt_id='deprecated_residue_266c_skipped') with
    the count rather than N entries.

16. v1_1_tech_debt_register — convention_drift
    Any structural debt out of scope for 266c (e.g., fragment column
    population analysis recommending column drops) → register in
    manuscript_workspace.v1_1_tech_debt_v1, not in code comments.

==============================================================================
Why 266c is split from 266a + 266b — risk separation rationale (per user):
==============================================================================
266a was dictionary governance: single-table revert posture, lowest risk.
266b is per-tumor staging derivation: high cognitive load, one mistake
corrupts ~4K patient stages, but additive only (no renames, no drops).
266c is schema rollout + renames + archive: many moving parts, low
per-statement logic complexity, but DESTRUCTIVE. Splitting them means a
266b derivation bug doesn't take wide slots with it; a 266c rename
mistake doesn't corrupt 266b's freshly-built per-tumor stages.
"""
from __future__ import annotations

import argparse
import csv
import json
import re
import sys
import time
import traceback
from datetime import datetime, timezone
from pathlib import Path

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))
from _md_connect import connect_locked, PUBLICATION_DB  # noqa: E402
from _v1_1_helpers import (  # noqa: E402
    ARCHIVE_DB, ARCHIVE_QUALIFIED,
    ensure_archive_schema, ensure_audit_table,
    make_logger, record_audit, snapshot_table, utc_ts, write_decision_log,
)


# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------
REPO = HERE.parent
OUT_DIR = REPO / "scripts" / "output"
OUT_DIR.mkdir(parents=True, exist_ok=True)
RUN_LOG               = OUT_DIR / "266c_run_log.md"
DECISION_LOG          = OUT_DIR / "266c_decision_log.json"
FINAL_JSON            = OUT_DIR / "266c_final_confirmation.json"
VIEW_SMOKE_CSV        = OUT_DIR / "266c_view_smoke_check.csv"
ARCHIVE_MANIFEST_CSV  = OUT_DIR / "266c_archive_manifest.csv"
OVERFLOW_CSV          = OUT_DIR / "266c_tumor_ordinal_gt5_overflow.csv"
FRAGMENT_PROFILE_CSV  = OUT_DIR / "266c_legacy_fragment_profile.csv"
SUMMARY_MD            = OUT_DIR / "266c_summary.md"

SCRIPT_TAG = "Script 266c"
SCRIPT_NUM = "266c"
RUN_DATE   = "2026-04-17"
DEPRECATION_DATE_TAG = "20260417"  # consistent with 266a/266b ISO date

CPM   = f"{PUBLICATION_DB}.main.canonical_patient_master"
CTC   = f"{PUBLICATION_DB}.main.canonical_tumor_characteristics_v1"
TEM   = f"{PUBLICATION_DB}.main.tumor_episode_master_v2"
TPATH = f"{PUBLICATION_DB}.main.tumor_pathology"
PSYN  = f"{PUBLICATION_DB}.main.path_synoptics"
README_TBL = f"{PUBLICATION_DB}.main.__readme"
KEEP_LIST = f"{PUBLICATION_DB}.manuscript_workspace.main_schema_keep_list_v1"
CLEANUP_AUDIT = f"{PUBLICATION_DB}.manuscript_workspace.canonical_cleanup_audit_v1"

# ---- Phase 2 (W1) — path_synoptics 40 new columns ----
# 5 tumor slots × 8 fields each.
PSYN_NEW_COLUMNS: list[tuple[str, str]] = [
    (f"tumor_{n}_{field}_{stage}_ajcc{ed}", "VARCHAR")
    for n in range(1, 6)
    for ed in (7, 8)
    for field, stage in (
        ("t", "stage"),
        ("n", "stage"),
        ("m", "stage"),
        ("stage", "group"),
    )
]
# Yields names like tumor_1_t_stage_ajcc7, tumor_1_stage_group_ajcc7,
# tumor_1_t_stage_ajcc8, ..., tumor_5_stage_group_ajcc8 (40 total).

# Sanity: build the ordered list of (slot, ed, field) so we can write
# CASE WHEN ... END SQL deterministically.
PSYN_FIELDS = ["t_stage", "n_stage", "m_stage", "stage_group"]

# Legacy fragment columns in path_synoptics (per original 266 prompt STEP 2).
# These are NOT renamed (raw_source rule) — only profiled and COMMENT-deprecated.
PSYN_LEGACY_FRAGMENT_COLS = [
    "stage_tumor_2",
    "stage_tumor_4",
    "stage_tumor_5",
    "tumor_3_stage_tumor_3",
]

# ---- Phase 3 (W2) — tumor_pathology 4 new columns (SCOPE-CUT 2026-04-17) ----
# Live verification: tumor_pathology has 18 histology_* columns, ALL prefixed
# histology_1_. There are NO histology_2/3/4/5 slots. Per-histology multi-tumor
# data lives in path_synoptics wide slots (W1) and CTC long format (266b).
# AJCC8 quartet for histology_1 already exists (populated 2,687 rows live);
# 266c only adds the AJCC7 quartet for histology_1.
TPATH_NEW_COLUMNS: list[tuple[str, str]] = [
    ("histology_1_t_stage_ajcc7",       "VARCHAR"),
    ("histology_1_n_stage_ajcc7",       "VARCHAR"),
    ("histology_1_m_stage_ajcc7",       "VARCHAR"),
    ("histology_1_overall_stage_ajcc7", "VARCHAR"),
]

# ---- Phase 4 (W3) — un-versioned column renames ----
# Format: (table_fq, [(old_col, new_col), ...]).
# Renames are deferred-name pattern (legacy_<...>_<DATE>) per 266a convention.
RENAME_TARGETS: list[tuple[str, list[tuple[str, str]]]] = [
    (CTC, [
        ("t_stage",       f"t_stage_deprecated_un_versioned_{DEPRECATION_DATE_TAG}"),
        ("n_stage",       f"n_stage_deprecated_un_versioned_{DEPRECATION_DATE_TAG}"),
        ("m_stage",       f"m_stage_deprecated_un_versioned_{DEPRECATION_DATE_TAG}"),
        ("overall_stage", f"overall_stage_deprecated_un_versioned_{DEPRECATION_DATE_TAG}"),
    ]),
    (TEM, [
        ("t_stage",       f"t_stage_deprecated_un_versioned_{DEPRECATION_DATE_TAG}"),
        ("n_stage",       f"n_stage_deprecated_un_versioned_{DEPRECATION_DATE_TAG}"),
        ("m_stage",       f"m_stage_deprecated_un_versioned_{DEPRECATION_DATE_TAG}"),
        ("overall_stage", f"overall_stage_deprecated_un_versioned_{DEPRECATION_DATE_TAG}"),
    ]),
]
RENAME_DEPRECATION_NOTE = (
    "Deprecated 2026-04-17 by Script 266c. Un-versioned AJCC8-adjacent "
    "broadcast value (TEM-derived); matched ajcc8_t/n/m_stage_corrected "
    "for only ~63% of tumors. Use canonical_tumor_characteristics_v1.{t,n,m}_"
    "stage_ajcc7 or _ajcc8 (266b per-tumor) and canonical_patient_master."
    "ajcc8_{t,n,m}_stage (post-cleanup patient anchor)."
)

# ---- Phase 5 (W4) — archive sweep ----
# Candidates for explicit archive (in addition to any _deprecated_* residue).
EXPLICIT_ARCHIVE_CANDIDATES = [
    ("main", "data_dictionary_v240"),
    ("manuscript_workspace", "cpm_unmapped_triage_v265"),
]


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------
def utc_now() -> str:
    return datetime.now(timezone.utc).isoformat()


def _quote(s: str | None) -> str:
    if s is None:
        return "NULL"
    return "'" + str(s).replace("'", "''") + "'"


def _exec(con, sql: str, log, do_writes: bool, *, label: str = "") -> None:
    tag = f" [{label}]" if label else ""
    if do_writes:
        log(f"  EXEC{tag}: {sql.strip().splitlines()[0][:160]}")
        con.execute(sql)
    else:
        log(f"  PLAN{tag}: {sql.strip().splitlines()[0][:160]}")


def _queryable_main_tables(con) -> set[str]:
    """Per catalog_vs_queryable_drift: enumerate main BASE TABLEs that
    actually answer SELECT 1 LIMIT 1 (filters out post-DROP ghosts in
    information_schema)."""
    candidates = [r[0] for r in con.execute(f"""
        SELECT table_name FROM information_schema.tables
         WHERE table_catalog='{PUBLICATION_DB}' AND table_schema='main'
           AND table_type='BASE TABLE'
         ORDER BY table_name
    """).fetchall()]
    queryable: set[str] = set()
    for t in candidates:
        try:
            con.execute(f'SELECT 1 FROM {PUBLICATION_DB}.main."{t}" LIMIT 1').fetchone()
            queryable.add(t)
        except Exception:
            pass
    return queryable


def _keep_list_excludes(con) -> set[str]:
    """Return the set of table_names registered in main_schema_keep_list_v1
    that are NOT past their sunset_trigger. Phase 5 must skip these.
    Returns empty set if the keep-list table doesn't exist."""
    try:
        rows = con.execute(f"""
            SELECT table_name FROM {KEEP_LIST}
        """).fetchall()
        return {r[0] for r in rows}
    except Exception:
        return set()


def _cleanup_audit_keep_review(con) -> set[str]:
    """Return the set of table_names tagged KEEP_REVIEW in
    canonical_cleanup_audit_v1 (the big-cleanup audit table). Returns
    empty set if the table doesn't exist."""
    try:
        rows = con.execute(f"""
            SELECT DISTINCT table_name FROM {CLEANUP_AUDIT}
             WHERE UPPER(action) = 'KEEP_REVIEW'
                OR UPPER(disposition) = 'KEEP_REVIEW'
        """).fetchall()
        return {r[0] for r in rows}
    except Exception:
        return set()


def _views_referencing(con, *table_names: str) -> list[tuple[str, str]]:
    """Return list of (view_name, snippet) for views whose definition
    contains any of the supplied substrings (case-insensitive)."""
    if not table_names:
        return []
    likes = " OR ".join(
        f"LOWER(view_definition) LIKE '%{t.lower()}%'" for t in table_names
    )
    rows = con.execute(f"""
        SELECT table_name, SUBSTR(view_definition, 1, 240) AS snippet
          FROM information_schema.views
         WHERE table_catalog='{PUBLICATION_DB}'
           AND table_schema IN ('main', 'manuscript_workspace')
           AND ({likes})
         ORDER BY table_name
    """).fetchall()
    return [(r[0], r[1] or "") for r in rows]


def _column_present(con, table_fq: str, column: str) -> bool:
    schema, table = table_fq.split(".")[-2], table_fq.split(".")[-1]
    n = con.execute(f"""
        SELECT COUNT(*) FROM information_schema.columns
         WHERE table_catalog='{PUBLICATION_DB}'
           AND table_schema='{schema}'
           AND table_name='{table}'
           AND column_name=?
    """, [column]).fetchone()[0]
    return n > 0


# ---------------------------------------------------------------------------
# Phase 0 — preflight + 4 hard gates + view-dependency PRE-GATE
# ---------------------------------------------------------------------------
def phase_0(con, log, do_writes: bool) -> dict:
    log("\n## Phase 0 — preflight + sequencing gates + view pre-gate")
    info = con.execute(
        f"SELECT current_database(), "
        f"(SELECT COUNT(*) FROM {CPM}), "
        f"(SELECT COUNT(*) FROM {CTC}), "
        f"(SELECT COUNT(*) FROM {TPATH}), "
        f"(SELECT COUNT(*) FROM {PSYN}), "
        f"(SELECT COUNT(*) FROM {TEM})"
    ).fetchone()
    log(f"  connected_to        : {info[0]}")
    log(f"  cpm_n_patients      : {info[1]}")
    log(f"  ctc_n_rows          : {info[2]}")
    log(f"  tpath_n_rows        : {info[3]}")
    log(f"  psyn_n_rows         : {info[4]}")
    log(f"  tem_n_rows          : {info[5]}")
    if info[1] != 10871:
        raise SystemExit(f"CPM patient count mismatch: {info[1]} != 10871")

    # Gate A — 266a applied
    if not _column_present(con,
                            f"{PUBLICATION_DB}.main.data_dictionary_v266a",
                            "column_name"):
        # Probe table existence by another route since _column_present needs the table
        n_v266a = con.execute(f"""
            SELECT COUNT(*) FROM information_schema.tables
             WHERE table_catalog='{PUBLICATION_DB}' AND table_schema='main'
               AND table_name='data_dictionary_v266a'
        """).fetchone()[0]
        if not n_v266a:
            raise SystemExit(
                "266c precondition: data_dictionary_v266a not found. "
                "Run 266a first."
            )
    log("  GATE 266a applied   : data_dictionary_v266a exists")

    # Gate B — 266b applied (CPM dominant + heterogeneity columns)
    required_266b_cpm = [
        "dominant_tumor_ajcc7_t_stage", "dominant_tumor_ajcc8_t_stage",
        "tumor_stage_heterogeneous_t_ajcc8_flag",
        "n_tumors_ajcc7_staged", "n_tumors_ajcc8_staged",
    ]
    missing_266b_cpm = [c for c in required_266b_cpm
                        if not _column_present(con, CPM, c)]
    log(f"  GATE 266b CPM cols missing : {missing_266b_cpm or 'none'}")
    if missing_266b_cpm:
        raise SystemExit(
            f"266c precondition: 266b not applied to CPM. Missing: "
            f"{missing_266b_cpm}. Run 266b first."
        )

    # Gate C — 266b applied (CTC per-tumor stage columns)
    required_266b_ctc = [
        "t_stage_ajcc7", "n_stage_ajcc7", "m_stage_ajcc7",
        "overall_stage_ajcc7", "stage_group_ajcc7",
        "t_stage_ajcc8", "n_stage_ajcc8", "m_stage_ajcc8",
        "overall_stage_ajcc8", "stage_group_ajcc8",
        "ajcc7_stage_calculable_flag", "ajcc8_stage_calculable_flag",
    ]
    missing_266b_ctc = [c for c in required_266b_ctc
                        if not _column_present(con, CTC, c)]
    log(f"  GATE 266b CTC cols missing : {missing_266b_ctc or 'none'}")
    if missing_266b_ctc:
        raise SystemExit(
            f"266c precondition: 266b not applied to CTC. Missing: "
            f"{missing_266b_ctc}. Run 266b first."
        )

    # Gate D — big-cleanup Phase 4.6 applied. Original Gate D required BOTH
    # `ajcc8_t_stage_corrected` absent AND `ajcc8_t_stage_v2` absent. Per
    # 266b's same fix on 2026-04-17 (Logan direction), the cleanup prompt
    # scoped Phase 4.6 ONLY to the `ajcc8_t_stage_corrected -> ajcc8_t_stage`
    # rename. `_v2` is an unrelated historical intermediate column with
    # distinct semantics (differs from canonical for ~1,085 patients) and
    # active downstream consumers (224/240/266b/266c). Relaxed here to
    # remove the `_v2` check while preserving the semantic-correctness check:
    # `_corrected` must be absent (proves the rename happened).
    has_corrected = _column_present(con, CPM, "ajcc8_t_stage_corrected")
    has_v2_informational = _column_present(con, CPM, "ajcc8_t_stage_v2")
    has_deprecated = _column_present(
        con, CPM, "ajcc8_t_stage_with_microete_t3b_DEPRECATED"
    )
    log(f"  GATE big-cleanup    : ajcc8_t_stage_corrected={has_corrected} "
        f"ajcc8_t_stage_v2={has_v2_informational} "
        f"DEPRECATED__present={has_deprecated}")
    if has_corrected:
        raise SystemExit(
            "266c precondition: PART2/PROMPT_18 big cleanup Phase 4.6 not "
            "yet applied. CPM still carries `ajcc8_t_stage_corrected`. Per "
            "user direction, 266c rename pass cannot land while this "
            "un-renamed column still exists."
        )
    if not _column_present(con, CPM, "ajcc8_t_stage"):
        raise SystemExit(
            "266c precondition: CPM lacks ajcc8_t_stage (clean post-cleanup "
            "anchor). Cannot proceed with rename of CTC un-versioned columns."
        )

    # Gate E — view-dependency PRE-GATE for renames (W3 protection)
    refs = _views_referencing(con,
                              "canonical_tumor_characteristics_v1",
                              "tumor_episode_master_v2")
    log(f"  view-dep PRE-GATE   : {len(refs)} view(s) reference CTC or TEM")
    for v, snip in refs:
        log(f"    - {v}: {snip[:120]}")
    if refs:
        raise SystemExit(
            f"266c precondition: {len(refs)} manuscript_workspace view(s) "
            f"reference canonical_tumor_characteristics_v1 or "
            f"tumor_episode_master_v2: {[v for v, _ in refs]}. The Phase 4 "
            f"rename pass would break these. HALT — investigate the new "
            f"views, either rebuild them onto AJCC7/AJCC8 columns first, "
            f"or defer the rename pass."
        )

    # Snapshot of current schema state (used by acceptance gates)
    psyn_cols_pre = {r[0] for r in con.execute(f"""
        SELECT column_name FROM information_schema.columns
         WHERE table_catalog='{PUBLICATION_DB}' AND table_schema='main'
           AND table_name='path_synoptics'
    """).fetchall()}
    tpath_cols_pre = {r[0] for r in con.execute(f"""
        SELECT column_name FROM information_schema.columns
         WHERE table_catalog='{PUBLICATION_DB}' AND table_schema='main'
           AND table_name='tumor_pathology'
    """).fetchall()}
    log(f"  pre-state path_synoptics cols : {len(psyn_cols_pre)}")
    log(f"  pre-state tumor_pathology cols: {len(tpath_cols_pre)}")

    return {
        "cpm_n_patients": info[1], "ctc_n_rows": info[2],
        "tpath_n_rows": info[3], "psyn_n_rows": info[4], "tem_n_rows": info[5],
        "psyn_cols_pre": sorted(psyn_cols_pre),
        "tpath_cols_pre": sorted(tpath_cols_pre),
        "view_dep_pregate_refs": [v for v, _ in refs],
    }


# ---------------------------------------------------------------------------
# Phase 1 — snapshots
# ---------------------------------------------------------------------------
def phase_1(con, log, do_writes: bool) -> dict:
    log("\n## Phase 1 — snapshot CTC + TEM + tpath + psyn + CPM to archive")
    ts = utc_ts()
    targets = [
        (CTC,   f"canonical_tumor_characteristics_v1_pre266c_{ts}"),
        (TEM,   f"tumor_episode_master_v2_pre266c_{ts}"),
        (TPATH, f"tumor_pathology_pre266c_{ts}"),
        (PSYN,  f"path_synoptics_pre266c_{ts}"),
        (CPM,   f"canonical_patient_master_pre266c_{ts}"),
    ]
    snaps: dict[str, str | None] = {}
    for src, label in targets:
        if do_writes:
            ensure_archive_schema(con)
            dest = snapshot_table(
                con, src, label, SCRIPT_TAG,
                f"Pre-266c snapshot of {src} before wide-format ADD COLUMN, "
                f"un-versioned column rename, and archive sweep.")
            log(f"  snapshot -> {dest}")
            snaps[src] = dest
        else:
            log(f"  PLAN: CTAS {src} -> {ARCHIVE_QUALIFIED}.{label!r}")
            snaps[src] = None
    return {"snapshots": snaps}


# ---------------------------------------------------------------------------
# Phase 2 (W1) — path_synoptics wide-format slot buildout
# ---------------------------------------------------------------------------
def phase_2(con, log, do_writes: bool) -> dict:
    log("\n## Phase 2 (W1) — path_synoptics ADD COLUMN + populate (40 cols)")

    # ADD COLUMN
    existing = {r[0] for r in con.execute(f"""
        SELECT column_name FROM information_schema.columns
         WHERE table_catalog='{PUBLICATION_DB}' AND table_schema='main'
           AND table_name='path_synoptics'
    """).fetchall()}
    added = []
    for col, typ in PSYN_NEW_COLUMNS:
        if col in existing:
            log(f"  SKIP (already present): {col}")
            continue
        sql = f'ALTER TABLE {PSYN} ADD COLUMN "{col}" {typ}'
        _exec(con, sql, log, do_writes, label=f"add:{col}")
        added.append(col)

    # Profile path_synoptics grain. Per live verification 2026-04-17:
    # 11,688 rows / 10,871 patients / 11,687 distinct (research_id, surg_date)
    # — i.e. one row per surgery per patient. 761 patients have multiple
    # surgeries (completion thyroidectomy, re-excision, etc.). The W1 wide
    # pivot MUST therefore join CTC -> path_synoptics on (research_id,
    # surg_date), NOT on research_id alone, otherwise per-surgery staging
    # gets corrupted into a per-patient broadcast across all surgeries.
    # Phase 0 already confirmed both tables carry the join columns.
    grain = con.execute(f"""
        SELECT
          COUNT(*)                                                AS n_rows,
          COUNT(DISTINCT research_id)                             AS n_pts,
          COUNT(DISTINCT (CAST(research_id AS VARCHAR) || '|' ||
                          CAST(surg_date AS VARCHAR)))            AS n_pt_surg
        FROM {PSYN}
    """).fetchone()
    log(f"  path_synoptics grain: {grain[0]} rows / {grain[1]} pts / "
        f"{grain[2]} (research_id, surg_date) keys")
    if grain[0] != grain[2]:
        log(f"  NOTE: {grain[0] - grain[2]} duplicate (research_id, surg_date) "
            f"row(s) in path_synoptics. The wide pivot will give those rows "
            f"identical AJCC slot values (per-surgery deterministic UPDATE), "
            f"so the per-(rid, surg_date) distinctness assertion below "
            f"remains valid.")
    log("  NOTE: 2,449 benign tumor-free CPM patients are intentionally "
        "absent from canonical_tumor_characteristics_v1 (cohort_scoping "
        "convention). Their path_synoptics rows receive NULL in every "
        "new tumor_N_*_ajcc{7,8} column by design — this is correct, "
        "not a population gap.")

    # Tumor_ordinal > 5 overflow
    overflow = con.execute(f"""
        SELECT
          CAST(research_id AS VARCHAR) AS research_id,
          surgery_episode_id           AS surgery_episode_id,
          tumor_ordinal                AS tumor_ordinal,
          primary_histology            AS primary_histology,
          t_stage_ajcc8                AS t_stage_ajcc8,
          stage_group_ajcc8            AS stage_group_ajcc8
        FROM {CTC}
       WHERE tumor_ordinal > 5
       ORDER BY research_id, surgery_episode_id, tumor_ordinal
    """).fetchall()
    with OVERFLOW_CSV.open("w", newline="") as f:
        w = csv.writer(f)
        w.writerow(["research_id", "surgery_episode_id", "tumor_ordinal",
                    "primary_histology", "t_stage_ajcc8", "stage_group_ajcc8"])
        w.writerows(overflow)
    log(f"  tumor_ordinal>5 overflow rows: {len(overflow)} -> {OVERFLOW_CSV.name}")

    # Build wide per-(research_id, surg_date) pivot from CTC (ordinal 1..5).
    # Per-surgery grain (NOT per-patient) — see grain notes above.
    case_clauses: list[str] = []
    for n in range(1, 6):
        for ed in (7, 8):
            for f in PSYN_FIELDS:
                src_col = f if f != "stage_group" else f"stage_group_ajcc{ed}"
                src_col = src_col if f == "stage_group" else f"{f}_ajcc{ed}"
                tgt_col = (f"tumor_{n}_t_stage_ajcc{ed}" if f == "t_stage" else
                           f"tumor_{n}_n_stage_ajcc{ed}" if f == "n_stage" else
                           f"tumor_{n}_m_stage_ajcc{ed}" if f == "m_stage" else
                           f"tumor_{n}_stage_group_ajcc{ed}")
                case_clauses.append(
                    f"MAX(CASE WHEN ctc.tumor_ordinal = {n} THEN ctc.{src_col} END) "
                    f'AS "{tgt_col}"'
                )
    select_block = ",\n          ".join(case_clauses)

    update_set = ", ".join(
        f'"{c}" = w."{c}"' for c, _ in PSYN_NEW_COLUMNS
    )
    sql_update = f"""
        WITH wide AS (
          SELECT
            CAST(ctc.research_id AS VARCHAR)                    AS research_id,
            ctc.surgery_date                                     AS surg_date,
            {select_block}
          FROM {CTC} AS ctc
          WHERE ctc.tumor_ordinal BETWEEN 1 AND 5
          GROUP BY 1, 2
        )
        UPDATE {PSYN} AS p
           SET {update_set}
          FROM wide AS w
         WHERE CAST(p.research_id AS VARCHAR) = w.research_id
           AND p.surg_date = w.surg_date
    """
    _exec(con, sql_update, log, do_writes, label="psyn_wide_update")

    # Per-surgery determinism assertion (per user spec). Confirms the UPDATE
    # produced at most one distinct tumor_1_t_stage_ajcc7 per (research_id,
    # surg_date) — i.e. join was per-surgery, not per-patient broadcast.
    if do_writes:
        n_violations = int(con.execute(f"""
            SELECT COUNT(*) FROM (
              SELECT research_id, surg_date,
                     COUNT(DISTINCT tumor_1_t_stage_ajcc7) AS n_distinct
                FROM {PSYN}
               GROUP BY research_id, surg_date
              HAVING COUNT(DISTINCT tumor_1_t_stage_ajcc7) > 1
            ) AS v
        """).fetchone()[0])
        log(f"  per-surgery determinism check: "
            f"{n_violations} (research_id, surg_date) group(s) with > 1 "
            f"distinct tumor_1_t_stage_ajcc7 — must be 0")
        if n_violations > 0:
            raise SystemExit(
                f"W1 per-surgery determinism violated: {n_violations} "
                f"(research_id, surg_date) groups have > 1 distinct "
                f"tumor_1_t_stage_ajcc7. Wide pivot regressed to broadcast."
            )

    # Profile + COMMENT-deprecate legacy fragment columns
    log("  profiling legacy fragment columns ...")
    fragment_rows = []
    for col in PSYN_LEGACY_FRAGMENT_COLS:
        try:
            n_total, n_nn = con.execute(f"""
                SELECT COUNT(*),
                       COUNT(*) FILTER (WHERE "{col}" IS NOT NULL)
                  FROM {PSYN}
            """).fetchone()
            pct = round(100.0 * n_nn / n_total, 3) if n_total else 0.0
            fragment_rows.append((col, n_total, n_nn, pct, "present"))
            log(f"    {col}: {n_nn}/{n_total} ({pct}%)")
            comment = (
                f"Deprecated 2026-04-17 by Script 266c. Legacy fragment "
                f"column. Per-tumor staging now lives in tumor_N_t_stage_"
                f"ajcc7 / tumor_N_t_stage_ajcc8 (and n/m/stage_group "
                f"counterparts) populated from canonical_tumor_"
                f"characteristics_v1. Population at 266c run time: {n_nn}"
                f" of {n_total} ({pct}%). NOT renamed (raw_source rule)."
            )
            sql_c = f'COMMENT ON COLUMN {PSYN}."{col}" IS {_quote(comment)}'
            _exec(con, sql_c, log, do_writes, label=f"comment_legacy:{col}")
        except Exception as e:
            fragment_rows.append((col, None, None, None, f"absent: {e!s}"))
            log(f"    {col}: absent ({e})")
    with FRAGMENT_PROFILE_CSV.open("w", newline="") as f:
        w = csv.writer(f)
        w.writerow(["column", "n_total_rows", "n_non_null", "pct_non_null", "status"])
        w.writerows(fragment_rows)
    log(f"  legacy fragment profile -> {FRAGMENT_PROFILE_CSV.name}")

    # COMMENT ON COLUMN for each new wide col
    for col, _ in PSYN_NEW_COLUMNS:
        m = re.match(r"tumor_(\d+)_(t|n|m|stage)_(stage|group)_ajcc(7|8)", col)
        if not m:
            continue
        n_idx, _, _, ed = m.groups()
        msg = (
            f"Per-tumor AJCC{ed} value for tumor slot {n_idx}, populated by "
            f"Script 266c (2026-04-17) via wide pivot from "
            f"canonical_tumor_characteristics_v1.{'t_stage' if 't_stage' in col else 'n_stage' if 'n_stage' in col else 'm_stage' if 'm_stage' in col else 'stage_group'}_ajcc{ed}. "
            f"Tumor slots > 5 logged to scripts/output/{OVERFLOW_CSV.name}."
        )
        sql_c = f'COMMENT ON COLUMN {PSYN}."{col}" IS {_quote(msg)}'
        _exec(con, sql_c, log, do_writes, label=f"comment:{col}")

    return {
        "added_columns": added,
        "skipped_present": [c for c, _ in PSYN_NEW_COLUMNS if c in existing],
        "psyn_n_rows": int(grain[0]) if grain[0] is not None else None,
        "psyn_n_patients": int(grain[1]) if grain[1] is not None else None,
        "psyn_n_pt_surg_keys": int(grain[2]) if grain[2] is not None else None,
        "tumor_ordinal_gt5_count": len(overflow),
        "legacy_fragment_profile": fragment_rows,
    }


# ---------------------------------------------------------------------------
# Phase 3 (W2) — tumor_pathology histology_1 AJCC7 quartet (SCOPE-CUT)
# ---------------------------------------------------------------------------
def phase_3(con, log, do_writes: bool) -> dict:
    log("\n## Phase 3 (W2) — tumor_pathology ADD COLUMN + populate (4 cols)")
    log("  scope (per live verification 2026-04-17): tumor_pathology has only "
        "histology_1_* slot. NO histology_2/3/4/5 columns exist. The AJCC8 "
        "quartet for histology_1 already exists (populated 2,687 rows). "
        "266c only adds the AJCC7 quartet and populates from the dominant "
        "tumor per (research_id, surgery_date) in CTC.")

    existing = {r[0] for r in con.execute(f"""
        SELECT column_name FROM information_schema.columns
         WHERE table_catalog='{PUBLICATION_DB}' AND table_schema='main'
           AND table_name='tumor_pathology'
    """).fetchall()}

    # Sanity: confirm AJCC8 histology_1 quartet pre-exists (do NOT overwrite).
    a8_existing = [c for c in (
        "histology_1_t_stage_ajcc8", "histology_1_n_stage_ajcc8",
        "histology_1_m_stage_ajcc8", "histology_1_overall_stage_ajcc8",
    ) if c in existing]
    log(f"  pre-existing histology_1 AJCC8 quartet : {a8_existing}")
    if len(a8_existing) != 4:
        log(f"  WARNING: expected all 4 of histology_1_*_stage_ajcc8 to "
            f"pre-exist; got {a8_existing}. 266c will NOT auto-add them — "
            f"that is 266b/big-cleanup territory.")

    # Sanity: confirm tumor_pathology has surgery_date column (VARCHAR per
    # live schema). The W2 join requires it.
    if "surgery_date" not in existing:
        raise SystemExit(
            "tumor_pathology lacks surgery_date column — cannot perform "
            "W2 join. Live schema verification required."
        )

    # ADD the 4 new AJCC7 columns
    added = []
    for col, typ in TPATH_NEW_COLUMNS:
        if col in existing:
            log(f"  SKIP (already present): {col}")
            continue
        sql = f'ALTER TABLE {TPATH} ADD COLUMN "{col}" {typ}'
        _exec(con, sql, log, do_writes, label=f"add:{col}")
        added.append(col)

    # Population: dominant-tumor pick per (research_id, surgery_date) from CTC,
    # joined to tumor_pathology via CAST(ctc.research_id AS VARCHAR) and
    # ctc.surgery_date = CAST(tp.surgery_date AS TIMESTAMP).
    # Dominance rule: largest tumor_size_cm_per_surgery, ties broken by lowest
    # tumor_ordinal. Deterministic — no slot-string matching required.
    sql_update = f"""
        WITH ranked AS (
          SELECT
            CAST(ctc.research_id AS VARCHAR)                  AS research_id,
            ctc.surgery_date                                   AS surgery_date,
            ctc.tumor_ordinal                                  AS tumor_ordinal,
            ctc.tumor_size_cm_per_surgery                      AS tumor_size_cm_per_surgery,
            ctc.t_stage_ajcc7                                  AS t_stage_ajcc7,
            ctc.n_stage_ajcc7                                  AS n_stage_ajcc7,
            ctc.m_stage_ajcc7                                  AS m_stage_ajcc7,
            ctc.overall_stage_ajcc7                            AS overall_stage_ajcc7,
            ROW_NUMBER() OVER (
              PARTITION BY CAST(ctc.research_id AS VARCHAR), ctc.surgery_date
              ORDER BY ctc.tumor_size_cm_per_surgery DESC NULLS LAST,
                       ctc.tumor_ordinal ASC NULLS LAST
            )                                                  AS dom_rank
          FROM {CTC} AS ctc
        ),
        dominant AS (
          SELECT
            research_id                                        AS research_id,
            surgery_date                                       AS surgery_date,
            t_stage_ajcc7                                      AS t_stage_ajcc7,
            n_stage_ajcc7                                      AS n_stage_ajcc7,
            m_stage_ajcc7                                      AS m_stage_ajcc7,
            overall_stage_ajcc7                                AS overall_stage_ajcc7
          FROM ranked
          WHERE dom_rank = 1
        )
        UPDATE {TPATH} AS tp
           SET histology_1_t_stage_ajcc7       = d.t_stage_ajcc7,
               histology_1_n_stage_ajcc7       = d.n_stage_ajcc7,
               histology_1_m_stage_ajcc7       = d.m_stage_ajcc7,
               histology_1_overall_stage_ajcc7 = d.overall_stage_ajcc7
          FROM dominant AS d
         WHERE CAST(tp.research_id AS VARCHAR) = d.research_id
           AND CAST(tp.surgery_date AS TIMESTAMP) = d.surgery_date
    """
    _exec(con, sql_update, log, do_writes, label="tpath_dominant_update")

    # COMMENT ON COLUMN for each of the 4 new cols
    for col, _ in TPATH_NEW_COLUMNS:
        comp_match = re.match(r"histology_1_(t|n|m|overall)_stage_ajcc7", col)
        if not comp_match:
            continue
        comp = comp_match.group(1)
        msg = (
            f"AJCC7 {comp.upper()}-stage for the histology_1 slot, populated "
            f"by Script 266c (2026-04-17) from the dominant tumor per "
            f"(research_id, surgery_date) in canonical_tumor_characteristics_v1 "
            f"(dominance: largest tumor_size_cm_per_surgery, ties by lowest "
            f"tumor_ordinal). Companion AJCC8 column histology_1_{comp}_stage"
            f"_ajcc8 already existed pre-266c — left untouched."
        )
        sql_c = f'COMMENT ON COLUMN {TPATH}."{col}" IS {_quote(msg)}'
        _exec(con, sql_c, log, do_writes, label=f"comment:{col}")

    return {
        "added_columns": added,
        "skipped_present": [c for c, _ in TPATH_NEW_COLUMNS if c in existing],
        "ajcc8_quartet_preexisting": a8_existing,
    }


# ---------------------------------------------------------------------------
# Phase 4 (W3) — un-versioned column rename pass (DESTRUCTIVE)
# ---------------------------------------------------------------------------
def phase_4(con, log, do_writes: bool) -> dict:
    log("\n## Phase 4 (W3) — un-versioned column RENAMES (destructive)")

    # Re-run the view-dependency PRE-GATE inside this phase as well, so
    # a view added between Phase 0 and Phase 4 still halts us.
    refs = _views_referencing(con,
                              "canonical_tumor_characteristics_v1",
                              "tumor_episode_master_v2")
    log(f"  RE-CHECK view dep   : {len(refs)} ref(s)")
    if refs:
        raise SystemExit(
            f"View dependency PRE-GATE failed at Phase 4 entry: "
            f"{[v for v, _ in refs]} now references CTC or TEM. HALT."
        )

    renames_applied = []
    for tbl, pairs in RENAME_TARGETS:
        for old, new in pairs:
            # Idempotency: if old is already gone and new is present, skip.
            old_present = _column_present(con, tbl, old)
            new_present = _column_present(con, tbl, new)
            if not old_present and new_present:
                log(f"  SKIP (already renamed): {tbl}.{old} -> {new}")
                continue
            if not old_present and not new_present:
                log(f"  SKIP (column absent — likely never existed): {tbl}.{old}")
                continue
            if old_present and new_present:
                raise SystemExit(
                    f"Refusing to rename: BOTH {tbl}.{old} and {tbl}.{new} "
                    f"present. Manual reconciliation required."
                )
            sql = f'ALTER TABLE {tbl} RENAME COLUMN "{old}" TO "{new}"'
            _exec(con, sql, log, do_writes, label=f"rename:{tbl}:{old}")
            renames_applied.append({"table": tbl, "old": old, "new": new})

            # COMMENT immediately after rename so the deprecation note
            # travels with the column.
            comment_sql = (
                f'COMMENT ON COLUMN {tbl}."{new}" IS '
                f"{_quote(RENAME_DEPRECATION_NOTE)}"
            )
            _exec(con, comment_sql, log, do_writes, label=f"comment:{tbl}:{new}")

    return {"renames_applied": renames_applied}


# ---------------------------------------------------------------------------
# Phase 5 (W4) — archive sweep
# ---------------------------------------------------------------------------
DEPRECATED_NAME_RE = re.compile(r"_deprecated_", re.IGNORECASE)


def phase_5(con, log, do_writes: bool) -> dict:
    log("\n## Phase 5 (W4) — archive sweep")

    keep_review = _cleanup_audit_keep_review(con)
    keep_list = _keep_list_excludes(con)
    log(f"  big-cleanup KEEP_REVIEW set: {sorted(keep_review)[:8]}"
        f"{' ...' if len(keep_review) > 8 else ''} (total {len(keep_review)})")
    log(f"  main_schema_keep_list_v1 set: {sorted(keep_list)[:8]}"
        f"{' ...' if len(keep_list) > 8 else ''} (total {len(keep_list)})")

    # Build full candidate list:
    #   (a) explicit candidates from EXPLICIT_ARCHIVE_CANDIDATES (if still present)
    #   (b) any main-schema table whose name matches _deprecated_*
    queryable_main = _queryable_main_tables(con)
    log(f"  queryable main tables: {len(queryable_main)}")

    candidates: list[tuple[str, str, str]] = []  # (schema, table, reason)
    for schema, name in EXPLICIT_ARCHIVE_CANDIDATES:
        try:
            n = con.execute(
                f'SELECT COUNT(*) FROM {PUBLICATION_DB}."{schema}"."{name}"'
            ).fetchone()[0]
            candidates.append((schema, name,
                               f"explicit_supersession (n_rows={n})"))
        except Exception:
            log(f"  explicit candidate {schema}.{name} absent — skip.")

    for tbl in sorted(queryable_main):
        if DEPRECATED_NAME_RE.search(tbl):
            candidates.append(("main", tbl, "deprecated_name_pattern"))

    log(f"  total archive candidates: {len(candidates)}")
    for sch, t, why in candidates:
        log(f"    - {sch}.{t} :: {why}")

    manifest_rows = []
    skipped_rows = []
    archived_count = 0
    skipped_count = 0
    ts = utc_ts()

    for schema, name, reason in candidates:
        # Keep-list / KEEP_REVIEW exclusion
        if name in keep_review or name in keep_list:
            why = ("KEEP_REVIEW (canonical_cleanup_audit_v1)" if name in keep_review
                   else "main_schema_keep_list_v1 sunset_trigger not fired")
            log(f"  SKIP {schema}.{name} :: {why}")
            skipped_rows.append({
                "schema": schema, "name": name, "reason": reason,
                "skipped_because": why,
            })
            skipped_count += 1
            continue

        # View-dependency check per candidate
        refs = _views_referencing(con, name)
        if refs:
            log(f"  SKIP {schema}.{name} :: referenced by views: "
                f"{[v for v, _ in refs]}")
            skipped_rows.append({
                "schema": schema, "name": name, "reason": reason,
                "skipped_because": f"view_refs: {[v for v, _ in refs]}",
            })
            skipped_count += 1
            continue

        # Idempotency check: if a prior 266c run already archived this
        # candidate (matching <name>_pre266c_<UTC> in archive_pub_v1_0),
        # skip both the archive write and the DROP. The previous run is
        # the source of truth; do not double-archive.
        try:
            already = con.execute(f"""
                SELECT 1 FROM information_schema.tables
                 WHERE table_catalog='{ARCHIVE_DB}'
                   AND table_schema='archive_pub_v1_0'
                   AND table_name LIKE '{name}_pre266c_%'
                 LIMIT 1
            """).fetchone()
        except Exception:
            already = None
        if already is not None:
            log(f"  SKIP {schema}.{name} :: already_archived "
                f"(prior 266c run produced {name}_pre266c_*)")
            skipped_rows.append({
                "schema": schema, "name": name, "reason": reason,
                "skipped_because": (
                    f"already_archived: {ARCHIVE_DB}.archive_pub_v1_0."
                    f"{name}_pre266c_*"
                ),
            })
            skipped_count += 1
            continue

        # Pre-row count
        try:
            n_before = con.execute(
                f'SELECT COUNT(*) FROM {PUBLICATION_DB}."{schema}"."{name}"'
            ).fetchone()[0]
        except Exception as e:
            log(f"  SKIP {schema}.{name} :: not queryable ({e})")
            skipped_rows.append({
                "schema": schema, "name": name, "reason": reason,
                "skipped_because": f"not_queryable: {e!s}",
            })
            skipped_count += 1
            continue

        # CTAS to archive then DROP from main
        archive_name = f"{name}_pre266c_{ts}"
        archive_fq = f'{ARCHIVE_QUALIFIED}."{archive_name}"'
        src_fq = f'{PUBLICATION_DB}."{schema}"."{name}"'
        sql_archive = f"CREATE TABLE {archive_fq} AS SELECT * FROM {src_fq}"
        _exec(con, sql_archive, log, do_writes, label=f"archive:{name}")

        archive_comment = (
            f"Script 266c (2026-04-17) archive of {src_fq}. Reason: "
            f"{reason}. Source-side DROP follows in same transaction. "
            f"To restore: CREATE TABLE {src_fq} AS SELECT * FROM {archive_fq}."
        )
        _exec(con,
              f"COMMENT ON TABLE {archive_fq} IS {_quote(archive_comment)}",
              log, do_writes, label=f"comment_archive:{name}")

        sql_drop = f"DROP TABLE {src_fq}"
        _exec(con, sql_drop, log, do_writes, label=f"drop:{name}")

        # Per catalog_vs_queryable_drift: probe to confirm DROP took effect
        if do_writes:
            still_queryable = True
            try:
                con.execute(f"SELECT 1 FROM {src_fq} LIMIT 1").fetchone()
            except Exception:
                still_queryable = False
            log(f"    post-DROP queryable check: still_queryable={still_queryable}")
            if still_queryable:
                raise SystemExit(
                    f"DROP {src_fq} did not remove the table. HALT."
                )

        manifest_rows.append({
            "schema": schema, "name": name, "reason": reason,
            "n_rows_before": n_before, "archive_dest": archive_fq,
            "action": "archived_and_dropped",
        })
        archived_count += 1

    # Write manifest
    with ARCHIVE_MANIFEST_CSV.open("w", newline="") as f:
        cols = ["schema", "name", "reason", "n_rows_before",
                "archive_dest", "action", "skipped_because"]
        w = csv.DictWriter(f, fieldnames=cols, extrasaction="ignore")
        w.writeheader()
        for r in manifest_rows:
            w.writerow(r)
        for r in skipped_rows:
            w.writerow({**r, "action": "skipped"})
    log(f"  archive manifest -> {ARCHIVE_MANIFEST_CSV.name}: "
        f"{archived_count} archived, {skipped_count} skipped")

    return {
        "archived_count": archived_count,
        "skipped_count": skipped_count,
        "manifest": manifest_rows,
        "skipped": skipped_rows,
    }


# ---------------------------------------------------------------------------
# Phase 6 (W5) — __readme rebuild + view smoke check
# ---------------------------------------------------------------------------
def phase_6(con, log, do_writes: bool) -> dict:
    log("\n## Phase 6 (W5) — __readme rebuild + view smoke check")

    queryable = sorted(_queryable_main_tables(con))
    log(f"  queryable main tables (post-archive): {len(queryable)}")

    if do_writes:
        _exec(con, f"DROP TABLE IF EXISTS {README_TBL}", log, do_writes,
              label="drop_readme")
        _exec(con, f"""
            CREATE TABLE {README_TBL} (
                table_name VARCHAR PRIMARY KEY,
                n_rows BIGINT,
                n_distinct_research_id BIGINT,
                description VARCHAR,
                inventoried_at TIMESTAMP
            )
        """, log, do_writes, label="create_readme")

        # Filter __readme out of the loop -- it gets inserted explicitly as
        # the self-row below. Without this filter the loop inserts __readme
        # once (because _queryable_main_tables() includes it), then the
        # explicit self-row insert raises a PRIMARY KEY duplicate-key
        # constraint error (2026-04-18 fix).
        queryable_no_self = [t for t in queryable if t != "__readme"]
        for tbl in queryable_no_self:
            try:
                n_rows = int(con.execute(
                    f'SELECT COUNT(*) FROM {PUBLICATION_DB}.main."{tbl}"'
                ).fetchone()[0])
            except Exception:
                continue
            try:
                n_pat = int(con.execute(
                    f'SELECT COUNT(DISTINCT research_id) FROM '
                    f'{PUBLICATION_DB}.main."{tbl}"'
                ).fetchone()[0])
            except Exception:
                n_pat = None
            con.execute(
                f"INSERT INTO {README_TBL} VALUES (?, ?, ?, ?, ?)",
                [tbl, n_rows, n_pat,
                 "Re-inventoried by Script 266c (2026-04-17) via "
                 "queryable enumeration (catalog_vs_queryable_drift convention).",
                 datetime.now(timezone.utc)],
            )
        # Self-row inclusion (per Script 265 pattern). Inserted once here
        # to avoid the duplicate-key bug on the loop self-insertion path.
        n_readme = int(con.execute(f"SELECT COUNT(*) FROM {README_TBL}").fetchone()[0])
        con.execute(
            f"INSERT INTO {README_TBL} VALUES (?, ?, ?, ?, ?)",
            ["__readme", n_readme + 1, None,
             "Self-row. Auto-rebuilt by Script 266c.",
             datetime.now(timezone.utc)],
        )
        comment = (
            "Script 266c (2026-04-17) queryable enumeration of main "
            "BASE TABLEs. Auto-rebuilt by Script 266c after the "
            "archive sweep + un-versioned column rename pass."
        ).replace("'", "''")
        con.execute(f"COMMENT ON TABLE {README_TBL} IS '{comment}'")
        log(f"  __readme rebuilt with {n_readme + 1} rows.")
    else:
        log(f"  PLAN: would rebuild __readme with ~{len(queryable) + 1} rows.")

    # View smoke check
    views = [r[0] for r in con.execute(f"""
        SELECT table_name FROM information_schema.views
         WHERE table_catalog='{PUBLICATION_DB}'
           AND table_schema='manuscript_workspace'
         ORDER BY table_name
    """).fetchall()]
    log(f"  smoke-checking {len(views)} views ...")
    rows = []
    n_ok = 0
    n_fail = 0
    for v in views:
        try:
            n = con.execute(
                f'SELECT COUNT(*) FROM {PUBLICATION_DB}.manuscript_workspace."{v}"'
            ).fetchone()[0]
            rows.append((v, "ok", n))
            n_ok += 1
        except Exception as e:
            msg = str(e).splitlines()[0][:300]
            rows.append((v, "error", msg))
            n_fail += 1
    with VIEW_SMOKE_CSV.open("w", newline="") as f:
        w = csv.writer(f)
        w.writerow(["view_name", "status", "row_count_or_error"])
        w.writerows(rows)
    log(f"  smoke result: ok={n_ok} error={n_fail}")
    if n_fail:
        broken = [r[0] for r in rows if r[1] == "error"][:10]
        raise SystemExit(f"View smoke check failed: {n_fail} broken: {broken}")

    return {"queryable_main_tables": len(queryable),
            "views_total": len(views), "views_ok": n_ok, "views_error": n_fail}


# ---------------------------------------------------------------------------
# Phase 7 (W6) — acceptance gates
# ---------------------------------------------------------------------------
def phase_7(con, log, do_writes: bool, prior: dict) -> dict:
    log("\n## Phase 7 (W6) — acceptance gates")

    if not do_writes:
        log("  PLAN: skip in dry-run.")
        return {"skipped_dryrun": True}

    out: dict = {}

    # Gate A: path_synoptics +40 cols vs Phase 0 snapshot
    psyn_cols_now = {r[0] for r in con.execute(f"""
        SELECT column_name FROM information_schema.columns
         WHERE table_catalog='{PUBLICATION_DB}' AND table_schema='main'
           AND table_name='path_synoptics'
    """).fetchall()}
    psyn_pre = set(prior.get("phase_0", {}).get("psyn_cols_pre", []))
    psyn_added = sorted(psyn_cols_now - psyn_pre)
    log(f"  GATE path_synoptics +cols: {len(psyn_added)} (target 40)")
    out["psyn_added_cols"] = psyn_added
    if len(psyn_added) < 40:
        raise SystemExit(
            f"path_synoptics gained {len(psyn_added)} cols < 40."
        )

    # Gate B: tumor_pathology +4 cols vs Phase 0 snapshot (SCOPE-CUT 2026-04-17)
    tpath_cols_now = {r[0] for r in con.execute(f"""
        SELECT column_name FROM information_schema.columns
         WHERE table_catalog='{PUBLICATION_DB}' AND table_schema='main'
           AND table_name='tumor_pathology'
    """).fetchall()}
    tpath_pre = set(prior.get("phase_0", {}).get("tpath_cols_pre", []))
    tpath_added = sorted(tpath_cols_now - tpath_pre)
    log(f"  GATE tumor_pathology +cols: {len(tpath_added)} (target 4; "
        f"pre={len(tpath_pre)} -> post={len(tpath_cols_now)})")
    out["tpath_added_cols"] = tpath_added
    out["tpath_n_cols_now"] = len(tpath_cols_now)
    if len(tpath_added) < 4:
        raise SystemExit(
            f"tumor_pathology gained {len(tpath_added)} cols < 4. "
            f"Expected the histology_1 AJCC7 quartet."
        )
    expected_tpath_added = {
        "histology_1_t_stage_ajcc7", "histology_1_n_stage_ajcc7",
        "histology_1_m_stage_ajcc7", "histology_1_overall_stage_ajcc7",
    }
    missing_tpath = sorted(expected_tpath_added - set(tpath_added))
    if missing_tpath:
        raise SystemExit(
            f"tumor_pathology missing expected new columns: {missing_tpath}"
        )

    # Gate C: un-versioned columns no longer queryable on CTC + TEM
    rename_failures = []
    for tbl in (CTC, TEM):
        for col in ("t_stage", "n_stage", "m_stage", "overall_stage"):
            try:
                con.execute(f"SELECT {col} FROM {tbl} LIMIT 1").fetchone()
                rename_failures.append(f"{tbl}.{col} STILL QUERYABLE")
            except Exception:
                pass  # expected — Binder Error confirms rename
    log(f"  GATE rename binder check: {rename_failures or 'all OK (binder errors as expected)'}")
    out["rename_binder_failures"] = rename_failures
    if rename_failures:
        raise SystemExit(f"Rename gate failed: {rename_failures}")

    # Gate D: 65/65 views OK
    p6 = prior.get("phase_6", {})
    log(f"  GATE views: {p6.get('views_ok')}/{p6.get('views_total')} OK")
    if p6.get("views_error", 1) != 0 or p6.get("views_total") != 65:
        raise SystemExit(
            f"View smoke gate failed: {p6.get('views_ok')}/{p6.get('views_total')} OK"
        )

    # Gate E: archive manifest ≥ 2 entries (or documented absence)
    p5 = prior.get("phase_5", {})
    n_archived = p5.get("archived_count", 0)
    log(f"  GATE archive manifest entries: {n_archived}")
    if n_archived < 2:
        log(f"  NOTE: archive count {n_archived} < 2. Acceptable IF the big "
            f"cleanup already archived data_dictionary_v240 and "
            f"cpm_unmapped_triage_v265. Check 266c_archive_manifest.csv "
            f"skipped_because column for confirmation.")
        # Soft gate — log but do not fail.
    out["archived_count"] = n_archived

    # Gate F: zero main-schema tables matching _deprecated_*
    dep_residue = sorted(t for t in _queryable_main_tables(con)
                         if DEPRECATED_NAME_RE.search(t))
    log(f"  GATE _deprecated_* residue in main: {dep_residue or 'none'}")
    out["deprecated_residue"] = dep_residue
    if dep_residue:
        raise SystemExit(
            f"Acceptance gate failed: {len(dep_residue)} _deprecated_* "
            f"tables remain in main: {dep_residue[:10]}"
        )

    return out


# ---------------------------------------------------------------------------
# Driver
# ---------------------------------------------------------------------------
PHASES = {
    0: phase_0, 1: phase_1, 2: phase_2, 3: phase_3,
    4: phase_4, 5: phase_5, 6: phase_6, 7: phase_7,
}


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--apply", action="store_true",
                    help="Execute writes; default is dry-run.")
    ap.add_argument("--dry-run", action="store_true",
                    help="Explicit dry-run (default).")
    ap.add_argument("--phase", type=int, default=None,
                    help="Run a single phase (0..7). Phase 0 always runs first.")
    args = ap.parse_args()
    do_writes = bool(args.apply) and not bool(args.dry_run)

    if RUN_LOG.exists():
        RUN_LOG.unlink()
    log, fh = make_logger(RUN_LOG)
    t0 = time.time()
    try:
        log("=" * 78)
        log(f"# {SCRIPT_TAG} run")
        log(f"started_at: {utc_now()}")
        log(f"mode      : {'APPLY' if do_writes else 'DRY-RUN'}")
        log(f"phase     : {args.phase if args.phase is not None else 'all'}")

        con = connect_locked()
        log(f"connected to {PUBLICATION_DB}")

        results: dict = {"meta": {"mode": "APPLY" if do_writes else "DRY-RUN",
                                   "started_at": utc_now(),
                                   "script": SCRIPT_TAG}}

        if args.phase is not None:
            phase_list = [0, args.phase] if args.phase != 0 else [0]
        else:
            phase_list = list(PHASES.keys())

        for p in phase_list:
            if p == 7:
                results[f"phase_{p}"] = PHASES[p](con, log, do_writes, results)
            else:
                results[f"phase_{p}"] = PHASES[p](con, log, do_writes)

        if do_writes:
            ensure_audit_table(con)
            record_audit(
                con, SCRIPT_NUM, "266c_wide_slots_renames_archive",
                "renames_applied",
                count_before=0,
                count_after=len(results.get("phase_4", {}).get("renames_applied", [])),
                target_after=8, status="OK",
                notes=("Wide-format slots + un-versioned column renames + archive sweep."))

        write_decision_log(DECISION_LOG, {
            "script": SCRIPT_TAG, "run_date": RUN_DATE,
            "mode": "APPLY" if do_writes else "DRY-RUN",
            "preflight_divergences": [],
            "results": results,
            "elapsed_seconds": round(time.time() - t0, 1),
        })

        if do_writes and 7 in phase_list:
            FINAL_JSON.write_text(
                json.dumps(results.get("phase_7", {}), indent=2, default=str)
            )
            p2 = results.get("phase_2", {})
            p3 = results.get("phase_3", {})
            p4 = results.get("phase_4", {})
            p5 = results.get("phase_5", {})
            p6 = results.get("phase_6", {})
            p7 = results.get("phase_7", {})
            summary = f"""# Script 266c — summary

- **Mode:** APPLY
- **path_synoptics new columns:** {len(p2.get('added_columns', []))} (target 40)
- **tumor_pathology new columns:** {len(p3.get('added_columns', []))} (target 4)
- **Tumor_ordinal > 5 overflow:** {p2.get('tumor_ordinal_gt5_count')}
- **Renames applied (CTC + TEM):** {len(p4.get('renames_applied', []))} (target 8)
- **Archived:** {p5.get('archived_count')} | **Skipped:** {p5.get('skipped_count')}
- **__readme rebuilt with:** {p6.get('queryable_main_tables')} queryable main tables
- **Views smoke-checked:** {p6.get('views_ok')} / {p6.get('views_total')} OK
- **Deprecated residue in main (post-sweep):** {p7.get('deprecated_residue') or 'none'}
- **Run log:** scripts/output/266c_run_log.md
- **Decision log:** scripts/output/266c_decision_log.json
- **Final confirmation:** scripts/output/266c_final_confirmation.json
- **Archive manifest:** scripts/output/266c_archive_manifest.csv
- **View smoke CSV:** scripts/output/266c_view_smoke_check.csv
- **Tumor ordinal overflow CSV:** scripts/output/266c_tumor_ordinal_gt5_overflow.csv
- **Legacy fragment profile CSV:** scripts/output/266c_legacy_fragment_profile.csv
"""
            SUMMARY_MD.write_text(summary)

        log(f"\nelapsed: {time.time() - t0:.1f}s")
        log("DONE")
        return 0
    except Exception as e:
        log(f"FATAL: {e!r}")
        log(traceback.format_exc())
        return 1
    finally:
        fh.close()


if __name__ == "__main__":
    sys.exit(main())
