#!/usr/bin/env python3
"""
M048 v1.3 — manuscript tables xlsx builder.
Reads v4 CSV outputs and writes M048_v1.3_tables_for_manuscript.xlsx
into M048_submission_package_v1.3/.

Run AFTER m048_run_analysis_v4.py completes.
"""
from __future__ import annotations

import os
import sys

import numpy as np
import pandas as pd

REPO_ROOT  = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
STUDY_DIR  = os.path.dirname(os.path.abspath(__file__))
V4_DIR     = os.path.join(STUDY_DIR, "v4")
V3_DIR     = os.path.join(STUDY_DIR, "v3")
PKG_V13    = os.path.join(REPO_ROOT, "M048_submission_package_v1.3")
OUT_XLSX   = os.path.join(PKG_V13, "M048_v1.3_tables_for_manuscript.xlsx")

os.makedirs(PKG_V13, exist_ok=True)


def _read(path: str, fallback: str | None = None) -> pd.DataFrame:
    if os.path.isfile(path):
        return pd.read_csv(path)
    if fallback and os.path.isfile(fallback):
        print(f"  [FALLBACK] {path} → {fallback}")
        return pd.read_csv(fallback)
    print(f"  [MISSING]  {path}")
    return pd.DataFrame()


def _fmt_or(row, or_col="or", lo_col="ci_lo", hi_col="ci_hi", p_col="p") -> str:
    try:
        o  = float(row[or_col])
        lo = float(row[lo_col])
        hi = float(row[hi_col])
        p  = float(row[p_col]) if p_col in row else np.nan
        if not np.isfinite(o):
            return "—"
        s = f"{o:.3f} ({lo:.3f}–{hi:.3f})"
        if np.isfinite(p):
            if   p < 0.001: s += " ***"
            elif p < 0.01:  s += " **"
            elif p < 0.05:  s += " *"
        return s
    except Exception:
        return "—"


def build_cover_sheet() -> pd.DataFrame:
    return pd.DataFrame({
        "Item": [
            "Manuscript", "Version", "Generated by", "Date",
            "Bug fixed (v1.3)", "Key v4 change",
            "v4 master BQ table", "v4 nodule BQ table",
        ],
        "Value": [
            "M048 — Racial Disparities in TI-RADS Thyroid Nodule Malignancy Risk",
            "v1.3 (mig_318b)",
            "m048_build_tables_xlsx_v4.py",
            pd.Timestamp.now().strftime("%Y-%m-%d"),
            "has_clt/has_mng/has_graves all-zero in v3 (Bug C); v4 re-derives from "
            "canonical_path_benign_patient_rollup_v1 → M4 step restored in cascade.",
            "M4 background-pathology step restored; expanded comorbidity sensitivity; "
            "mediation extended to 8 mediators × 2 races; arm D now removes has_clt patients.",
            "pub_workspace.m048_v4_patient_master_v1 (n=3,375; analytic n=3,121)",
            "pub_workspace.m048_v4_nodule_master_v1",
        ],
    })


def build_table_2_cascade() -> pd.DataFrame:
    df = _read(os.path.join(V4_DIR, "m048_v4_cascade.csv"))
    if df.empty:
        return df
    rows = []
    for step in ["M0", "M1", "M2", "M3", "M4", "M5", "M6"]:
        sub = df[df["model_step"] == step]
        for _, r in sub.iterrows():
            rows.append({
                "Model Step": step,
                "Race vs White": r.get("race_level", ""),
                "OR (95% CI)":   _fmt_or(r),
                "p-value":       f"{float(r['p']):.4f}" if pd.notna(r.get("p")) else "—",
                "N":             int(r["n"]) if pd.notna(r.get("n")) else "",
                "AIC":           f"{float(r['aic']):.1f}" if pd.notna(r.get("aic")) else "—",
            })
    return pd.DataFrame(rows)


def build_table_3_full_model() -> pd.DataFrame:
    df = _read(os.path.join(V4_DIR, "m048_v4_full_model_OR.csv"))
    if df.empty:
        return df
    df["OR (95% CI)"] = df.apply(_fmt_or, axis=1)
    df["p-value"] = df["p"].apply(lambda x: f"{float(x):.4f}" if pd.notna(x) else "—")
    return df[["param", "or", "ci_lo", "ci_hi", "p", "OR (95% CI)", "p-value"]]


def build_table_4_bethesda() -> pd.DataFrame:
    df = _read(os.path.join(V4_DIR, "m048_v4_bethesda_stratified_TR_ROM.csv"))
    if df.empty:
        return df
    df["OR (95% CI)"] = df.apply(_fmt_or, axis=1)
    return df[["bethesda_bucket", "race_level", "n", "n_events", "OR (95% CI)", "p"]]


def build_table_5_bethesda_interaction() -> pd.DataFrame:
    df = _read(os.path.join(V4_DIR, "m048_v4_bethesda_stratified_TR_interaction.csv"))
    if df.empty:
        return df
    df["OR (95% CI)"] = df.apply(_fmt_or, axis=1)
    return df[["bethesda_bucket", "interaction_term", "coef", "OR (95% CI)", "p", "p_bonf", "n"]]


def build_table_6_race_x_tr() -> pd.DataFrame:
    df = _read(os.path.join(V4_DIR, "m048_v4_interaction_race_x_tr.csv"),
               os.path.join(V3_DIR, "m048_v3_interaction_race_x_tr.csv"))
    return df


def build_table_7_mediation() -> pd.DataFrame:
    df = _read(os.path.join(V4_DIR, "m048_v4_mediation.csv"))
    if df.empty:
        return df
    df["IE (median)"]        = df["indirect_median"].apply(lambda x: f"{x:.4f}" if pd.notna(x) else "—")
    df["IE winsor mean"]     = df["indirect_winsor_mean"].apply(lambda x: f"{x:.4f}" if pd.notna(x) else "—")
    df["95% CI"]             = df.apply(lambda r: f"({float(r['ci_lo']):.4f}, {float(r['ci_hi']):.4f})"
                                        if pd.notna(r.get("ci_lo")) else "—", axis=1)
    return df[["mediator", "type", "race_target", "scope", "IE (median)", "IE winsor mean", "95% CI"]]


def build_table_8_sensitivity() -> pd.DataFrame:
    df = _read(os.path.join(V4_DIR, "m048_v4_sensitivity_arms.csv"))
    if df.empty:
        return df
    df["OR (95% CI)"] = df.apply(
        lambda r: _fmt_or(r) if pd.notna(r.get("or")) else r.get("error", "—"), axis=1
    )
    return df[["arm", "race_level", "n", "OR (95% CI)", "p"]].dropna(subset=["race_level"])


def build_table_8b_comorbidity() -> pd.DataFrame:
    df = _read(os.path.join(V4_DIR, "m048_v4_comorbidity_sensitivity.csv"))
    if df.empty:
        return df
    df["OR (95% CI)"] = df.apply(_fmt_or, axis=1)
    return df[["model_label", "term", "or", "ci_lo", "ci_hi", "p", "OR (95% CI)"]]


def build_table_8c_background_path() -> pd.DataFrame:
    return _read(os.path.join(V4_DIR, "m048_v4_background_path_by_race.csv"))


def build_table_9_disparity() -> pd.DataFrame:
    return _read(os.path.join(V4_DIR, "m048_v4_disparity_direction_table.csv"),
                 os.path.join(V3_DIR, "m048_v3_disparity_direction_table.csv"))


def build_table_10_nodule() -> pd.DataFrame:
    df = _read(os.path.join(V4_DIR, "m048_v4_per_nodule_cluster_robust.csv"))
    if df.empty:
        return df
    if "or" in df.columns:
        df["OR (95% CI)"] = df.apply(_fmt_or, axis=1)
    return df


def build_table_11_balance() -> pd.DataFrame:
    df = _read(os.path.join(V4_DIR, "m048_v4_covariate_balance.csv"))
    return df


def build_table_12_qa() -> pd.DataFrame:
    return _read(os.path.join(V4_DIR, "m048_v4_qa_gates.csv"))


def build_table_13_bethesda_x_race_x_tr() -> pd.DataFrame:
    return _read(
        os.path.join(V4_DIR, "m048_v4_bethesda_x_race_x_tr_rom.csv"),
        os.path.join(V3_DIR, "m048_v3_bethesda_x_race_x_tr_rom.csv"),
    )


def build_table_1c_pmh() -> pd.DataFrame:
    return _read(os.path.join(V4_DIR, "m048_v4_pmh_by_race.csv"))


def main() -> None:
    sheets: dict[str, pd.DataFrame] = {
        "Cover":                      build_cover_sheet(),
        "Table_2_Cascade":            build_table_2_cascade(),
        "Table_3_Full_Model":         build_table_3_full_model(),
        "Table_4_Bethesda_Stratified": build_table_4_bethesda(),
        "Table_5_Bethesda_TR_Interaction": build_table_5_bethesda_interaction(),
        "Table_6_Race_x_TR_Interaction":   build_table_6_race_x_tr(),
        "Table_7_Mediation":          build_table_7_mediation(),
        "Table_8_Sensitivity_Arms":   build_table_8_sensitivity(),
        "Table_8b_Comorbidity_Sensitivity": build_table_8b_comorbidity(),
        "Table_8c_Background_Path_by_Race": build_table_8c_background_path(),
        "Table_9_Disparity_Direction":  build_table_9_disparity(),
        "Table_10_Per_Nodule_Cluster":  build_table_10_nodule(),
        "Table_11_Covariate_Balance":   build_table_11_balance(),
        "Table_12_QA_Gates":            build_table_12_qa(),
        "Table_13_Bethesda_x_Race_x_TR": build_table_13_bethesda_x_race_x_tr(),
        "Table_1c_Comorbidities_PMH":    build_table_1c_pmh(),
    }

    print(f"[XLSX] Writing {OUT_XLSX} ...")
    with pd.ExcelWriter(OUT_XLSX, engine="openpyxl") as writer:
        for sheet_name, df in sheets.items():
            if df is None or df.empty:
                print(f"  [EMPTY] {sheet_name}")
                df = pd.DataFrame([{"note": "no data available"}])
            # truncate sheet names to 31 chars (Excel limit)
            sn = sheet_name[:31]
            df.to_excel(writer, sheet_name=sn, index=False)
            print(f"  wrote {sn} ({len(df)} rows)")

    print(f"\n[DONE] {OUT_XLSX}")


if __name__ == "__main__":
    main()
