#!/usr/bin/env python3
"""mig_178 — histology vocabulary cleanup + cross-table uniformity audit.

This migration applies the Logan-ratified decision to reject a synthetic
``mtc_ptc_mixed`` histology code. Mixed PTC/MTC patients remain represented as
separate canonical histology labels (``MTC | PTC``) derived from malignant path
 events. The script:

* snapshots affected publication tables to archive_pub_v1_0;
* normalizes raw/metastatic/recurrent histology strings in path malignant events
  and rollup surfaces;
* re-derives CPM ``histologic_types_all`` and ``histologic_variants_all`` with
  sorted ``STRING_AGG(DISTINCT ...)`` from canonical_path_malignant_events_v1;
* scrubs PM path histology raw mirrors to the same normalized rollups;
* creates read-only audit tables in manuscript_workspace.

No clinical note text is printed; reports contain structured histology labels
and aggregate counts only.
"""
from __future__ import annotations

import argparse
import sys
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

import duckdb

REPO_ROOT = Path(__file__).resolve().parents[2]
SCRIPTS_DIR = REPO_ROOT / "scripts"
if str(SCRIPTS_DIR) not in sys.path:
    sys.path.insert(0, str(SCRIPTS_DIR))

from _md_connect import connect_locked  # noqa: E402

PUB_DB = "thyroid_canonical_publication_v1_0"
ARCHIVE_DB = "Thyroid 2026 UPdated"
ARCHIVE_SCHEMA = "archive_pub_v1_0"
RUN_ID = "mig_178_histology_vocab_cleanup_20260429"
REPORT_PATH = REPO_ROOT / "qc_framework_v1" / "reports" / "mig_178_histology_vocab_cleanup_20260429.md"
SQL_PATH = REPO_ROOT / "qc_framework_v1" / "migrations" / "178_histology_vocab_cleanup_20260429.sql"
RATIFICATION_NOTES = REPO_ROOT / "exports" / "mig168_pm_vocab_audit_20260429_175417" / "RATIFICATION_NOTES_20260429.md"

TARGET_COLS = [
    "histologic_types_all",
    "histologic_variants_all",
    "path_histology_raw",
    "path_histology_variant_raw",
]


@dataclass
class Metrics:
    snapshot_cpm: str | None
    snapshot_events: str | None
    snapshot_rollup: str | None
    pm_ptc_mtc_exact_pre: int
    pm_ptc_mtc_any_pre: int
    events_ptc_mtc_patients_pre: int
    bad_values_pre: int
    event_rows_changed: int
    cpm_rows_changed: int
    rollup_rows_changed: int
    bad_values_post: int
    ptc_mtc_patients_post: int
    uniformity_failures_post: int


def qident(name: str) -> str:
    return '"' + name.replace('"', '""') + '"'


def df_scalar(con: duckdb.DuckDBPyConnection, sql: str, params: list[Any] | None = None) -> Any:
    return con.execute(sql, params or []).fetchone()[0]


def write_sql_artifact() -> None:
    SQL_PATH.parent.mkdir(parents=True, exist_ok=True)
    SQL_PATH.write_text(
        """-- mig_178 — histology vocabulary cleanup + cross-table uniformity audit
-- Generated by qc_framework_v1/scripts/apply_mig178_histology_vocab_cleanup.py
-- Execute through the Python script so snapshots, reports, and post-state gates run together.
-- Core decisions:
--   * Reject synthetic mtc_ptc_mixed; represent mixed PTC/MTC patients as separate labels.
--   * Normalize metastatic/recurrent prefixes out of histology type fields.
--   * Re-derive CPM histologic_types_all and histologic_variants_all from canonical_path_malignant_events_v1.
--   * Audit PM, canonical_path_malignant_events_v1, and canonical_path_malignant_patient_rollup_v1 for uniformity.
""",
        encoding="utf-8",
    )


def install_macros(con: duckdb.DuckDBPyConnection) -> None:
    con.execute(
        r"""
        CREATE OR REPLACE TEMP MACRO mig178_clean_text(x) AS (
          NULLIF(
            regexp_replace(
              TRIM(regexp_replace(CAST(x AS VARCHAR), '[\r\n\t]+', ' ', 'g')),
              '\s+', ' ', 'g'
            ),
            ''
          )
        )
        """
    )
    con.execute(
        r"""
        CREATE OR REPLACE TEMP MACRO mig178_norm_histology(x) AS (
          CASE
            WHEN x IS NULL OR mig178_clean_text(x) IS NULL THEN NULL
            WHEN regexp_matches(LOWER(mig178_clean_text(x)), '(papillary|paillary|\bptc\b)') THEN 'PTC'
            WHEN regexp_matches(LOWER(mig178_clean_text(x)), '(medullary|\bmtc\b)') THEN 'MTC'
            WHEN regexp_matches(LOWER(mig178_clean_text(x)), 'differentiated high grade') THEN 'differentiated high grade thyroid carcinoma'
            WHEN regexp_matches(LOWER(mig178_clean_text(x)), 'poorly differentiated') THEN 'poorly differentiated thyroid carcinoma'
            WHEN regexp_matches(LOWER(mig178_clean_text(x)), 'anaplastic') THEN 'anaplastic carcinoma'
            WHEN regexp_matches(LOWER(mig178_clean_text(x)), 'niftp') THEN 'NIFTP'
            WHEN regexp_matches(LOWER(mig178_clean_text(x)), 'ftump') THEN 'FTUMP'
            WHEN regexp_matches(LOWER(mig178_clean_text(x)), 'h[üu]rthle cell carcinoma|hurthle cell carcinoma') THEN 'Hurthle cell carcinoma'
            WHEN regexp_matches(LOWER(mig178_clean_text(x)), 'follicular carcinoma|insular carcinoma') THEN 'follicular carcinoma'
            WHEN regexp_matches(LOWER(mig178_clean_text(x)), 'angiosarcoma') THEN 'angiosarcoma'
            WHEN regexp_matches(LOWER(mig178_clean_text(x)), 'neuroendocrine') THEN 'neuroendocrine tumor'
            WHEN regexp_matches(LOWER(mig178_clean_text(x)), 'follicular adenoma') THEN 'follicular adenoma'
            WHEN regexp_matches(LOWER(mig178_clean_text(x)), 'thyroid carcinoma|carcinoma') THEN 'DTC (NOS)'
            ELSE mig178_clean_text(x)
          END
        )
        """
    )
    con.execute(
        r"""
        CREATE OR REPLACE TEMP MACRO mig178_norm_variant(x) AS (
          CASE
            WHEN x IS NULL OR mig178_clean_text(x) IS NULL THEN NULL
            WHEN LOWER(mig178_clean_text(x)) IN ('metastatic', 'recurrent') THEN NULL
            WHEN regexp_matches(LOWER(mig178_clean_text(x)), 'microcarcioma|micorcarcinoma|microcarcinoma') THEN 'microcarcinoma'
            WHEN regexp_matches(LOWER(mig178_clean_text(x)), 'tall cell|tal cell|varaint') THEN 'tall cell'
            WHEN regexp_matches(LOWER(mig178_clean_text(x)), 'follicular') THEN 'follicular'
            WHEN regexp_matches(LOWER(mig178_clean_text(x)), 'classic|classical') THEN 'classical'
            WHEN regexp_matches(LOWER(mig178_clean_text(x)), 'hurth|oncocytic|onocytic') THEN 'oncocytic/hurthle'
            WHEN regexp_matches(LOWER(mig178_clean_text(x)), 'hobnail') THEN 'hobnail'
            WHEN regexp_matches(LOWER(mig178_clean_text(x)), 'diffuse sclerosing') THEN 'diffuse sclerosing'
            WHEN regexp_matches(LOWER(mig178_clean_text(x)), 'cribiform|cribriform') THEN 'cribriform morular'
            WHEN regexp_matches(LOWER(mig178_clean_text(x)), 'minimally invasive') THEN 'minimally invasive'
            WHEN regexp_matches(LOWER(mig178_clean_text(x)), 'widely invasive') THEN 'widely invasive'
            WHEN regexp_matches(LOWER(mig178_clean_text(x)), 'insular') THEN 'insular'
            WHEN regexp_matches(LOWER(mig178_clean_text(x)), 'solid') THEN 'solid'
            WHEN regexp_matches(LOWER(mig178_clean_text(x)), 'warthin') THEN 'warthin-like'
            WHEN regexp_matches(LOWER(mig178_clean_text(x)), 'macrofollicular') THEN 'macrofollicular'
            WHEN regexp_matches(LOWER(mig178_clean_text(x)), 'high grade') THEN 'high grade'
            ELSE LOWER(mig178_clean_text(x))
          END
        )
        """
    )


def create_snapshots(con: duckdb.DuckDBPyConnection, ts_tag: str) -> tuple[str, str, str]:
    con.execute(f"CREATE SCHEMA IF NOT EXISTS {qident(ARCHIVE_DB)}.{qident(ARCHIVE_SCHEMA)}")
    cpm_snap = f"canonical_patient_master_histology_pre_mig178_{ts_tag}"
    events_snap = f"canonical_path_malignant_events_v1_pre_mig178_{ts_tag}"
    rollup_snap = f"canonical_path_malignant_patient_rollup_v1_pre_mig178_{ts_tag}"
    cpm_fq = f"{qident(ARCHIVE_DB)}.{qident(ARCHIVE_SCHEMA)}.{qident(cpm_snap)}"
    events_fq = f"{qident(ARCHIVE_DB)}.{qident(ARCHIVE_SCHEMA)}.{qident(events_snap)}"
    rollup_fq = f"{qident(ARCHIVE_DB)}.{qident(ARCHIVE_SCHEMA)}.{qident(rollup_snap)}"
    con.execute(
        f"""
        CREATE TABLE {cpm_fq} AS
        SELECT research_id, histologic_types_all, histologic_variants_all,
               path_histology_raw, path_histology_variant_raw, cpm_built_at
        FROM main.canonical_patient_master
        """
    )
    con.execute(f"CREATE TABLE {events_fq} AS SELECT * FROM main.canonical_path_malignant_events_v1")
    con.execute(f"CREATE TABLE {rollup_fq} AS SELECT * FROM main.canonical_path_malignant_patient_rollup_v1")
    return cpm_fq, events_fq, rollup_fq


def bad_value_count(con: duckdb.DuckDBPyConnection) -> int:
    return int(df_scalar(con, r"""
        WITH values AS (
          SELECT 'pm.histologic_types_all' src, CAST(research_id AS VARCHAR) rid, histologic_types_all val FROM main.canonical_patient_master
          UNION ALL SELECT 'pm.histologic_variants_all', CAST(research_id AS VARCHAR), histologic_variants_all FROM main.canonical_patient_master
          UNION ALL SELECT 'pm.path_histology_raw', CAST(research_id AS VARCHAR), path_histology_raw FROM main.canonical_patient_master
          UNION ALL SELECT 'pm.path_histology_variant_raw', CAST(research_id AS VARCHAR), path_histology_variant_raw FROM main.canonical_patient_master
          UNION ALL SELECT 'events.primary_histology', CAST(research_id AS VARCHAR), primary_histology FROM main.canonical_path_malignant_events_v1
          UNION ALL SELECT 'events.histology_variant', CAST(research_id AS VARCHAR), histology_variant FROM main.canonical_path_malignant_events_v1
          UNION ALL SELECT 'rollup.dominant_histology', CAST(research_id AS VARCHAR), dominant_histology FROM main.canonical_path_malignant_patient_rollup_v1
          UNION ALL SELECT 'rollup.poc_tumor_1_histologic_type', CAST(research_id AS VARCHAR), poc_tumor_1_histologic_type FROM main.canonical_path_malignant_patient_rollup_v1
        )
        SELECT COUNT(*)
        FROM values
        WHERE val IS NOT NULL
          AND regexp_matches(LOWER(CAST(val AS VARCHAR)), 'metastatic|recurrent|mixed composit|\?|[\r\n]')
    """))


def collect_pre_metrics(con: duckdb.DuckDBPyConnection) -> dict[str, int]:
    return {
        "pm_ptc_mtc_exact_pre": int(df_scalar(con, r"""
            SELECT COUNT(*)
            FROM main.canonical_patient_master
            WHERE histologic_types_all IN ('PTC | MTC', 'MTC | PTC')
        """)),
        "pm_ptc_mtc_any_pre": int(df_scalar(con, r"""
            SELECT COUNT(*)
            FROM main.canonical_patient_master
            WHERE histologic_types_all ILIKE '%PTC%'
              AND (histologic_types_all ILIKE '%MTC%' OR histologic_types_all ILIKE '%medullary%')
        """)),
        "events_ptc_mtc_patients_pre": int(df_scalar(con, r"""
            WITH per AS (
              SELECT CAST(research_id AS VARCHAR) rid,
                     BOOL_OR(regexp_matches(LOWER(COALESCE(primary_histology,'')), '(papillary|\bptc\b)')) has_ptc,
                     BOOL_OR(regexp_matches(LOWER(COALESCE(primary_histology,'')), '(medullary|\bmtc\b)')) has_mtc
              FROM main.canonical_path_malignant_events_v1
              GROUP BY 1
            )
            SELECT COUNT(*) FROM per WHERE has_ptc AND has_mtc
        """)),
        "bad_values_pre": bad_value_count(con),
    }


def apply_cleanup(con: duckdb.DuckDBPyConnection) -> None:
    con.execute(
        """
        UPDATE main.canonical_path_malignant_events_v1
        SET primary_histology = mig178_norm_histology(primary_histology),
            histology_variant = mig178_norm_variant(histology_variant),
            build_script = '178_histology_vocab_cleanup',
            build_ts = CAST(CURRENT_TIMESTAMP AS TIMESTAMP)
        WHERE primary_histology IS DISTINCT FROM mig178_norm_histology(primary_histology)
           OR histology_variant IS DISTINCT FROM mig178_norm_variant(histology_variant)
        """
    )
    con.execute(
        """
        CREATE OR REPLACE TEMP TABLE mig178_patient_histology_rollup AS
        SELECT
            CAST(research_id AS VARCHAR) AS research_id,
            STRING_AGG(DISTINCT primary_histology, ' | ' ORDER BY primary_histology)
              FILTER (WHERE primary_histology IS NOT NULL) AS histologic_types_all_new,
            STRING_AGG(DISTINCT histology_variant, ' | ' ORDER BY histology_variant)
              FILTER (WHERE histology_variant IS NOT NULL) AS histologic_variants_all_new
        FROM main.canonical_path_malignant_events_v1
        GROUP BY 1
        """
    )
    con.execute(
        """
        UPDATE main.canonical_patient_master AS p
        SET histologic_types_all = r.histologic_types_all_new,
            histologic_variants_all = r.histologic_variants_all_new,
            path_histology_raw = r.histologic_types_all_new,
            path_histology_variant_raw = r.histologic_variants_all_new,
            cpm_built_at = CAST(CURRENT_TIMESTAMP AS TIMESTAMP)
        FROM mig178_patient_histology_rollup r
        WHERE p.research_id = r.research_id
          AND (
            p.histologic_types_all IS DISTINCT FROM r.histologic_types_all_new OR
            p.histologic_variants_all IS DISTINCT FROM r.histologic_variants_all_new OR
            p.path_histology_raw IS DISTINCT FROM r.histologic_types_all_new OR
            p.path_histology_variant_raw IS DISTINCT FROM r.histologic_variants_all_new
          )
        """
    )
    con.execute(
        """
        UPDATE main.canonical_path_malignant_patient_rollup_v1
        SET dominant_histology = mig178_norm_histology(dominant_histology),
            poc_tumor_1_histologic_type = mig178_norm_histology(poc_tumor_1_histologic_type),
            build_script = '178_histology_vocab_cleanup',
            build_ts = CAST(CURRENT_TIMESTAMP AS TIMESTAMP)
        WHERE dominant_histology IS DISTINCT FROM mig178_norm_histology(dominant_histology)
           OR poc_tumor_1_histologic_type IS DISTINCT FROM mig178_norm_histology(poc_tumor_1_histologic_type)
        """
    )


def build_audit_tables(con: duckdb.DuckDBPyConnection) -> None:
    con.execute(
        """
        CREATE OR REPLACE TABLE manuscript_workspace.mig178_ptc_mtc_patient_audit_v1 AS
        WITH event_rollup AS (
          SELECT
            CAST(research_id AS VARCHAR) AS research_id,
            BOOL_OR(primary_histology = 'PTC') AS has_ptc,
            BOOL_OR(primary_histology = 'MTC') AS has_mtc,
            STRING_AGG(DISTINCT primary_histology, ' | ' ORDER BY primary_histology)
              FILTER (WHERE primary_histology IS NOT NULL) AS event_histologies_normalized,
            STRING_AGG(DISTINCT histology_variant, ' | ' ORDER BY histology_variant)
              FILTER (WHERE histology_variant IS NOT NULL) AS event_variants_normalized,
            COUNT(*) AS n_path_malignant_events
          FROM main.canonical_path_malignant_events_v1
          GROUP BY 1
        )
        SELECT
          e.research_id,
          e.n_path_malignant_events,
          e.event_histologies_normalized,
          e.event_variants_normalized,
          p.histologic_types_all AS pm_histologic_types_all,
          p.histologic_variants_all AS pm_histologic_variants_all,
          r.dominant_histology AS rollup_dominant_histology,
          CASE
            WHEN e.event_histologies_normalized = p.histologic_types_all THEN 'pm_matches_events'
            ELSE 'pm_event_mismatch_review'
          END AS pm_event_status,
          CAST(CURRENT_TIMESTAMP AS TIMESTAMP) AS audited_at
        FROM event_rollup e
        JOIN main.canonical_patient_master p ON p.research_id = e.research_id
        LEFT JOIN main.canonical_path_malignant_patient_rollup_v1 r
          ON CAST(r.research_id AS VARCHAR) = e.research_id
        WHERE e.has_ptc AND e.has_mtc
        ORDER BY TRY_CAST(e.research_id AS BIGINT)
        """
    )
    con.execute(
        r"""
        CREATE OR REPLACE TABLE manuscript_workspace.mig178_histology_vocab_uniformity_audit_v1 AS
        WITH values AS (
          SELECT 'canonical_patient_master' AS table_name, 'histologic_types_all' AS column_name, CAST(research_id AS VARCHAR) AS research_id, histologic_types_all AS value FROM main.canonical_patient_master
          UNION ALL SELECT 'canonical_patient_master', 'histologic_variants_all', CAST(research_id AS VARCHAR), histologic_variants_all FROM main.canonical_patient_master
          UNION ALL SELECT 'canonical_patient_master', 'path_histology_raw', CAST(research_id AS VARCHAR), path_histology_raw FROM main.canonical_patient_master
          UNION ALL SELECT 'canonical_patient_master', 'path_histology_variant_raw', CAST(research_id AS VARCHAR), path_histology_variant_raw FROM main.canonical_patient_master
          UNION ALL SELECT 'canonical_path_malignant_events_v1', 'primary_histology', CAST(research_id AS VARCHAR), primary_histology FROM main.canonical_path_malignant_events_v1
          UNION ALL SELECT 'canonical_path_malignant_events_v1', 'histology_variant', CAST(research_id AS VARCHAR), histology_variant FROM main.canonical_path_malignant_events_v1
          UNION ALL SELECT 'canonical_path_malignant_patient_rollup_v1', 'dominant_histology', CAST(research_id AS VARCHAR), dominant_histology FROM main.canonical_path_malignant_patient_rollup_v1
          UNION ALL SELECT 'canonical_path_malignant_patient_rollup_v1', 'poc_tumor_1_histologic_type', CAST(research_id AS VARCHAR), poc_tumor_1_histologic_type FROM main.canonical_path_malignant_patient_rollup_v1
        ), classified AS (
          SELECT
            table_name,
            column_name,
            value,
            COUNT(*) AS n_rows,
            COUNT(DISTINCT research_id) AS n_patients,
            CASE
              WHEN value IS NULL THEN 'null_ok'
              WHEN regexp_matches(LOWER(CAST(value AS VARCHAR)), 'mtc_ptc_mixed|mixed composit') THEN 'FAIL_mixed_composite_token'
              WHEN regexp_matches(LOWER(CAST(value AS VARCHAR)), 'metastatic|recurrent') THEN 'FAIL_metastatic_recurrent_prefix'
              WHEN regexp_matches(CAST(value AS VARCHAR), '[\r\n]') THEN 'FAIL_embedded_newline'
              WHEN regexp_matches(CAST(value AS VARCHAR), '\?') THEN 'FAIL_uncertainty_marker'
              ELSE 'PASS'
            END AS uniformity_status
          FROM values
          GROUP BY 1,2,3
        )
        SELECT *, CAST(CURRENT_TIMESTAMP AS TIMESTAMP) AS audited_at
        FROM classified
        ORDER BY
          CASE WHEN uniformity_status='PASS' THEN 2 WHEN uniformity_status='null_ok' THEN 3 ELSE 1 END,
          table_name, column_name, n_rows DESC, value
        """
    )
    con.execute(
        """
        CREATE OR REPLACE TABLE manuscript_workspace.mig178_histology_cleanup_summary_v1 AS
        SELECT * FROM (
          SELECT 'ptc_mtc_patient_audit_rows' AS metric, COUNT(*)::VARCHAR AS value FROM manuscript_workspace.mig178_ptc_mtc_patient_audit_v1
          UNION ALL
          SELECT 'uniformity_fail_values', COUNT(*)::VARCHAR FROM manuscript_workspace.mig178_histology_vocab_uniformity_audit_v1 WHERE uniformity_status LIKE 'FAIL%'
          UNION ALL
          SELECT 'uniformity_pass_values', COUNT(*)::VARCHAR FROM manuscript_workspace.mig178_histology_vocab_uniformity_audit_v1 WHERE uniformity_status = 'PASS'
          UNION ALL
          SELECT 'mtc_ptc_mixed_values_remaining', COUNT(*)::VARCHAR FROM manuscript_workspace.mig178_histology_vocab_uniformity_audit_v1 WHERE LOWER(COALESCE(value,'')) LIKE '%mtc_ptc_mixed%'
        )
        """
    )


def write_provenance(con: duckdb.DuckDBPyConnection, started_at: datetime, held: int) -> None:
    con.execute("DELETE FROM manuscript_workspace.cpm_reconciliation_provenance_v1 WHERE run_id = ?", [RUN_ID])
    con.execute(
        """
        INSERT INTO manuscript_workspace.cpm_reconciliation_provenance_v1
          (run_id, started_at, ended_at, phases_applied,
           critical_findings_cleared, high_findings_cleared,
           med_findings_cleared, held_for_adjudication)
        VALUES (?, ?, CAST(CURRENT_TIMESTAMP AS TIMESTAMP),
          'ratification_review;snapshots;event_histology_scrub;cpm_histology_rollup_rederive;path_rollup_scrub;uniformity_audit',
          '1', '1', '1', ?)
        """,
        [RUN_ID, started_at.replace(tzinfo=None), str(held)],
    )


def build_report(con: duckdb.DuckDBPyConnection, metrics: Metrics) -> str:
    summary = con.execute("SELECT metric, value FROM manuscript_workspace.mig178_histology_cleanup_summary_v1 ORDER BY metric").fetchdf()
    ptc_mtc_count = df_scalar(con, "SELECT COUNT(*) FROM manuscript_workspace.mig178_ptc_mtc_patient_audit_v1")
    ptc_mtc_mismatches = df_scalar(
        con,
        """
        SELECT COUNT(*)
        FROM manuscript_workspace.mig178_ptc_mtc_patient_audit_v1
        WHERE pm_event_status <> 'pm_matches_events'
        """,
    )
    named_examples = con.execute(
        """
        SELECT
          p.research_id,
          p.histologic_types_all AS cleaned_pm_histologic_types_all,
          COALESCE(p.histologic_variants_all, 'NULL') AS cleaned_pm_variant_list,
          r.dominant_histology AS rollup_dominant,
          r.poc_tumor_1_histologic_type AS rollup_tumor_1_histology
        FROM main.canonical_patient_master p
        LEFT JOIN main.canonical_path_malignant_patient_rollup_v1 r
          ON CAST(r.research_id AS VARCHAR)=p.research_id
        WHERE p.research_id IN ('2168','3331')
        ORDER BY TRY_CAST(p.research_id AS BIGINT)
        """
    ).fetchdf()
    failures = con.execute(
        """
        SELECT table_name, column_name, value, n_rows, n_patients, uniformity_status
        FROM manuscript_workspace.mig178_histology_vocab_uniformity_audit_v1
        WHERE uniformity_status LIKE 'FAIL%'
        ORDER BY table_name, column_name, n_rows DESC, value
        """
    ).fetchdf()
    lines = [
        "# mig_178 — histology vocabulary cleanup + cross-table uniformity audit",
        "",
        f"**Date:** {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M:%SZ')}",
        f"**Run ID:** `{RUN_ID}`",
        "**Posture:** applied to MotherDuck publication DB with archive snapshots and audit tables.",
        "",
        "## Decision summary",
        "",
        "- Read the mig_168 histology ratification notes.",
        "- Applied Logan's updated decision to reject a synthetic `mtc_ptc_mixed` code.",
        "- Mixed PTC/MTC patients are represented by separate canonical labels, usually `MTC | PTC`, derived from path malignant events.",
        "- Raw strings such as `MTC\\nPTC mixed composit` and `metastatic PTC?` were normalized away in the canonical histology surfaces.",
        "",
        "## Archive snapshots",
        "",
        f"- CPM: `{metrics.snapshot_cpm}`",
        f"- Path malignant events: `{metrics.snapshot_events}`",
        f"- Path malignant rollup: `{metrics.snapshot_rollup}`",
        "",
        "## Execution metrics",
        "",
        "| Metric | Value |",
        "|---|---:|",
        f"| PM exact `PTC | MTC` / `MTC | PTC` patients before | {metrics.pm_ptc_mtc_exact_pre} |",
        f"| PM any PTC+MTC/medullary patients before | {metrics.pm_ptc_mtc_any_pre} |",
        f"| Event-derived PTC+MTC patients before | {metrics.events_ptc_mtc_patients_pre} |",
        f"| Bad raw-pattern values before | {metrics.bad_values_pre} |",
        f"| Path malignant event rows changed | {metrics.event_rows_changed} |",
        f"| CPM rows changed | {metrics.cpm_rows_changed} |",
        f"| Path malignant rollup rows changed | {metrics.rollup_rows_changed} |",
        f"| Event-derived PTC+MTC patients after | {metrics.ptc_mtc_patients_post} |",
        f"| Bad raw-pattern values after | {metrics.bad_values_post} |",
        f"| Uniformity failure values after | {metrics.uniformity_failures_post} |",
        "",
        "## Audit table summary",
        "",
        summary.to_markdown(index=False) if not summary.empty else "No summary rows.",
        "",
        "## PTC/MTC patient audit",
        "",
        f"The full {ptc_mtc_count}-patient audit is materialized in `manuscript_workspace.mig178_ptc_mtc_patient_audit_v1`; mismatches after cleanup: {ptc_mtc_mismatches}.",
        "",
        "Named spot checks:",
        "",
        named_examples.to_markdown(index=False) if not named_examples.empty else "Named examples not found.",
        "",
        "## Remaining uniformity failures",
        "",
        failures.to_markdown(index=False) if not failures.empty else "No remaining uniformity failures.",
        "",
        "## Tables created",
        "",
        "- `manuscript_workspace.mig178_ptc_mtc_patient_audit_v1`",
        "- `manuscript_workspace.mig178_histology_vocab_uniformity_audit_v1`",
        "- `manuscript_workspace.mig178_histology_cleanup_summary_v1`",
        "",
        "## mig_172 unblock note",
        "",
        "The multi-label/free-text histology lane is now mechanically separated from the four enum-column mig_172 apply scope. `mtc_ptc_mixed` is not present as a canonical value in the cleaned cross-table audit surface.",
        "",
    ]
    REPORT_PATH.parent.mkdir(parents=True, exist_ok=True)
    report = "\n".join(lines)
    REPORT_PATH.write_text(report, encoding="utf-8")
    return report


def run(apply: bool) -> Metrics:
    started_at = datetime.now(timezone.utc)
    ts_tag = started_at.strftime("%Y%m%d_%H%M%S")
    write_sql_artifact()
    con = connect_locked()
    install_macros(con)
    pre = collect_pre_metrics(con)

    snapshot_cpm = snapshot_events = snapshot_rollup = None
    event_rows_changed = cpm_rows_changed = rollup_rows_changed = 0

    if apply:
        snapshot_cpm, snapshot_events, snapshot_rollup = create_snapshots(con, ts_tag)
        apply_cleanup(con)
        build_audit_tables(con)
        event_rows_changed = int(df_scalar(con, f"""
            SELECT COUNT(*)
            FROM main.canonical_path_malignant_events_v1 e
            JOIN {snapshot_events} s
              ON e.research_id=s.research_id
             AND e.surgery_episode_id IS NOT DISTINCT FROM s.surgery_episode_id
             AND e.tumor_ordinal IS NOT DISTINCT FROM s.tumor_ordinal
             AND e.surgery_date IS NOT DISTINCT FROM s.surgery_date
             AND e.specimen_focus_id IS NOT DISTINCT FROM s.specimen_focus_id
            WHERE e.primary_histology IS DISTINCT FROM s.primary_histology
               OR e.histology_variant IS DISTINCT FROM s.histology_variant
        """))
        cpm_rows_changed = int(df_scalar(con, f"""
            SELECT COUNT(*)
            FROM main.canonical_patient_master p
            JOIN {snapshot_cpm} s USING (research_id)
            WHERE p.histologic_types_all IS DISTINCT FROM s.histologic_types_all
               OR p.histologic_variants_all IS DISTINCT FROM s.histologic_variants_all
               OR p.path_histology_raw IS DISTINCT FROM s.path_histology_raw
               OR p.path_histology_variant_raw IS DISTINCT FROM s.path_histology_variant_raw
        """))
        rollup_rows_changed = int(df_scalar(con, f"""
            SELECT COUNT(*)
            FROM main.canonical_path_malignant_patient_rollup_v1 r
            JOIN {snapshot_rollup} s USING (research_id)
            WHERE r.dominant_histology IS DISTINCT FROM s.dominant_histology
               OR r.poc_tumor_1_histologic_type IS DISTINCT FROM s.poc_tumor_1_histologic_type
        """))
    else:
        # Dry run creates temp audit equivalent only for metric preview.
        con.execute(
            """
            CREATE OR REPLACE TEMP TABLE mig178_patient_histology_rollup_preview AS
            SELECT CAST(research_id AS VARCHAR) AS research_id,
                   STRING_AGG(DISTINCT mig178_norm_histology(primary_histology), ' | ' ORDER BY mig178_norm_histology(primary_histology))
                     FILTER (WHERE mig178_norm_histology(primary_histology) IS NOT NULL) AS histologic_types_all_new,
                   STRING_AGG(DISTINCT mig178_norm_variant(histology_variant), ' | ' ORDER BY mig178_norm_variant(histology_variant))
                     FILTER (WHERE mig178_norm_variant(histology_variant) IS NOT NULL) AS histologic_variants_all_new
            FROM main.canonical_path_malignant_events_v1
            GROUP BY 1
            """
        )

    if apply:
        bad_post = bad_value_count(con)
        ptc_mtc_post = int(df_scalar(con, "SELECT COUNT(*) FROM manuscript_workspace.mig178_ptc_mtc_patient_audit_v1"))
        uniformity_failures = int(df_scalar(con, "SELECT COUNT(*) FROM manuscript_workspace.mig178_histology_vocab_uniformity_audit_v1 WHERE uniformity_status LIKE 'FAIL%'"))
        write_provenance(con, started_at, uniformity_failures)
    else:
        bad_post = pre["bad_values_pre"]
        ptc_mtc_post = pre["events_ptc_mtc_patients_pre"]
        uniformity_failures = -1

    metrics = Metrics(
        snapshot_cpm=snapshot_cpm,
        snapshot_events=snapshot_events,
        snapshot_rollup=snapshot_rollup,
        pm_ptc_mtc_exact_pre=pre["pm_ptc_mtc_exact_pre"],
        pm_ptc_mtc_any_pre=pre["pm_ptc_mtc_any_pre"],
        events_ptc_mtc_patients_pre=pre["events_ptc_mtc_patients_pre"],
        bad_values_pre=pre["bad_values_pre"],
        event_rows_changed=event_rows_changed,
        cpm_rows_changed=cpm_rows_changed,
        rollup_rows_changed=rollup_rows_changed,
        bad_values_post=bad_post,
        ptc_mtc_patients_post=ptc_mtc_post,
        uniformity_failures_post=uniformity_failures,
    )
    if apply:
        build_report(con, metrics)
    return metrics


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--apply", action="store_true", help="Apply MotherDuck writes. Without this, run read-only preview only.")
    parser.add_argument("--dry-run", action="store_true", help="Explicit read-only preview mode.")
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    if not RATIFICATION_NOTES.exists():
        raise FileNotFoundError(f"Missing ratification notes: {RATIFICATION_NOTES}")
    apply = bool(args.apply and not args.dry_run)
    metrics = run(apply=apply)
    print(f"apply={apply}")
    print(metrics)
    if apply:
        print(f"report={REPORT_PATH}")
        print(f"sql_artifact={SQL_PATH}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
