"""
qc_framework_v1/scripts/build_t4b_invasion_positive_review.py
=============================================================

Builds the positive-subset review CSV for canonical_t4b_invasion_events_v1
under Protocol v2.

Table shape (944 rows / 19 cols): three named anatomic findings
(prevertebral_fascia_invasion, carotid_encasement, mediastinal_vessel_invasion)
plus a t4b_implication staging column.

Positive-subset rule (findings-primary, feedback_findings_vs_staging.md):
  ANY of the three anatomic findings is 'present'  --or--
  t4b_implication = 'pT4b' (catches pathologist-stage-only assertions
  for Logan to adjudicate per the airway mig_82 precedent)

Distribution at time of writing:
  All-unknown / unable_to_determine: 897 rows (95%)
  Positive (any 'present' or pT4b):   18 rows
  Edge cases (some absent):           29 rows

Plus a small set of edge-case rows where a finding is 'absent' but
t4b_implication != 'unable_to_determine' (potential findings-vs-staging
disagreements) included for context.

CSV columns:
  t4b_event_id, research_id, note_type, note_index,
  prevertebral_fascia_invasion, carotid_encasement,
  mediastinal_vessel_invasion, t4b_implication,
  confidence, evidence_quote, reasoning,
  llm_model, your_decision, your_note

your_decision vocabulary (mirrors airway pattern):
  ACCEPT          -- default
  REJECT          -- drop row
  RECLASS_T4B     -- t4b_implication should be 'pT4b'
  RECLASS_NOT_T4B -- t4b_implication should be 'not_pT4b'
  RECLASS_UTD     -- t4b_implication should be 'unable_to_determine'

Output:
  verification_csvs/canonical_t4b_invasion_events_v1/
    positive_subset_review__mig_91.csv
"""
from __future__ import annotations

import csv
from pathlib import Path

import duckdb

REPO_ROOT = Path(__file__).resolve().parents[2]
OUT = (
    REPO_ROOT
    / "verification_csvs"
    / "canonical_t4b_invasion_events_v1"
    / "positive_subset_review__mig_91.csv"
)
DB = "thyroid_canonical_publication_v1_0"

PREAMBLE = """\
# T4b invasion positive-subset review -- canonical_t4b_invasion_events_v1
# Protocol v2 LLM-output canonical (airway-style per-finding review)
# batch_id: mig_91_t4b_invasion_positive_review
# Generated by qc_framework_v1/scripts/build_t4b_invasion_positive_review.py
#
# Total rows in canonical: 944. This CSV contains the positive-subset:
#   ANY anatomic finding = 'present', OR t4b_implication = 'pT4b',
#   OR an edge case where any anatomic finding = 'absent' (so you can
#   sanity-check the pathologist staging cases).
#
# Apply rule (findings-vs-staging, feedback_findings_vs_staging.md):
#   pT4b iff at least one of the three anatomic findings is 'present'.
#   The t4b_implication column should follow the findings, NOT override
#   them. Pathologist stage-only assertions (pT4b with all anatomic
#   findings 'unknown') are CARRY-FORWARD candidates -- ACCEPT them only
#   if you confirm via evidence_quote that the pathologist actually saw
#   it; otherwise RECLASS to unable_to_determine.
#
# your_decision vocabulary:
#   ACCEPT          -- default (blank == ACCEPT)
#   REJECT          -- false-positive, drop the row at sign-off
#   RECLASS_T4B     -- override t4b_implication to 'pT4b'
#   RECLASS_NOT_T4B -- override t4b_implication to 'not_pT4b'
#   RECLASS_UTD     -- override t4b_implication to 'unable_to_determine'
"""


def main() -> None:
    con = duckdb.connect("md:")
    con.execute(f'USE "{DB}"')
    rows = con.execute(
        """
        SELECT
          t4b_event_id, research_id, note_type, note_index,
          prevertebral_fascia_invasion, carotid_encasement,
          mediastinal_vessel_invasion, t4b_implication,
          confidence, evidence_quote, reasoning, llm_model,
          CASE
            WHEN prevertebral_fascia_invasion = 'present'
              OR carotid_encasement           = 'present'
              OR mediastinal_vessel_invasion  = 'present'
              OR t4b_implication              = 'pT4b'
            THEN 1 ELSE 0 END AS is_positive,
          CASE
            WHEN prevertebral_fascia_invasion = 'absent'
              OR carotid_encasement           = 'absent'
              OR mediastinal_vessel_invasion  = 'absent'
            THEN 1 ELSE 0 END AS is_edge_absent
        FROM main.canonical_t4b_invasion_events_v1
        WHERE prevertebral_fascia_invasion = 'present'
           OR carotid_encasement           = 'present'
           OR mediastinal_vessel_invasion  = 'present'
           OR t4b_implication              = 'pT4b'
           OR prevertebral_fascia_invasion = 'absent'
           OR carotid_encasement           = 'absent'
           OR mediastinal_vessel_invasion  = 'absent'
        ORDER BY is_positive DESC, t4b_implication, research_id
        """
    ).fetchall()
    print(f"t4b positive+edge rows: {len(rows)}")

    OUT.parent.mkdir(parents=True, exist_ok=True)
    with open(OUT, "w", newline="") as f:
        f.write(PREAMBLE)
        w = csv.writer(f)
        w.writerow([
            "t4b_event_id", "research_id", "note_type", "note_index",
            "prevertebral_fascia_invasion", "carotid_encasement",
            "mediastinal_vessel_invasion", "t4b_implication",
            "confidence", "evidence_quote", "reasoning", "llm_model",
            "is_positive", "is_edge_absent",
            "your_decision", "your_note",
        ])
        for r in rows:
            w.writerow(list(r) + ["", ""])
    print(f"-> wrote {OUT}")


if __name__ == "__main__":
    main()
