"""
qc_framework_v1/scripts/build_vascular_invasion_positive_review.py
==================================================================

Builds the positive-subset review CSV for canonical_vascular_invasion_events_v1
under Protocol v2.

Table shape (3,861 rows / 22 cols): per-mention vascular/lymphatic/perineural
invasion + lvi_collapsed (V/L combined) + tumor_type_context.

Positive-subset rule (findings-primary, feedback_findings_vs_staging.md):
  ANY of (vascular_invasion, lymphatic_invasion, perineural_invasion,
  lvi_collapsed) = 'present'

Distribution at time of writing:
  vascular_invasion='present':   742
  lymphatic_invasion='present':  889
  perineural_invasion='present': 103
  lvi_collapsed='present':      1,193
  Union (one row may have multiple): ~1,500 estimated

Subset only the positives + edge-case 'absent' rows where vessel_count > 0
(potential findings-vs-status disagreements). Negative rows (all
'absent'/'unknown' findings) are not surfaced for review.

CSV columns:
  vi_event_id, research_id, note_type, note_index,
  vascular_invasion, vascular_invasion_extent, vessel_count,
  lymphatic_invasion, perineural_invasion, lvi_collapsed,
  tumor_type_context, confidence, evidence_quote, reasoning,
  llm_model, your_decision, your_note

your_decision vocabulary:
  ACCEPT             -- default
  REJECT             -- drop row at sign-off
  RECLASS_VASCULAR   -- vascular_invasion should change (specify in your_note)
  RECLASS_LYMPHATIC  -- lymphatic_invasion should change
  RECLASS_PERINEURAL -- perineural_invasion should change
  RECLASS_LVI        -- lvi_collapsed should change
  RECLASS_MULTI      -- multiple cols change; describe in your_note

Output:
  verification_csvs/canonical_vascular_invasion_events_v1/
    positive_subset_review__mig_91.csv
"""
from __future__ import annotations

import csv
from pathlib import Path

import duckdb

REPO_ROOT = Path(__file__).resolve().parents[2]
OUT = (
    REPO_ROOT
    / "verification_csvs"
    / "canonical_vascular_invasion_events_v1"
    / "positive_subset_review__mig_91.csv"
)
DB = "thyroid_canonical_publication_v1_0"

PREAMBLE = """\
# Vascular invasion positive-subset review -- canonical_vascular_invasion_events_v1
# Protocol v2 LLM-output canonical (airway-style per-finding review)
# batch_id: mig_91_vascular_invasion_positive_review
# Generated by qc_framework_v1/scripts/build_vascular_invasion_positive_review.py
#
# Total rows in canonical: 3,861. This CSV contains the positive-subset:
#   ANY of (vascular_invasion, lymphatic_invasion, perineural_invasion,
#   lvi_collapsed) = 'present'.
#   Plus edge cases: vessel_count > 0 with all VI cols 'absent'/'unknown'
#   (potential findings-vs-count disagreements).
#
# Apply rule (findings-vs-staging, feedback_findings_vs_staging.md):
#   The 4 anatomic finding columns are PRIMARY. lvi_collapsed should
#   follow vascular_invasion OR lymphatic_invasion (i.e. lvi_collapsed
#   is a derivation, not an independent assertion). Flag any lvi_collapsed
#   = 'present' rows where both vascular_invasion AND lymphatic_invasion
#   are 'absent'/'unknown' as RECLASS_LVI candidates.
#
# vessel_count semantics: if vessel_count > 0 then vascular_invasion
#   should be 'present'; if vessel_count = 0 then 'absent'. Mismatches
#   are findings-vs-status discrepancies.
#
# your_decision vocabulary:
#   ACCEPT             -- default (blank == ACCEPT)
#   REJECT             -- false-positive, drop the row at sign-off
#   RECLASS_VASCULAR   -- vascular_invasion should change; specify in note
#   RECLASS_LYMPHATIC  -- lymphatic_invasion should change
#   RECLASS_PERINEURAL -- perineural_invasion should change
#   RECLASS_LVI        -- lvi_collapsed should change
#   RECLASS_MULTI      -- multiple cols change; describe in your_note
"""


def main() -> None:
    con = duckdb.connect("md:")
    con.execute(f'USE "{DB}"')
    rows = con.execute(
        """
        SELECT
          vi_event_id, research_id, note_type, note_index,
          vascular_invasion, vascular_invasion_extent, vessel_count,
          lymphatic_invasion, perineural_invasion, lvi_collapsed,
          tumor_type_context, confidence, evidence_quote, reasoning,
          llm_model,
          CASE
            WHEN vascular_invasion   = 'present'
              OR lymphatic_invasion  = 'present'
              OR perineural_invasion = 'present'
              OR lvi_collapsed       = 'present'
            THEN 1 ELSE 0 END AS is_positive,
          CASE
            WHEN COALESCE(vessel_count, 0) > 0
             AND vascular_invasion != 'present'
            THEN 1 ELSE 0 END AS is_count_findings_disagreement,
          CASE
            WHEN lvi_collapsed       = 'present'
             AND vascular_invasion  IN ('absent','unknown',NULL)
             AND lymphatic_invasion IN ('absent','unknown',NULL)
            THEN 1 ELSE 0 END AS is_lvi_disagreement
        FROM main.canonical_vascular_invasion_events_v1
        WHERE vascular_invasion   = 'present'
           OR lymphatic_invasion  = 'present'
           OR perineural_invasion = 'present'
           OR lvi_collapsed       = 'present'
           OR (COALESCE(vessel_count, 0) > 0
               AND vascular_invasion != 'present')
        ORDER BY is_positive DESC,
                 is_lvi_disagreement DESC,
                 is_count_findings_disagreement DESC,
                 research_id, note_type, note_index
        """
    ).fetchall()
    print(f"vascular positive+edge rows: {len(rows)}")

    OUT.parent.mkdir(parents=True, exist_ok=True)
    with open(OUT, "w", newline="") as f:
        f.write(PREAMBLE)
        w = csv.writer(f)
        w.writerow([
            "vi_event_id", "research_id", "note_type", "note_index",
            "vascular_invasion", "vascular_invasion_extent", "vessel_count",
            "lymphatic_invasion", "perineural_invasion", "lvi_collapsed",
            "tumor_type_context", "confidence",
            "evidence_quote", "reasoning", "llm_model",
            "is_positive", "is_count_findings_disagreement",
            "is_lvi_disagreement",
            "your_decision", "your_note",
        ])
        for r in rows:
            w.writerow(list(r) + ["", ""])
    print(f"-> wrote {OUT}")


if __name__ == "__main__":
    main()
