"""
qc_framework_v1/scripts/build_fna_date_raw_canary.py
====================================================

Generates the Step B canary verification CSV for
canonical_fna_events_v1.fna_date_raw under Protocol v2.

Mechanical_source_compare logic (matches what was probed via MCP):
  - Source: manuscript_workspace.fna_source_long_v1_step_b (loaded from
    raw/FNAs 12_5_2025.xlsx > FNA Bethesda)
  - DB: main.canonical_fna_events_v1
  - Join: FULL OUTER on (research_id, fna_index)
  - Normalization:
      strip leading/trailing whitespace (incl. \\t \\n)
      empty string -> NULL
      'not specified' / 'n/s' / 'not available' / 'none' /
      'date unknown' / 'date unknown:' (case-insensitive) -> NULL
      try_strptime against: %Y-%m-%d %H:%M:%S | %Y-%m-%d | %m/%d/%Y |
      %m/%d/%y (and dash-no-pad variants); when parsed, canonicalize to
      YYYY-MM-DD HH:MM:SS
  - match_flag:
      MATCH                 -- both null OR raw-trim equal OR parsed dates equal
      MISMATCH              -- both parsed and dates differ
      NO_SOURCE_MATCH       -- DB row exists, no source row on (rid, fna_index)
      SOURCE_NO_DB_MATCH    -- source row exists, no DB row on (rid, fna_index)
      DB_NULL_SOURCE_HAS    -- db null, source not null
      SOURCE_NULL_DB_HAS    -- source null, db not null
      AMBIGUOUS             -- 2-digit year on either side (incl. cases where
                               raw strings agree but year is ambiguous), OR
                               one side parses and the other doesn't

CSV columns (per session brief):
  research_id, fna_event_id, fna_index, fna_seq_n,
  source_workbook, source_sheet, source_row, source_col,
  db_value, source_value, match_flag,
  your_correction, your_note

Sort order:
  MISMATCH / NO_SOURCE_MATCH / SOURCE_NO_DB_MATCH /
  DB_NULL_SOURCE_HAS / SOURCE_NULL_DB_HAS / AMBIGUOUS  -> top
  MATCH                                                -> below
  Within group: research_id, fna_index ascending

Output:
  verification_csvs/canonical_fna_events_v1/fna_date_raw__mig_65_logan_step_b.csv
"""

from __future__ import annotations

import sys
from pathlib import Path

import duckdb

REPO_ROOT = Path(__file__).resolve().parents[2]
OUT_CSV = (
    REPO_ROOT
    / "verification_csvs"
    / "canonical_fna_events_v1"
    / "fna_date_raw__mig_65_logan_step_b.csv"
)
DEST_DB = "thyroid_canonical_publication_v1_0"

# Sort priority for non-MATCH flags (lower = higher in CSV)
FLAG_PRIORITY = {
    "MISMATCH": 0,
    "NO_SOURCE_MATCH": 1,
    "SOURCE_NO_DB_MATCH": 2,
    "DB_NULL_SOURCE_HAS": 3,
    "SOURCE_NULL_DB_HAS": 4,
    "AMBIGUOUS": 5,
    "MATCH": 99,
}

PREAMBLE = f"""\
# Verification canary CSV -- canonical_fna_events_v1.fna_date_raw
# Protocol v2 Step B (mechanical_source_compare) -- batch_id: mig_65_fna_date_raw
# Generated by qc_framework_v1/scripts/build_fna_date_raw_canary.py
# Source workbook: raw/FNAs 12_5_2025.xlsx > sheet 'FNA Bethesda'
# Staging table:   manuscript_workspace.fna_source_long_v1_step_b
#
# Normalization rules:
#   - Strip leading/trailing whitespace (\\t \\n included)
#   - Empty string and ('not specified','n/s','not available','none',
#     'date unknown','date unknown:') -> NULL
#   - Date parsers tried (in order): %Y-%m-%d %H:%M:%S | %Y-%m-%d |
#     %m/%d/%Y | %m/%d/%y (and dash-no-pad variants)
#   - When both sides parse, canonical compare = YYYY-MM-DD HH:MM:SS
#
# Sort: MISMATCH / NO_SOURCE_MATCH / SOURCE_NO_DB_MATCH /
#       DB_NULL_SOURCE_HAS / SOURCE_NULL_DB_HAS / AMBIGUOUS first; MATCH below.
#
# To submit corrections: fill `your_correction` (raw replacement value) and
# `your_note` for any rows you want changed; leave blank for rows you accept
# as-is. Save the CSV. Claude bulk-applies via query_rw + appends to
# manuscript_workspace.canonical_logan_review_log_v1.
"""


SQL = """
WITH src AS (
  SELECT research_id, fna_index, source_workbook, source_sheet, source_row,
         source_col_date AS source_col, source_col_name_date AS source_col_name,
         date_raw AS source_value
  FROM manuscript_workspace.fna_source_long_v1_step_b
),
db AS (
  SELECT research_id, fna_event_id, fna_index, fna_seq_n,
         fna_date_raw AS db_value
  FROM main.canonical_fna_events_v1
),
joined AS (
  SELECT
    COALESCE(db.research_id, src.research_id) AS research_id,
    COALESCE(db.fna_index, src.fna_index)     AS fna_index,
    db.fna_event_id, db.fna_seq_n,
    src.source_workbook, src.source_sheet, src.source_row, src.source_col, src.source_col_name,
    db.db_value, src.source_value
  FROM db FULL OUTER JOIN src
    ON db.research_id = src.research_id AND db.fna_index = src.fna_index
),
trimmed AS (
  SELECT *,
    NULLIF(TRIM(BOTH FROM REGEXP_REPLACE(db_value,     '^\\s+|\\s+$', '', 'g')), '') AS db_trim,
    NULLIF(TRIM(BOTH FROM REGEXP_REPLACE(source_value, '^\\s+|\\s+$', '', 'g')), '') AS src_trim
  FROM joined
),
clean AS (
  SELECT *,
    CASE WHEN LOWER(db_trim)  IN ('not specified','n/s','not available','none','date unknown:','date unknown') THEN NULL ELSE db_trim  END AS db_clean,
    CASE WHEN LOWER(src_trim) IN ('not specified','n/s','not available','none','date unknown:','date unknown') THEN NULL ELSE src_trim END AS src_clean
  FROM trimmed
),
canon AS (
  SELECT *,
    COALESCE(
      try_strptime(db_clean, '%Y-%m-%d %H:%M:%S'),
      try_strptime(db_clean, '%Y-%m-%d'),
      try_strptime(db_clean, '%m/%d/%Y'),
      try_strptime(db_clean, '%-m/%-d/%Y'),
      try_strptime(db_clean, '%m/%d/%y'),
      try_strptime(db_clean, '%-m/%-d/%y')
    ) AS db_dt,
    COALESCE(
      try_strptime(src_clean, '%Y-%m-%d %H:%M:%S'),
      try_strptime(src_clean, '%Y-%m-%d'),
      try_strptime(src_clean, '%m/%d/%Y'),
      try_strptime(src_clean, '%-m/%-d/%Y'),
      try_strptime(src_clean, '%m/%d/%y'),
      try_strptime(src_clean, '%-m/%-d/%y')
    ) AS src_dt,
    (db_clean  ~ '^\\d{1,2}/\\d{1,2}/\\d{2}(\\D|$)' AND db_clean  !~ '^\\d{1,2}/\\d{1,2}/\\d{4}')
      OR (src_clean ~ '^\\d{1,2}/\\d{1,2}/\\d{2}(\\D|$)' AND src_clean !~ '^\\d{1,2}/\\d{1,2}/\\d{4}')
      AS has_2digit_year
  FROM clean
),
flagged AS (
  SELECT
    research_id, fna_event_id, fna_index, fna_seq_n,
    COALESCE(source_workbook, 'FNAs 12_5_2025.xlsx') AS source_workbook,
    COALESCE(source_sheet,    'FNA Bethesda')        AS source_sheet,
    source_row, source_col,
    db_value, source_value,
    CASE
      WHEN fna_event_id IS NULL                       THEN 'SOURCE_NO_DB_MATCH'
      WHEN source_workbook IS NULL                    THEN 'NO_SOURCE_MATCH'
      WHEN db_clean IS NULL AND src_clean IS NULL     THEN 'MATCH'
      WHEN db_clean IS NULL AND src_clean IS NOT NULL THEN 'DB_NULL_SOURCE_HAS'
      WHEN db_clean IS NOT NULL AND src_clean IS NULL THEN 'SOURCE_NULL_DB_HAS'
      WHEN db_dt IS NOT NULL AND src_dt IS NOT NULL AND db_dt = src_dt
        THEN CASE WHEN has_2digit_year THEN 'AMBIGUOUS' ELSE 'MATCH' END
      WHEN db_dt IS NOT NULL AND src_dt IS NOT NULL AND db_dt <> src_dt THEN 'MISMATCH'
      WHEN db_dt IS NULL AND src_dt IS NULL AND db_clean = src_clean    THEN 'MATCH'
      WHEN db_dt IS NULL OR  src_dt IS NULL                             THEN 'AMBIGUOUS'
      ELSE 'MISMATCH'
    END AS match_flag
  FROM canon
)
SELECT
  research_id,
  fna_event_id,
  fna_index,
  fna_seq_n,
  source_workbook,
  source_sheet,
  source_row,
  source_col,
  db_value,
  source_value,
  match_flag,
  ''  AS your_correction,
  ''  AS your_note
FROM flagged
ORDER BY
  CASE match_flag
    WHEN 'MISMATCH'           THEN 0
    WHEN 'NO_SOURCE_MATCH'    THEN 1
    WHEN 'SOURCE_NO_DB_MATCH' THEN 2
    WHEN 'DB_NULL_SOURCE_HAS' THEN 3
    WHEN 'SOURCE_NULL_DB_HAS' THEN 4
    WHEN 'AMBIGUOUS'          THEN 5
    ELSE 99
  END,
  research_id,
  fna_index
"""


def main() -> None:
    print(f"[canary] connecting MotherDuck ({DEST_DB})")
    con = duckdb.connect("md:")
    con.execute(f"USE {DEST_DB}")

    print("[canary] running merge query server-side...")
    con.execute(f"COPY ({SQL}) TO '{OUT_CSV.with_suffix('.tmp.csv')}' "
                f"WITH (HEADER, FORMAT CSV)")
    tmp = OUT_CSV.with_suffix(".tmp.csv")

    # Prepend the preamble (CSV readers ignore lines starting with `#`
    # if instructed; Excel will treat them as data unless the user skips
    # the leading rows. We document this in the file header.)
    print(f"[canary] writing {OUT_CSV} with preamble")
    body = tmp.read_text()
    OUT_CSV.write_text(PREAMBLE + body)
    tmp.unlink()

    n_lines = sum(1 for _ in OUT_CSV.open())
    print(f"[canary] CSV lines (incl preamble + header): {n_lines}")

    # Recompute and report match-flag counts from the CSV body
    print("\n[canary] flag counts:")
    counts = con.execute(f"""
        WITH cte AS ({SQL})
        SELECT match_flag, COUNT(*) AS n
        FROM cte
        GROUP BY 1
        ORDER BY CASE match_flag
            WHEN 'MISMATCH'           THEN 0
            WHEN 'NO_SOURCE_MATCH'    THEN 1
            WHEN 'SOURCE_NO_DB_MATCH' THEN 2
            WHEN 'DB_NULL_SOURCE_HAS' THEN 3
            WHEN 'SOURCE_NULL_DB_HAS' THEN 4
            WHEN 'AMBIGUOUS'          THEN 5
            ELSE 99 END
    """).fetchall()
    for flag, n in counts:
        print(f"  {flag:20s} {n:6d}")
    print(f"[canary] saved: {OUT_CSV}")


if __name__ == "__main__":
    main()
