"""
qc_framework_v1/scripts/build_path_malignant_surgery_date_review.py
===================================================================

Generates the Step B verification CSV for
canonical_path_malignant_events_v1.surgery_date under Protocol v2.

Mechanical_source_compare logic:
  - Source: main.path_synoptics.surg_date (loaded from
    raw/All Diagnoses & synoptic 12_1_2025.xlsx > sheet 'synoptics + Dx merged')
  - DB: main.canonical_path_malignant_events_v1.surgery_date
  - Join: per-canonical-row EXISTS check on (research_id, surgery_date)
    against path_synoptics, since canonical is the long-form unwind of
    the wide-format path_synoptics (one path_synoptics row -> up to 5
    canonical rows via tumor_N slots) and surgery_date is per-surgery
    (constant across tumors).
  - Both columns are TIMESTAMP; no string normalization needed. The
    20YY rule for 2-digit years (memory: reference_2digit_year_convention.md)
    is upstream of the path_synoptics load and does not apply at this
    level of comparison -- both values are already TIMESTAMP.
  - match_flag values:
      MATCH                 -- both sides agree (exact TIMESTAMP equality)
      MISMATCH              -- both sides have a value, values disagree
      NO_SOURCE_MATCH       -- DB row exists, source has no row for this
                               (research_id, surgery_date) pair
      DB_NULL_SOURCE_HAS    -- db null, source has a value for the patient
      SOURCE_NULL_DB_HAS    -- db has a value, source has none

CSV columns:
  research_id, surgery_episode_id, tumor_ordinal, synoptic_row_ix,
  source_workbook, source_sheet, source_locator,
  db_value, source_value, match_flag, your_correction, your_note

Sort: MISMATCH / NO_SOURCE_MATCH / DB_NULL_SOURCE_HAS /
      SOURCE_NULL_DB_HAS first; MATCH below.

Output:
  verification_csvs/canonical_path_malignant_events_v1/surgery_date__mig_85.csv
"""

from __future__ import annotations

from pathlib import Path

import duckdb

REPO_ROOT = Path(__file__).resolve().parents[2]
OUT_CSV = (
    REPO_ROOT
    / "verification_csvs"
    / "canonical_path_malignant_events_v1"
    / "surgery_date__mig_85.csv"
)
DEST_DB = "thyroid_canonical_publication_v1_0"

PREAMBLE = """\
# Verification CSV -- canonical_path_malignant_events_v1.surgery_date
# Protocol v2 Step B (mechanical_source_compare) -- batch_id: mig_85_path_malignant_surgery_date
# Generated by qc_framework_v1/scripts/build_path_malignant_surgery_date_review.py
# Source workbook: raw/All Diagnoses & synoptic 12_1_2025.xlsx > sheet 'synoptics + Dx merged'
# Mirrored in DB at: main.path_synoptics.surg_date
#
# Match logic:
#   - DB and source are both TIMESTAMP; exact equality.
#   - Per-canonical-row EXISTS against path_synoptics on (research_id, surg_date).
#   - canonical is the long-form unwind of wide path_synoptics (tumor_N slots),
#     so surgery_date is the per-surgery anchor and shared across tumors.
#
# Sort: MISMATCH / NO_SOURCE_MATCH / DB_NULL_SOURCE_HAS / SOURCE_NULL_DB_HAS first; MATCH below.
#
# To submit corrections: fill `your_correction` (raw replacement value) and
# `your_note` for any rows you want changed. Save the CSV. Claude bulk-applies
# via query_rw + appends to manuscript_workspace.canonical_logan_review_log_v1.
"""


SQL = """
WITH probe AS (
  SELECT
    c.research_id,
    c.surgery_episode_id,
    c.tumor_ordinal,
    c.synoptic_row_ix,
    c.surgery_date AS db_value,
    EXISTS (
      SELECT 1 FROM main.path_synoptics ps
      WHERE CAST(c.research_id AS VARCHAR) = ps.research_id
        AND c.surgery_date = ps.surg_date
    ) AS source_match_for_date,
    EXISTS (
      SELECT 1 FROM main.path_synoptics ps
      WHERE CAST(c.research_id AS VARCHAR) = ps.research_id
    ) AS patient_in_synoptics,
    (SELECT MAX(ps.surg_date) FROM main.path_synoptics ps
       WHERE CAST(c.research_id AS VARCHAR) = ps.research_id
         AND c.surgery_date = ps.surg_date) AS source_value_matched
  FROM main.canonical_path_malignant_events_v1 c
)
SELECT
  research_id,
  surgery_episode_id,
  tumor_ordinal,
  synoptic_row_ix,
  'All Diagnoses & synoptic 12_1_2025.xlsx' AS source_workbook,
  'synoptics + Dx merged'                   AS source_sheet,
  'research_id=' || CAST(research_id AS VARCHAR)
    || ', surg_date=' || CAST(db_value AS VARCHAR) AS source_locator,
  db_value,
  source_value_matched AS source_value,
  CASE
    WHEN db_value IS NULL AND NOT patient_in_synoptics THEN 'NO_SOURCE_MATCH'
    WHEN db_value IS NULL AND patient_in_synoptics     THEN 'DB_NULL_SOURCE_HAS'
    WHEN source_match_for_date                          THEN 'MATCH'
    WHEN patient_in_synoptics                           THEN 'MISMATCH'
    ELSE 'NO_SOURCE_MATCH'
  END AS match_flag,
  '' AS your_correction,
  '' AS your_note
FROM probe
ORDER BY
  CASE
    WHEN db_value IS NULL AND NOT patient_in_synoptics THEN 0
    WHEN db_value IS NULL AND patient_in_synoptics     THEN 1
    WHEN source_match_for_date                          THEN 99
    WHEN patient_in_synoptics                           THEN 2
    ELSE 0
  END,
  research_id, surgery_episode_id, tumor_ordinal
"""


def main() -> None:
    print(f"[surgery_date] connecting MotherDuck ({DEST_DB})")
    con = duckdb.connect("md:")
    con.execute(f"USE {DEST_DB}")

    OUT_CSV.parent.mkdir(parents=True, exist_ok=True)

    print("[surgery_date] running compare server-side, COPY to local disk...")
    tmp = OUT_CSV.with_suffix(".tmp.csv")
    con.execute(
        f"COPY ({SQL}) TO '{tmp}' WITH (HEADER, FORMAT CSV)"
    )

    print(f"[surgery_date] writing {OUT_CSV} with preamble")
    body = tmp.read_text()
    OUT_CSV.write_text(PREAMBLE + body)
    tmp.unlink()

    n_lines = sum(1 for _ in OUT_CSV.open())
    print(f"[surgery_date] CSV lines (incl preamble + header): {n_lines}")

    print("\n[surgery_date] flag counts:")
    counts = con.execute(f"""
        WITH cte AS ({SQL})
        SELECT match_flag, COUNT(*) AS n
        FROM cte
        GROUP BY 1
        ORDER BY CASE match_flag
            WHEN 'MISMATCH'           THEN 0
            WHEN 'NO_SOURCE_MATCH'    THEN 1
            WHEN 'DB_NULL_SOURCE_HAS' THEN 2
            WHEN 'SOURCE_NULL_DB_HAS' THEN 3
            WHEN 'MATCH'              THEN 99
            ELSE 50 END
    """).fetchall()
    for flag, n in counts:
        print(f"  {flag:22s} {n:6d}")
    print(f"[surgery_date] saved: {OUT_CSV}")


if __name__ == "__main__":
    main()
