"""
qc_framework_v1/scripts/build_esophageal_invasion_full_review.py
================================================================

Builds the per-finding review CSV for canonical_esophageal_invasion_events_v1
under Protocol v2 (LLM-output canonical, airway-style review pattern).

The table is small (188 rows / 11 unique entity_type x present_or_negated combos
at the time of writing). Pull ALL rows; sort positives first so Logan can scan
the clinical positives quickly. Negated/non-clinical rows follow at the bottom.

CSV columns:
  research_id, note_row_id, note_type, note_date, source_column,
  entity_type, entity_value, present_or_negated, confidence,
  evidence_text, source_line, entity_date,
  is_positive_clinical, your_decision, your_note

Decision vocabulary (your_decision):
  ACCEPT      -- keep as-is (default if left blank)
  REJECT      -- false-positive, drop the row at sign-off
  RECLASS     -- value should change (write the corrected entity_value
                 + updated present_or_negated in your_note)

Output:
  verification_csvs/canonical_esophageal_invasion_events_v1/
    positive_subset_review__mig_91.csv

Auth: MotherDuck SSO (default account). Per
reference_protocol_v2_md_accounts.md, ensure the active SSO is
logan.glosser.eras@gmail.com (the publication DB lives there).
"""
from __future__ import annotations

import csv
from pathlib import Path

import duckdb

REPO_ROOT = Path(__file__).resolve().parents[2]
OUT = (
    REPO_ROOT
    / "verification_csvs"
    / "canonical_esophageal_invasion_events_v1"
    / "positive_subset_review__mig_91.csv"
)
DB = "thyroid_canonical_publication_v1_0"

# entity_types that, when present_or_negated='present', indicate a clinically
# positive esophageal-invasion finding (vs procedural-context-only mentions).
POSITIVE_ENTITY_TYPES = (
    "esophageal_invasion_present",
    "esophageal_invasion_extent",
    "esophageal_muscularis_invasion",
    "esophageal_mucosal_invasion",
    "esophageal_invasion_length_cm",
    "esophageal_repair_performed",
)

PREAMBLE = """\
# Esophageal invasion full review -- canonical_esophageal_invasion_events_v1
# Protocol v2 LLM-output canonical (airway-style per-finding review)
# batch_id: mig_91_esophageal_invasion_full_review
# Generated by qc_framework_v1/scripts/build_esophageal_invasion_full_review.py
#
# Total rows: 188 (small enough to review the entire table). Sort:
#   - is_positive_clinical = 1 first (clinically positive findings)
#   - then non-positive entries grouped by entity_type
#
# entity_types that are POSITIVE (when present_or_negated='present'):
#   esophageal_invasion_present, esophageal_invasion_extent,
#   esophageal_muscularis_invasion, esophageal_mucosal_invasion,
#   esophageal_invasion_length_cm, esophageal_repair_performed
#
# your_decision vocabulary:
#   ACCEPT  -- keep as-is (default; blank == ACCEPT)
#   REJECT  -- false-positive, drop the row at sign-off
#   RECLASS -- value/status should change; describe in your_note
#
# Apply rule (findings-vs-staging, feedback_findings_vs_staging.md):
#   Anatomic invasion findings are PRIMARY. Mass-effect / compression /
#   procedural-context-only mentions ('repair_performed' without
#   real lumen breach, 'compression', 'displacement') should be
#   REJECTED or RECLASSED unless a true invasion is documented.
"""


def main() -> None:
    con = duckdb.connect("md:")
    con.execute(f'USE "{DB}"')
    rows = con.execute(
        f"""
        SELECT
          research_id, note_row_id, note_type, note_date, source_column,
          entity_type, entity_value, present_or_negated, confidence,
          evidence_text, source_line, entity_date,
          CASE
            WHEN present_or_negated = 'present'
             AND entity_type IN ({", ".join(f"'{t}'" for t in POSITIVE_ENTITY_TYPES)})
            THEN 1 ELSE 0 END AS is_positive_clinical
        FROM main.canonical_esophageal_invasion_events_v1
        ORDER BY is_positive_clinical DESC,
                 entity_type, present_or_negated, research_id
        """
    ).fetchall()
    print(f"esophageal rows: {len(rows)}")

    OUT.parent.mkdir(parents=True, exist_ok=True)
    with open(OUT, "w", newline="") as f:
        f.write(PREAMBLE)
        w = csv.writer(f)
        w.writerow([
            "research_id", "note_row_id", "note_type", "note_date",
            "source_column", "entity_type", "entity_value",
            "present_or_negated", "confidence",
            "evidence_text", "source_line", "entity_date",
            "is_positive_clinical",
            "your_decision", "your_note",
        ])
        for r in rows:
            w.writerow(list(r) + ["", ""])
    print(f"-> wrote {OUT}")


if __name__ == "__main__":
    main()
